.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.10.1 */

glabel func_8001D970
/* 1E570 8001D970 3C028008 */  lui        $v0, %hi(D_80087E38)
/* 1E574 8001D974 24427E38 */  addiu      $v0, $v0, %lo(D_80087E38)
/* 1E578 8001D978 24030100 */  addiu      $v1, $zero, 0x100
.L8001D97C:
/* 1E57C 8001D97C 2463FFFC */  addiu      $v1, $v1, -0x4
/* 1E580 8001D980 A4400000 */  sh         $zero, 0x0($v0)
/* 1E584 8001D984 A4400040 */  sh         $zero, 0x40($v0)
/* 1E588 8001D988 A4400080 */  sh         $zero, 0x80($v0)
/* 1E58C 8001D98C A44000C0 */  sh         $zero, 0xC0($v0)
/* 1E590 8001D990 1460FFFA */  bnez       $v1, .L8001D97C
/* 1E594 8001D994 24420100 */   addiu     $v0, $v0, 0x100
/* 1E598 8001D998 3C018008 */  lui        $at, %hi(D_80087E30)
/* 1E59C 8001D99C AC207E30 */  sw         $zero, %lo(D_80087E30)($at)
/* 1E5A0 8001D9A0 03E00008 */  jr         $ra
/* 1E5A4 8001D9A4 00000000 */   nop

glabel func_8001D9A8
/* 1E5A8 8001D9A8 3C0E8008 */  lui        $t6, %hi(D_80087E38)
/* 1E5AC 8001D9AC 95CE7E38 */  lhu        $t6, %lo(D_80087E38)($t6)
/* 1E5B0 8001D9B0 3C038008 */  lui        $v1, %hi(D_80087E38)
/* 1E5B4 8001D9B4 24637E38 */  addiu      $v1, $v1, %lo(D_80087E38)
/* 1E5B8 8001D9B8 11C00007 */  beqz       $t6, .L8001D9D8
/* 1E5BC 8001D9BC 24020100 */   addiu     $v0, $zero, 0x100
/* 1E5C0 8001D9C0 2442FFFF */  addiu      $v0, $v0, -0x1
.L8001D9C4:
/* 1E5C4 8001D9C4 10400004 */  beqz       $v0, .L8001D9D8
/* 1E5C8 8001D9C8 24630040 */   addiu     $v1, $v1, 0x40
/* 1E5CC 8001D9CC 946F0000 */  lhu        $t7, 0x0($v1)
/* 1E5D0 8001D9D0 55E0FFFC */  bnel       $t7, $zero, .L8001D9C4
/* 1E5D4 8001D9D4 2442FFFF */   addiu     $v0, $v0, -0x1
.L8001D9D8:
/* 1E5D8 8001D9D8 10400014 */  beqz       $v0, .L8001DA2C
/* 1E5DC 8001D9DC 00804025 */   or        $t0, $a0, $zero
/* 1E5E0 8001D9E0 3C028008 */  lui        $v0, %hi(D_80087E30)
/* 1E5E4 8001D9E4 24427E30 */  addiu      $v0, $v0, %lo(D_80087E30)
/* 1E5E8 8001D9E8 00604825 */  or         $t1, $v1, $zero
/* 1E5EC 8001D9EC 2499003C */  addiu      $t9, $a0, 0x3C
.L8001D9F0:
/* 1E5F0 8001D9F0 8D010000 */  lw         $at, 0x0($t0)
/* 1E5F4 8001D9F4 2508000C */  addiu      $t0, $t0, 0xC
/* 1E5F8 8001D9F8 2529000C */  addiu      $t1, $t1, 0xC
/* 1E5FC 8001D9FC AD21FFF4 */  sw         $at, -0xC($t1)
/* 1E600 8001DA00 8D01FFF8 */  lw         $at, -0x8($t0)
/* 1E604 8001DA04 AD21FFF8 */  sw         $at, -0x8($t1)
/* 1E608 8001DA08 8D01FFFC */  lw         $at, -0x4($t0)
/* 1E60C 8001DA0C 1519FFF8 */  bne        $t0, $t9, .L8001D9F0
/* 1E610 8001DA10 AD21FFFC */   sw        $at, -0x4($t1)
/* 1E614 8001DA14 8D010000 */  lw         $at, 0x0($t0)
/* 1E618 8001DA18 AD210000 */  sw         $at, 0x0($t1)
/* 1E61C 8001DA1C 8C4A0000 */  lw         $t2, 0x0($v0)
/* 1E620 8001DA20 254B0001 */  addiu      $t3, $t2, 0x1
/* 1E624 8001DA24 10000002 */  b          .L8001DA30
/* 1E628 8001DA28 AC4B0000 */   sw        $t3, 0x0($v0)
.L8001DA2C:
/* 1E62C 8001DA2C 00001825 */  or         $v1, $zero, $zero
.L8001DA30:
/* 1E630 8001DA30 00601025 */  or         $v0, $v1, $zero
/* 1E634 8001DA34 03E00008 */  jr         $ra
/* 1E638 8001DA38 00000000 */   nop

glabel func_8001DA3C
/* 1E63C 8001DA3C 27BDFF00 */  addiu      $sp, $sp, -0x100
/* 1E640 8001DA40 AFB70054 */  sw         $s7, 0x54($sp)
/* 1E644 8001DA44 3C178008 */  lui        $s7, %hi(D_80087E30)
/* 1E648 8001DA48 26F77E30 */  addiu      $s7, $s7, %lo(D_80087E30)
/* 1E64C 8001DA4C AFBF005C */  sw         $ra, 0x5C($sp)
/* 1E650 8001DA50 AFBE0058 */  sw         $fp, 0x58($sp)
/* 1E654 8001DA54 AFB60050 */  sw         $s6, 0x50($sp)
/* 1E658 8001DA58 AFB5004C */  sw         $s5, 0x4C($sp)
/* 1E65C 8001DA5C AFB40048 */  sw         $s4, 0x48($sp)
/* 1E660 8001DA60 AFB30044 */  sw         $s3, 0x44($sp)
/* 1E664 8001DA64 AFB20040 */  sw         $s2, 0x40($sp)
/* 1E668 8001DA68 AFB1003C */  sw         $s1, 0x3C($sp)
/* 1E66C 8001DA6C AFB00038 */  sw         $s0, 0x38($sp)
/* 1E670 8001DA70 F7B60030 */  sdc1       $f22, 0x30($sp)
/* 1E674 8001DA74 F7B40028 */  sdc1       $f20, 0x28($sp)
/* 1E678 8001DA78 AFA40100 */  sw         $a0, 0x100($sp)
/* 1E67C 8001DA7C 8EF40000 */  lw         $s4, 0x0($s7)
/* 1E680 8001DA80 3C108008 */  lui        $s0, %hi(D_80087E38)
/* 1E684 8001DA84 0000A825 */  or         $s5, $zero, $zero
/* 1E688 8001DA88 12800089 */  beqz       $s4, .L8001DCB0
/* 1E68C 8001DA8C 26107E38 */   addiu     $s0, $s0, %lo(D_80087E38)
/* 1E690 8001DA90 3C013F80 */  lui        $at, (0x3F800000 >> 16)
/* 1E694 8001DA94 3C168008 */  lui        $s6, %hi(D_80085E48)
/* 1E698 8001DA98 3C138008 */  lui        $s3, %hi(D_8007A180)
/* 1E69C 8001DA9C 3C128008 */  lui        $s2, %hi(gMasterGfxPos)
/* 1E6A0 8001DAA0 4481B000 */  mtc1       $at, $f22
/* 1E6A4 8001DAA4 4480A000 */  mtc1       $zero, $f20
/* 1E6A8 8001DAA8 2652A184 */  addiu      $s2, $s2, %lo(gMasterGfxPos)
/* 1E6AC 8001DAAC 2673A180 */  addiu      $s3, $s3, %lo(D_8007A180)
/* 1E6B0 8001DAB0 26D65E48 */  addiu      $s6, $s6, %lo(D_80085E48)
/* 1E6B4 8001DAB4 3C1E0600 */  lui        $fp, (0x6000000 >> 16)
/* 1E6B8 8001DAB8 27B100B4 */  addiu      $s1, $sp, 0xB4
.L8001DABC:
/* 1E6BC 8001DABC 96020000 */  lhu        $v0, 0x0($s0)
/* 1E6C0 8001DAC0 10400079 */  beqz       $v0, .L8001DCA8
/* 1E6C4 8001DAC4 00000000 */   nop
/* 1E6C8 8001DAC8 8E030010 */  lw         $v1, 0x10($s0)
/* 1E6CC 8001DACC 244EFFFF */  addiu      $t6, $v0, -0x1
/* 1E6D0 8001DAD0 A60E0000 */  sh         $t6, 0x0($s0)
/* 1E6D4 8001DAD4 12A3000A */  beq        $s5, $v1, .L8001DB00
/* 1E6D8 8001DAD8 00602825 */   or        $a1, $v1, $zero
/* 1E6DC 8001DADC 920F000B */  lbu        $t7, 0xB($s0)
/* 1E6E0 8001DAE0 92040008 */  lbu        $a0, 0x8($s0)
/* 1E6E4 8001DAE4 92060009 */  lbu        $a2, 0x9($s0)
/* 1E6E8 8001DAE8 9207000A */  lbu        $a3, 0xA($s0)
/* 1E6EC 8001DAEC AFAF0010 */  sw         $t7, 0x10($sp)
/* 1E6F0 8001DAF0 9218000C */  lbu        $t8, 0xC($s0)
/* 1E6F4 8001DAF4 0060A825 */  or         $s5, $v1, $zero
/* 1E6F8 8001DAF8 0C00773A */  jal        func_8001DCE8
/* 1E6FC 8001DAFC AFB80014 */   sw        $t8, 0x14($sp)
.L8001DB00:
/* 1E700 8001DB00 8E020004 */  lw         $v0, 0x4($s0)
/* 1E704 8001DB04 50400006 */  beql       $v0, $zero, .L8001DB20
/* 1E708 8001DB08 8E420000 */   lw        $v0, 0x0($s2)
/* 1E70C 8001DB0C 0040F809 */  jalr       $v0
/* 1E710 8001DB10 02002025 */   or        $a0, $s0, $zero
/* 1E714 8001DB14 10000009 */  b          .L8001DB3C
/* 1E718 8001DB18 92090002 */   lbu       $t1, 0x2($s0)
/* 1E71C 8001DB1C 8E420000 */  lw         $v0, 0x0($s2)
.L8001DB20:
/* 1E720 8001DB20 3C088005 */  lui        $t0, %hi(D_8004F060)
/* 1E724 8001DB24 2508F060 */  addiu      $t0, $t0, %lo(D_8004F060)
/* 1E728 8001DB28 24590008 */  addiu      $t9, $v0, 0x8
/* 1E72C 8001DB2C AE590000 */  sw         $t9, 0x0($s2)
/* 1E730 8001DB30 AC480004 */  sw         $t0, 0x4($v0)
/* 1E734 8001DB34 AC5E0000 */  sw         $fp, 0x0($v0)
/* 1E738 8001DB38 92090002 */  lbu        $t1, 0x2($s0)
.L8001DB3C:
/* 1E73C 8001DB3C 02202025 */  or         $a0, $s1, $zero
/* 1E740 8001DB40 312A0001 */  andi       $t2, $t1, 0x1
/* 1E744 8001DB44 51400016 */  beql       $t2, $zero, .L8001DBA0
/* 1E748 8001DB48 C6CA000C */   lwc1      $f10, 0xC($s6)
/* 1E74C 8001DB4C 02202025 */  or         $a0, $s1, $zero
/* 1E750 8001DB50 8E050030 */  lw         $a1, 0x30($s0)
/* 1E754 8001DB54 8E060034 */  lw         $a2, 0x34($s0)
/* 1E758 8001DB58 0C009E32 */  jal        func_800278C8
/* 1E75C 8001DB5C 8E070038 */   lw        $a3, 0x38($s0)
/* 1E760 8001DB60 C6040018 */  lwc1       $f4, 0x18($s0)
/* 1E764 8001DB64 02202025 */  or         $a0, $s1, $zero
/* 1E768 8001DB68 E7A400E4 */  swc1       $f4, 0xE4($sp)
/* 1E76C 8001DB6C C606001C */  lwc1       $f6, 0x1C($s0)
/* 1E770 8001DB70 E7A600E8 */  swc1       $f6, 0xE8($sp)
/* 1E774 8001DB74 C6080020 */  lwc1       $f8, 0x20($s0)
/* 1E778 8001DB78 E7A800EC */  swc1       $f8, 0xEC($sp)
/* 1E77C 8001DB7C C6000028 */  lwc1       $f0, 0x28($s0)
/* 1E780 8001DB80 44050000 */  mfc1       $a1, $f0
/* 1E784 8001DB84 44060000 */  mfc1       $a2, $f0
/* 1E788 8001DB88 44070000 */  mfc1       $a3, $f0
/* 1E78C 8001DB8C 0C009F2D */  jal        func_80027CB4
/* 1E790 8001DB90 00000000 */   nop
/* 1E794 8001DB94 1000001F */  b          .L8001DC14
/* 1E798 8001DB98 8E620000 */   lw        $v0, 0x0($s3)
/* 1E79C 8001DB9C C6CA000C */  lwc1       $f10, 0xC($s6)
.L8001DBA0:
/* 1E7A0 8001DBA0 C6D00010 */  lwc1       $f16, 0x10($s6)
/* 1E7A4 8001DBA4 C6D20014 */  lwc1       $f18, 0x14($s6)
/* 1E7A8 8001DBA8 8E050018 */  lw         $a1, 0x18($s0)
/* 1E7AC 8001DBAC 8E06001C */  lw         $a2, 0x1C($s0)
/* 1E7B0 8001DBB0 8E070020 */  lw         $a3, 0x20($s0)
/* 1E7B4 8001DBB4 E7AA0010 */  swc1       $f10, 0x10($sp)
/* 1E7B8 8001DBB8 E7B00014 */  swc1       $f16, 0x14($sp)
/* 1E7BC 8001DBBC 0C009D77 */  jal        func_800275DC
/* 1E7C0 8001DBC0 E7B20018 */   swc1      $f18, 0x18($sp)
/* 1E7C4 8001DBC4 C6000024 */  lwc1       $f0, 0x24($s0)
/* 1E7C8 8001DBC8 4600A032 */  c.eq.s     $f20, $f0
/* 1E7CC 8001DBCC 00000000 */  nop
/* 1E7D0 8001DBD0 4503000B */  bc1tl      .L8001DC00
/* 1E7D4 8001DBD4 4407B000 */   mfc1      $a3, $f22
/* 1E7D8 8001DBD8 4405A000 */  mfc1       $a1, $f20
/* 1E7DC 8001DBDC 4406A000 */  mfc1       $a2, $f20
/* 1E7E0 8001DBE0 44070000 */  mfc1       $a3, $f0
/* 1E7E4 8001DBE4 0C009D0C */  jal        func_80027430
/* 1E7E8 8001DBE8 27A40074 */   addiu     $a0, $sp, 0x74
/* 1E7EC 8001DBEC 27A40074 */  addiu      $a0, $sp, 0x74
/* 1E7F0 8001DBF0 02202825 */  or         $a1, $s1, $zero
/* 1E7F4 8001DBF4 0C00E2AC */  jal        func_80038AB0
/* 1E7F8 8001DBF8 02203025 */   or        $a2, $s1, $zero
/* 1E7FC 8001DBFC 4407B000 */  mfc1       $a3, $f22
.L8001DC00:
/* 1E800 8001DC00 02202025 */  or         $a0, $s1, $zero
/* 1E804 8001DC04 8E050028 */  lw         $a1, 0x28($s0)
/* 1E808 8001DC08 0C009F2D */  jal        func_80027CB4
/* 1E80C 8001DC0C 8E06002C */   lw        $a2, 0x2C($s0)
/* 1E810 8001DC10 8E620000 */  lw         $v0, 0x0($s3)
.L8001DC14:
/* 1E814 8001DC14 8FAB0100 */  lw         $t3, 0x100($sp)
/* 1E818 8001DC18 284101E6 */  slti       $at, $v0, 0x1E6
/* 1E81C 8001DC1C 1020001B */  beqz       $at, .L8001DC8C
/* 1E820 8001DC20 00026180 */   sll       $t4, $v0, 6
/* 1E824 8001DC24 016C2821 */  addu       $a1, $t3, $t4
/* 1E828 8001DC28 24A500C0 */  addiu      $a1, $a1, 0xC0
/* 1E82C 8001DC2C 0C00E1E8 */  jal        func_800387A0
/* 1E830 8001DC30 02202025 */   or        $a0, $s1, $zero
/* 1E834 8001DC34 8E420000 */  lw         $v0, 0x0($s2)
/* 1E838 8001DC38 3C0E0102 */  lui        $t6, (0x1020040 >> 16)
/* 1E83C 8001DC3C 35CE0040 */  ori        $t6, $t6, (0x1020040 & 0xFFFF)
/* 1E840 8001DC40 244D0008 */  addiu      $t5, $v0, 0x8
/* 1E844 8001DC44 AE4D0000 */  sw         $t5, 0x0($s2)
/* 1E848 8001DC48 AC4E0000 */  sw         $t6, 0x0($v0)
/* 1E84C 8001DC4C 8E6F0000 */  lw         $t7, 0x0($s3)
/* 1E850 8001DC50 3C080200 */  lui        $t0, %hi(D_2000000)
/* 1E854 8001DC54 25080000 */  addiu      $t0, $t0, %lo(D_2000000)
/* 1E858 8001DC58 000FC180 */  sll        $t8, $t7, 6
/* 1E85C 8001DC5C 271900C0 */  addiu      $t9, $t8, 0xC0
/* 1E860 8001DC60 03284821 */  addu       $t1, $t9, $t0
/* 1E864 8001DC64 AC490004 */  sw         $t1, 0x4($v0)
/* 1E868 8001DC68 8E6A0000 */  lw         $t2, 0x0($s3)
/* 1E86C 8001DC6C 254B0001 */  addiu      $t3, $t2, 0x1
/* 1E870 8001DC70 AE6B0000 */  sw         $t3, 0x0($s3)
/* 1E874 8001DC74 8E420000 */  lw         $v0, 0x0($s2)
/* 1E878 8001DC78 244C0008 */  addiu      $t4, $v0, 0x8
/* 1E87C 8001DC7C AE4C0000 */  sw         $t4, 0x0($s2)
/* 1E880 8001DC80 AC5E0000 */  sw         $fp, 0x0($v0)
/* 1E884 8001DC84 8E0D0014 */  lw         $t5, 0x14($s0)
/* 1E888 8001DC88 AC4D0004 */  sw         $t5, 0x4($v0)
.L8001DC8C:
/* 1E88C 8001DC8C 960E0000 */  lhu        $t6, 0x0($s0)
/* 1E890 8001DC90 2694FFFF */  addiu      $s4, $s4, -0x1
/* 1E894 8001DC94 15C00004 */  bnez       $t6, .L8001DCA8
/* 1E898 8001DC98 00000000 */   nop
/* 1E89C 8001DC9C 8EEF0000 */  lw         $t7, 0x0($s7)
/* 1E8A0 8001DCA0 25F8FFFF */  addiu      $t8, $t7, -0x1
/* 1E8A4 8001DCA4 AEF80000 */  sw         $t8, 0x0($s7)
.L8001DCA8:
/* 1E8A8 8001DCA8 1680FF84 */  bnez       $s4, .L8001DABC
/* 1E8AC 8001DCAC 26100040 */   addiu     $s0, $s0, 0x40
.L8001DCB0:
/* 1E8B0 8001DCB0 8FBF005C */  lw         $ra, 0x5C($sp)
/* 1E8B4 8001DCB4 D7B40028 */  ldc1       $f20, 0x28($sp)
/* 1E8B8 8001DCB8 D7B60030 */  ldc1       $f22, 0x30($sp)
/* 1E8BC 8001DCBC 8FB00038 */  lw         $s0, 0x38($sp)
/* 1E8C0 8001DCC0 8FB1003C */  lw         $s1, 0x3C($sp)
/* 1E8C4 8001DCC4 8FB20040 */  lw         $s2, 0x40($sp)
/* 1E8C8 8001DCC8 8FB30044 */  lw         $s3, 0x44($sp)
/* 1E8CC 8001DCCC 8FB40048 */  lw         $s4, 0x48($sp)
/* 1E8D0 8001DCD0 8FB5004C */  lw         $s5, 0x4C($sp)
/* 1E8D4 8001DCD4 8FB60050 */  lw         $s6, 0x50($sp)
/* 1E8D8 8001DCD8 8FB70054 */  lw         $s7, 0x54($sp)
/* 1E8DC 8001DCDC 8FBE0058 */  lw         $fp, 0x58($sp)
/* 1E8E0 8001DCE0 03E00008 */  jr         $ra
/* 1E8E4 8001DCE4 27BD0100 */   addiu     $sp, $sp, 0x100

glabel func_8001DCE8
/* 1E8E8 8001DCE8 27BDFEF0 */  addiu      $sp, $sp, -0x110
/* 1E8EC 8001DCEC AFB30014 */  sw         $s3, 0x14($sp)
/* 1E8F0 8001DCF0 AFB00008 */  sw         $s0, 0x8($sp)
/* 1E8F4 8001DCF4 AFA40110 */  sw         $a0, 0x110($sp)
/* 1E8F8 8001DCF8 308E00FF */  andi       $t6, $a0, 0xFF
/* 1E8FC 8001DCFC 01C02025 */  or         $a0, $t6, $zero
/* 1E900 8001DD00 00C08025 */  or         $s0, $a2, $zero
/* 1E904 8001DD04 00E09825 */  or         $s3, $a3, $zero
/* 1E908 8001DD08 AFB20010 */  sw         $s2, 0x10($sp)
/* 1E90C 8001DD0C AFB1000C */  sw         $s1, 0xC($sp)
/* 1E910 8001DD10 AFA50114 */  sw         $a1, 0x114($sp)
/* 1E914 8001DD14 3C028005 */  lui        $v0, %hi(D_8004F0A0)
/* 1E918 8001DD18 2442F0A0 */  addiu      $v0, $v0, %lo(D_8004F0A0)
/* 1E91C 8001DD1C 00004025 */  or         $t0, $zero, $zero
.L8001DD20:
/* 1E920 8001DD20 00487821 */  addu       $t7, $v0, $t0
/* 1E924 8001DD24 91F80000 */  lbu        $t8, 0x0($t7)
/* 1E928 8001DD28 0310082A */  slt        $at, $t8, $s0
/* 1E92C 8001DD2C 50200007 */  beql       $at, $zero, .L8001DD4C
/* 1E930 8001DD30 25080001 */   addiu     $t0, $t0, 0x1
/* 1E934 8001DD34 25080001 */  addiu      $t0, $t0, 0x1
/* 1E938 8001DD38 311900FF */  andi       $t9, $t0, 0xFF
/* 1E93C 8001DD3C 2F210007 */  sltiu      $at, $t9, 0x7
/* 1E940 8001DD40 1420FFF7 */  bnez       $at, .L8001DD20
/* 1E944 8001DD44 03204025 */   or        $t0, $t9, $zero
/* 1E948 8001DD48 25080001 */  addiu      $t0, $t0, 0x1
.L8001DD4C:
/* 1E94C 8001DD4C 310E00FF */  andi       $t6, $t0, 0xFF
/* 1E950 8001DD50 01C04025 */  or         $t0, $t6, $zero
/* 1E954 8001DD54 00001825 */  or         $v1, $zero, $zero
.L8001DD58:
/* 1E958 8001DD58 00437821 */  addu       $t7, $v0, $v1
/* 1E95C 8001DD5C 91F80000 */  lbu        $t8, 0x0($t7)
/* 1E960 8001DD60 0313082A */  slt        $at, $t8, $s3
/* 1E964 8001DD64 50200007 */  beql       $at, $zero, .L8001DD84
/* 1E968 8001DD68 24630001 */   addiu     $v1, $v1, 0x1
/* 1E96C 8001DD6C 24630001 */  addiu      $v1, $v1, 0x1
/* 1E970 8001DD70 307900FF */  andi       $t9, $v1, 0xFF
/* 1E974 8001DD74 2F210007 */  sltiu      $at, $t9, 0x7
/* 1E978 8001DD78 1420FFF7 */  bnez       $at, .L8001DD58
/* 1E97C 8001DD7C 03201825 */   or        $v1, $t9, $zero
/* 1E980 8001DD80 24630001 */  addiu      $v1, $v1, 0x1
.L8001DD84:
/* 1E984 8001DD84 306E00FF */  andi       $t6, $v1, 0xFF
/* 1E988 8001DD88 2C810008 */  sltiu      $at, $a0, 0x8
/* 1E98C 8001DD8C 10200414 */  beqz       $at, .L8001EDE0
/* 1E990 8001DD90 01C01825 */   or        $v1, $t6, $zero
/* 1E994 8001DD94 00047880 */  sll        $t7, $a0, 2
/* 1E998 8001DD98 3C018007 */  lui        $at, %hi(jtbl_8006F480_main)
/* 1E99C 8001DD9C 002F0821 */  addu       $at, $at, $t7
/* 1E9A0 8001DDA0 8C2FF480 */  lw         $t7, %lo(jtbl_8006F480_main)($at)
/* 1E9A4 8001DDA4 01E00008 */  jr         $t7
/* 1E9A8 8001DDA8 00000000 */   nop
glabel .L8001DDAC
/* 1E9AC 8001DDAC 3C048008 */  lui        $a0, %hi(gMasterGfxPos)
/* 1E9B0 8001DDB0 2484A184 */  addiu      $a0, $a0, %lo(gMasterGfxPos)
/* 1E9B4 8001DDB4 8C820000 */  lw         $v0, 0x0($a0)
/* 1E9B8 8001DDB8 3C19FD10 */  lui        $t9, (0xFD100000 >> 16)
/* 1E9BC 8001DDBC 306D000F */  andi       $t5, $v1, 0xF
/* 1E9C0 8001DDC0 24580008 */  addiu      $t8, $v0, 0x8
/* 1E9C4 8001DDC4 AC980000 */  sw         $t8, 0x0($a0)
/* 1E9C8 8001DDC8 AC590000 */  sw         $t9, 0x0($v0)
/* 1E9CC 8001DDCC 8FAE0114 */  lw         $t6, 0x114($sp)
/* 1E9D0 8001DDD0 3C18F510 */  lui        $t8, (0xF5100000 >> 16)
/* 1E9D4 8001DDD4 3112000F */  andi       $s2, $t0, 0xF
/* 1E9D8 8001DDD8 AC4E0004 */  sw         $t6, 0x4($v0)
/* 1E9DC 8001DDDC 8C860000 */  lw         $a2, 0x0($a0)
/* 1E9E0 8001DDE0 3C010700 */  lui        $at, (0x7000000 >> 16)
/* 1E9E4 8001DDE4 00127100 */  sll        $t6, $s2, 4
/* 1E9E8 8001DDE8 24CF0008 */  addiu      $t7, $a2, 0x8
/* 1E9EC 8001DDEC AC8F0000 */  sw         $t7, 0x0($a0)
/* 1E9F0 8001DDF0 ACD80000 */  sw         $t8, 0x0($a2)
/* 1E9F4 8001DDF4 93AC0127 */  lbu        $t4, 0x127($sp)
/* 1E9F8 8001DDF8 93B10123 */  lbu        $s1, 0x123($sp)
/* 1E9FC 8001DDFC 000D7B80 */  sll        $t7, $t5, 14
/* 1EA00 8001DE00 31990003 */  andi       $t9, $t4, 0x3
/* 1EA04 8001DE04 00196480 */  sll        $t4, $t9, 18
/* 1EA08 8001DE08 01E06825 */  or         $t5, $t7, $zero
/* 1EA0C 8001DE0C 32380003 */  andi       $t8, $s1, 0x3
/* 1EA10 8001DE10 00188A00 */  sll        $s1, $t8, 8
/* 1EA14 8001DE14 01817825 */  or         $t7, $t4, $at
/* 1EA18 8001DE18 01EDC025 */  or         $t8, $t7, $t5
/* 1EA1C 8001DE1C 0311C825 */  or         $t9, $t8, $s1
/* 1EA20 8001DE20 01C09025 */  or         $s2, $t6, $zero
/* 1EA24 8001DE24 032E7025 */  or         $t6, $t9, $t6
/* 1EA28 8001DE28 ACCE0004 */  sw         $t6, 0x4($a2)
/* 1EA2C 8001DE2C 8C870000 */  lw         $a3, 0x0($a0)
/* 1EA30 8001DE30 3C18E600 */  lui        $t8, (0xE6000000 >> 16)
/* 1EA34 8001DE34 00102840 */  sll        $a1, $s0, 1
/* 1EA38 8001DE38 24EF0008 */  addiu      $t7, $a3, 0x8
/* 1EA3C 8001DE3C AC8F0000 */  sw         $t7, 0x0($a0)
/* 1EA40 8001DE40 ACE00004 */  sw         $zero, 0x4($a3)
/* 1EA44 8001DE44 ACF80000 */  sw         $t8, 0x0($a3)
/* 1EA48 8001DE48 02130019 */  multu      $s0, $s3
/* 1EA4C 8001DE4C 8C8A0000 */  lw         $t2, 0x0($a0)
/* 1EA50 8001DE50 3C0EF300 */  lui        $t6, (0xF3000000 >> 16)
/* 1EA54 8001DE54 240B07FF */  addiu      $t3, $zero, 0x7FF
/* 1EA58 8001DE58 25590008 */  addiu      $t9, $t2, 0x8
/* 1EA5C 8001DE5C AC990000 */  sw         $t9, 0x0($a0)
/* 1EA60 8001DE60 AD4E0000 */  sw         $t6, 0x0($t2)
/* 1EA64 8001DE64 00004812 */  mflo       $t1
/* 1EA68 8001DE68 2529FFFF */  addiu      $t1, $t1, -0x1
/* 1EA6C 8001DE6C 292107FF */  slti       $at, $t1, 0x7FF
/* 1EA70 8001DE70 10200003 */  beqz       $at, .L8001DE80
/* 1EA74 8001DE74 00000000 */   nop
/* 1EA78 8001DE78 10000001 */  b          .L8001DE80
/* 1EA7C 8001DE7C 01205825 */   or        $t3, $t1, $zero
.L8001DE80:
/* 1EA80 8001DE80 04A10003 */  bgez       $a1, .L8001DE90
/* 1EA84 8001DE84 000510C3 */   sra       $v0, $a1, 3
/* 1EA88 8001DE88 24A10007 */  addiu      $at, $a1, 0x7
/* 1EA8C 8001DE8C 000110C3 */  sra        $v0, $at, 3
.L8001DE90:
/* 1EA90 8001DE90 1C400003 */  bgtz       $v0, .L8001DEA0
/* 1EA94 8001DE94 00404825 */   or        $t1, $v0, $zero
/* 1EA98 8001DE98 10000001 */  b          .L8001DEA0
/* 1EA9C 8001DE9C 24090001 */   addiu     $t1, $zero, 0x1
.L8001DEA0:
/* 1EAA0 8001DEA0 1C400003 */  bgtz       $v0, .L8001DEB0
/* 1EAA4 8001DEA4 252F07FF */   addiu     $t7, $t1, 0x7FF
/* 1EAA8 8001DEA8 10000002 */  b          .L8001DEB4
/* 1EAAC 8001DEAC 24030001 */   addiu     $v1, $zero, 0x1
.L8001DEB0:
/* 1EAB0 8001DEB0 00401825 */  or         $v1, $v0, $zero
.L8001DEB4:
/* 1EAB4 8001DEB4 01E3001A */  div        $zero, $t7, $v1
/* 1EAB8 8001DEB8 14600002 */  bnez       $v1, .L8001DEC4
/* 1EABC 8001DEBC 00000000 */   nop
/* 1EAC0 8001DEC0 0007000D */  break      7
.L8001DEC4:
/* 1EAC4 8001DEC4 2401FFFF */  addiu      $at, $zero, -0x1
/* 1EAC8 8001DEC8 14610004 */  bne        $v1, $at, .L8001DEDC
/* 1EACC 8001DECC 3C018000 */   lui       $at, (0x80000000 >> 16)
/* 1EAD0 8001DED0 15E10002 */  bne        $t7, $at, .L8001DEDC
/* 1EAD4 8001DED4 00000000 */   nop
/* 1EAD8 8001DED8 0006000D */  break      6
.L8001DEDC:
/* 1EADC 8001DEDC 0000C012 */  mflo       $t8
/* 1EAE0 8001DEE0 33190FFF */  andi       $t9, $t8, 0xFFF
/* 1EAE4 8001DEE4 3C010700 */  lui        $at, (0x7000000 >> 16)
/* 1EAE8 8001DEE8 316F0FFF */  andi       $t7, $t3, 0xFFF
/* 1EAEC 8001DEEC 000FC300 */  sll        $t8, $t7, 12
/* 1EAF0 8001DEF0 03217025 */  or         $t6, $t9, $at
/* 1EAF4 8001DEF4 01D8C825 */  or         $t9, $t6, $t8
/* 1EAF8 8001DEF8 AD590004 */  sw         $t9, 0x4($t2)
/* 1EAFC 8001DEFC 8C820000 */  lw         $v0, 0x0($a0)
/* 1EB00 8001DF00 3C0EE700 */  lui        $t6, (0xE7000000 >> 16)
/* 1EB04 8001DF04 24B90007 */  addiu      $t9, $a1, 0x7
/* 1EB08 8001DF08 244F0008 */  addiu      $t7, $v0, 0x8
/* 1EB0C 8001DF0C AC8F0000 */  sw         $t7, 0x0($a0)
/* 1EB10 8001DF10 AC400004 */  sw         $zero, 0x4($v0)
/* 1EB14 8001DF14 AC4E0000 */  sw         $t6, 0x0($v0)
/* 1EB18 8001DF18 8C820000 */  lw         $v0, 0x0($a0)
/* 1EB1C 8001DF1C 001978C3 */  sra        $t7, $t9, 3
/* 1EB20 8001DF20 31EE01FF */  andi       $t6, $t7, 0x1FF
/* 1EB24 8001DF24 24580008 */  addiu      $t8, $v0, 0x8
/* 1EB28 8001DF28 AC980000 */  sw         $t8, 0x0($a0)
/* 1EB2C 8001DF2C 000EC240 */  sll        $t8, $t6, 9
/* 1EB30 8001DF30 018D7825 */  or         $t7, $t4, $t5
/* 1EB34 8001DF34 3C01F510 */  lui        $at, (0xF5100000 >> 16)
/* 1EB38 8001DF38 0301C825 */  or         $t9, $t8, $at
/* 1EB3C 8001DF3C 01F17025 */  or         $t6, $t7, $s1
/* 1EB40 8001DF40 01D2C025 */  or         $t8, $t6, $s2
/* 1EB44 8001DF44 AC580004 */  sw         $t8, 0x4($v0)
/* 1EB48 8001DF48 AC590000 */  sw         $t9, 0x0($v0)
/* 1EB4C 8001DF4C 8C820000 */  lw         $v0, 0x0($a0)
/* 1EB50 8001DF50 260EFFFF */  addiu      $t6, $s0, -0x1
/* 1EB54 8001DF54 000EC080 */  sll        $t8, $t6, 2
/* 1EB58 8001DF58 24590008 */  addiu      $t9, $v0, 0x8
/* 1EB5C 8001DF5C AC990000 */  sw         $t9, 0x0($a0)
/* 1EB60 8001DF60 33190FFF */  andi       $t9, $t8, 0xFFF
/* 1EB64 8001DF64 3C0FF200 */  lui        $t7, (0xF2000000 >> 16)
/* 1EB68 8001DF68 266EFFFF */  addiu      $t6, $s3, -0x1
/* 1EB6C 8001DF6C AC4F0000 */  sw         $t7, 0x0($v0)
/* 1EB70 8001DF70 00197B00 */  sll        $t7, $t9, 12
/* 1EB74 8001DF74 000EC080 */  sll        $t8, $t6, 2
/* 1EB78 8001DF78 33190FFF */  andi       $t9, $t8, 0xFFF
/* 1EB7C 8001DF7C 01F97025 */  or         $t6, $t7, $t9
/* 1EB80 8001DF80 AC4E0004 */  sw         $t6, 0x4($v0)
/* 1EB84 8001DF84 8C820000 */  lw         $v0, 0x0($a0)
/* 1EB88 8001DF88 3C0FBA00 */  lui        $t7, (0xBA000E02 >> 16)
/* 1EB8C 8001DF8C 35EF0E02 */  ori        $t7, $t7, (0xBA000E02 & 0xFFFF)
/* 1EB90 8001DF90 24580008 */  addiu      $t8, $v0, 0x8
/* 1EB94 8001DF94 AC980000 */  sw         $t8, 0x0($a0)
/* 1EB98 8001DF98 AFA200EC */  sw         $v0, 0xEC($sp)
/* 1EB9C 8001DF9C AC400004 */  sw         $zero, 0x4($v0)
/* 1EBA0 8001DFA0 AC4F0000 */  sw         $t7, 0x0($v0)
/* 1EBA4 8001DFA4 1000038F */  b          .L8001EDE4
/* 1EBA8 8001DFA8 8FB00008 */   lw        $s0, 0x8($sp)
glabel .L8001DFAC
/* 1EBAC 8001DFAC 3C048008 */  lui        $a0, %hi(gMasterGfxPos)
/* 1EBB0 8001DFB0 2484A184 */  addiu      $a0, $a0, %lo(gMasterGfxPos)
/* 1EBB4 8001DFB4 8C850000 */  lw         $a1, 0x0($a0)
/* 1EBB8 8001DFB8 3C18FD18 */  lui        $t8, (0xFD180000 >> 16)
/* 1EBBC 8001DFBC 306D000F */  andi       $t5, $v1, 0xF
/* 1EBC0 8001DFC0 24AE0008 */  addiu      $t6, $a1, 0x8
/* 1EBC4 8001DFC4 AC8E0000 */  sw         $t6, 0x0($a0)
/* 1EBC8 8001DFC8 ACB80000 */  sw         $t8, 0x0($a1)
/* 1EBCC 8001DFCC 8FAF0114 */  lw         $t7, 0x114($sp)
/* 1EBD0 8001DFD0 3C0EF518 */  lui        $t6, (0xF5180000 >> 16)
/* 1EBD4 8001DFD4 3112000F */  andi       $s2, $t0, 0xF
/* 1EBD8 8001DFD8 ACAF0004 */  sw         $t7, 0x4($a1)
/* 1EBDC 8001DFDC 8C860000 */  lw         $a2, 0x0($a0)
/* 1EBE0 8001DFE0 3C010700 */  lui        $at, (0x7000000 >> 16)
/* 1EBE4 8001DFE4 00127900 */  sll        $t7, $s2, 4
/* 1EBE8 8001DFE8 24D90008 */  addiu      $t9, $a2, 0x8
/* 1EBEC 8001DFEC AC990000 */  sw         $t9, 0x0($a0)
/* 1EBF0 8001DFF0 ACCE0000 */  sw         $t6, 0x0($a2)
/* 1EBF4 8001DFF4 93AC0127 */  lbu        $t4, 0x127($sp)
/* 1EBF8 8001DFF8 93B10123 */  lbu        $s1, 0x123($sp)
/* 1EBFC 8001DFFC 000DCB80 */  sll        $t9, $t5, 14
/* 1EC00 8001E000 31980003 */  andi       $t8, $t4, 0x3
/* 1EC04 8001E004 00186480 */  sll        $t4, $t8, 18
/* 1EC08 8001E008 03206825 */  or         $t5, $t9, $zero
/* 1EC0C 8001E00C 322E0003 */  andi       $t6, $s1, 0x3
/* 1EC10 8001E010 000E8A00 */  sll        $s1, $t6, 8
/* 1EC14 8001E014 0181C825 */  or         $t9, $t4, $at
/* 1EC18 8001E018 032D7025 */  or         $t6, $t9, $t5
/* 1EC1C 8001E01C 01D1C025 */  or         $t8, $t6, $s1
/* 1EC20 8001E020 01E09025 */  or         $s2, $t7, $zero
/* 1EC24 8001E024 030F7825 */  or         $t7, $t8, $t7
/* 1EC28 8001E028 ACCF0004 */  sw         $t7, 0x4($a2)
/* 1EC2C 8001E02C 8C870000 */  lw         $a3, 0x0($a0)
/* 1EC30 8001E030 3C0EE600 */  lui        $t6, (0xE6000000 >> 16)
/* 1EC34 8001E034 00101080 */  sll        $v0, $s0, 2
/* 1EC38 8001E038 24F90008 */  addiu      $t9, $a3, 0x8
/* 1EC3C 8001E03C AC990000 */  sw         $t9, 0x0($a0)
/* 1EC40 8001E040 ACE00004 */  sw         $zero, 0x4($a3)
/* 1EC44 8001E044 ACEE0000 */  sw         $t6, 0x0($a3)
/* 1EC48 8001E048 02130019 */  multu      $s0, $s3
/* 1EC4C 8001E04C 8C8A0000 */  lw         $t2, 0x0($a0)
/* 1EC50 8001E050 3C0FF300 */  lui        $t7, (0xF3000000 >> 16)
/* 1EC54 8001E054 240B07FF */  addiu      $t3, $zero, 0x7FF
/* 1EC58 8001E058 25580008 */  addiu      $t8, $t2, 0x8
/* 1EC5C 8001E05C AC980000 */  sw         $t8, 0x0($a0)
/* 1EC60 8001E060 AD4F0000 */  sw         $t7, 0x0($t2)
/* 1EC64 8001E064 00004812 */  mflo       $t1
/* 1EC68 8001E068 2529FFFF */  addiu      $t1, $t1, -0x1
/* 1EC6C 8001E06C 292107FF */  slti       $at, $t1, 0x7FF
/* 1EC70 8001E070 10200003 */  beqz       $at, .L8001E080
/* 1EC74 8001E074 00000000 */   nop
/* 1EC78 8001E078 10000001 */  b          .L8001E080
/* 1EC7C 8001E07C 01205825 */   or        $t3, $t1, $zero
.L8001E080:
/* 1EC80 8001E080 04410003 */  bgez       $v0, .L8001E090
/* 1EC84 8001E084 0002C8C3 */   sra       $t9, $v0, 3
/* 1EC88 8001E088 24410007 */  addiu      $at, $v0, 0x7
/* 1EC8C 8001E08C 0001C8C3 */  sra        $t9, $at, 3
.L8001E090:
/* 1EC90 8001E090 1F200003 */  bgtz       $t9, .L8001E0A0
/* 1EC94 8001E094 03201025 */   or        $v0, $t9, $zero
/* 1EC98 8001E098 10000002 */  b          .L8001E0A4
/* 1EC9C 8001E09C 24090001 */   addiu     $t1, $zero, 0x1
.L8001E0A0:
/* 1ECA0 8001E0A0 00404825 */  or         $t1, $v0, $zero
.L8001E0A4:
/* 1ECA4 8001E0A4 1C400003 */  bgtz       $v0, .L8001E0B4
/* 1ECA8 8001E0A8 252E07FF */   addiu     $t6, $t1, 0x7FF
/* 1ECAC 8001E0AC 10000002 */  b          .L8001E0B8
/* 1ECB0 8001E0B0 24030001 */   addiu     $v1, $zero, 0x1
.L8001E0B4:
/* 1ECB4 8001E0B4 00401825 */  or         $v1, $v0, $zero
.L8001E0B8:
/* 1ECB8 8001E0B8 01C3001A */  div        $zero, $t6, $v1
/* 1ECBC 8001E0BC 14600002 */  bnez       $v1, .L8001E0C8
/* 1ECC0 8001E0C0 00000000 */   nop
/* 1ECC4 8001E0C4 0007000D */  break      7
.L8001E0C8:
/* 1ECC8 8001E0C8 2401FFFF */  addiu      $at, $zero, -0x1
/* 1ECCC 8001E0CC 14610004 */  bne        $v1, $at, .L8001E0E0
/* 1ECD0 8001E0D0 3C018000 */   lui       $at, (0x80000000 >> 16)
/* 1ECD4 8001E0D4 15C10002 */  bne        $t6, $at, .L8001E0E0
/* 1ECD8 8001E0D8 00000000 */   nop
/* 1ECDC 8001E0DC 0006000D */  break      6
.L8001E0E0:
/* 1ECE0 8001E0E0 0000C012 */  mflo       $t8
/* 1ECE4 8001E0E4 330F0FFF */  andi       $t7, $t8, 0xFFF
/* 1ECE8 8001E0E8 3C010700 */  lui        $at, (0x7000000 >> 16)
/* 1ECEC 8001E0EC 316E0FFF */  andi       $t6, $t3, 0xFFF
/* 1ECF0 8001E0F0 000EC300 */  sll        $t8, $t6, 12
/* 1ECF4 8001E0F4 01E1C825 */  or         $t9, $t7, $at
/* 1ECF8 8001E0F8 03387825 */  or         $t7, $t9, $t8
/* 1ECFC 8001E0FC AD4F0004 */  sw         $t7, 0x4($t2)
/* 1ED00 8001E100 8C820000 */  lw         $v0, 0x0($a0)
/* 1ED04 8001E104 3C19E700 */  lui        $t9, (0xE7000000 >> 16)
/* 1ED08 8001E108 00107840 */  sll        $t7, $s0, 1
/* 1ED0C 8001E10C 244E0008 */  addiu      $t6, $v0, 0x8
/* 1ED10 8001E110 AC8E0000 */  sw         $t6, 0x0($a0)
/* 1ED14 8001E114 AC400004 */  sw         $zero, 0x4($v0)
/* 1ED18 8001E118 AC590000 */  sw         $t9, 0x0($v0)
/* 1ED1C 8001E11C 8C820000 */  lw         $v0, 0x0($a0)
/* 1ED20 8001E120 25EE0007 */  addiu      $t6, $t7, 0x7
/* 1ED24 8001E124 000EC8C3 */  sra        $t9, $t6, 3
/* 1ED28 8001E128 24580008 */  addiu      $t8, $v0, 0x8
/* 1ED2C 8001E12C AC980000 */  sw         $t8, 0x0($a0)
/* 1ED30 8001E130 333801FF */  andi       $t8, $t9, 0x1FF
/* 1ED34 8001E134 00187A40 */  sll        $t7, $t8, 9
/* 1ED38 8001E138 018DC825 */  or         $t9, $t4, $t5
/* 1ED3C 8001E13C 3C01F518 */  lui        $at, (0xF5180000 >> 16)
/* 1ED40 8001E140 01E17025 */  or         $t6, $t7, $at
/* 1ED44 8001E144 0331C025 */  or         $t8, $t9, $s1
/* 1ED48 8001E148 03127825 */  or         $t7, $t8, $s2
/* 1ED4C 8001E14C AC4F0004 */  sw         $t7, 0x4($v0)
/* 1ED50 8001E150 AC4E0000 */  sw         $t6, 0x0($v0)
/* 1ED54 8001E154 8C820000 */  lw         $v0, 0x0($a0)
/* 1ED58 8001E158 2618FFFF */  addiu      $t8, $s0, -0x1
/* 1ED5C 8001E15C 00187880 */  sll        $t7, $t8, 2
/* 1ED60 8001E160 244E0008 */  addiu      $t6, $v0, 0x8
/* 1ED64 8001E164 AC8E0000 */  sw         $t6, 0x0($a0)
/* 1ED68 8001E168 31EE0FFF */  andi       $t6, $t7, 0xFFF
/* 1ED6C 8001E16C 3C19F200 */  lui        $t9, (0xF2000000 >> 16)
/* 1ED70 8001E170 2678FFFF */  addiu      $t8, $s3, -0x1
/* 1ED74 8001E174 AC590000 */  sw         $t9, 0x0($v0)
/* 1ED78 8001E178 000ECB00 */  sll        $t9, $t6, 12
/* 1ED7C 8001E17C 00187880 */  sll        $t7, $t8, 2
/* 1ED80 8001E180 31EE0FFF */  andi       $t6, $t7, 0xFFF
/* 1ED84 8001E184 032EC025 */  or         $t8, $t9, $t6
/* 1ED88 8001E188 AC580004 */  sw         $t8, 0x4($v0)
/* 1ED8C 8001E18C 8C820000 */  lw         $v0, 0x0($a0)
/* 1ED90 8001E190 3C19BA00 */  lui        $t9, (0xBA000E02 >> 16)
/* 1ED94 8001E194 37390E02 */  ori        $t9, $t9, (0xBA000E02 & 0xFFFF)
/* 1ED98 8001E198 244F0008 */  addiu      $t7, $v0, 0x8
/* 1ED9C 8001E19C AC8F0000 */  sw         $t7, 0x0($a0)
/* 1EDA0 8001E1A0 AC400004 */  sw         $zero, 0x4($v0)
/* 1EDA4 8001E1A4 AC590000 */  sw         $t9, 0x0($v0)
/* 1EDA8 8001E1A8 1000030E */  b          .L8001EDE4
/* 1EDAC 8001E1AC 8FB00008 */   lw        $s0, 0x8($sp)
glabel .L8001E1B0
/* 1EDB0 8001E1B0 3C048008 */  lui        $a0, %hi(gMasterGfxPos)
/* 1EDB4 8001E1B4 2484A184 */  addiu      $a0, $a0, %lo(gMasterGfxPos)
/* 1EDB8 8001E1B8 8C850000 */  lw         $a1, 0x0($a0)
/* 1EDBC 8001E1BC 3C18FD90 */  lui        $t8, (0xFD900000 >> 16)
/* 1EDC0 8001E1C0 306D000F */  andi       $t5, $v1, 0xF
/* 1EDC4 8001E1C4 24AE0008 */  addiu      $t6, $a1, 0x8
/* 1EDC8 8001E1C8 AC8E0000 */  sw         $t6, 0x0($a0)
/* 1EDCC 8001E1CC ACB80000 */  sw         $t8, 0x0($a1)
/* 1EDD0 8001E1D0 8FAF0114 */  lw         $t7, 0x114($sp)
/* 1EDD4 8001E1D4 3C0EF590 */  lui        $t6, (0xF5900000 >> 16)
/* 1EDD8 8001E1D8 3112000F */  andi       $s2, $t0, 0xF
/* 1EDDC 8001E1DC ACAF0004 */  sw         $t7, 0x4($a1)
/* 1EDE0 8001E1E0 8C860000 */  lw         $a2, 0x0($a0)
/* 1EDE4 8001E1E4 3C010700 */  lui        $at, (0x7000000 >> 16)
/* 1EDE8 8001E1E8 00127900 */  sll        $t7, $s2, 4
/* 1EDEC 8001E1EC 24D90008 */  addiu      $t9, $a2, 0x8
/* 1EDF0 8001E1F0 AC990000 */  sw         $t9, 0x0($a0)
/* 1EDF4 8001E1F4 ACCE0000 */  sw         $t6, 0x0($a2)
/* 1EDF8 8001E1F8 93AC0127 */  lbu        $t4, 0x127($sp)
/* 1EDFC 8001E1FC 93B10123 */  lbu        $s1, 0x123($sp)
/* 1EE00 8001E200 000DCB80 */  sll        $t9, $t5, 14
/* 1EE04 8001E204 31980003 */  andi       $t8, $t4, 0x3
/* 1EE08 8001E208 00186480 */  sll        $t4, $t8, 18
/* 1EE0C 8001E20C 03206825 */  or         $t5, $t9, $zero
/* 1EE10 8001E210 322E0003 */  andi       $t6, $s1, 0x3
/* 1EE14 8001E214 000E8A00 */  sll        $s1, $t6, 8
/* 1EE18 8001E218 0181C825 */  or         $t9, $t4, $at
/* 1EE1C 8001E21C 032D7025 */  or         $t6, $t9, $t5
/* 1EE20 8001E220 01D1C025 */  or         $t8, $t6, $s1
/* 1EE24 8001E224 01E09025 */  or         $s2, $t7, $zero
/* 1EE28 8001E228 030F7825 */  or         $t7, $t8, $t7
/* 1EE2C 8001E22C ACCF0004 */  sw         $t7, 0x4($a2)
/* 1EE30 8001E230 8C870000 */  lw         $a3, 0x0($a0)
/* 1EE34 8001E234 3C0EE600 */  lui        $t6, (0xE6000000 >> 16)
/* 1EE38 8001E238 02005025 */  or         $t2, $s0, $zero
/* 1EE3C 8001E23C 24F90008 */  addiu      $t9, $a3, 0x8
/* 1EE40 8001E240 AC990000 */  sw         $t9, 0x0($a0)
/* 1EE44 8001E244 ACE00004 */  sw         $zero, 0x4($a3)
/* 1EE48 8001E248 ACEE0000 */  sw         $t6, 0x0($a3)
/* 1EE4C 8001E24C 02130019 */  multu      $s0, $s3
/* 1EE50 8001E250 8C820000 */  lw         $v0, 0x0($a0)
/* 1EE54 8001E254 3C0FF300 */  lui        $t7, (0xF3000000 >> 16)
/* 1EE58 8001E258 240B07FF */  addiu      $t3, $zero, 0x7FF
/* 1EE5C 8001E25C 24580008 */  addiu      $t8, $v0, 0x8
/* 1EE60 8001E260 AC980000 */  sw         $t8, 0x0($a0)
/* 1EE64 8001E264 AC4F0000 */  sw         $t7, 0x0($v0)
/* 1EE68 8001E268 AFA200BC */  sw         $v0, 0xBC($sp)
/* 1EE6C 8001E26C 00004812 */  mflo       $t1
/* 1EE70 8001E270 25290001 */  addiu      $t1, $t1, 0x1
/* 1EE74 8001E274 0009C843 */  sra        $t9, $t1, 1
/* 1EE78 8001E278 2729FFFF */  addiu      $t1, $t9, -0x1
/* 1EE7C 8001E27C 292107FF */  slti       $at, $t1, 0x7FF
/* 1EE80 8001E280 10200003 */  beqz       $at, .L8001E290
/* 1EE84 8001E284 00000000 */   nop
/* 1EE88 8001E288 10000001 */  b          .L8001E290
/* 1EE8C 8001E28C 01205825 */   or        $t3, $t1, $zero
.L8001E290:
/* 1EE90 8001E290 05410003 */  bgez       $t2, .L8001E2A0
/* 1EE94 8001E294 000A10C3 */   sra       $v0, $t2, 3
/* 1EE98 8001E298 25410007 */  addiu      $at, $t2, 0x7
/* 1EE9C 8001E29C 000110C3 */  sra        $v0, $at, 3
.L8001E2A0:
/* 1EEA0 8001E2A0 1C400003 */  bgtz       $v0, .L8001E2B0
/* 1EEA4 8001E2A4 00404825 */   or        $t1, $v0, $zero
/* 1EEA8 8001E2A8 10000001 */  b          .L8001E2B0
/* 1EEAC 8001E2AC 24090001 */   addiu     $t1, $zero, 0x1
.L8001E2B0:
/* 1EEB0 8001E2B0 1C400003 */  bgtz       $v0, .L8001E2C0
/* 1EEB4 8001E2B4 252E07FF */   addiu     $t6, $t1, 0x7FF
/* 1EEB8 8001E2B8 10000002 */  b          .L8001E2C4
/* 1EEBC 8001E2BC 24030001 */   addiu     $v1, $zero, 0x1
.L8001E2C0:
/* 1EEC0 8001E2C0 00401825 */  or         $v1, $v0, $zero
.L8001E2C4:
/* 1EEC4 8001E2C4 01C3001A */  div        $zero, $t6, $v1
/* 1EEC8 8001E2C8 14600002 */  bnez       $v1, .L8001E2D4
/* 1EECC 8001E2CC 00000000 */   nop
/* 1EED0 8001E2D0 0007000D */  break      7
.L8001E2D4:
/* 1EED4 8001E2D4 2401FFFF */  addiu      $at, $zero, -0x1
/* 1EED8 8001E2D8 14610004 */  bne        $v1, $at, .L8001E2EC
/* 1EEDC 8001E2DC 3C018000 */   lui       $at, (0x80000000 >> 16)
/* 1EEE0 8001E2E0 15C10002 */  bne        $t6, $at, .L8001E2EC
/* 1EEE4 8001E2E4 00000000 */   nop
/* 1EEE8 8001E2E8 0006000D */  break      6
.L8001E2EC:
/* 1EEEC 8001E2EC 0000C012 */  mflo       $t8
/* 1EEF0 8001E2F0 330F0FFF */  andi       $t7, $t8, 0xFFF
/* 1EEF4 8001E2F4 316E0FFF */  andi       $t6, $t3, 0xFFF
/* 1EEF8 8001E2F8 000EC300 */  sll        $t8, $t6, 12
/* 1EEFC 8001E2FC 8FAE00BC */  lw         $t6, 0xBC($sp)
/* 1EF00 8001E300 3C010700 */  lui        $at, (0x7000000 >> 16)
/* 1EF04 8001E304 01E1C825 */  or         $t9, $t7, $at
/* 1EF08 8001E308 03387825 */  or         $t7, $t9, $t8
/* 1EF0C 8001E30C ADCF0004 */  sw         $t7, 0x4($t6)
/* 1EF10 8001E310 8C820000 */  lw         $v0, 0x0($a0)
/* 1EF14 8001E314 3C18E700 */  lui        $t8, (0xE7000000 >> 16)
/* 1EF18 8001E318 254E0007 */  addiu      $t6, $t2, 0x7
/* 1EF1C 8001E31C 24590008 */  addiu      $t9, $v0, 0x8
/* 1EF20 8001E320 AC990000 */  sw         $t9, 0x0($a0)
/* 1EF24 8001E324 AC400004 */  sw         $zero, 0x4($v0)
/* 1EF28 8001E328 AC580000 */  sw         $t8, 0x0($v0)
/* 1EF2C 8001E32C 8C820000 */  lw         $v0, 0x0($a0)
/* 1EF30 8001E330 000EC8C3 */  sra        $t9, $t6, 3
/* 1EF34 8001E334 333801FF */  andi       $t8, $t9, 0x1FF
/* 1EF38 8001E338 244F0008 */  addiu      $t7, $v0, 0x8
/* 1EF3C 8001E33C AC8F0000 */  sw         $t7, 0x0($a0)
/* 1EF40 8001E340 00187A40 */  sll        $t7, $t8, 9
/* 1EF44 8001E344 018DC825 */  or         $t9, $t4, $t5
/* 1EF48 8001E348 3C01F588 */  lui        $at, (0xF5880000 >> 16)
/* 1EF4C 8001E34C 01E17025 */  or         $t6, $t7, $at
/* 1EF50 8001E350 0331C025 */  or         $t8, $t9, $s1
/* 1EF54 8001E354 03127825 */  or         $t7, $t8, $s2
/* 1EF58 8001E358 AC4F0004 */  sw         $t7, 0x4($v0)
/* 1EF5C 8001E35C AC4E0000 */  sw         $t6, 0x0($v0)
/* 1EF60 8001E360 8C820000 */  lw         $v0, 0x0($a0)
/* 1EF64 8001E364 2618FFFF */  addiu      $t8, $s0, -0x1
/* 1EF68 8001E368 00187880 */  sll        $t7, $t8, 2
/* 1EF6C 8001E36C 244E0008 */  addiu      $t6, $v0, 0x8
/* 1EF70 8001E370 AC8E0000 */  sw         $t6, 0x0($a0)
/* 1EF74 8001E374 31EE0FFF */  andi       $t6, $t7, 0xFFF
/* 1EF78 8001E378 3C19F200 */  lui        $t9, (0xF2000000 >> 16)
/* 1EF7C 8001E37C 2678FFFF */  addiu      $t8, $s3, -0x1
/* 1EF80 8001E380 AC590000 */  sw         $t9, 0x0($v0)
/* 1EF84 8001E384 000ECB00 */  sll        $t9, $t6, 12
/* 1EF88 8001E388 00187880 */  sll        $t7, $t8, 2
/* 1EF8C 8001E38C 31EE0FFF */  andi       $t6, $t7, 0xFFF
/* 1EF90 8001E390 032EC025 */  or         $t8, $t9, $t6
/* 1EF94 8001E394 AC580004 */  sw         $t8, 0x4($v0)
/* 1EF98 8001E398 8C820000 */  lw         $v0, 0x0($a0)
/* 1EF9C 8001E39C 3C19BA00 */  lui        $t9, (0xBA000E02 >> 16)
/* 1EFA0 8001E3A0 37390E02 */  ori        $t9, $t9, (0xBA000E02 & 0xFFFF)
/* 1EFA4 8001E3A4 244F0008 */  addiu      $t7, $v0, 0x8
/* 1EFA8 8001E3A8 AC8F0000 */  sw         $t7, 0x0($a0)
/* 1EFAC 8001E3AC AC400004 */  sw         $zero, 0x4($v0)
/* 1EFB0 8001E3B0 AC590000 */  sw         $t9, 0x0($v0)
/* 1EFB4 8001E3B4 1000028B */  b          .L8001EDE4
/* 1EFB8 8001E3B8 8FB00008 */   lw        $s0, 0x8($sp)
glabel .L8001E3BC
/* 1EFBC 8001E3BC 3C048008 */  lui        $a0, %hi(gMasterGfxPos)
/* 1EFC0 8001E3C0 2484A184 */  addiu      $a0, $a0, %lo(gMasterGfxPos)
/* 1EFC4 8001E3C4 8C850000 */  lw         $a1, 0x0($a0)
/* 1EFC8 8001E3C8 3C18FD70 */  lui        $t8, (0xFD700000 >> 16)
/* 1EFCC 8001E3CC 306D000F */  andi       $t5, $v1, 0xF
/* 1EFD0 8001E3D0 24AE0008 */  addiu      $t6, $a1, 0x8
/* 1EFD4 8001E3D4 AC8E0000 */  sw         $t6, 0x0($a0)
/* 1EFD8 8001E3D8 ACB80000 */  sw         $t8, 0x0($a1)
/* 1EFDC 8001E3DC 8FAF0114 */  lw         $t7, 0x114($sp)
/* 1EFE0 8001E3E0 3C0EF570 */  lui        $t6, (0xF5700000 >> 16)
/* 1EFE4 8001E3E4 3112000F */  andi       $s2, $t0, 0xF
/* 1EFE8 8001E3E8 ACAF0004 */  sw         $t7, 0x4($a1)
/* 1EFEC 8001E3EC 8C860000 */  lw         $a2, 0x0($a0)
/* 1EFF0 8001E3F0 3C010700 */  lui        $at, (0x7000000 >> 16)
/* 1EFF4 8001E3F4 00127900 */  sll        $t7, $s2, 4
/* 1EFF8 8001E3F8 24D90008 */  addiu      $t9, $a2, 0x8
/* 1EFFC 8001E3FC AC990000 */  sw         $t9, 0x0($a0)
/* 1F000 8001E400 ACCE0000 */  sw         $t6, 0x0($a2)
/* 1F004 8001E404 93AC0127 */  lbu        $t4, 0x127($sp)
/* 1F008 8001E408 93B10123 */  lbu        $s1, 0x123($sp)
/* 1F00C 8001E40C 000DCB80 */  sll        $t9, $t5, 14
/* 1F010 8001E410 31980003 */  andi       $t8, $t4, 0x3
/* 1F014 8001E414 00186480 */  sll        $t4, $t8, 18
/* 1F018 8001E418 03206825 */  or         $t5, $t9, $zero
/* 1F01C 8001E41C 322E0003 */  andi       $t6, $s1, 0x3
/* 1F020 8001E420 000E8A00 */  sll        $s1, $t6, 8
/* 1F024 8001E424 0181C825 */  or         $t9, $t4, $at
/* 1F028 8001E428 032D7025 */  or         $t6, $t9, $t5
/* 1F02C 8001E42C 01D1C025 */  or         $t8, $t6, $s1
/* 1F030 8001E430 01E09025 */  or         $s2, $t7, $zero
/* 1F034 8001E434 030F7825 */  or         $t7, $t8, $t7
/* 1F038 8001E438 ACCF0004 */  sw         $t7, 0x4($a2)
/* 1F03C 8001E43C 8C870000 */  lw         $a3, 0x0($a0)
/* 1F040 8001E440 3C0EE600 */  lui        $t6, (0xE6000000 >> 16)
/* 1F044 8001E444 02005025 */  or         $t2, $s0, $zero
/* 1F048 8001E448 24F90008 */  addiu      $t9, $a3, 0x8
/* 1F04C 8001E44C AC990000 */  sw         $t9, 0x0($a0)
/* 1F050 8001E450 ACE00004 */  sw         $zero, 0x4($a3)
/* 1F054 8001E454 ACEE0000 */  sw         $t6, 0x0($a3)
/* 1F058 8001E458 02130019 */  multu      $s0, $s3
/* 1F05C 8001E45C 8C820000 */  lw         $v0, 0x0($a0)
/* 1F060 8001E460 3C0FF300 */  lui        $t7, (0xF3000000 >> 16)
/* 1F064 8001E464 240B07FF */  addiu      $t3, $zero, 0x7FF
/* 1F068 8001E468 24580008 */  addiu      $t8, $v0, 0x8
/* 1F06C 8001E46C AC980000 */  sw         $t8, 0x0($a0)
/* 1F070 8001E470 AC4F0000 */  sw         $t7, 0x0($v0)
/* 1F074 8001E474 AFA2009C */  sw         $v0, 0x9C($sp)
/* 1F078 8001E478 00004812 */  mflo       $t1
/* 1F07C 8001E47C 25290001 */  addiu      $t1, $t1, 0x1
/* 1F080 8001E480 0009C843 */  sra        $t9, $t1, 1
/* 1F084 8001E484 2729FFFF */  addiu      $t1, $t9, -0x1
/* 1F088 8001E488 292107FF */  slti       $at, $t1, 0x7FF
/* 1F08C 8001E48C 10200003 */  beqz       $at, .L8001E49C
/* 1F090 8001E490 00000000 */   nop
/* 1F094 8001E494 10000001 */  b          .L8001E49C
/* 1F098 8001E498 01205825 */   or        $t3, $t1, $zero
.L8001E49C:
/* 1F09C 8001E49C 05410003 */  bgez       $t2, .L8001E4AC
/* 1F0A0 8001E4A0 000A10C3 */   sra       $v0, $t2, 3
/* 1F0A4 8001E4A4 25410007 */  addiu      $at, $t2, 0x7
/* 1F0A8 8001E4A8 000110C3 */  sra        $v0, $at, 3
.L8001E4AC:
/* 1F0AC 8001E4AC 1C400003 */  bgtz       $v0, .L8001E4BC
/* 1F0B0 8001E4B0 00404825 */   or        $t1, $v0, $zero
/* 1F0B4 8001E4B4 10000001 */  b          .L8001E4BC
/* 1F0B8 8001E4B8 24090001 */   addiu     $t1, $zero, 0x1
.L8001E4BC:
/* 1F0BC 8001E4BC 1C400003 */  bgtz       $v0, .L8001E4CC
/* 1F0C0 8001E4C0 252E07FF */   addiu     $t6, $t1, 0x7FF
/* 1F0C4 8001E4C4 10000002 */  b          .L8001E4D0
/* 1F0C8 8001E4C8 24030001 */   addiu     $v1, $zero, 0x1
.L8001E4CC:
/* 1F0CC 8001E4CC 00401825 */  or         $v1, $v0, $zero
.L8001E4D0:
/* 1F0D0 8001E4D0 01C3001A */  div        $zero, $t6, $v1
/* 1F0D4 8001E4D4 14600002 */  bnez       $v1, .L8001E4E0
/* 1F0D8 8001E4D8 00000000 */   nop
/* 1F0DC 8001E4DC 0007000D */  break      7
.L8001E4E0:
/* 1F0E0 8001E4E0 2401FFFF */  addiu      $at, $zero, -0x1
/* 1F0E4 8001E4E4 14610004 */  bne        $v1, $at, .L8001E4F8
/* 1F0E8 8001E4E8 3C018000 */   lui       $at, (0x80000000 >> 16)
/* 1F0EC 8001E4EC 15C10002 */  bne        $t6, $at, .L8001E4F8
/* 1F0F0 8001E4F0 00000000 */   nop
/* 1F0F4 8001E4F4 0006000D */  break      6
.L8001E4F8:
/* 1F0F8 8001E4F8 0000C012 */  mflo       $t8
/* 1F0FC 8001E4FC 330F0FFF */  andi       $t7, $t8, 0xFFF
/* 1F100 8001E500 316E0FFF */  andi       $t6, $t3, 0xFFF
/* 1F104 8001E504 000EC300 */  sll        $t8, $t6, 12
/* 1F108 8001E508 8FAE009C */  lw         $t6, 0x9C($sp)
/* 1F10C 8001E50C 3C010700 */  lui        $at, (0x7000000 >> 16)
/* 1F110 8001E510 01E1C825 */  or         $t9, $t7, $at
/* 1F114 8001E514 03387825 */  or         $t7, $t9, $t8
/* 1F118 8001E518 ADCF0004 */  sw         $t7, 0x4($t6)
/* 1F11C 8001E51C 8C820000 */  lw         $v0, 0x0($a0)
/* 1F120 8001E520 3C18E700 */  lui        $t8, (0xE7000000 >> 16)
/* 1F124 8001E524 254E0007 */  addiu      $t6, $t2, 0x7
/* 1F128 8001E528 24590008 */  addiu      $t9, $v0, 0x8
/* 1F12C 8001E52C AC990000 */  sw         $t9, 0x0($a0)
/* 1F130 8001E530 AC400004 */  sw         $zero, 0x4($v0)
/* 1F134 8001E534 AC580000 */  sw         $t8, 0x0($v0)
/* 1F138 8001E538 8C820000 */  lw         $v0, 0x0($a0)
/* 1F13C 8001E53C 000EC8C3 */  sra        $t9, $t6, 3
/* 1F140 8001E540 333801FF */  andi       $t8, $t9, 0x1FF
/* 1F144 8001E544 244F0008 */  addiu      $t7, $v0, 0x8
/* 1F148 8001E548 AC8F0000 */  sw         $t7, 0x0($a0)
/* 1F14C 8001E54C 00187A40 */  sll        $t7, $t8, 9
/* 1F150 8001E550 018DC825 */  or         $t9, $t4, $t5
/* 1F154 8001E554 3C01F568 */  lui        $at, (0xF5680000 >> 16)
/* 1F158 8001E558 01E17025 */  or         $t6, $t7, $at
/* 1F15C 8001E55C 0331C025 */  or         $t8, $t9, $s1
/* 1F160 8001E560 03127825 */  or         $t7, $t8, $s2
/* 1F164 8001E564 AC4F0004 */  sw         $t7, 0x4($v0)
/* 1F168 8001E568 AC4E0000 */  sw         $t6, 0x0($v0)
/* 1F16C 8001E56C 8C820000 */  lw         $v0, 0x0($a0)
/* 1F170 8001E570 2618FFFF */  addiu      $t8, $s0, -0x1
/* 1F174 8001E574 00187880 */  sll        $t7, $t8, 2
/* 1F178 8001E578 244E0008 */  addiu      $t6, $v0, 0x8
/* 1F17C 8001E57C AC8E0000 */  sw         $t6, 0x0($a0)
/* 1F180 8001E580 31EE0FFF */  andi       $t6, $t7, 0xFFF
/* 1F184 8001E584 3C19F200 */  lui        $t9, (0xF2000000 >> 16)
/* 1F188 8001E588 2678FFFF */  addiu      $t8, $s3, -0x1
/* 1F18C 8001E58C AC590000 */  sw         $t9, 0x0($v0)
/* 1F190 8001E590 000ECB00 */  sll        $t9, $t6, 12
/* 1F194 8001E594 00187880 */  sll        $t7, $t8, 2
/* 1F198 8001E598 31EE0FFF */  andi       $t6, $t7, 0xFFF
/* 1F19C 8001E59C 032EC025 */  or         $t8, $t9, $t6
/* 1F1A0 8001E5A0 AC580004 */  sw         $t8, 0x4($v0)
/* 1F1A4 8001E5A4 8C820000 */  lw         $v0, 0x0($a0)
/* 1F1A8 8001E5A8 3C19BA00 */  lui        $t9, (0xBA000E02 >> 16)
/* 1F1AC 8001E5AC 37390E02 */  ori        $t9, $t9, (0xBA000E02 & 0xFFFF)
/* 1F1B0 8001E5B0 244F0008 */  addiu      $t7, $v0, 0x8
/* 1F1B4 8001E5B4 AC8F0000 */  sw         $t7, 0x0($a0)
/* 1F1B8 8001E5B8 AC400004 */  sw         $zero, 0x4($v0)
/* 1F1BC 8001E5BC AC590000 */  sw         $t9, 0x0($v0)
/* 1F1C0 8001E5C0 10000208 */  b          .L8001EDE4
/* 1F1C4 8001E5C4 8FB00008 */   lw        $s0, 0x8($sp)
glabel .L8001E5C8
/* 1F1C8 8001E5C8 3C048008 */  lui        $a0, %hi(gMasterGfxPos)
/* 1F1CC 8001E5CC 2484A184 */  addiu      $a0, $a0, %lo(gMasterGfxPos)
/* 1F1D0 8001E5D0 8C850000 */  lw         $a1, 0x0($a0)
/* 1F1D4 8001E5D4 3C18FD90 */  lui        $t8, (0xFD900000 >> 16)
/* 1F1D8 8001E5D8 306D000F */  andi       $t5, $v1, 0xF
/* 1F1DC 8001E5DC 24AE0008 */  addiu      $t6, $a1, 0x8
/* 1F1E0 8001E5E0 AC8E0000 */  sw         $t6, 0x0($a0)
/* 1F1E4 8001E5E4 ACB80000 */  sw         $t8, 0x0($a1)
/* 1F1E8 8001E5E8 8FAF0114 */  lw         $t7, 0x114($sp)
/* 1F1EC 8001E5EC 3C0EF590 */  lui        $t6, (0xF5900000 >> 16)
/* 1F1F0 8001E5F0 3112000F */  andi       $s2, $t0, 0xF
/* 1F1F4 8001E5F4 ACAF0004 */  sw         $t7, 0x4($a1)
/* 1F1F8 8001E5F8 8C860000 */  lw         $a2, 0x0($a0)
/* 1F1FC 8001E5FC 3C010700 */  lui        $at, (0x7000000 >> 16)
/* 1F200 8001E600 00127900 */  sll        $t7, $s2, 4
/* 1F204 8001E604 24D90008 */  addiu      $t9, $a2, 0x8
/* 1F208 8001E608 AC990000 */  sw         $t9, 0x0($a0)
/* 1F20C 8001E60C ACCE0000 */  sw         $t6, 0x0($a2)
/* 1F210 8001E610 93AC0127 */  lbu        $t4, 0x127($sp)
/* 1F214 8001E614 93B10123 */  lbu        $s1, 0x123($sp)
/* 1F218 8001E618 000DCB80 */  sll        $t9, $t5, 14
/* 1F21C 8001E61C 31980003 */  andi       $t8, $t4, 0x3
/* 1F220 8001E620 00186480 */  sll        $t4, $t8, 18
/* 1F224 8001E624 03206825 */  or         $t5, $t9, $zero
/* 1F228 8001E628 322E0003 */  andi       $t6, $s1, 0x3
/* 1F22C 8001E62C 000E8A00 */  sll        $s1, $t6, 8
/* 1F230 8001E630 0181C825 */  or         $t9, $t4, $at
/* 1F234 8001E634 032D7025 */  or         $t6, $t9, $t5
/* 1F238 8001E638 01D1C025 */  or         $t8, $t6, $s1
/* 1F23C 8001E63C 01E09025 */  or         $s2, $t7, $zero
/* 1F240 8001E640 030F7825 */  or         $t7, $t8, $t7
/* 1F244 8001E644 ACCF0004 */  sw         $t7, 0x4($a2)
/* 1F248 8001E648 8C870000 */  lw         $a3, 0x0($a0)
/* 1F24C 8001E64C 3C0EE600 */  lui        $t6, (0xE6000000 >> 16)
/* 1F250 8001E650 240B07FF */  addiu      $t3, $zero, 0x7FF
/* 1F254 8001E654 24F90008 */  addiu      $t9, $a3, 0x8
/* 1F258 8001E658 AC990000 */  sw         $t9, 0x0($a0)
/* 1F25C 8001E65C ACE00004 */  sw         $zero, 0x4($a3)
/* 1F260 8001E660 ACEE0000 */  sw         $t6, 0x0($a3)
/* 1F264 8001E664 02130019 */  multu      $s0, $s3
/* 1F268 8001E668 8C8A0000 */  lw         $t2, 0x0($a0)
/* 1F26C 8001E66C 3C0FF300 */  lui        $t7, (0xF3000000 >> 16)
/* 1F270 8001E670 25580008 */  addiu      $t8, $t2, 0x8
/* 1F274 8001E674 AC980000 */  sw         $t8, 0x0($a0)
/* 1F278 8001E678 AD4F0000 */  sw         $t7, 0x0($t2)
/* 1F27C 8001E67C 00004812 */  mflo       $t1
/* 1F280 8001E680 25290003 */  addiu      $t1, $t1, 0x3
/* 1F284 8001E684 0009C883 */  sra        $t9, $t1, 2
/* 1F288 8001E688 2729FFFF */  addiu      $t1, $t9, -0x1
/* 1F28C 8001E68C 292107FF */  slti       $at, $t1, 0x7FF
/* 1F290 8001E690 10200003 */  beqz       $at, .L8001E6A0
/* 1F294 8001E694 00000000 */   nop
/* 1F298 8001E698 10000001 */  b          .L8001E6A0
/* 1F29C 8001E69C 01205825 */   or        $t3, $t1, $zero
.L8001E6A0:
/* 1F2A0 8001E6A0 06010003 */  bgez       $s0, .L8001E6B0
/* 1F2A4 8001E6A4 00101103 */   sra       $v0, $s0, 4
/* 1F2A8 8001E6A8 2601000F */  addiu      $at, $s0, 0xF
/* 1F2AC 8001E6AC 00011103 */  sra        $v0, $at, 4
.L8001E6B0:
/* 1F2B0 8001E6B0 1C400003 */  bgtz       $v0, .L8001E6C0
/* 1F2B4 8001E6B4 00404825 */   or        $t1, $v0, $zero
/* 1F2B8 8001E6B8 10000001 */  b          .L8001E6C0
/* 1F2BC 8001E6BC 24090001 */   addiu     $t1, $zero, 0x1
.L8001E6C0:
/* 1F2C0 8001E6C0 1C400003 */  bgtz       $v0, .L8001E6D0
/* 1F2C4 8001E6C4 252E07FF */   addiu     $t6, $t1, 0x7FF
/* 1F2C8 8001E6C8 10000002 */  b          .L8001E6D4
/* 1F2CC 8001E6CC 24030001 */   addiu     $v1, $zero, 0x1
.L8001E6D0:
/* 1F2D0 8001E6D0 00401825 */  or         $v1, $v0, $zero
.L8001E6D4:
/* 1F2D4 8001E6D4 01C3001A */  div        $zero, $t6, $v1
/* 1F2D8 8001E6D8 14600002 */  bnez       $v1, .L8001E6E4
/* 1F2DC 8001E6DC 00000000 */   nop
/* 1F2E0 8001E6E0 0007000D */  break      7
.L8001E6E4:
/* 1F2E4 8001E6E4 2401FFFF */  addiu      $at, $zero, -0x1
/* 1F2E8 8001E6E8 14610004 */  bne        $v1, $at, .L8001E6FC
/* 1F2EC 8001E6EC 3C018000 */   lui       $at, (0x80000000 >> 16)
/* 1F2F0 8001E6F0 15C10002 */  bne        $t6, $at, .L8001E6FC
/* 1F2F4 8001E6F4 00000000 */   nop
/* 1F2F8 8001E6F8 0006000D */  break      6
.L8001E6FC:
/* 1F2FC 8001E6FC 0000C012 */  mflo       $t8
/* 1F300 8001E700 330F0FFF */  andi       $t7, $t8, 0xFFF
/* 1F304 8001E704 3C010700 */  lui        $at, (0x7000000 >> 16)
/* 1F308 8001E708 316E0FFF */  andi       $t6, $t3, 0xFFF
/* 1F30C 8001E70C 000EC300 */  sll        $t8, $t6, 12
/* 1F310 8001E710 01E1C825 */  or         $t9, $t7, $at
/* 1F314 8001E714 03387825 */  or         $t7, $t9, $t8
/* 1F318 8001E718 AD4F0004 */  sw         $t7, 0x4($t2)
/* 1F31C 8001E71C 8C820000 */  lw         $v0, 0x0($a0)
/* 1F320 8001E720 3C19E700 */  lui        $t9, (0xE7000000 >> 16)
/* 1F324 8001E724 00107843 */  sra        $t7, $s0, 1
/* 1F328 8001E728 244E0008 */  addiu      $t6, $v0, 0x8
/* 1F32C 8001E72C AC8E0000 */  sw         $t6, 0x0($a0)
/* 1F330 8001E730 AC400004 */  sw         $zero, 0x4($v0)
/* 1F334 8001E734 AC590000 */  sw         $t9, 0x0($v0)
/* 1F338 8001E738 8C820000 */  lw         $v0, 0x0($a0)
/* 1F33C 8001E73C 25EE0007 */  addiu      $t6, $t7, 0x7
/* 1F340 8001E740 000EC8C3 */  sra        $t9, $t6, 3
/* 1F344 8001E744 24580008 */  addiu      $t8, $v0, 0x8
/* 1F348 8001E748 AC980000 */  sw         $t8, 0x0($a0)
/* 1F34C 8001E74C 333801FF */  andi       $t8, $t9, 0x1FF
/* 1F350 8001E750 00187A40 */  sll        $t7, $t8, 9
/* 1F354 8001E754 018DC825 */  or         $t9, $t4, $t5
/* 1F358 8001E758 3C01F580 */  lui        $at, (0xF5800000 >> 16)
/* 1F35C 8001E75C 01E17025 */  or         $t6, $t7, $at
/* 1F360 8001E760 0331C025 */  or         $t8, $t9, $s1
/* 1F364 8001E764 03127825 */  or         $t7, $t8, $s2
/* 1F368 8001E768 AC4F0004 */  sw         $t7, 0x4($v0)
/* 1F36C 8001E76C AC4E0000 */  sw         $t6, 0x0($v0)
/* 1F370 8001E770 8C820000 */  lw         $v0, 0x0($a0)
/* 1F374 8001E774 2618FFFF */  addiu      $t8, $s0, -0x1
/* 1F378 8001E778 00187880 */  sll        $t7, $t8, 2
/* 1F37C 8001E77C 244E0008 */  addiu      $t6, $v0, 0x8
/* 1F380 8001E780 AC8E0000 */  sw         $t6, 0x0($a0)
/* 1F384 8001E784 31EE0FFF */  andi       $t6, $t7, 0xFFF
/* 1F388 8001E788 3C19F200 */  lui        $t9, (0xF2000000 >> 16)
/* 1F38C 8001E78C 2678FFFF */  addiu      $t8, $s3, -0x1
/* 1F390 8001E790 AC590000 */  sw         $t9, 0x0($v0)
/* 1F394 8001E794 000ECB00 */  sll        $t9, $t6, 12
/* 1F398 8001E798 00187880 */  sll        $t7, $t8, 2
/* 1F39C 8001E79C 31EE0FFF */  andi       $t6, $t7, 0xFFF
/* 1F3A0 8001E7A0 032EC025 */  or         $t8, $t9, $t6
/* 1F3A4 8001E7A4 AC580004 */  sw         $t8, 0x4($v0)
/* 1F3A8 8001E7A8 8C820000 */  lw         $v0, 0x0($a0)
/* 1F3AC 8001E7AC 3C19BA00 */  lui        $t9, (0xBA000E02 >> 16)
/* 1F3B0 8001E7B0 37390E02 */  ori        $t9, $t9, (0xBA000E02 & 0xFFFF)
/* 1F3B4 8001E7B4 244F0008 */  addiu      $t7, $v0, 0x8
/* 1F3B8 8001E7B8 AC8F0000 */  sw         $t7, 0x0($a0)
/* 1F3BC 8001E7BC AC400004 */  sw         $zero, 0x4($v0)
/* 1F3C0 8001E7C0 AC590000 */  sw         $t9, 0x0($v0)
/* 1F3C4 8001E7C4 10000187 */  b          .L8001EDE4
/* 1F3C8 8001E7C8 8FB00008 */   lw        $s0, 0x8($sp)
glabel .L8001E7CC
/* 1F3CC 8001E7CC 3C048008 */  lui        $a0, %hi(gMasterGfxPos)
/* 1F3D0 8001E7D0 2484A184 */  addiu      $a0, $a0, %lo(gMasterGfxPos)
/* 1F3D4 8001E7D4 8C850000 */  lw         $a1, 0x0($a0)
/* 1F3D8 8001E7D8 3C18FD70 */  lui        $t8, (0xFD700000 >> 16)
/* 1F3DC 8001E7DC 306D000F */  andi       $t5, $v1, 0xF
/* 1F3E0 8001E7E0 24AE0008 */  addiu      $t6, $a1, 0x8
/* 1F3E4 8001E7E4 AC8E0000 */  sw         $t6, 0x0($a0)
/* 1F3E8 8001E7E8 ACB80000 */  sw         $t8, 0x0($a1)
/* 1F3EC 8001E7EC 8FAF0114 */  lw         $t7, 0x114($sp)
/* 1F3F0 8001E7F0 3C0EF570 */  lui        $t6, (0xF5700000 >> 16)
/* 1F3F4 8001E7F4 3112000F */  andi       $s2, $t0, 0xF
/* 1F3F8 8001E7F8 ACAF0004 */  sw         $t7, 0x4($a1)
/* 1F3FC 8001E7FC 8C860000 */  lw         $a2, 0x0($a0)
/* 1F400 8001E800 3C010700 */  lui        $at, (0x7000000 >> 16)
/* 1F404 8001E804 00127900 */  sll        $t7, $s2, 4
/* 1F408 8001E808 24D90008 */  addiu      $t9, $a2, 0x8
/* 1F40C 8001E80C AC990000 */  sw         $t9, 0x0($a0)
/* 1F410 8001E810 ACCE0000 */  sw         $t6, 0x0($a2)
/* 1F414 8001E814 93AC0127 */  lbu        $t4, 0x127($sp)
/* 1F418 8001E818 93B10123 */  lbu        $s1, 0x123($sp)
/* 1F41C 8001E81C 000DCB80 */  sll        $t9, $t5, 14
/* 1F420 8001E820 31980003 */  andi       $t8, $t4, 0x3
/* 1F424 8001E824 00186480 */  sll        $t4, $t8, 18
/* 1F428 8001E828 03206825 */  or         $t5, $t9, $zero
/* 1F42C 8001E82C 322E0003 */  andi       $t6, $s1, 0x3
/* 1F430 8001E830 000E8A00 */  sll        $s1, $t6, 8
/* 1F434 8001E834 0181C825 */  or         $t9, $t4, $at
/* 1F438 8001E838 032D7025 */  or         $t6, $t9, $t5
/* 1F43C 8001E83C 01D1C025 */  or         $t8, $t6, $s1
/* 1F440 8001E840 01E09025 */  or         $s2, $t7, $zero
/* 1F444 8001E844 030F7825 */  or         $t7, $t8, $t7
/* 1F448 8001E848 ACCF0004 */  sw         $t7, 0x4($a2)
/* 1F44C 8001E84C 8C870000 */  lw         $a3, 0x0($a0)
/* 1F450 8001E850 3C0EE600 */  lui        $t6, (0xE6000000 >> 16)
/* 1F454 8001E854 240B07FF */  addiu      $t3, $zero, 0x7FF
/* 1F458 8001E858 24F90008 */  addiu      $t9, $a3, 0x8
/* 1F45C 8001E85C AC990000 */  sw         $t9, 0x0($a0)
/* 1F460 8001E860 ACE00004 */  sw         $zero, 0x4($a3)
/* 1F464 8001E864 ACEE0000 */  sw         $t6, 0x0($a3)
/* 1F468 8001E868 02130019 */  multu      $s0, $s3
/* 1F46C 8001E86C 8C8A0000 */  lw         $t2, 0x0($a0)
/* 1F470 8001E870 3C0FF300 */  lui        $t7, (0xF3000000 >> 16)
/* 1F474 8001E874 25580008 */  addiu      $t8, $t2, 0x8
/* 1F478 8001E878 AC980000 */  sw         $t8, 0x0($a0)
/* 1F47C 8001E87C AD4F0000 */  sw         $t7, 0x0($t2)
/* 1F480 8001E880 00004812 */  mflo       $t1
/* 1F484 8001E884 25290003 */  addiu      $t1, $t1, 0x3
/* 1F488 8001E888 0009C883 */  sra        $t9, $t1, 2
/* 1F48C 8001E88C 2729FFFF */  addiu      $t1, $t9, -0x1
/* 1F490 8001E890 292107FF */  slti       $at, $t1, 0x7FF
/* 1F494 8001E894 10200003 */  beqz       $at, .L8001E8A4
/* 1F498 8001E898 00000000 */   nop
/* 1F49C 8001E89C 10000001 */  b          .L8001E8A4
/* 1F4A0 8001E8A0 01205825 */   or        $t3, $t1, $zero
.L8001E8A4:
/* 1F4A4 8001E8A4 06010003 */  bgez       $s0, .L8001E8B4
/* 1F4A8 8001E8A8 00101103 */   sra       $v0, $s0, 4
/* 1F4AC 8001E8AC 2601000F */  addiu      $at, $s0, 0xF
/* 1F4B0 8001E8B0 00011103 */  sra        $v0, $at, 4
.L8001E8B4:
/* 1F4B4 8001E8B4 1C400003 */  bgtz       $v0, .L8001E8C4
/* 1F4B8 8001E8B8 00404825 */   or        $t1, $v0, $zero
/* 1F4BC 8001E8BC 10000001 */  b          .L8001E8C4
/* 1F4C0 8001E8C0 24090001 */   addiu     $t1, $zero, 0x1
.L8001E8C4:
/* 1F4C4 8001E8C4 1C400003 */  bgtz       $v0, .L8001E8D4
/* 1F4C8 8001E8C8 252E07FF */   addiu     $t6, $t1, 0x7FF
/* 1F4CC 8001E8CC 10000002 */  b          .L8001E8D8
/* 1F4D0 8001E8D0 24030001 */   addiu     $v1, $zero, 0x1
.L8001E8D4:
/* 1F4D4 8001E8D4 00401825 */  or         $v1, $v0, $zero
.L8001E8D8:
/* 1F4D8 8001E8D8 01C3001A */  div        $zero, $t6, $v1
/* 1F4DC 8001E8DC 14600002 */  bnez       $v1, .L8001E8E8
/* 1F4E0 8001E8E0 00000000 */   nop
/* 1F4E4 8001E8E4 0007000D */  break      7
.L8001E8E8:
/* 1F4E8 8001E8E8 2401FFFF */  addiu      $at, $zero, -0x1
/* 1F4EC 8001E8EC 14610004 */  bne        $v1, $at, .L8001E900
/* 1F4F0 8001E8F0 3C018000 */   lui       $at, (0x80000000 >> 16)
/* 1F4F4 8001E8F4 15C10002 */  bne        $t6, $at, .L8001E900
/* 1F4F8 8001E8F8 00000000 */   nop
/* 1F4FC 8001E8FC 0006000D */  break      6
.L8001E900:
/* 1F500 8001E900 0000C012 */  mflo       $t8
/* 1F504 8001E904 330F0FFF */  andi       $t7, $t8, 0xFFF
/* 1F508 8001E908 3C010700 */  lui        $at, (0x7000000 >> 16)
/* 1F50C 8001E90C 316E0FFF */  andi       $t6, $t3, 0xFFF
/* 1F510 8001E910 000EC300 */  sll        $t8, $t6, 12
/* 1F514 8001E914 01E1C825 */  or         $t9, $t7, $at
/* 1F518 8001E918 03387825 */  or         $t7, $t9, $t8
/* 1F51C 8001E91C AD4F0004 */  sw         $t7, 0x4($t2)
/* 1F520 8001E920 8C820000 */  lw         $v0, 0x0($a0)
/* 1F524 8001E924 3C19E700 */  lui        $t9, (0xE7000000 >> 16)
/* 1F528 8001E928 00107843 */  sra        $t7, $s0, 1
/* 1F52C 8001E92C 244E0008 */  addiu      $t6, $v0, 0x8
/* 1F530 8001E930 AC8E0000 */  sw         $t6, 0x0($a0)
/* 1F534 8001E934 AC400004 */  sw         $zero, 0x4($v0)
/* 1F538 8001E938 AC590000 */  sw         $t9, 0x0($v0)
/* 1F53C 8001E93C 8C820000 */  lw         $v0, 0x0($a0)
/* 1F540 8001E940 25EE0007 */  addiu      $t6, $t7, 0x7
/* 1F544 8001E944 000EC8C3 */  sra        $t9, $t6, 3
/* 1F548 8001E948 24580008 */  addiu      $t8, $v0, 0x8
/* 1F54C 8001E94C AC980000 */  sw         $t8, 0x0($a0)
/* 1F550 8001E950 333801FF */  andi       $t8, $t9, 0x1FF
/* 1F554 8001E954 00187A40 */  sll        $t7, $t8, 9
/* 1F558 8001E958 018DC825 */  or         $t9, $t4, $t5
/* 1F55C 8001E95C 3C01F560 */  lui        $at, (0xF5600000 >> 16)
/* 1F560 8001E960 01E17025 */  or         $t6, $t7, $at
/* 1F564 8001E964 0331C025 */  or         $t8, $t9, $s1
/* 1F568 8001E968 03127825 */  or         $t7, $t8, $s2
/* 1F56C 8001E96C AC4F0004 */  sw         $t7, 0x4($v0)
/* 1F570 8001E970 AC4E0000 */  sw         $t6, 0x0($v0)
/* 1F574 8001E974 8C820000 */  lw         $v0, 0x0($a0)
/* 1F578 8001E978 2618FFFF */  addiu      $t8, $s0, -0x1
/* 1F57C 8001E97C 00187880 */  sll        $t7, $t8, 2
/* 1F580 8001E980 244E0008 */  addiu      $t6, $v0, 0x8
/* 1F584 8001E984 AC8E0000 */  sw         $t6, 0x0($a0)
/* 1F588 8001E988 31EE0FFF */  andi       $t6, $t7, 0xFFF
/* 1F58C 8001E98C 3C19F200 */  lui        $t9, (0xF2000000 >> 16)
/* 1F590 8001E990 2678FFFF */  addiu      $t8, $s3, -0x1
/* 1F594 8001E994 AC590000 */  sw         $t9, 0x0($v0)
/* 1F598 8001E998 000ECB00 */  sll        $t9, $t6, 12
/* 1F59C 8001E99C 00187880 */  sll        $t7, $t8, 2
/* 1F5A0 8001E9A0 31EE0FFF */  andi       $t6, $t7, 0xFFF
/* 1F5A4 8001E9A4 032EC025 */  or         $t8, $t9, $t6
/* 1F5A8 8001E9A8 AC580004 */  sw         $t8, 0x4($v0)
/* 1F5AC 8001E9AC 8C820000 */  lw         $v0, 0x0($a0)
/* 1F5B0 8001E9B0 3C19BA00 */  lui        $t9, (0xBA000E02 >> 16)
/* 1F5B4 8001E9B4 37390E02 */  ori        $t9, $t9, (0xBA000E02 & 0xFFFF)
/* 1F5B8 8001E9B8 244F0008 */  addiu      $t7, $v0, 0x8
/* 1F5BC 8001E9BC AC8F0000 */  sw         $t7, 0x0($a0)
/* 1F5C0 8001E9C0 AC400004 */  sw         $zero, 0x4($v0)
/* 1F5C4 8001E9C4 AC590000 */  sw         $t9, 0x0($v0)
/* 1F5C8 8001E9C8 10000106 */  b          .L8001EDE4
/* 1F5CC 8001E9CC 8FB00008 */   lw        $s0, 0x8($sp)
glabel .L8001E9D0
/* 1F5D0 8001E9D0 3C048008 */  lui        $a0, %hi(gMasterGfxPos)
/* 1F5D4 8001E9D4 2484A184 */  addiu      $a0, $a0, %lo(gMasterGfxPos)
/* 1F5D8 8001E9D8 8C850000 */  lw         $a1, 0x0($a0)
/* 1F5DC 8001E9DC 3C18FD50 */  lui        $t8, (0xFD500000 >> 16)
/* 1F5E0 8001E9E0 306D000F */  andi       $t5, $v1, 0xF
/* 1F5E4 8001E9E4 24AE0008 */  addiu      $t6, $a1, 0x8
/* 1F5E8 8001E9E8 AC8E0000 */  sw         $t6, 0x0($a0)
/* 1F5EC 8001E9EC ACB80000 */  sw         $t8, 0x0($a1)
/* 1F5F0 8001E9F0 8FAF0114 */  lw         $t7, 0x114($sp)
/* 1F5F4 8001E9F4 3C0EF550 */  lui        $t6, (0xF5500000 >> 16)
/* 1F5F8 8001E9F8 3112000F */  andi       $s2, $t0, 0xF
/* 1F5FC 8001E9FC ACAF0004 */  sw         $t7, 0x4($a1)
/* 1F600 8001EA00 8C860000 */  lw         $a2, 0x0($a0)
/* 1F604 8001EA04 3C010700 */  lui        $at, (0x7000000 >> 16)
/* 1F608 8001EA08 00127900 */  sll        $t7, $s2, 4
/* 1F60C 8001EA0C 24D90008 */  addiu      $t9, $a2, 0x8
/* 1F610 8001EA10 AC990000 */  sw         $t9, 0x0($a0)
/* 1F614 8001EA14 ACCE0000 */  sw         $t6, 0x0($a2)
/* 1F618 8001EA18 93AC0127 */  lbu        $t4, 0x127($sp)
/* 1F61C 8001EA1C 93B10123 */  lbu        $s1, 0x123($sp)
/* 1F620 8001EA20 000DCB80 */  sll        $t9, $t5, 14
/* 1F624 8001EA24 31980003 */  andi       $t8, $t4, 0x3
/* 1F628 8001EA28 00186480 */  sll        $t4, $t8, 18
/* 1F62C 8001EA2C 03206825 */  or         $t5, $t9, $zero
/* 1F630 8001EA30 322E0003 */  andi       $t6, $s1, 0x3
/* 1F634 8001EA34 000E8A00 */  sll        $s1, $t6, 8
/* 1F638 8001EA38 0181C825 */  or         $t9, $t4, $at
/* 1F63C 8001EA3C 032D7025 */  or         $t6, $t9, $t5
/* 1F640 8001EA40 01D1C025 */  or         $t8, $t6, $s1
/* 1F644 8001EA44 01E09025 */  or         $s2, $t7, $zero
/* 1F648 8001EA48 030F7825 */  or         $t7, $t8, $t7
/* 1F64C 8001EA4C ACCF0004 */  sw         $t7, 0x4($a2)
/* 1F650 8001EA50 8C870000 */  lw         $a3, 0x0($a0)
/* 1F654 8001EA54 3C0EE600 */  lui        $t6, (0xE6000000 >> 16)
/* 1F658 8001EA58 240B07FF */  addiu      $t3, $zero, 0x7FF
/* 1F65C 8001EA5C 24F90008 */  addiu      $t9, $a3, 0x8
/* 1F660 8001EA60 AC990000 */  sw         $t9, 0x0($a0)
/* 1F664 8001EA64 ACE00004 */  sw         $zero, 0x4($a3)
/* 1F668 8001EA68 ACEE0000 */  sw         $t6, 0x0($a3)
/* 1F66C 8001EA6C 02130019 */  multu      $s0, $s3
/* 1F670 8001EA70 8C8A0000 */  lw         $t2, 0x0($a0)
/* 1F674 8001EA74 3C0FF300 */  lui        $t7, (0xF3000000 >> 16)
/* 1F678 8001EA78 25580008 */  addiu      $t8, $t2, 0x8
/* 1F67C 8001EA7C AC980000 */  sw         $t8, 0x0($a0)
/* 1F680 8001EA80 AD4F0000 */  sw         $t7, 0x0($t2)
/* 1F684 8001EA84 00004812 */  mflo       $t1
/* 1F688 8001EA88 25290003 */  addiu      $t1, $t1, 0x3
/* 1F68C 8001EA8C 0009C883 */  sra        $t9, $t1, 2
/* 1F690 8001EA90 2729FFFF */  addiu      $t1, $t9, -0x1
/* 1F694 8001EA94 292107FF */  slti       $at, $t1, 0x7FF
/* 1F698 8001EA98 10200003 */  beqz       $at, .L8001EAA8
/* 1F69C 8001EA9C 00000000 */   nop
/* 1F6A0 8001EAA0 10000001 */  b          .L8001EAA8
/* 1F6A4 8001EAA4 01205825 */   or        $t3, $t1, $zero
.L8001EAA8:
/* 1F6A8 8001EAA8 06010003 */  bgez       $s0, .L8001EAB8
/* 1F6AC 8001EAAC 00101103 */   sra       $v0, $s0, 4
/* 1F6B0 8001EAB0 2601000F */  addiu      $at, $s0, 0xF
/* 1F6B4 8001EAB4 00011103 */  sra        $v0, $at, 4
.L8001EAB8:
/* 1F6B8 8001EAB8 1C400003 */  bgtz       $v0, .L8001EAC8
/* 1F6BC 8001EABC 00404825 */   or        $t1, $v0, $zero
/* 1F6C0 8001EAC0 10000001 */  b          .L8001EAC8
/* 1F6C4 8001EAC4 24090001 */   addiu     $t1, $zero, 0x1
.L8001EAC8:
/* 1F6C8 8001EAC8 1C400003 */  bgtz       $v0, .L8001EAD8
/* 1F6CC 8001EACC 252E07FF */   addiu     $t6, $t1, 0x7FF
/* 1F6D0 8001EAD0 10000002 */  b          .L8001EADC
/* 1F6D4 8001EAD4 24030001 */   addiu     $v1, $zero, 0x1
.L8001EAD8:
/* 1F6D8 8001EAD8 00401825 */  or         $v1, $v0, $zero
.L8001EADC:
/* 1F6DC 8001EADC 01C3001A */  div        $zero, $t6, $v1
/* 1F6E0 8001EAE0 14600002 */  bnez       $v1, .L8001EAEC
/* 1F6E4 8001EAE4 00000000 */   nop
/* 1F6E8 8001EAE8 0007000D */  break      7
.L8001EAEC:
/* 1F6EC 8001EAEC 2401FFFF */  addiu      $at, $zero, -0x1
/* 1F6F0 8001EAF0 14610004 */  bne        $v1, $at, .L8001EB04
/* 1F6F4 8001EAF4 3C018000 */   lui       $at, (0x80000000 >> 16)
/* 1F6F8 8001EAF8 15C10002 */  bne        $t6, $at, .L8001EB04
/* 1F6FC 8001EAFC 00000000 */   nop
/* 1F700 8001EB00 0006000D */  break      6
.L8001EB04:
/* 1F704 8001EB04 0000C012 */  mflo       $t8
/* 1F708 8001EB08 330F0FFF */  andi       $t7, $t8, 0xFFF
/* 1F70C 8001EB0C 3C010700 */  lui        $at, (0x7000000 >> 16)
/* 1F710 8001EB10 316E0FFF */  andi       $t6, $t3, 0xFFF
/* 1F714 8001EB14 000EC300 */  sll        $t8, $t6, 12
/* 1F718 8001EB18 01E1C825 */  or         $t9, $t7, $at
/* 1F71C 8001EB1C 03387825 */  or         $t7, $t9, $t8
/* 1F720 8001EB20 AD4F0004 */  sw         $t7, 0x4($t2)
/* 1F724 8001EB24 8C820000 */  lw         $v0, 0x0($a0)
/* 1F728 8001EB28 3C19E700 */  lui        $t9, (0xE7000000 >> 16)
/* 1F72C 8001EB2C 00107843 */  sra        $t7, $s0, 1
/* 1F730 8001EB30 244E0008 */  addiu      $t6, $v0, 0x8
/* 1F734 8001EB34 AC8E0000 */  sw         $t6, 0x0($a0)
/* 1F738 8001EB38 AC400004 */  sw         $zero, 0x4($v0)
/* 1F73C 8001EB3C AC590000 */  sw         $t9, 0x0($v0)
/* 1F740 8001EB40 8C820000 */  lw         $v0, 0x0($a0)
/* 1F744 8001EB44 25EE0007 */  addiu      $t6, $t7, 0x7
/* 1F748 8001EB48 000EC8C3 */  sra        $t9, $t6, 3
/* 1F74C 8001EB4C 24580008 */  addiu      $t8, $v0, 0x8
/* 1F750 8001EB50 AC980000 */  sw         $t8, 0x0($a0)
/* 1F754 8001EB54 333801FF */  andi       $t8, $t9, 0x1FF
/* 1F758 8001EB58 00187A40 */  sll        $t7, $t8, 9
/* 1F75C 8001EB5C 018DC825 */  or         $t9, $t4, $t5
/* 1F760 8001EB60 3C01F540 */  lui        $at, (0xF5400000 >> 16)
/* 1F764 8001EB64 01E17025 */  or         $t6, $t7, $at
/* 1F768 8001EB68 0331C025 */  or         $t8, $t9, $s1
/* 1F76C 8001EB6C 03127825 */  or         $t7, $t8, $s2
/* 1F770 8001EB70 AC4F0004 */  sw         $t7, 0x4($v0)
/* 1F774 8001EB74 AC4E0000 */  sw         $t6, 0x0($v0)
/* 1F778 8001EB78 8C820000 */  lw         $v0, 0x0($a0)
/* 1F77C 8001EB7C 2618FFFF */  addiu      $t8, $s0, -0x1
/* 1F780 8001EB80 00187880 */  sll        $t7, $t8, 2
/* 1F784 8001EB84 244E0008 */  addiu      $t6, $v0, 0x8
/* 1F788 8001EB88 AC8E0000 */  sw         $t6, 0x0($a0)
/* 1F78C 8001EB8C 31EE0FFF */  andi       $t6, $t7, 0xFFF
/* 1F790 8001EB90 3C19F200 */  lui        $t9, (0xF2000000 >> 16)
/* 1F794 8001EB94 2678FFFF */  addiu      $t8, $s3, -0x1
/* 1F798 8001EB98 AC590000 */  sw         $t9, 0x0($v0)
/* 1F79C 8001EB9C 000ECB00 */  sll        $t9, $t6, 12
/* 1F7A0 8001EBA0 00187880 */  sll        $t7, $t8, 2
/* 1F7A4 8001EBA4 31EE0FFF */  andi       $t6, $t7, 0xFFF
/* 1F7A8 8001EBA8 032EC025 */  or         $t8, $t9, $t6
/* 1F7AC 8001EBAC AC580004 */  sw         $t8, 0x4($v0)
/* 1F7B0 8001EBB0 8C820000 */  lw         $v0, 0x0($a0)
/* 1F7B4 8001EBB4 3C19BA00 */  lui        $t9, (0xBA000E02 >> 16)
/* 1F7B8 8001EBB8 37390E02 */  ori        $t9, $t9, (0xBA000E02 & 0xFFFF)
/* 1F7BC 8001EBBC 244F0008 */  addiu      $t7, $v0, 0x8
/* 1F7C0 8001EBC0 AC8F0000 */  sw         $t7, 0x0($a0)
/* 1F7C4 8001EBC4 340E8000 */  ori        $t6, $zero, 0x8000
/* 1F7C8 8001EBC8 AC4E0004 */  sw         $t6, 0x4($v0)
/* 1F7CC 8001EBCC AC590000 */  sw         $t9, 0x0($v0)
/* 1F7D0 8001EBD0 10000084 */  b          .L8001EDE4
/* 1F7D4 8001EBD4 8FB00008 */   lw        $s0, 0x8($sp)
glabel .L8001EBD8
/* 1F7D8 8001EBD8 3C048008 */  lui        $a0, %hi(gMasterGfxPos)
/* 1F7DC 8001EBDC 2484A184 */  addiu      $a0, $a0, %lo(gMasterGfxPos)
/* 1F7E0 8001EBE0 8C850000 */  lw         $a1, 0x0($a0)
/* 1F7E4 8001EBE4 3C0FFD50 */  lui        $t7, (0xFD500000 >> 16)
/* 1F7E8 8001EBE8 306D000F */  andi       $t5, $v1, 0xF
/* 1F7EC 8001EBEC 24B80008 */  addiu      $t8, $a1, 0x8
/* 1F7F0 8001EBF0 AC980000 */  sw         $t8, 0x0($a0)
/* 1F7F4 8001EBF4 ACAF0000 */  sw         $t7, 0x0($a1)
/* 1F7F8 8001EBF8 8FB90114 */  lw         $t9, 0x114($sp)
/* 1F7FC 8001EBFC 3C18F550 */  lui        $t8, (0xF5500000 >> 16)
/* 1F800 8001EC00 3112000F */  andi       $s2, $t0, 0xF
/* 1F804 8001EC04 ACB90004 */  sw         $t9, 0x4($a1)
/* 1F808 8001EC08 8C860000 */  lw         $a2, 0x0($a0)
/* 1F80C 8001EC0C 3C010700 */  lui        $at, (0x7000000 >> 16)
/* 1F810 8001EC10 0012C900 */  sll        $t9, $s2, 4
/* 1F814 8001EC14 24CE0008 */  addiu      $t6, $a2, 0x8
/* 1F818 8001EC18 AC8E0000 */  sw         $t6, 0x0($a0)
/* 1F81C 8001EC1C ACD80000 */  sw         $t8, 0x0($a2)
/* 1F820 8001EC20 93AC0127 */  lbu        $t4, 0x127($sp)
/* 1F824 8001EC24 93B10123 */  lbu        $s1, 0x123($sp)
/* 1F828 8001EC28 000D7380 */  sll        $t6, $t5, 14
/* 1F82C 8001EC2C 318F0003 */  andi       $t7, $t4, 0x3
/* 1F830 8001EC30 000F6480 */  sll        $t4, $t7, 18
/* 1F834 8001EC34 01C06825 */  or         $t5, $t6, $zero
/* 1F838 8001EC38 32380003 */  andi       $t8, $s1, 0x3
/* 1F83C 8001EC3C 00188A00 */  sll        $s1, $t8, 8
/* 1F840 8001EC40 01817025 */  or         $t6, $t4, $at
/* 1F844 8001EC44 01CDC025 */  or         $t8, $t6, $t5
/* 1F848 8001EC48 03117825 */  or         $t7, $t8, $s1
/* 1F84C 8001EC4C 03209025 */  or         $s2, $t9, $zero
/* 1F850 8001EC50 01F9C825 */  or         $t9, $t7, $t9
/* 1F854 8001EC54 ACD90004 */  sw         $t9, 0x4($a2)
/* 1F858 8001EC58 8C870000 */  lw         $a3, 0x0($a0)
/* 1F85C 8001EC5C 3C18E600 */  lui        $t8, (0xE6000000 >> 16)
/* 1F860 8001EC60 02005025 */  or         $t2, $s0, $zero
/* 1F864 8001EC64 24EE0008 */  addiu      $t6, $a3, 0x8
/* 1F868 8001EC68 AC8E0000 */  sw         $t6, 0x0($a0)
/* 1F86C 8001EC6C ACE00004 */  sw         $zero, 0x4($a3)
/* 1F870 8001EC70 ACF80000 */  sw         $t8, 0x0($a3)
/* 1F874 8001EC74 02130019 */  multu      $s0, $s3
/* 1F878 8001EC78 8C820000 */  lw         $v0, 0x0($a0)
/* 1F87C 8001EC7C 3C19F300 */  lui        $t9, (0xF3000000 >> 16)
/* 1F880 8001EC80 240B07FF */  addiu      $t3, $zero, 0x7FF
/* 1F884 8001EC84 244F0008 */  addiu      $t7, $v0, 0x8
/* 1F888 8001EC88 AC8F0000 */  sw         $t7, 0x0($a0)
/* 1F88C 8001EC8C AC590000 */  sw         $t9, 0x0($v0)
/* 1F890 8001EC90 AFA2001C */  sw         $v0, 0x1C($sp)
/* 1F894 8001EC94 00004812 */  mflo       $t1
/* 1F898 8001EC98 25290001 */  addiu      $t1, $t1, 0x1
/* 1F89C 8001EC9C 00097043 */  sra        $t6, $t1, 1
/* 1F8A0 8001ECA0 25C9FFFF */  addiu      $t1, $t6, -0x1
/* 1F8A4 8001ECA4 292107FF */  slti       $at, $t1, 0x7FF
/* 1F8A8 8001ECA8 10200003 */  beqz       $at, .L8001ECB8
/* 1F8AC 8001ECAC 00000000 */   nop
/* 1F8B0 8001ECB0 10000001 */  b          .L8001ECB8
/* 1F8B4 8001ECB4 01205825 */   or        $t3, $t1, $zero
.L8001ECB8:
/* 1F8B8 8001ECB8 05410003 */  bgez       $t2, .L8001ECC8
/* 1F8BC 8001ECBC 000A10C3 */   sra       $v0, $t2, 3
/* 1F8C0 8001ECC0 25410007 */  addiu      $at, $t2, 0x7
/* 1F8C4 8001ECC4 000110C3 */  sra        $v0, $at, 3
.L8001ECC8:
/* 1F8C8 8001ECC8 1C400003 */  bgtz       $v0, .L8001ECD8
/* 1F8CC 8001ECCC 00404825 */   or        $t1, $v0, $zero
/* 1F8D0 8001ECD0 10000001 */  b          .L8001ECD8
/* 1F8D4 8001ECD4 24090001 */   addiu     $t1, $zero, 0x1
.L8001ECD8:
/* 1F8D8 8001ECD8 1C400003 */  bgtz       $v0, .L8001ECE8
/* 1F8DC 8001ECDC 253807FF */   addiu     $t8, $t1, 0x7FF
/* 1F8E0 8001ECE0 10000002 */  b          .L8001ECEC
/* 1F8E4 8001ECE4 24030001 */   addiu     $v1, $zero, 0x1
.L8001ECE8:
/* 1F8E8 8001ECE8 00401825 */  or         $v1, $v0, $zero
.L8001ECEC:
/* 1F8EC 8001ECEC 0303001A */  div        $zero, $t8, $v1
/* 1F8F0 8001ECF0 14600002 */  bnez       $v1, .L8001ECFC
/* 1F8F4 8001ECF4 00000000 */   nop
/* 1F8F8 8001ECF8 0007000D */  break      7
.L8001ECFC:
/* 1F8FC 8001ECFC 2401FFFF */  addiu      $at, $zero, -0x1
/* 1F900 8001ED00 14610004 */  bne        $v1, $at, .L8001ED14
/* 1F904 8001ED04 3C018000 */   lui       $at, (0x80000000 >> 16)
/* 1F908 8001ED08 17010002 */  bne        $t8, $at, .L8001ED14
/* 1F90C 8001ED0C 00000000 */   nop
/* 1F910 8001ED10 0006000D */  break      6
.L8001ED14:
/* 1F914 8001ED14 00007812 */  mflo       $t7
/* 1F918 8001ED18 31F90FFF */  andi       $t9, $t7, 0xFFF
/* 1F91C 8001ED1C 31780FFF */  andi       $t8, $t3, 0xFFF
/* 1F920 8001ED20 00187B00 */  sll        $t7, $t8, 12
/* 1F924 8001ED24 8FB8001C */  lw         $t8, 0x1C($sp)
/* 1F928 8001ED28 3C010700 */  lui        $at, (0x7000000 >> 16)
/* 1F92C 8001ED2C 03217025 */  or         $t6, $t9, $at
/* 1F930 8001ED30 01CFC825 */  or         $t9, $t6, $t7
/* 1F934 8001ED34 AF190004 */  sw         $t9, 0x4($t8)
/* 1F938 8001ED38 8C820000 */  lw         $v0, 0x0($a0)
/* 1F93C 8001ED3C 3C0FE700 */  lui        $t7, (0xE7000000 >> 16)
/* 1F940 8001ED40 25580007 */  addiu      $t8, $t2, 0x7
/* 1F944 8001ED44 244E0008 */  addiu      $t6, $v0, 0x8
/* 1F948 8001ED48 AC8E0000 */  sw         $t6, 0x0($a0)
/* 1F94C 8001ED4C AC400004 */  sw         $zero, 0x4($v0)
/* 1F950 8001ED50 AC4F0000 */  sw         $t7, 0x0($v0)
/* 1F954 8001ED54 8C820000 */  lw         $v0, 0x0($a0)
/* 1F958 8001ED58 001870C3 */  sra        $t6, $t8, 3
/* 1F95C 8001ED5C 31CF01FF */  andi       $t7, $t6, 0x1FF
/* 1F960 8001ED60 24590008 */  addiu      $t9, $v0, 0x8
/* 1F964 8001ED64 AC990000 */  sw         $t9, 0x0($a0)
/* 1F968 8001ED68 000FCA40 */  sll        $t9, $t7, 9
/* 1F96C 8001ED6C 018D7025 */  or         $t6, $t4, $t5
/* 1F970 8001ED70 3C01F548 */  lui        $at, (0xF5480000 >> 16)
/* 1F974 8001ED74 0321C025 */  or         $t8, $t9, $at
/* 1F978 8001ED78 01D17825 */  or         $t7, $t6, $s1
/* 1F97C 8001ED7C 01F2C825 */  or         $t9, $t7, $s2
/* 1F980 8001ED80 AC590004 */  sw         $t9, 0x4($v0)
/* 1F984 8001ED84 AC580000 */  sw         $t8, 0x0($v0)
/* 1F988 8001ED88 8C820000 */  lw         $v0, 0x0($a0)
/* 1F98C 8001ED8C 260FFFFF */  addiu      $t7, $s0, -0x1
/* 1F990 8001ED90 000FC880 */  sll        $t9, $t7, 2
/* 1F994 8001ED94 24580008 */  addiu      $t8, $v0, 0x8
/* 1F998 8001ED98 AC980000 */  sw         $t8, 0x0($a0)
/* 1F99C 8001ED9C 33380FFF */  andi       $t8, $t9, 0xFFF
/* 1F9A0 8001EDA0 3C0EF200 */  lui        $t6, (0xF2000000 >> 16)
/* 1F9A4 8001EDA4 266FFFFF */  addiu      $t7, $s3, -0x1
/* 1F9A8 8001EDA8 AC4E0000 */  sw         $t6, 0x0($v0)
/* 1F9AC 8001EDAC 00187300 */  sll        $t6, $t8, 12
/* 1F9B0 8001EDB0 000FC880 */  sll        $t9, $t7, 2
/* 1F9B4 8001EDB4 33380FFF */  andi       $t8, $t9, 0xFFF
/* 1F9B8 8001EDB8 01D87825 */  or         $t7, $t6, $t8
/* 1F9BC 8001EDBC AC4F0004 */  sw         $t7, 0x4($v0)
/* 1F9C0 8001EDC0 8C820000 */  lw         $v0, 0x0($a0)
/* 1F9C4 8001EDC4 3C0EBA00 */  lui        $t6, (0xBA000E02 >> 16)
/* 1F9C8 8001EDC8 35CE0E02 */  ori        $t6, $t6, (0xBA000E02 & 0xFFFF)
/* 1F9CC 8001EDCC 24590008 */  addiu      $t9, $v0, 0x8
/* 1F9D0 8001EDD0 AC990000 */  sw         $t9, 0x0($a0)
/* 1F9D4 8001EDD4 34188000 */  ori        $t8, $zero, 0x8000
/* 1F9D8 8001EDD8 AC580004 */  sw         $t8, 0x4($v0)
/* 1F9DC 8001EDDC AC4E0000 */  sw         $t6, 0x0($v0)
.L8001EDE0:
/* 1F9E0 8001EDE0 8FB00008 */  lw         $s0, 0x8($sp)
.L8001EDE4:
/* 1F9E4 8001EDE4 8FB1000C */  lw         $s1, 0xC($sp)
/* 1F9E8 8001EDE8 8FB20010 */  lw         $s2, 0x10($sp)
/* 1F9EC 8001EDEC 8FB30014 */  lw         $s3, 0x14($sp)
/* 1F9F0 8001EDF0 03E00008 */  jr         $ra
/* 1F9F4 8001EDF4 27BD0110 */   addiu     $sp, $sp, 0x110
/* 1F9F8 8001EDF8 00000000 */  nop
/* 1F9FC 8001EDFC 00000000 */  nop
