.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.10.1 */

glabel func_8001EE00
/* 1FA00 8001EE00 3C028009 */  lui        $v0, %hi(D_8008BE52)
/* 1FA04 8001EE04 2442BE52 */  addiu      $v0, $v0, %lo(D_8008BE52)
/* 1FA08 8001EE08 944E0000 */  lhu        $t6, 0x0($v0)
/* 1FA0C 8001EE0C 44802000 */  mtc1       $zero, $f4
/* 1FA10 8001EE10 3C188008 */  lui        $t8, %hi(D_800842E8)
/* 1FA14 8001EE14 31CF8000 */  andi       $t7, $t6, 0x8000
/* 1FA18 8001EE18 A44F0000 */  sh         $t7, 0x0($v0)
/* 1FA1C 8001EE1C 971842E8 */  lhu        $t8, %lo(D_800842E8)($t8)
/* 1FA20 8001EE20 3C018009 */  lui        $at, %hi(D_8008BFAC)
/* 1FA24 8001EE24 E424BFAC */  swc1       $f4, %lo(D_8008BFAC)($at)
/* 1FA28 8001EE28 3C018009 */  lui        $at, %hi(D_8008BFB0)
/* 1FA2C 8001EE2C 33190001 */  andi       $t9, $t8, 0x1
/* 1FA30 8001EE30 13200016 */  beqz       $t9, .L8001EE8C
/* 1FA34 8001EE34 A420BFB0 */   sh        $zero, %lo(D_8008BFB0)($at)
/* 1FA38 8001EE38 3C028008 */  lui        $v0, %hi(D_8007C284)
/* 1FA3C 8001EE3C 8C42C284 */  lw         $v0, %lo(D_8007C284)($v0)
/* 1FA40 8001EE40 3C048008 */  lui        $a0, %hi(D_800842C0)
/* 1FA44 8001EE44 3C018009 */  lui        $at, %hi(D_8008BF98)
/* 1FA48 8001EE48 8C430030 */  lw         $v1, 0x30($v0)
/* 1FA4C 8001EE4C 1060000C */  beqz       $v1, .L8001EE80
/* 1FA50 8001EE50 00000000 */   nop
/* 1FA54 8001EE54 8C8442C0 */  lw         $a0, %lo(D_800842C0)($a0)
/* 1FA58 8001EE58 3C018009 */  lui        $at, %hi(D_8008BF98)
/* 1FA5C 8001EE5C 000440C0 */  sll        $t0, $a0, 3
/* 1FA60 8001EE60 00684821 */  addu       $t1, $v1, $t0
/* 1FA64 8001EE64 AC29BF98 */  sw         $t1, %lo(D_8008BF98)($at)
/* 1FA68 8001EE68 8C4A0034 */  lw         $t2, 0x34($v0)
/* 1FA6C 8001EE6C 00045900 */  sll        $t3, $a0, 4
/* 1FA70 8001EE70 3C018009 */  lui        $at, %hi(D_8008BF9C)
/* 1FA74 8001EE74 014B6021 */  addu       $t4, $t2, $t3
/* 1FA78 8001EE78 03E00008 */  jr         $ra
/* 1FA7C 8001EE7C AC2CBF9C */   sw        $t4, %lo(D_8008BF9C)($at)
.L8001EE80:
/* 1FA80 8001EE80 AC20BF98 */  sw         $zero, %lo(D_8008BF98)($at)
/* 1FA84 8001EE84 3C018009 */  lui        $at, %hi(D_8008BF9C)
/* 1FA88 8001EE88 AC20BF9C */  sw         $zero, %lo(D_8008BF9C)($at)
.L8001EE8C:
/* 1FA8C 8001EE8C 03E00008 */  jr         $ra
/* 1FA90 8001EE90 00000000 */   nop

glabel func_8001EE94
/* 1FA94 8001EE94 27BDFFC0 */  addiu      $sp, $sp, -0x40
/* 1FA98 8001EE98 AFBF001C */  sw         $ra, 0x1C($sp)
/* 1FA9C 8001EE9C 3C028009 */  lui        $v0, %hi(D_8008BE52)
/* 1FAA0 8001EEA0 9442BE52 */  lhu        $v0, %lo(D_8008BE52)($v0)
/* 1FAA4 8001EEA4 304E0001 */  andi       $t6, $v0, 0x1
/* 1FAA8 8001EEA8 15C000AA */  bnez       $t6, .L8001F154
/* 1FAAC 8001EEAC 304F8000 */   andi      $t7, $v0, 0x8000
/* 1FAB0 8001EEB0 15E000A8 */  bnez       $t7, .L8001F154
/* 1FAB4 8001EEB4 3C188008 */   lui       $t8, %hi(D_8007AA80)
/* 1FAB8 8001EEB8 9718AA80 */  lhu        $t8, %lo(D_8007AA80)($t8)
/* 1FABC 8001EEBC 3C018008 */  lui        $at, %hi(D_8007A9A8)
/* 1FAC0 8001EEC0 33190001 */  andi       $t9, $t8, 0x1
/* 1FAC4 8001EEC4 572000A4 */  bnel       $t9, $zero, .L8001F158
/* 1FAC8 8001EEC8 8FBF001C */   lw        $ra, 0x1C($sp)
/* 1FACC 8001EECC C420A9A8 */  lwc1       $f0, %lo(D_8007A9A8)($at)
/* 1FAD0 8001EED0 44802000 */  mtc1       $zero, $f4
/* 1FAD4 8001EED4 3C038009 */  lui        $v1, %hi(D_8008BFAC)
/* 1FAD8 8001EED8 2463BFAC */  addiu      $v1, $v1, %lo(D_8008BFAC)
/* 1FADC 8001EEDC 46002032 */  c.eq.s     $f4, $f0
/* 1FAE0 8001EEE0 00000000 */  nop
/* 1FAE4 8001EEE4 4503009C */  bc1tl      .L8001F158
/* 1FAE8 8001EEE8 8FBF001C */   lw        $ra, 0x1C($sp)
/* 1FAEC 8001EEEC C4660000 */  lwc1       $f6, 0x0($v1)
/* 1FAF0 8001EEF0 3C014049 */  lui        $at, (0x40490000 >> 16)
/* 1FAF4 8001EEF4 44819800 */  mtc1       $at, $f19
/* 1FAF8 8001EEF8 46003200 */  add.s      $f8, $f6, $f0
/* 1FAFC 8001EEFC 44809000 */  mtc1       $zero, $f18
/* 1FB00 8001EF00 3C028009 */  lui        $v0, %hi(D_8008BFB0)
/* 1FB04 8001EF04 2442BFB0 */  addiu      $v0, $v0, %lo(D_8008BFB0)
/* 1FB08 8001EF08 E4680000 */  swc1       $f8, 0x0($v1)
/* 1FB0C 8001EF0C C46A0000 */  lwc1       $f10, 0x0($v1)
/* 1FB10 8001EF10 46005421 */  cvt.d.s    $f16, $f10
/* 1FB14 8001EF14 4630903E */  c.le.d     $f18, $f16
/* 1FB18 8001EF18 00000000 */  nop
/* 1FB1C 8001EF1C 4502008E */  bc1fl      .L8001F158
/* 1FB20 8001EF20 8FBF001C */   lw        $ra, 0x1C($sp)
/* 1FB24 8001EF24 94480000 */  lhu        $t0, 0x0($v0)
/* 1FB28 8001EF28 240407D0 */  addiu      $a0, $zero, 0x7D0
/* 1FB2C 8001EF2C 25090032 */  addiu      $t1, $t0, 0x32
/* 1FB30 8001EF30 0C009BA4 */  jal        func_80026E90
/* 1FB34 8001EF34 A4490000 */   sh        $t1, 0x0($v0)
/* 1FB38 8001EF38 3C0A8009 */  lui        $t2, %hi(D_8008BFB0)
/* 1FB3C 8001EF3C 954ABFB0 */  lhu        $t2, %lo(D_8008BFB0)($t2)
/* 1FB40 8001EF40 004A082B */  sltu       $at, $v0, $t2
/* 1FB44 8001EF44 10200080 */  beqz       $at, .L8001F148
/* 1FB48 8001EF48 3C028008 */   lui       $v0, %hi(D_8007AA08)
/* 1FB4C 8001EF4C 2442AA08 */  addiu      $v0, $v0, %lo(D_8007AA08)
/* 1FB50 8001EF50 C44C0018 */  lwc1       $f12, 0x18($v0)
/* 1FB54 8001EF54 C44E0020 */  lwc1       $f14, 0x20($v0)
/* 1FB58 8001EF58 E7AC003C */  swc1       $f12, 0x3C($sp)
/* 1FB5C 8001EF5C 0C007F82 */  jal        func_8001FE08
/* 1FB60 8001EF60 E7AE0038 */   swc1      $f14, 0x38($sp)
/* 1FB64 8001EF64 10400078 */  beqz       $v0, .L8001F148
/* 1FB68 8001EF68 C7AC003C */   lwc1      $f12, 0x3C($sp)
/* 1FB6C 8001EF6C 3C068009 */  lui        $a2, %hi(D_8008BF98)
/* 1FB70 8001EF70 8CC6BF98 */  lw         $a2, %lo(D_8008BF98)($a2)
/* 1FB74 8001EF74 C7AE0038 */  lwc1       $f14, 0x38($sp)
/* 1FB78 8001EF78 0C007F51 */  jal        func_8001FD44
/* 1FB7C 8001EF7C AFA20024 */   sw        $v0, 0x24($sp)
/* 1FB80 8001EF80 10400071 */  beqz       $v0, .L8001F148
/* 1FB84 8001EF84 8FA30024 */   lw        $v1, 0x24($sp)
/* 1FB88 8001EF88 3C018009 */  lui        $at, %hi(D_8008BFB0)
/* 1FB8C 8001EF8C A420BFB0 */  sh         $zero, %lo(D_8008BFB0)($at)
/* 1FB90 8001EF90 846B0000 */  lh         $t3, 0x0($v1)
/* 1FB94 8001EF94 846C0002 */  lh         $t4, 0x2($v1)
/* 1FB98 8001EF98 C7A4003C */  lwc1       $f4, 0x3C($sp)
/* 1FB9C 8001EF9C 448B3000 */  mtc1       $t3, $f6
/* 1FBA0 8001EFA0 448C8000 */  mtc1       $t4, $f16
/* 1FBA4 8001EFA4 C7AA0038 */  lwc1       $f10, 0x38($sp)
/* 1FBA8 8001EFA8 46803220 */  cvt.s.w    $f8, $f6
/* 1FBAC 8001EFAC AFA20028 */  sw         $v0, 0x28($sp)
/* 1FBB0 8001EFB0 AFA30024 */  sw         $v1, 0x24($sp)
/* 1FBB4 8001EFB4 468084A0 */  cvt.s.w    $f18, $f16
/* 1FBB8 8001EFB8 46082301 */  sub.s      $f12, $f4, $f8
/* 1FBBC 8001EFBC 0C009C34 */  jal        func_800270D0
/* 1FBC0 8001EFC0 46125381 */   sub.s     $f14, $f10, $f18
/* 1FBC4 8001EFC4 8FA30024 */  lw         $v1, 0x24($sp)
/* 1FBC8 8001EFC8 8FA40028 */  lw         $a0, 0x28($sp)
/* 1FBCC 8001EFCC 44060000 */  mfc1       $a2, $f0
/* 1FBD0 8001EFD0 846D0000 */  lh         $t5, 0x0($v1)
/* 1FBD4 8001EFD4 846E0002 */  lh         $t6, 0x2($v1)
/* 1FBD8 8001EFD8 24870008 */  addiu      $a3, $a0, 0x8
/* 1FBDC 8001EFDC 448D3000 */  mtc1       $t5, $f6
/* 1FBE0 8001EFE0 448E2000 */  mtc1       $t6, $f4
/* 1FBE4 8001EFE4 46803320 */  cvt.s.w    $f12, $f6
/* 1FBE8 8001EFE8 0C007FC4 */  jal        func_8001FF10
/* 1FBEC 8001EFEC 468023A0 */   cvt.s.w   $f14, $f4
/* 1FBF0 8001EFF0 8FA30024 */  lw         $v1, 0x24($sp)
/* 1FBF4 8001EFF4 3C018009 */  lui        $at, %hi(D_8008BE5C)
/* 1FBF8 8001EFF8 3C028009 */  lui        $v0, %hi(D_8008BE52)
/* 1FBFC 8001EFFC 846F0000 */  lh         $t7, 0x0($v1)
/* 1FC00 8001F000 2442BE52 */  addiu      $v0, $v0, %lo(D_8008BE52)
/* 1FC04 8001F004 24190205 */  addiu      $t9, $zero, 0x205
/* 1FC08 8001F008 448F4000 */  mtc1       $t7, $f8
/* 1FC0C 8001F00C 3C0B8008 */  lui        $t3, %hi(D_8007C050)
/* 1FC10 8001F010 3C0D8008 */  lui        $t5, %hi(D_8007B930)
/* 1FC14 8001F014 46804420 */  cvt.s.w    $f16, $f8
/* 1FC18 8001F018 3C098008 */  lui        $t1, %hi(D_8007AA1C)
/* 1FC1C 8001F01C 24080014 */  addiu      $t0, $zero, 0x14
/* 1FC20 8001F020 E430BE5C */  swc1       $f16, %lo(D_8008BE5C)($at)
/* 1FC24 8001F024 84780002 */  lh         $t8, 0x2($v1)
/* 1FC28 8001F028 3C018009 */  lui        $at, %hi(D_8008BE60)
/* 1FC2C 8001F02C 44985000 */  mtc1       $t8, $f10
/* 1FC30 8001F030 00000000 */  nop
/* 1FC34 8001F034 468054A0 */  cvt.s.w    $f18, $f10
/* 1FC38 8001F038 E432BE60 */  swc1       $f18, %lo(D_8008BE60)($at)
/* 1FC3C 8001F03C A4590000 */  sh         $t9, 0x0($v0)
/* 1FC40 8001F040 956BC050 */  lhu        $t3, %lo(D_8007C050)($t3)
/* 1FC44 8001F044 3C018009 */  lui        $at, %hi(D_8008BE56)
/* 1FC48 8001F048 A420BE56 */  sh         $zero, %lo(D_8008BE56)($at)
/* 1FC4C 8001F04C 000B6080 */  sll        $t4, $t3, 2
/* 1FC50 8001F050 018B6021 */  addu       $t4, $t4, $t3
/* 1FC54 8001F054 000C6080 */  sll        $t4, $t4, 2
/* 1FC58 8001F058 018B6023 */  subu       $t4, $t4, $t3
/* 1FC5C 8001F05C 000C6100 */  sll        $t4, $t4, 4
/* 1FC60 8001F060 01AC6821 */  addu       $t5, $t5, $t4
/* 1FC64 8001F064 8DADB930 */  lw         $t5, %lo(D_8007B930)($t5)
/* 1FC68 8001F068 8D29AA1C */  lw         $t1, %lo(D_8007AA1C)($t1)
/* 1FC6C 8001F06C 3C018009 */  lui        $at, %hi(D_8008BE54)
/* 1FC70 8001F070 A428BE54 */  sh         $t0, %lo(D_8008BE54)($at)
/* 1FC74 8001F074 95AE000C */  lhu        $t6, 0xC($t5)
/* 1FC78 8001F078 952A000C */  lhu        $t2, 0xC($t1)
/* 1FC7C 8001F07C 014E082A */  slt        $at, $t2, $t6
/* 1FC80 8001F080 10200006 */  beqz       $at, .L8001F09C
/* 1FC84 8001F084 3C018009 */   lui       $at, %hi(D_8008BE58)
/* 1FC88 8001F088 A420BE58 */  sh         $zero, %lo(D_8008BE58)($at)
/* 1FC8C 8001F08C 944F0000 */  lhu        $t7, 0x0($v0)
/* 1FC90 8001F090 35F80002 */  ori        $t8, $t7, 0x2
/* 1FC94 8001F094 10000006 */  b          .L8001F0B0
/* 1FC98 8001F098 A4580000 */   sh        $t8, 0x0($v0)
.L8001F09C:
/* 1FC9C 8001F09C 3C198009 */  lui        $t9, %hi(D_8008BE5A)
/* 1FCA0 8001F0A0 9739BE5A */  lhu        $t9, %lo(D_8008BE5A)($t9)
/* 1FCA4 8001F0A4 3C018009 */  lui        $at, %hi(D_8008BE58)
/* 1FCA8 8001F0A8 2728FFFF */  addiu      $t0, $t9, -0x1
/* 1FCAC 8001F0AC A428BE58 */  sh         $t0, %lo(D_8008BE58)($at)
.L8001F0B0:
/* 1FCB0 8001F0B0 0C0011FE */  jal        func_800047F8
/* 1FCB4 8001F0B4 00000000 */   nop
/* 1FCB8 8001F0B8 0C0090C3 */  jal        func_8002430C
/* 1FCBC 8001F0BC 00000000 */   nop
/* 1FCC0 8001F0C0 3C0142C8 */  lui        $at, (0x42C80000 >> 16)
/* 1FCC4 8001F0C4 44813000 */  mtc1       $at, $f6
/* 1FCC8 8001F0C8 3C028009 */  lui        $v0, %hi(D_8008BE6C)
/* 1FCCC 8001F0CC 2442BE6C */  addiu      $v0, $v0, %lo(D_8008BE6C)
/* 1FCD0 8001F0D0 E4460000 */  swc1       $f6, 0x0($v0)
/* 1FCD4 8001F0D4 C4440000 */  lwc1       $f4, 0x0($v0)
/* 1FCD8 8001F0D8 3C018007 */  lui        $at, %hi(D_8006F4A0)
/* 1FCDC 8001F0DC D430F4A0 */  ldc1       $f16, %lo(D_8006F4A0)($at)
/* 1FCE0 8001F0E0 46002221 */  cvt.d.s    $f8, $f4
/* 1FCE4 8001F0E4 3C058009 */  lui        $a1, %hi(D_8008BE5C)
/* 1FCE8 8001F0E8 46304282 */  mul.d      $f10, $f8, $f16
/* 1FCEC 8001F0EC 3C068008 */  lui        $a2, %hi(D_8007AA24)
/* 1FCF0 8001F0F0 3C078009 */  lui        $a3, %hi(D_8008BE60)
/* 1FCF4 8001F0F4 8CE7BE60 */  lw         $a3, %lo(D_8008BE60)($a3)
/* 1FCF8 8001F0F8 8CC6AA24 */  lw         $a2, %lo(D_8007AA24)($a2)
/* 1FCFC 8001F0FC 8CA5BE5C */  lw         $a1, %lo(D_8008BE5C)($a1)
/* 1FD00 8001F100 00002025 */  or         $a0, $zero, $zero
/* 1FD04 8001F104 462054A0 */  cvt.s.d    $f18, $f10
/* 1FD08 8001F108 0C007018 */  jal        func_8001C060
/* 1FD0C 8001F10C E7B20010 */   swc1      $f18, 0x10($sp)
/* 1FD10 8001F110 3C018009 */  lui        $at, %hi(D_8008BF94)
/* 1FD14 8001F114 A422BF94 */  sh         $v0, %lo(D_8008BF94)($at)
/* 1FD18 8001F118 3C018009 */  lui        $at, %hi(D_8008BE4C)
/* 1FD1C 8001F11C A420BE4C */  sh         $zero, %lo(D_8008BE4C)($at)
/* 1FD20 8001F120 3C018009 */  lui        $at, %hi(D_8008BE4E)
/* 1FD24 8001F124 24090001 */  addiu      $t1, $zero, 0x1
/* 1FD28 8001F128 3C048008 */  lui        $a0, %hi(D_8007B900)
/* 1FD2C 8001F12C A429BE4E */  sh         $t1, %lo(D_8008BE4E)($at)
/* 1FD30 8001F130 0C009BA4 */  jal        func_80026E90
/* 1FD34 8001F134 8C84B900 */   lw        $a0, %lo(D_8007B900)($a0)
/* 1FD38 8001F138 3C018009 */  lui        $at, %hi(D_8008BE50)
/* 1FD3C 8001F13C A422BE50 */  sh         $v0, %lo(D_8008BE50)($at)
/* 1FD40 8001F140 0C00A9AE */  jal        func_8002A6B8
/* 1FD44 8001F144 2404000D */   addiu     $a0, $zero, 0xD
.L8001F148:
/* 1FD48 8001F148 44803000 */  mtc1       $zero, $f6
/* 1FD4C 8001F14C 3C018009 */  lui        $at, %hi(D_8008BFAC)
/* 1FD50 8001F150 E426BFAC */  swc1       $f6, %lo(D_8008BFAC)($at)
.L8001F154:
/* 1FD54 8001F154 8FBF001C */  lw         $ra, 0x1C($sp)
.L8001F158:
/* 1FD58 8001F158 27BD0040 */  addiu      $sp, $sp, 0x40
/* 1FD5C 8001F15C 03E00008 */  jr         $ra
/* 1FD60 8001F160 00000000 */   nop

glabel func_8001F164
/* 1FD64 8001F164 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 1FD68 8001F168 AFBF001C */  sw         $ra, 0x1C($sp)
/* 1FD6C 8001F16C 3C028008 */  lui        $v0, %hi(D_8007C140)
/* 1FD70 8001F170 8C42C140 */  lw         $v0, %lo(D_8007C140)($v0)
/* 1FD74 8001F174 24010007 */  addiu      $at, $zero, 0x7
/* 1FD78 8001F178 3C038008 */  lui        $v1, %hi(D_8007C048)
/* 1FD7C 8001F17C 14410007 */  bne        $v0, $at, .L8001F19C
/* 1FD80 8001F180 2463C048 */   addiu     $v1, $v1, %lo(D_8007C048)
/* 1FD84 8001F184 44800000 */  mtc1       $zero, $f0
/* 1FD88 8001F188 3C018009 */  lui        $at, %hi(D_8008BE5C)
/* 1FD8C 8001F18C E420BE5C */  swc1       $f0, %lo(D_8008BE5C)($at)
/* 1FD90 8001F190 3C018009 */  lui        $at, %hi(D_8008BE60)
/* 1FD94 8001F194 10000009 */  b          .L8001F1BC
/* 1FD98 8001F198 E420BE60 */   swc1      $f0, %lo(D_8008BE60)($at)
.L8001F19C:
/* 1FD9C 8001F19C 3C018008 */  lui        $at, %hi(D_8007C174)
/* 1FDA0 8001F1A0 C424C174 */  lwc1       $f4, %lo(D_8007C174)($at)
/* 1FDA4 8001F1A4 3C018009 */  lui        $at, %hi(D_8008BE5C)
/* 1FDA8 8001F1A8 E424BE5C */  swc1       $f4, %lo(D_8008BE5C)($at)
/* 1FDAC 8001F1AC 3C018008 */  lui        $at, %hi(D_8007C17C)
/* 1FDB0 8001F1B0 C426C17C */  lwc1       $f6, %lo(D_8007C17C)($at)
/* 1FDB4 8001F1B4 3C018009 */  lui        $at, %hi(D_8008BE60)
/* 1FDB8 8001F1B8 E426BE60 */  swc1       $f6, %lo(D_8008BE60)($at)
.L8001F1BC:
/* 1FDBC 8001F1BC 240E0305 */  addiu      $t6, $zero, 0x305
/* 1FDC0 8001F1C0 3C018009 */  lui        $at, %hi(D_8008BE52)
/* 1FDC4 8001F1C4 A42EBE52 */  sh         $t6, %lo(D_8008BE52)($at)
/* 1FDC8 8001F1C8 3C018009 */  lui        $at, %hi(D_8008BE56)
/* 1FDCC 8001F1CC A420BE56 */  sh         $zero, %lo(D_8008BE56)($at)
/* 1FDD0 8001F1D0 3C018009 */  lui        $at, %hi(D_8008BE54)
/* 1FDD4 8001F1D4 A420BE54 */  sh         $zero, %lo(D_8008BE54)($at)
/* 1FDD8 8001F1D8 8C6F0000 */  lw         $t7, 0x0($v1)
/* 1FDDC 8001F1DC 3C088008 */  lui        $t0, %hi(D_8007C04C)
/* 1FDE0 8001F1E0 3C018009 */  lui        $at, %hi(D_8008BFA0)
/* 1FDE4 8001F1E4 2508C04C */  addiu      $t0, $t0, %lo(D_8007C04C)
/* 1FDE8 8001F1E8 AC2FBFA0 */  sw         $t7, %lo(D_8008BFA0)($at)
/* 1FDEC 8001F1EC 8D180000 */  lw         $t8, 0x0($t0)
/* 1FDF0 8001F1F0 3C018009 */  lui        $at, %hi(D_8008BFA4)
/* 1FDF4 8001F1F4 3C19803B */  lui        $t9, %hi(D_803ABA58)
/* 1FDF8 8001F1F8 AC38BFA4 */  sw         $t8, %lo(D_8008BFA4)($at)
/* 1FDFC 8001F1FC 3C018009 */  lui        $at, %hi(D_8008BFA8)
/* 1FE00 8001F200 AC22BFA8 */  sw         $v0, %lo(D_8008BFA8)($at)
/* 1FE04 8001F204 3C09803B */  lui        $t1, %hi(D_803AC3F8)
/* 1FE08 8001F208 2739BA58 */  addiu      $t9, $t9, %lo(D_803ABA58)
/* 1FE0C 8001F20C 2529C3F8 */  addiu      $t1, $t1, %lo(D_803AC3F8)
/* 1FE10 8001F210 AC790000 */  sw         $t9, 0x0($v1)
/* 1FE14 8001F214 AD090000 */  sw         $t1, 0x0($t0)
/* 1FE18 8001F218 3C0A8008 */  lui        $t2, %hi(D_8007B908)
/* 1FE1C 8001F21C 254AB908 */  addiu      $t2, $t2, %lo(D_8007B908)
/* 1FE20 8001F220 3C058009 */  lui        $a1, %hi(D_8008BE5C)
/* 1FE24 8001F224 3C068009 */  lui        $a2, %hi(D_8008BE60)
/* 1FE28 8001F228 3C078008 */  lui        $a3, %hi(D_8007C184)
/* 1FE2C 8001F22C 8CE7C184 */  lw         $a3, %lo(D_8007C184)($a3)
/* 1FE30 8001F230 8CC6BE60 */  lw         $a2, %lo(D_8008BE60)($a2)
/* 1FE34 8001F234 8CA5BE5C */  lw         $a1, %lo(D_8008BE5C)($a1)
/* 1FE38 8001F238 AFAA0010 */  sw         $t2, 0x10($sp)
/* 1FE3C 8001F23C 0C003467 */  jal        func_8000D19C
/* 1FE40 8001F240 2444FFFF */   addiu     $a0, $v0, -0x1
/* 1FE44 8001F244 0C00330C */  jal        func_8000CC30
/* 1FE48 8001F248 00000000 */   nop
/* 1FE4C 8001F24C 3C018008 */  lui        $at, %hi(D_8007C140)
/* 1FE50 8001F250 3C028008 */  lui        $v0, %hi(D_8007B900)
/* 1FE54 8001F254 AC20C140 */  sw         $zero, %lo(D_8007C140)($at)
/* 1FE58 8001F258 2442B900 */  addiu      $v0, $v0, %lo(D_8007B900)
/* 1FE5C 8001F25C 240B0001 */  addiu      $t3, $zero, 0x1
/* 1FE60 8001F260 AC4B0000 */  sw         $t3, 0x0($v0)
/* 1FE64 8001F264 3C018009 */  lui        $at, %hi(D_8008BE5A)
/* 1FE68 8001F268 0C002A57 */  jal        func_8000A95C
/* 1FE6C 8001F26C A42BBE5A */   sh        $t3, %lo(D_8008BE5A)($at)
/* 1FE70 8001F270 24020001 */  addiu      $v0, $zero, 0x1
/* 1FE74 8001F274 3C018009 */  lui        $at, %hi(D_8008BF90)
/* 1FE78 8001F278 AC22BF90 */  sw         $v0, %lo(D_8008BF90)($at)
/* 1FE7C 8001F27C 3C0D8008 */  lui        $t5, %hi(D_8007B934)
/* 1FE80 8001F280 25ADB934 */  addiu      $t5, $t5, %lo(D_8007B934)
/* 1FE84 8001F284 3C018009 */  lui        $at, %hi(D_8008BF70)
/* 1FE88 8001F288 AC2DBF70 */  sw         $t5, %lo(D_8008BF70)($at)
/* 1FE8C 8001F28C 3C018009 */  lui        $at, %hi(D_8008BE4C)
/* 1FE90 8001F290 A422BE4C */  sh         $v0, %lo(D_8008BE4C)($at)
/* 1FE94 8001F294 3C018009 */  lui        $at, %hi(D_8008BE4E)
/* 1FE98 8001F298 3C0E8009 */  lui        $t6, %hi(D_8008BE5A)
/* 1FE9C 8001F29C 95CEBE5A */  lhu        $t6, %lo(D_8008BE5A)($t6)
/* 1FEA0 8001F2A0 A422BE4E */  sh         $v0, %lo(D_8008BE4E)($at)
/* 1FEA4 8001F2A4 3C018009 */  lui        $at, %hi(D_8008BE50)
/* 1FEA8 8001F2A8 A420BE50 */  sh         $zero, %lo(D_8008BE50)($at)
/* 1FEAC 8001F2AC 3C188009 */  lui        $t8, %hi(D_8008BFA8)
/* 1FEB0 8001F2B0 8F18BFA8 */  lw         $t8, %lo(D_8008BFA8)($t8)
/* 1FEB4 8001F2B4 3C018009 */  lui        $at, %hi(D_8008BE58)
/* 1FEB8 8001F2B8 25CFFFFF */  addiu      $t7, $t6, -0x1
/* 1FEBC 8001F2BC A42FBE58 */  sh         $t7, %lo(D_8008BE58)($at)
/* 1FEC0 8001F2C0 24010008 */  addiu      $at, $zero, 0x8
/* 1FEC4 8001F2C4 13010003 */  beq        $t8, $at, .L8001F2D4
/* 1FEC8 8001F2C8 24020029 */   addiu     $v0, $zero, 0x29
/* 1FECC 8001F2CC 10000001 */  b          .L8001F2D4
/* 1FED0 8001F2D0 00001025 */   or        $v0, $zero, $zero
.L8001F2D4:
/* 1FED4 8001F2D4 00022600 */  sll        $a0, $v0, 24
/* 1FED8 8001F2D8 0004CE03 */  sra        $t9, $a0, 24
/* 1FEDC 8001F2DC 0C00A9AE */  jal        func_8002A6B8
/* 1FEE0 8001F2E0 03202025 */   or        $a0, $t9, $zero
/* 1FEE4 8001F2E4 0C0011FE */  jal        func_800047F8
/* 1FEE8 8001F2E8 00000000 */   nop
/* 1FEEC 8001F2EC 0C0090C3 */  jal        func_8002430C
/* 1FEF0 8001F2F0 00000000 */   nop
/* 1FEF4 8001F2F4 3C098009 */  lui        $t1, %hi(D_8008BFA8)
/* 1FEF8 8001F2F8 8D29BFA8 */  lw         $t1, %lo(D_8008BFA8)($t1)
/* 1FEFC 8001F2FC 3C018005 */  lui        $at, %hi(D_8004F29C)
/* 1FF00 8001F300 3C028009 */  lui        $v0, %hi(D_8008BE6C)
/* 1FF04 8001F304 00095080 */  sll        $t2, $t1, 2
/* 1FF08 8001F308 002A0821 */  addu       $at, $at, $t2
/* 1FF0C 8001F30C C428F29C */  lwc1       $f8, %lo(D_8004F29C)($at)
/* 1FF10 8001F310 2442BE6C */  addiu      $v0, $v0, %lo(D_8008BE6C)
/* 1FF14 8001F314 3C018007 */  lui        $at, %hi(D_8006F4A8)
/* 1FF18 8001F318 E4480000 */  swc1       $f8, 0x0($v0)
/* 1FF1C 8001F31C C44A0000 */  lwc1       $f10, 0x0($v0)
/* 1FF20 8001F320 D432F4A8 */  ldc1       $f18, %lo(D_8006F4A8)($at)
/* 1FF24 8001F324 3C058009 */  lui        $a1, %hi(D_8008BE5C)
/* 1FF28 8001F328 46005421 */  cvt.d.s    $f16, $f10
/* 1FF2C 8001F32C 3C068008 */  lui        $a2, %hi(D_8007C178)
/* 1FF30 8001F330 46328102 */  mul.d      $f4, $f16, $f18
/* 1FF34 8001F334 3C078009 */  lui        $a3, %hi(D_8008BE60)
/* 1FF38 8001F338 8CE7BE60 */  lw         $a3, %lo(D_8008BE60)($a3)
/* 1FF3C 8001F33C 8CC6C178 */  lw         $a2, %lo(D_8007C178)($a2)
/* 1FF40 8001F340 8CA5BE5C */  lw         $a1, %lo(D_8008BE5C)($a1)
/* 1FF44 8001F344 00002025 */  or         $a0, $zero, $zero
/* 1FF48 8001F348 462021A0 */  cvt.s.d    $f6, $f4
/* 1FF4C 8001F34C 0C007018 */  jal        func_8001C060
/* 1FF50 8001F350 E7A60010 */   swc1      $f6, 0x10($sp)
/* 1FF54 8001F354 3C018009 */  lui        $at, %hi(D_8008BF94)
/* 1FF58 8001F358 A422BF94 */  sh         $v0, %lo(D_8008BF94)($at)
/* 1FF5C 8001F35C 8FBF001C */  lw         $ra, 0x1C($sp)
/* 1FF60 8001F360 27BD0020 */  addiu      $sp, $sp, 0x20
/* 1FF64 8001F364 03E00008 */  jr         $ra
/* 1FF68 8001F368 00000000 */   nop

glabel func_8001F36C
/* 1FF6C 8001F36C 27BDFFD8 */  addiu      $sp, $sp, -0x28
/* 1FF70 8001F370 AFBF0014 */  sw         $ra, 0x14($sp)
/* 1FF74 8001F374 3C028009 */  lui        $v0, %hi(D_8008BE4C)
/* 1FF78 8001F378 9442BE4C */  lhu        $v0, %lo(D_8008BE4C)($v0)
/* 1FF7C 8001F37C 3C198008 */  lui        $t9, %hi(D_8007B908)
/* 1FF80 8001F380 2739B908 */  addiu      $t9, $t9, %lo(D_8007B908)
/* 1FF84 8001F384 10400006 */  beqz       $v0, .L8001F3A0
/* 1FF88 8001F388 3C0E8009 */   lui       $t6, %hi(D_8008BE50)
/* 1FF8C 8001F38C 24010001 */  addiu      $at, $zero, 0x1
/* 1FF90 8001F390 104100B2 */  beq        $v0, $at, .L8001F65C
/* 1FF94 8001F394 00000000 */   nop
/* 1FF98 8001F398 10000138 */  b          .L8001F87C
/* 1FF9C 8001F39C 8FBF0014 */   lw        $ra, 0x14($sp)
.L8001F3A0:
/* 1FFA0 8001F3A0 95CEBE50 */  lhu        $t6, %lo(D_8008BE50)($t6)
/* 1FFA4 8001F3A4 3C028008 */  lui        $v0, %hi(D_8007AA08)
/* 1FFA8 8001F3A8 2442AA08 */  addiu      $v0, $v0, %lo(D_8007AA08)
/* 1FFAC 8001F3AC 000E7880 */  sll        $t7, $t6, 2
/* 1FFB0 8001F3B0 01EE7821 */  addu       $t7, $t7, $t6
/* 1FFB4 8001F3B4 000F7880 */  sll        $t7, $t7, 2
/* 1FFB8 8001F3B8 01EE7823 */  subu       $t7, $t7, $t6
/* 1FFBC 8001F3BC 000F7900 */  sll        $t7, $t7, 4
/* 1FFC0 8001F3C0 25F8002C */  addiu      $t8, $t7, 0x2C
/* 1FFC4 8001F3C4 03191821 */  addu       $v1, $t8, $t9
/* 1FFC8 8001F3C8 C4640000 */  lwc1       $f4, 0x0($v1)
/* 1FFCC 8001F3CC C4460018 */  lwc1       $f6, 0x18($v0)
/* 1FFD0 8001F3D0 C4680008 */  lwc1       $f8, 0x8($v1)
/* 1FFD4 8001F3D4 C44A0020 */  lwc1       $f10, 0x20($v0)
/* 1FFD8 8001F3D8 AFA30018 */  sw         $v1, 0x18($sp)
/* 1FFDC 8001F3DC 46062301 */  sub.s      $f12, $f4, $f6
/* 1FFE0 8001F3E0 0C009C34 */  jal        func_800270D0
/* 1FFE4 8001F3E4 460A4381 */   sub.s     $f14, $f8, $f10
/* 1FFE8 8001F3E8 24040064 */  addiu      $a0, $zero, 0x64
/* 1FFEC 8001F3EC 0C009BA4 */  jal        func_80026E90
/* 1FFF0 8001F3F0 E7A0001C */   swc1      $f0, 0x1C($sp)
/* 1FFF4 8001F3F4 2C410033 */  sltiu      $at, $v0, 0x33
/* 1FFF8 8001F3F8 8FA30018 */  lw         $v1, 0x18($sp)
/* 1FFFC 8001F3FC 14200019 */  bnez       $at, .L8001F464
/* 20000 8001F400 C7AE001C */   lwc1      $f14, 0x1C($sp)
/* 20004 8001F404 3C018007 */  lui        $at, %hi(D_8006F4B0)
/* 20008 8001F408 D430F4B0 */  ldc1       $f16, %lo(D_8006F4B0)($at)
/* 2000C 8001F40C 46007121 */  cvt.d.s    $f4, $f14
/* 20010 8001F410 3C018007 */  lui        $at, %hi(D_8006F4B8)
/* 20014 8001F414 46302180 */  add.d      $f6, $f4, $f16
/* 20018 8001F418 D428F4B8 */  ldc1       $f8, %lo(D_8006F4B8)($at)
/* 2001C 8001F41C 3C018007 */  lui        $at, %hi(D_8006F4C0)
/* 20020 8001F420 462033A0 */  cvt.s.d    $f14, $f6
/* 20024 8001F424 46007021 */  cvt.d.s    $f0, $f14
/* 20028 8001F428 4628003C */  c.lt.d     $f0, $f8
/* 2002C 8001F42C 00000000 */  nop
/* 20030 8001F430 45020006 */  bc1fl      .L8001F44C
/* 20034 8001F434 4620803C */   c.lt.d    $f16, $f0
/* 20038 8001F438 D42CF4C0 */  ldc1       $f12, %lo(D_8006F4C0)($at)
/* 2003C 8001F43C 462C0280 */  add.d      $f10, $f0, $f12
/* 20040 8001F440 10000008 */  b          .L8001F464
/* 20044 8001F444 462053A0 */   cvt.s.d   $f14, $f10
/* 20048 8001F448 4620803C */  c.lt.d     $f16, $f0
.L8001F44C:
/* 2004C 8001F44C 3C018007 */  lui        $at, %hi(D_8006F4C8)
/* 20050 8001F450 45000004 */  bc1f       .L8001F464
/* 20054 8001F454 00000000 */   nop
/* 20058 8001F458 D42CF4C8 */  ldc1       $f12, %lo(D_8006F4C8)($at)
/* 2005C 8001F45C 462C0101 */  sub.d      $f4, $f0, $f12
/* 20060 8001F460 462023A0 */  cvt.s.d    $f14, $f4
.L8001F464:
/* 20064 8001F464 3C018007 */  lui        $at, %hi(D_8006F4D0)
/* 20068 8001F468 D42CF4D0 */  ldc1       $f12, %lo(D_8006F4D0)($at)
/* 2006C 8001F46C 3C018007 */  lui        $at, %hi(D_8006F4D8)
/* 20070 8001F470 D430F4D8 */  ldc1       $f16, %lo(D_8006F4D8)($at)
/* 20074 8001F474 3C018007 */  lui        $at, %hi(D_8006F4E0)
/* 20078 8001F478 D428F4E0 */  ldc1       $f8, %lo(D_8006F4E0)($at)
/* 2007C 8001F47C 460071A1 */  cvt.d.s    $f6, $f14
/* 20080 8001F480 3C018007 */  lui        $at, %hi(D_8006F4E8)
/* 20084 8001F484 46283280 */  add.d      $f10, $f6, $f8
/* 20088 8001F488 D424F4E8 */  ldc1       $f4, %lo(D_8006F4E8)($at)
/* 2008C 8001F48C 462053A0 */  cvt.s.d    $f14, $f10
/* 20090 8001F490 46007021 */  cvt.d.s    $f0, $f14
/* 20094 8001F494 4624003C */  c.lt.d     $f0, $f4
/* 20098 8001F498 00000000 */  nop
/* 2009C 8001F49C 45020005 */  bc1fl      .L8001F4B4
/* 200A0 8001F4A0 4620803C */   c.lt.d    $f16, $f0
/* 200A4 8001F4A4 462C0180 */  add.d      $f6, $f0, $f12
/* 200A8 8001F4A8 10000007 */  b          .L8001F4C8
/* 200AC 8001F4AC 462033A0 */   cvt.s.d   $f14, $f6
/* 200B0 8001F4B0 4620803C */  c.lt.d     $f16, $f0
.L8001F4B4:
/* 200B4 8001F4B4 00000000 */  nop
/* 200B8 8001F4B8 45020004 */  bc1fl      .L8001F4CC
/* 200BC 8001F4BC 44808000 */   mtc1      $zero, $f16
/* 200C0 8001F4C0 462C0201 */  sub.d      $f8, $f0, $f12
/* 200C4 8001F4C4 462043A0 */  cvt.s.d    $f14, $f8
.L8001F4C8:
/* 200C8 8001F4C8 44808000 */  mtc1       $zero, $f16
.L8001F4CC:
/* 200CC 8001F4CC 3C058009 */  lui        $a1, %hi(D_8008BE40)
/* 200D0 8001F4D0 24A5BE40 */  addiu      $a1, $a1, %lo(D_8008BE40)
/* 200D4 8001F4D4 E4B00000 */  swc1       $f16, 0x0($a1)
/* 200D8 8001F4D8 8C620064 */  lw         $v0, 0x64($v1)
/* 200DC 8001F4DC C442001C */  lwc1       $f2, 0x1C($v0)
/* 200E0 8001F4E0 C44C0018 */  lwc1       $f12, 0x18($v0)
/* 200E4 8001F4E4 460C103C */  c.lt.s     $f2, $f12
/* 200E8 8001F4E8 00000000 */  nop
/* 200EC 8001F4EC 4502000D */  bc1fl      .L8001F524
/* 200F0 8001F4F0 C4640024 */   lwc1      $f4, 0x24($v1)
/* 200F4 8001F4F4 C46A0024 */  lwc1       $f10, 0x24($v1)
/* 200F8 8001F4F8 3C01402E */  lui        $at, (0x402E0000 >> 16)
/* 200FC 8001F4FC 44819800 */  mtc1       $at, $f19
/* 20100 8001F500 460A6102 */  mul.s      $f4, $f12, $f10
/* 20104 8001F504 44809000 */  mtc1       $zero, $f18
/* 20108 8001F508 46002021 */  cvt.d.s    $f0, $f4
/* 2010C 8001F50C 46200180 */  add.d      $f6, $f0, $f0
/* 20110 8001F510 46323200 */  add.d      $f8, $f6, $f18
/* 20114 8001F514 462042A0 */  cvt.s.d    $f10, $f8
/* 20118 8001F518 1000000B */  b          .L8001F548
/* 2011C 8001F51C E4AA0004 */   swc1      $f10, 0x4($a1)
/* 20120 8001F520 C4640024 */  lwc1       $f4, 0x24($v1)
.L8001F524:
/* 20124 8001F524 3C01402E */  lui        $at, (0x402E0000 >> 16)
/* 20128 8001F528 44819800 */  mtc1       $at, $f19
/* 2012C 8001F52C 46041182 */  mul.s      $f6, $f2, $f4
/* 20130 8001F530 44809000 */  mtc1       $zero, $f18
/* 20134 8001F534 46003021 */  cvt.d.s    $f0, $f6
/* 20138 8001F538 46200200 */  add.d      $f8, $f0, $f0
/* 2013C 8001F53C 46324280 */  add.d      $f10, $f8, $f18
/* 20140 8001F540 46205120 */  cvt.s.d    $f4, $f10
/* 20144 8001F544 E4A40004 */  swc1       $f4, 0x4($a1)
.L8001F548:
/* 20148 8001F548 C4A60004 */  lwc1       $f6, 0x4($a1)
/* 2014C 8001F54C 3C013FF8 */  lui        $at, (0x3FF80000 >> 16)
/* 20150 8001F550 44815800 */  mtc1       $at, $f11
/* 20154 8001F554 44805000 */  mtc1       $zero, $f10
/* 20158 8001F558 46003221 */  cvt.d.s    $f8, $f6
/* 2015C 8001F55C 3C028008 */  lui        $v0, %hi(D_80085E48)
/* 20160 8001F560 462A4102 */  mul.d      $f4, $f8, $f10
/* 20164 8001F564 24425E48 */  addiu      $v0, $v0, %lo(D_80085E48)
/* 20168 8001F568 46007306 */  mov.s      $f12, $f14
/* 2016C 8001F56C AFA30018 */  sw         $v1, 0x18($sp)
/* 20170 8001F570 462021A0 */  cvt.s.d    $f6, $f4
/* 20174 8001F574 0C009C6D */  jal        func_800271B4
/* 20178 8001F578 E446004C */   swc1      $f6, 0x4C($v0)
/* 2017C 8001F57C 8FA30018 */  lw         $v1, 0x18($sp)
/* 20180 8001F580 3C058009 */  lui        $a1, %hi(D_8008BE40)
/* 20184 8001F584 24A5BE40 */  addiu      $a1, $a1, %lo(D_8008BE40)
/* 20188 8001F588 C4AA0000 */  lwc1       $f10, 0x0($a1)
/* 2018C 8001F58C C4680000 */  lwc1       $f8, 0x0($v1)
/* 20190 8001F590 3C028008 */  lui        $v0, %hi(D_80085E48)
/* 20194 8001F594 24425E48 */  addiu      $v0, $v0, %lo(D_80085E48)
/* 20198 8001F598 460A4100 */  add.s      $f4, $f8, $f10
/* 2019C 8001F59C C4A80004 */  lwc1       $f8, 0x4($a1)
/* 201A0 8001F5A0 3C01402E */  lui        $at, (0x402E0000 >> 16)
/* 201A4 8001F5A4 44819800 */  mtc1       $at, $f19
/* 201A8 8001F5A8 E444000C */  swc1       $f4, 0xC($v0)
/* 201AC 8001F5AC C4660008 */  lwc1       $f6, 0x8($v1)
/* 201B0 8001F5B0 44809000 */  mtc1       $zero, $f18
/* 201B4 8001F5B4 3C018008 */  lui        $at, %hi(D_8007AA24)
/* 201B8 8001F5B8 46083280 */  add.s      $f10, $f6, $f8
/* 201BC 8001F5BC 44808000 */  mtc1       $zero, $f16
/* 201C0 8001F5C0 3C058009 */  lui        $a1, %hi(D_8008BE4C)
/* 201C4 8001F5C4 3C048009 */  lui        $a0, %hi(D_8008BE4E)
/* 201C8 8001F5C8 E44A0014 */  swc1       $f10, 0x14($v0)
/* 201CC 8001F5CC C4640004 */  lwc1       $f4, 0x4($v1)
/* 201D0 8001F5D0 2484BE4E */  addiu      $a0, $a0, %lo(D_8008BE4E)
/* 201D4 8001F5D4 24A5BE4C */  addiu      $a1, $a1, %lo(D_8008BE4C)
/* 201D8 8001F5D8 460021A1 */  cvt.d.s    $f6, $f4
/* 201DC 8001F5DC 46323200 */  add.d      $f8, $f6, $f18
/* 201E0 8001F5E0 462042A0 */  cvt.s.d    $f10, $f8
/* 201E4 8001F5E4 E44A0010 */  swc1       $f10, 0x10($v0)
/* 201E8 8001F5E8 C4440010 */  lwc1       $f4, 0x10($v0)
/* 201EC 8001F5EC C420AA24 */  lwc1       $f0, %lo(D_8007AA24)($at)
/* 201F0 8001F5F0 3C014170 */  lui        $at, (0x41700000 >> 16)
/* 201F4 8001F5F4 44815000 */  mtc1       $at, $f10
/* 201F8 8001F5F8 4600203C */  c.lt.s     $f4, $f0
/* 201FC 8001F5FC 3C018007 */  lui        $at, %hi(D_8006F4F0)
/* 20200 8001F600 45020003 */  bc1fl      .L8001F610
/* 20204 8001F604 E4500048 */   swc1      $f16, 0x48($v0)
/* 20208 8001F608 E4400010 */  swc1       $f0, 0x10($v0)
/* 2020C 8001F60C E4500048 */  swc1       $f16, 0x48($v0)
.L8001F610:
/* 20210 8001F610 C4460048 */  lwc1       $f6, 0x48($v0)
/* 20214 8001F614 AC400000 */  sw         $zero, 0x0($v0)
/* 20218 8001F618 E450003C */  swc1       $f16, 0x3C($v0)
/* 2021C 8001F61C E4460044 */  swc1       $f6, 0x44($v0)
/* 20220 8001F620 C4480044 */  lwc1       $f8, 0x44($v0)
/* 20224 8001F624 E44A0058 */  swc1       $f10, 0x58($v0)
/* 20228 8001F628 AC430080 */  sw         $v1, 0x80($v0)
/* 2022C 8001F62C E4480040 */  swc1       $f8, 0x40($v0)
/* 20230 8001F630 C424F4F0 */  lwc1       $f4, %lo(D_8006F4F0)($at)
/* 20234 8001F634 C446002C */  lwc1       $f6, 0x2C($v0)
/* 20238 8001F638 3C018008 */  lui        $at, %hi(D_80085F78)
/* 2023C 8001F63C E4440070 */  swc1       $f4, 0x70($v0)
/* 20240 8001F640 E4265F78 */  swc1       $f6, %lo(D_80085F78)($at)
/* 20244 8001F644 94A80000 */  lhu        $t0, 0x0($a1)
/* 20248 8001F648 240A003C */  addiu      $t2, $zero, 0x3C
/* 2024C 8001F64C A48A0000 */  sh         $t2, 0x0($a0)
/* 20250 8001F650 25090001 */  addiu      $t1, $t0, 0x1
/* 20254 8001F654 10000088 */  b          .L8001F878
/* 20258 8001F658 A4A90000 */   sh        $t1, 0x0($a1)
.L8001F65C:
/* 2025C 8001F65C 3C048009 */  lui        $a0, %hi(D_8008BE4E)
/* 20260 8001F660 2484BE4E */  addiu      $a0, $a0, %lo(D_8008BE4E)
/* 20264 8001F664 948B0000 */  lhu        $t3, 0x0($a0)
/* 20268 8001F668 256CFFFF */  addiu      $t4, $t3, -0x1
/* 2026C 8001F66C 318DFFFF */  andi       $t5, $t4, 0xFFFF
/* 20270 8001F670 15A00081 */  bnez       $t5, .L8001F878
/* 20274 8001F674 A48C0000 */   sh        $t4, 0x0($a0)
/* 20278 8001F678 3C028009 */  lui        $v0, %hi(D_8008BE52)
/* 2027C 8001F67C 2442BE52 */  addiu      $v0, $v0, %lo(D_8008BE52)
/* 20280 8001F680 944E0000 */  lhu        $t6, 0x0($v0)
/* 20284 8001F684 3C048008 */  lui        $a0, %hi(D_80085F60)
/* 20288 8001F688 31CFFDFF */  andi       $t7, $t6, 0xFDFF
/* 2028C 8001F68C A44F0000 */  sh         $t7, 0x0($v0)
/* 20290 8001F690 0C00576D */  jal        func_80015DB4
/* 20294 8001F694 8C845F60 */   lw        $a0, %lo(D_80085F60)($a0)
/* 20298 8001F698 3C028008 */  lui        $v0, %hi(D_8007AA08)
/* 2029C 8001F69C 3C018009 */  lui        $at, %hi(D_8008BE5C)
/* 202A0 8001F6A0 C428BE5C */  lwc1       $f8, %lo(D_8008BE5C)($at)
/* 202A4 8001F6A4 2442AA08 */  addiu      $v0, $v0, %lo(D_8007AA08)
/* 202A8 8001F6A8 3C018009 */  lui        $at, %hi(D_8008BE60)
/* 202AC 8001F6AC C44A0018 */  lwc1       $f10, 0x18($v0)
/* 202B0 8001F6B0 C424BE60 */  lwc1       $f4, %lo(D_8008BE60)($at)
/* 202B4 8001F6B4 C4460020 */  lwc1       $f6, 0x20($v0)
/* 202B8 8001F6B8 460A4301 */  sub.s      $f12, $f8, $f10
/* 202BC 8001F6BC 0C009C34 */  jal        func_800270D0
/* 202C0 8001F6C0 46062381 */   sub.s     $f14, $f4, $f6
/* 202C4 8001F6C4 3C018007 */  lui        $at, %hi(D_8006F4F8)
/* 202C8 8001F6C8 D430F4F8 */  ldc1       $f16, %lo(D_8006F4F8)($at)
/* 202CC 8001F6CC 46000221 */  cvt.d.s    $f8, $f0
/* 202D0 8001F6D0 3C058009 */  lui        $a1, %hi(D_8008BE40)
/* 202D4 8001F6D4 46304280 */  add.d      $f10, $f8, $f16
/* 202D8 8001F6D8 3C018007 */  lui        $at, %hi(D_8006F508)
/* 202DC 8001F6DC 24A5BE40 */  addiu      $a1, $a1, %lo(D_8008BE40)
/* 202E0 8001F6E0 462053A0 */  cvt.s.d    $f14, $f10
/* 202E4 8001F6E4 460070A1 */  cvt.d.s    $f2, $f14
/* 202E8 8001F6E8 4622803C */  c.lt.d     $f16, $f2
/* 202EC 8001F6EC 44808000 */  mtc1       $zero, $f16
/* 202F0 8001F6F0 45000006 */  bc1f       .L8001F70C
/* 202F4 8001F6F4 00000000 */   nop
/* 202F8 8001F6F8 3C018007 */  lui        $at, %hi(D_8006F500)
/* 202FC 8001F6FC D42CF500 */  ldc1       $f12, %lo(D_8006F500)($at)
/* 20300 8001F700 462C1101 */  sub.d      $f4, $f2, $f12
/* 20304 8001F704 1000000A */  b          .L8001F730
/* 20308 8001F708 462023A0 */   cvt.s.d   $f14, $f4
.L8001F70C:
/* 2030C 8001F70C D426F508 */  ldc1       $f6, %lo(D_8006F508)($at)
/* 20310 8001F710 3C018007 */  lui        $at, %hi(D_8006F510)
/* 20314 8001F714 4626103C */  c.lt.d     $f2, $f6
/* 20318 8001F718 00000000 */  nop
/* 2031C 8001F71C 45020005 */  bc1fl      .L8001F734
/* 20320 8001F720 3C014248 */   lui       $at, (0x42480000 >> 16)
/* 20324 8001F724 D42CF510 */  ldc1       $f12, %lo(D_8006F510)($at)
/* 20328 8001F728 462C1200 */  add.d      $f8, $f2, $f12
/* 2032C 8001F72C 462043A0 */  cvt.s.d    $f14, $f8
.L8001F730:
/* 20330 8001F730 3C014248 */  lui        $at, (0x42480000 >> 16)
.L8001F734:
/* 20334 8001F734 44815000 */  mtc1       $at, $f10
/* 20338 8001F738 E4B00000 */  swc1       $f16, 0x0($a1)
/* 2033C 8001F73C 46007306 */  mov.s      $f12, $f14
/* 20340 8001F740 0C009C6D */  jal        func_800271B4
/* 20344 8001F744 E4AA0004 */   swc1      $f10, 0x4($a1)
/* 20348 8001F748 3C038008 */  lui        $v1, %hi(D_8007AA08)
/* 2034C 8001F74C 3C058009 */  lui        $a1, %hi(D_8008BE40)
/* 20350 8001F750 24A5BE40 */  addiu      $a1, $a1, %lo(D_8008BE40)
/* 20354 8001F754 2463AA08 */  addiu      $v1, $v1, %lo(D_8007AA08)
/* 20358 8001F758 C4640018 */  lwc1       $f4, 0x18($v1)
/* 2035C 8001F75C C4A60000 */  lwc1       $f6, 0x0($a1)
/* 20360 8001F760 C46A001C */  lwc1       $f10, 0x1C($v1)
/* 20364 8001F764 3C01403E */  lui        $at, (0x403E0000 >> 16)
/* 20368 8001F768 46062200 */  add.s      $f8, $f4, $f6
/* 2036C 8001F76C 44803000 */  mtc1       $zero, $f6
/* 20370 8001F770 44813800 */  mtc1       $at, $f7
/* 20374 8001F774 3C028008 */  lui        $v0, %hi(D_80085E48)
/* 20378 8001F778 46005121 */  cvt.d.s    $f4, $f10
/* 2037C 8001F77C 24425E48 */  addiu      $v0, $v0, %lo(D_80085E48)
/* 20380 8001F780 E448000C */  swc1       $f8, 0xC($v0)
/* 20384 8001F784 46262200 */  add.d      $f8, $f4, $f6
/* 20388 8001F788 44808000 */  mtc1       $zero, $f16
/* 2038C 8001F78C C4A60004 */  lwc1       $f6, 0x4($a1)
/* 20390 8001F790 C4640020 */  lwc1       $f4, 0x20($v1)
/* 20394 8001F794 462042A0 */  cvt.s.d    $f10, $f8
/* 20398 8001F798 E4500048 */  swc1       $f16, 0x48($v0)
/* 2039C 8001F79C 94590008 */  lhu        $t9, 0x8($v0)
/* 203A0 8001F7A0 46062200 */  add.s      $f8, $f4, $f6
/* 203A4 8001F7A4 E44A0010 */  swc1       $f10, 0x10($v0)
/* 203A8 8001F7A8 C44A0048 */  lwc1       $f10, 0x48($v0)
/* 203AC 8001F7AC 24180004 */  addiu      $t8, $zero, 0x4
/* 203B0 8001F7B0 37280010 */  ori        $t0, $t9, 0x10
/* 203B4 8001F7B4 E44A0044 */  swc1       $f10, 0x44($v0)
/* 203B8 8001F7B8 C4440044 */  lwc1       $f4, 0x44($v0)
/* 203BC 8001F7BC AC580000 */  sw         $t8, 0x0($v0)
/* 203C0 8001F7C0 A4480008 */  sh         $t0, 0x8($v0)
/* 203C4 8001F7C4 E4480014 */  swc1       $f8, 0x14($v0)
/* 203C8 8001F7C8 3C098009 */  lui        $t1, %hi(D_8008BE52)
/* 203CC 8001F7CC E450003C */  swc1       $f16, 0x3C($v0)
/* 203D0 8001F7D0 E4440040 */  swc1       $f4, 0x40($v0)
/* 203D4 8001F7D4 9529BE52 */  lhu        $t1, %lo(D_8008BE52)($t1)
/* 203D8 8001F7D8 3C0F8008 */  lui        $t7, %hi(D_8007AA20)
/* 203DC 8001F7DC 3C0B8009 */  lui        $t3, %hi(D_8008BFA8)
/* 203E0 8001F7E0 312A0100 */  andi       $t2, $t1, 0x100
/* 203E4 8001F7E4 1140000E */  beqz       $t2, .L8001F820
/* 203E8 8001F7E8 25EFAA20 */   addiu     $t7, $t7, %lo(D_8007AA20)
/* 203EC 8001F7EC 8D6BBFA8 */  lw         $t3, %lo(D_8008BFA8)($t3)
/* 203F0 8001F7F0 24010008 */  addiu      $at, $zero, 0x8
/* 203F4 8001F7F4 1561000A */  bne        $t3, $at, .L8001F820
/* 203F8 8001F7F8 3C014248 */   lui       $at, (0x42480000 >> 16)
/* 203FC 8001F7FC 44813000 */  mtc1       $at, $f6
/* 20400 8001F800 3C0141E0 */  lui        $at, (0x41E00000 >> 16)
/* 20404 8001F804 44814000 */  mtc1       $at, $f8
/* 20408 8001F808 3C014334 */  lui        $at, (0x43340000 >> 16)
/* 2040C 8001F80C 44815000 */  mtc1       $at, $f10
/* 20410 8001F810 E4460058 */  swc1       $f6, 0x58($v0)
/* 20414 8001F814 E448005C */  swc1       $f8, 0x5C($v0)
/* 20418 8001F818 10000011 */  b          .L8001F860
/* 2041C 8001F81C E44A004C */   swc1      $f10, 0x4C($v0)
.L8001F820:
/* 20420 8001F820 3C0C8008 */  lui        $t4, %hi(D_800842BC)
/* 20424 8001F824 8D8C42BC */  lw         $t4, %lo(D_800842BC)($t4)
/* 20428 8001F828 3C0E8005 */  lui        $t6, %hi(D_8004F0B0)
/* 2042C 8001F82C 25CEF0B0 */  addiu      $t6, $t6, %lo(D_8004F0B0)
/* 20430 8001F830 000C6880 */  sll        $t5, $t4, 2
/* 20434 8001F834 01AC6823 */  subu       $t5, $t5, $t4
/* 20438 8001F838 000D6880 */  sll        $t5, $t5, 2
/* 2043C 8001F83C 01AE1821 */  addu       $v1, $t5, $t6
/* 20440 8001F840 C4660000 */  lwc1       $f6, 0x0($v1)
/* 20444 8001F844 C4440058 */  lwc1       $f4, 0x58($v0)
/* 20448 8001F848 C44A004C */  lwc1       $f10, 0x4C($v0)
/* 2044C 8001F84C 46062200 */  add.s      $f8, $f4, $f6
/* 20450 8001F850 C4640004 */  lwc1       $f4, 0x4($v1)
/* 20454 8001F854 46045180 */  add.s      $f6, $f10, $f4
/* 20458 8001F858 E4480058 */  swc1       $f8, 0x58($v0)
/* 2045C 8001F85C E446004C */  swc1       $f6, 0x4C($v0)
.L8001F860:
/* 20460 8001F860 AC4F0080 */  sw         $t7, 0x80($v0)
/* 20464 8001F864 3C018007 */  lui        $at, %hi(D_8006F518)
/* 20468 8001F868 C428F518 */  lwc1       $f8, %lo(D_8006F518)($at)
/* 2046C 8001F86C 3C018008 */  lui        $at, %hi(D_80085F84)
/* 20470 8001F870 E4480070 */  swc1       $f8, 0x70($v0)
/* 20474 8001F874 E4305F84 */  swc1       $f16, %lo(D_80085F84)($at)
.L8001F878:
/* 20478 8001F878 8FBF0014 */  lw         $ra, 0x14($sp)
.L8001F87C:
/* 2047C 8001F87C 27BD0028 */  addiu      $sp, $sp, 0x28
/* 20480 8001F880 03E00008 */  jr         $ra
/* 20484 8001F884 00000000 */   nop

glabel func_8001F888
/* 20488 8001F888 27BDFFD0 */  addiu      $sp, $sp, -0x30
/* 2048C 8001F88C 3C098009 */  lui        $t1, %hi(D_8008BE52)
/* 20490 8001F890 2529BE52 */  addiu      $t1, $t1, %lo(D_8008BE52)
/* 20494 8001F894 AFBF001C */  sw         $ra, 0x1C($sp)
/* 20498 8001F898 95230000 */  lhu        $v1, 0x0($t1)
/* 2049C 8001F89C 3C048009 */  lui        $a0, %hi(D_8008BE54)
/* 204A0 8001F8A0 2484BE54 */  addiu      $a0, $a0, %lo(D_8008BE54)
/* 204A4 8001F8A4 306E0004 */  andi       $t6, $v1, 0x4
/* 204A8 8001F8A8 51C000D7 */  beql       $t6, $zero, .L8001FC08
/* 204AC 8001F8AC 8FBF001C */   lw        $ra, 0x1C($sp)
/* 204B0 8001F8B0 94820000 */  lhu        $v0, 0x0($a0)
/* 204B4 8001F8B4 10400003 */  beqz       $v0, .L8001F8C4
/* 204B8 8001F8B8 244FFFFF */   addiu     $t7, $v0, -0x1
/* 204BC 8001F8BC 100000D1 */  b          .L8001FC04
/* 204C0 8001F8C0 A48F0000 */   sh        $t7, 0x0($a0)
.L8001F8C4:
/* 204C4 8001F8C4 30780002 */  andi       $t8, $v1, 0x2
/* 204C8 8001F8C8 13000010 */  beqz       $t8, .L8001F90C
/* 204CC 8001F8CC 3C198009 */   lui       $t9, %hi(D_8008BE58)
/* 204D0 8001F8D0 9739BE58 */  lhu        $t9, %lo(D_8008BE58)($t9)
/* 204D4 8001F8D4 3C0C8008 */  lui        $t4, %hi(D_8007C050)
/* 204D8 8001F8D8 3C0F8008 */  lui        $t7, %hi(D_8007B908)
/* 204DC 8001F8DC 00195840 */  sll        $t3, $t9, 1
/* 204E0 8001F8E0 018B6021 */  addu       $t4, $t4, $t3
/* 204E4 8001F8E4 958CC050 */  lhu        $t4, %lo(D_8007C050)($t4)
/* 204E8 8001F8E8 25EFB908 */  addiu      $t7, $t7, %lo(D_8007B908)
/* 204EC 8001F8EC 000C6880 */  sll        $t5, $t4, 2
/* 204F0 8001F8F0 01AC6821 */  addu       $t5, $t5, $t4
/* 204F4 8001F8F4 000D6880 */  sll        $t5, $t5, 2
/* 204F8 8001F8F8 01AC6823 */  subu       $t5, $t5, $t4
/* 204FC 8001F8FC 000D6900 */  sll        $t5, $t5, 4
/* 20500 8001F900 25AE002C */  addiu      $t6, $t5, 0x2C
/* 20504 8001F904 10000003 */  b          .L8001F914
/* 20508 8001F908 01CF4021 */   addu      $t0, $t6, $t7
.L8001F90C:
/* 2050C 8001F90C 3C088008 */  lui        $t0, %hi(D_8007AA20)
/* 20510 8001F910 2508AA20 */  addiu      $t0, $t0, %lo(D_8007AA20)
.L8001F914:
/* 20514 8001F914 95180060 */  lhu        $t8, 0x60($t0)
/* 20518 8001F918 33190001 */  andi       $t9, $t8, 0x1
/* 2051C 8001F91C 172000B9 */  bnez       $t9, .L8001FC04
/* 20520 8001F920 3C0B8008 */   lui       $t3, %hi(D_8007B900)
/* 20524 8001F924 8D6BB900 */  lw         $t3, %lo(D_8007B900)($t3)
/* 20528 8001F928 00002825 */  or         $a1, $zero, $zero
/* 2052C 8001F92C 306C0400 */  andi       $t4, $v1, 0x400
/* 20530 8001F930 11600002 */  beqz       $t3, .L8001F93C
/* 20534 8001F934 346E0008 */   ori       $t6, $v1, 0x8
/* 20538 8001F938 11800025 */  beqz       $t4, .L8001F9D0
.L8001F93C:
/* 2053C 8001F93C 31CF0100 */   andi      $t7, $t6, 0x100
/* 20540 8001F940 A52E0000 */  sh         $t6, 0x0($t1)
/* 20544 8001F944 11E00017 */  beqz       $t7, .L8001F9A4
/* 20548 8001F948 24050001 */   addiu     $a1, $zero, 0x1
/* 2054C 8001F94C 3C048009 */  lui        $a0, %hi(D_8008BFA8)
/* 20550 8001F950 8C84BFA8 */  lw         $a0, %lo(D_8008BFA8)($a0)
/* 20554 8001F954 AFA5002C */  sw         $a1, 0x2C($sp)
/* 20558 8001F958 AFA80024 */  sw         $t0, 0x24($sp)
/* 2055C 8001F95C 2484FFFF */  addiu      $a0, $a0, -0x1
/* 20560 8001F960 3098FFFF */  andi       $t8, $a0, 0xFFFF
/* 20564 8001F964 0C0034F3 */  jal        func_8000D3CC
/* 20568 8001F968 03002025 */   or        $a0, $t8, $zero
/* 2056C 8001F96C 3C048009 */  lui        $a0, %hi(D_8008BFA8)
/* 20570 8001F970 8C84BFA8 */  lw         $a0, %lo(D_8008BFA8)($a0)
/* 20574 8001F974 0C00354A */  jal        func_8000D528
/* 20578 8001F978 2484FFFF */   addiu     $a0, $a0, -0x1
/* 2057C 8001F97C 3C198009 */  lui        $t9, %hi(D_8008BFA0)
/* 20580 8001F980 8F39BFA0 */  lw         $t9, %lo(D_8008BFA0)($t9)
/* 20584 8001F984 3C0B8009 */  lui        $t3, %hi(D_8008BFA4)
/* 20588 8001F988 8D6BBFA4 */  lw         $t3, %lo(D_8008BFA4)($t3)
/* 2058C 8001F98C 3C018008 */  lui        $at, %hi(D_8007C048)
/* 20590 8001F990 AC39C048 */  sw         $t9, %lo(D_8007C048)($at)
/* 20594 8001F994 3C018008 */  lui        $at, %hi(D_8007C04C)
/* 20598 8001F998 8FA5002C */  lw         $a1, 0x2C($sp)
/* 2059C 8001F99C 8FA80024 */  lw         $t0, 0x24($sp)
/* 205A0 8001F9A0 AC2BC04C */  sw         $t3, %lo(D_8007C04C)($at)
.L8001F9A4:
/* 205A4 8001F9A4 AFA5002C */  sw         $a1, 0x2C($sp)
/* 205A8 8001F9A8 0C00803E */  jal        func_800200F8
/* 205AC 8001F9AC AFA80024 */   sw        $t0, 0x24($sp)
/* 205B0 8001F9B0 3C098009 */  lui        $t1, %hi(D_8008BE52)
/* 205B4 8001F9B4 3C018008 */  lui        $at, %hi(D_8007A9BC)
/* 205B8 8001F9B8 AC22A9BC */  sw         $v0, %lo(D_8007A9BC)($at)
/* 205BC 8001F9BC 2529BE52 */  addiu      $t1, $t1, %lo(D_8008BE52)
/* 205C0 8001F9C0 95230000 */  lhu        $v1, 0x0($t1)
/* 205C4 8001F9C4 8FA5002C */  lw         $a1, 0x2C($sp)
/* 205C8 8001F9C8 10000011 */  b          .L8001FA10
/* 205CC 8001F9CC 8FA80024 */   lw        $t0, 0x24($sp)
.L8001F9D0:
/* 205D0 8001F9D0 306C0010 */  andi       $t4, $v1, 0x10
/* 205D4 8001F9D4 11800003 */  beqz       $t4, .L8001F9E4
/* 205D8 8001F9D8 306D0100 */   andi      $t5, $v1, 0x100
/* 205DC 8001F9DC 1000000C */  b          .L8001FA10
/* 205E0 8001F9E0 24050001 */   addiu     $a1, $zero, 0x1
.L8001F9E4:
/* 205E4 8001F9E4 15A0000A */  bnez       $t5, .L8001FA10
/* 205E8 8001F9E8 3C0A8008 */   lui       $t2, %hi(D_8007AA08)
/* 205EC 8001F9EC 254AAA08 */  addiu      $t2, $t2, %lo(D_8007AA08)
/* 205F0 8001F9F0 8D4E0008 */  lw         $t6, 0x8($t2)
/* 205F4 8001F9F4 34780010 */  ori        $t8, $v1, 0x10
/* 205F8 8001F9F8 31CF0020 */  andi       $t7, $t6, 0x20
/* 205FC 8001F9FC 11E00004 */  beqz       $t7, .L8001FA10
/* 20600 8001FA00 00000000 */   nop
/* 20604 8001FA04 A5380000 */  sh         $t8, 0x0($t1)
/* 20608 8001FA08 24050001 */  addiu      $a1, $zero, 0x1
/* 2060C 8001FA0C 3303FFFF */  andi       $v1, $t8, 0xFFFF
.L8001FA10:
/* 20610 8001FA10 3C0A8008 */  lui        $t2, %hi(D_8007AA08)
/* 20614 8001FA14 10A00027 */  beqz       $a1, .L8001FAB4
/* 20618 8001FA18 254AAA08 */   addiu     $t2, $t2, %lo(D_8007AA08)
/* 2061C 8001FA1C 3079FFFE */  andi       $t9, $v1, 0xFFFE
/* 20620 8001FA20 A5390000 */  sh         $t9, 0x0($t1)
/* 20624 8001FA24 3C018009 */  lui        $at, %hi(D_8008C162)
/* 20628 8001FA28 A420C162 */  sh         $zero, %lo(D_8008C162)($at)
/* 2062C 8001FA2C 3C048009 */  lui        $a0, %hi(D_8008BF94)
/* 20630 8001FA30 9484BF94 */  lhu        $a0, %lo(D_8008BF94)($a0)
/* 20634 8001FA34 8D470020 */  lw         $a3, 0x20($t2)
/* 20638 8001FA38 8D46001C */  lw         $a2, 0x1C($t2)
/* 2063C 8001FA3C 0C0070A6 */  jal        func_8001C298
/* 20640 8001FA40 8D450018 */   lw        $a1, 0x18($t2)
/* 20644 8001FA44 0C002997 */  jal        func_8000A65C
/* 20648 8001FA48 00000000 */   nop
/* 2064C 8001FA4C 3C048008 */  lui        $a0, %hi(D_80085F60)
/* 20650 8001FA50 0C005886 */  jal        func_80016218
/* 20654 8001FA54 8C845F60 */   lw        $a0, %lo(D_80085F60)($a0)
/* 20658 8001FA58 3C098009 */  lui        $t1, %hi(D_8008BE52)
/* 2065C 8001FA5C 2529BE52 */  addiu      $t1, $t1, %lo(D_8008BE52)
/* 20660 8001FA60 95230000 */  lhu        $v1, 0x0($t1)
/* 20664 8001FA64 3C058008 */  lui        $a1, %hi(D_800842C0)
/* 20668 8001FA68 2404002B */  addiu      $a0, $zero, 0x2B
/* 2066C 8001FA6C 306B0100 */  andi       $t3, $v1, 0x100
/* 20670 8001FA70 11600003 */  beqz       $t3, .L8001FA80
/* 20674 8001FA74 306CFEFF */   andi      $t4, $v1, 0xFEFF
/* 20678 8001FA78 A52C0000 */  sh         $t4, 0x0($t1)
/* 2067C 8001FA7C 3183FFFF */  andi       $v1, $t4, 0xFFFF
.L8001FA80:
/* 20680 8001FA80 306D0010 */  andi       $t5, $v1, 0x10
/* 20684 8001FA84 11A00007 */  beqz       $t5, .L8001FAA4
/* 20688 8001FA88 00003025 */   or        $a2, $zero, $zero
/* 2068C 8001FA8C 3C048008 */  lui        $a0, %hi(D_800842BC)
/* 20690 8001FA90 8C8442BC */  lw         $a0, %lo(D_800842BC)($a0)
/* 20694 8001FA94 0C00A9D1 */  jal        func_8002A744
/* 20698 8001FA98 8CA542C0 */   lw        $a1, %lo(D_800842C0)($a1)
/* 2069C 8001FA9C 1000005A */  b          .L8001FC08
/* 206A0 8001FAA0 8FBF001C */   lw        $ra, 0x1C($sp)
.L8001FAA4:
/* 206A4 8001FAA4 0C00A9BD */  jal        func_8002A6F4
/* 206A8 8001FAA8 24050008 */   addiu     $a1, $zero, 0x8
/* 206AC 8001FAAC 10000056 */  b          .L8001FC08
/* 206B0 8001FAB0 8FBF001C */   lw        $ra, 0x1C($sp)
.L8001FAB4:
/* 206B4 8001FAB4 3062FFFB */  andi       $v0, $v1, 0xFFFB
/* 206B8 8001FAB8 A5220000 */  sh         $v0, 0x0($t1)
/* 206BC 8001FABC 304F0002 */  andi       $t7, $v0, 0x2
/* 206C0 8001FAC0 11E0000A */  beqz       $t7, .L8001FAEC
/* 206C4 8001FAC4 01E01025 */   or        $v0, $t7, $zero
/* 206C8 8001FAC8 0C002A8A */  jal        func_8000AA28
/* 206CC 8001FACC AFA80024 */   sw        $t0, 0x24($sp)
/* 206D0 8001FAD0 3C028009 */  lui        $v0, %hi(D_8008BE52)
/* 206D4 8001FAD4 9442BE52 */  lhu        $v0, %lo(D_8008BE52)($v0)
/* 206D8 8001FAD8 3C0A8008 */  lui        $t2, %hi(D_8007AA08)
/* 206DC 8001FADC 254AAA08 */  addiu      $t2, $t2, %lo(D_8007AA08)
/* 206E0 8001FAE0 30580002 */  andi       $t8, $v0, 0x2
/* 206E4 8001FAE4 03001025 */  or         $v0, $t8, $zero
/* 206E8 8001FAE8 8FA80024 */  lw         $t0, 0x24($sp)
.L8001FAEC:
/* 206EC 8001FAEC C5040000 */  lwc1       $f4, 0x0($t0)
/* 206F0 8001FAF0 3C038009 */  lui        $v1, %hi(D_8008BE64)
/* 206F4 8001FAF4 2463BE64 */  addiu      $v1, $v1, %lo(D_8008BE64)
/* 206F8 8001FAF8 E4640000 */  swc1       $f4, 0x0($v1)
/* 206FC 8001FAFC C5060008 */  lwc1       $f6, 0x8($t0)
/* 20700 8001FB00 3C098009 */  lui        $t1, %hi(D_8008BE68)
/* 20704 8001FB04 2529BE68 */  addiu      $t1, $t1, %lo(D_8008BE68)
/* 20708 8001FB08 10400010 */  beqz       $v0, .L8001FB4C
/* 2070C 8001FB0C E5260000 */   swc1      $f6, 0x0($t1)
/* 20710 8001FB10 3C198009 */  lui        $t9, %hi(D_8008BE58)
/* 20714 8001FB14 9739BE58 */  lhu        $t9, %lo(D_8008BE58)($t9)
/* 20718 8001FB18 3C0C8008 */  lui        $t4, %hi(D_8007C050)
/* 2071C 8001FB1C 3C018008 */  lui        $at, %hi(D_8007B918)
/* 20720 8001FB20 00195840 */  sll        $t3, $t9, 1
/* 20724 8001FB24 018B6021 */  addu       $t4, $t4, $t3
/* 20728 8001FB28 958CC050 */  lhu        $t4, %lo(D_8007C050)($t4)
/* 2072C 8001FB2C 000C6880 */  sll        $t5, $t4, 2
/* 20730 8001FB30 01AC6821 */  addu       $t5, $t5, $t4
/* 20734 8001FB34 000D6880 */  sll        $t5, $t5, 2
/* 20738 8001FB38 01AC6823 */  subu       $t5, $t5, $t4
/* 2073C 8001FB3C 000D6900 */  sll        $t5, $t5, 4
/* 20740 8001FB40 002D0821 */  addu       $at, $at, $t5
/* 20744 8001FB44 10000002 */  b          .L8001FB50
/* 20748 8001FB48 C420B918 */   lwc1      $f0, %lo(D_8007B918)($at)
.L8001FB4C:
/* 2074C 8001FB4C C540000C */  lwc1       $f0, 0xC($t2)
.L8001FB50:
/* 20750 8001FB50 10400011 */  beqz       $v0, .L8001FB98
/* 20754 8001FB54 3C018007 */   lui       $at, %hi(D_8006F520)
/* 20758 8001FB58 3C0E8009 */  lui        $t6, %hi(D_8008BE58)
/* 2075C 8001FB5C 95CEBE58 */  lhu        $t6, %lo(D_8008BE58)($t6)
/* 20760 8001FB60 3C188008 */  lui        $t8, %hi(D_8007C050)
/* 20764 8001FB64 3C0C8008 */  lui        $t4, %hi(D_8007B908)
/* 20768 8001FB68 000E7840 */  sll        $t7, $t6, 1
/* 2076C 8001FB6C 030FC021 */  addu       $t8, $t8, $t7
/* 20770 8001FB70 9718C050 */  lhu        $t8, %lo(D_8007C050)($t8)
/* 20774 8001FB74 258CB908 */  addiu      $t4, $t4, %lo(D_8007B908)
/* 20778 8001FB78 0018C880 */  sll        $t9, $t8, 2
/* 2077C 8001FB7C 0338C821 */  addu       $t9, $t9, $t8
/* 20780 8001FB80 0019C880 */  sll        $t9, $t9, 2
/* 20784 8001FB84 0338C823 */  subu       $t9, $t9, $t8
/* 20788 8001FB88 0019C900 */  sll        $t9, $t9, 4
/* 2078C 8001FB8C 272B002C */  addiu      $t3, $t9, 0x2C
/* 20790 8001FB90 10000003 */  b          .L8001FBA0
/* 20794 8001FB94 016C4021 */   addu      $t0, $t3, $t4
.L8001FB98:
/* 20798 8001FB98 3C088008 */  lui        $t0, %hi(D_8007AA20)
/* 2079C 8001FB9C 2508AA20 */  addiu      $t0, $t0, %lo(D_8007AA20)
.L8001FBA0:
/* 207A0 8001FBA0 8D0D0068 */  lw         $t5, 0x68($t0)
/* 207A4 8001FBA4 8D0E0064 */  lw         $t6, 0x64($t0)
/* 207A8 8001FBA8 C5100024 */  lwc1       $f16, 0x24($t0)
/* 207AC 8001FBAC C5A80090 */  lwc1       $f8, 0x90($t5)
/* 207B0 8001FBB0 C5CA0018 */  lwc1       $f10, 0x18($t6)
/* 207B4 8001FBB4 46080002 */  mul.s      $f0, $f0, $f8
/* 207B8 8001FBB8 00000000 */  nop
/* 207BC 8001FBBC 46105482 */  mul.s      $f18, $f10, $f16
/* 207C0 8001FBC0 10400003 */  beqz       $v0, .L8001FBD0
/* 207C4 8001FBC4 46120000 */   add.s     $f0, $f0, $f18
/* 207C8 8001FBC8 10000002 */  b          .L8001FBD4
/* 207CC 8001FBCC 24020001 */   addiu     $v0, $zero, 0x1
.L8001FBD0:
/* 207D0 8001FBD0 24020002 */  addiu      $v0, $zero, 0x2
.L8001FBD4:
/* 207D4 8001FBD4 D426F520 */  ldc1       $f6, %lo(D_8006F520)($at)
/* 207D8 8001FBD8 46000121 */  cvt.d.s    $f4, $f0
/* 207DC 8001FBDC 8D060004 */  lw         $a2, 0x4($t0)
/* 207E0 8001FBE0 46262202 */  mul.d      $f8, $f4, $f6
/* 207E4 8001FBE4 3044FFFF */  andi       $a0, $v0, 0xFFFF
/* 207E8 8001FBE8 8C650000 */  lw         $a1, 0x0($v1)
/* 207EC 8001FBEC 8D270000 */  lw         $a3, 0x0($t1)
/* 207F0 8001FBF0 462042A0 */  cvt.s.d    $f10, $f8
/* 207F4 8001FBF4 0C007018 */  jal        func_8001C060
/* 207F8 8001FBF8 E7AA0010 */   swc1      $f10, 0x10($sp)
/* 207FC 8001FBFC 3C018009 */  lui        $at, %hi(D_8008BF96)
/* 20800 8001FC00 A422BF96 */  sh         $v0, %lo(D_8008BF96)($at)
.L8001FC04:
/* 20804 8001FC04 8FBF001C */  lw         $ra, 0x1C($sp)
.L8001FC08:
/* 20808 8001FC08 27BD0030 */  addiu      $sp, $sp, 0x30
/* 2080C 8001FC0C 03E00008 */  jr         $ra
/* 20810 8001FC10 00000000 */   nop

glabel func_8001FC14
/* 20814 8001FC14 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 20818 8001FC18 AFBF0014 */  sw         $ra, 0x14($sp)
/* 2081C 8001FC1C AFA40018 */  sw         $a0, 0x18($sp)
/* 20820 8001FC20 0C006869 */  jal        func_8001A1A4
/* 20824 8001FC24 8FA40018 */   lw        $a0, 0x18($sp)
/* 20828 8001FC28 3C0D8009 */  lui        $t5, %hi(D_8008BE52)
/* 2082C 8001FC2C 25ADBE52 */  addiu      $t5, $t5, %lo(D_8008BE52)
/* 20830 8001FC30 95AC0000 */  lhu        $t4, 0x0($t5)
/* 20834 8001FC34 8FBF0018 */  lw         $ra, 0x18($sp)
/* 20838 8001FC38 318E0001 */  andi       $t6, $t4, 0x1
/* 2083C 8001FC3C 11C0003D */  beqz       $t6, .L8001FD34
/* 20840 8001FC40 318F0002 */   andi      $t7, $t4, 0x2
/* 20844 8001FC44 15E0002D */  bnez       $t7, .L8001FCFC
/* 20848 8001FC48 3C018009 */   lui       $at, %hi(D_8008BE54)
/* 2084C 8001FC4C 3C028009 */  lui        $v0, %hi(D_8008BE5A)
/* 20850 8001FC50 9442BE5A */  lhu        $v0, %lo(D_8008BE5A)($v0)
/* 20854 8001FC54 3C038009 */  lui        $v1, %hi(D_8008BE58)
/* 20858 8001FC58 240AFFFF */  addiu      $t2, $zero, -0x1
/* 2085C 8001FC5C 10400020 */  beqz       $v0, .L8001FCE0
/* 20860 8001FC60 00403025 */   or        $a2, $v0, $zero
/* 20864 8001FC64 3C088008 */  lui        $t0, %hi(D_8007B908)
/* 20868 8001FC68 3C078008 */  lui        $a3, %hi(D_8007C050)
/* 2086C 8001FC6C 3C058009 */  lui        $a1, %hi(D_8008BE58)
/* 20870 8001FC70 24A5BE58 */  addiu      $a1, $a1, %lo(D_8008BE58)
/* 20874 8001FC74 24E7C050 */  addiu      $a3, $a3, %lo(D_8007C050)
/* 20878 8001FC78 2508B908 */  addiu      $t0, $t0, %lo(D_8007B908)
/* 2087C 8001FC7C 9463BE58 */  lhu        $v1, %lo(D_8008BE58)($v1)
/* 20880 8001FC80 00405825 */  or         $t3, $v0, $zero
/* 20884 8001FC84 24090130 */  addiu      $t1, $zero, 0x130
/* 20888 8001FC88 24780001 */  addiu      $t8, $v1, 0x1
.L8001FC8C:
/* 2088C 8001FC8C 3303FFFF */  andi       $v1, $t8, 0xFFFF
/* 20890 8001FC90 006B082A */  slt        $at, $v1, $t3
/* 20894 8001FC94 14200003 */  bnez       $at, .L8001FCA4
/* 20898 8001FC98 A4B80000 */   sh        $t8, 0x0($a1)
/* 2089C 8001FC9C A4A00000 */  sh         $zero, 0x0($a1)
/* 208A0 8001FCA0 3003FFFF */  andi       $v1, $zero, 0xFFFF
.L8001FCA4:
/* 208A4 8001FCA4 0003C840 */  sll        $t9, $v1, 1
/* 208A8 8001FCA8 00F97021 */  addu       $t6, $a3, $t9
/* 208AC 8001FCAC 95C20000 */  lhu        $v0, 0x0($t6)
/* 208B0 8001FCB0 00490019 */  multu      $v0, $t1
/* 208B4 8001FCB4 00007812 */  mflo       $t7
/* 208B8 8001FCB8 010F2021 */  addu       $a0, $t0, $t7
/* 208BC 8001FCBC 9498000A */  lhu        $t8, 0xA($a0)
/* 208C0 8001FCC0 53000005 */  beql       $t8, $zero, .L8001FCD8
/* 208C4 8001FCC4 24C6FFFF */   addiu     $a2, $a2, -0x1
/* 208C8 8001FCC8 8499007C */  lh         $t9, 0x7C($a0)
/* 208CC 8001FCCC 15590004 */  bne        $t2, $t9, .L8001FCE0
/* 208D0 8001FCD0 00000000 */   nop
/* 208D4 8001FCD4 24C6FFFF */  addiu      $a2, $a2, -0x1
.L8001FCD8:
/* 208D8 8001FCD8 54C0FFEC */  bnel       $a2, $zero, .L8001FC8C
/* 208DC 8001FCDC 24780001 */   addiu     $t8, $v1, 0x1
.L8001FCE0:
/* 208E0 8001FCE0 14C00003 */  bnez       $a2, .L8001FCF0
/* 208E4 8001FCE4 240F0014 */   addiu     $t7, $zero, 0x14
/* 208E8 8001FCE8 358E0400 */  ori        $t6, $t4, 0x400
/* 208EC 8001FCEC A5AE0000 */  sh         $t6, 0x0($t5)
.L8001FCF0:
/* 208F0 8001FCF0 3C018009 */  lui        $at, %hi(D_8008BE54)
/* 208F4 8001FCF4 10000002 */  b          .L8001FD00
/* 208F8 8001FCF8 A42FBE54 */   sh        $t7, %lo(D_8008BE54)($at)
.L8001FCFC:
/* 208FC 8001FCFC A420BE54 */  sh         $zero, %lo(D_8008BE54)($at)
.L8001FD00:
/* 20900 8001FD00 3C048009 */  lui        $a0, %hi(D_8008BF96)
/* 20904 8001FD04 8FE50000 */  lw         $a1, 0x0($ra)
/* 20908 8001FD08 8FE60004 */  lw         $a2, 0x4($ra)
/* 2090C 8001FD0C 8FE70008 */  lw         $a3, 0x8($ra)
/* 20910 8001FD10 0C0070A6 */  jal        func_8001C298
/* 20914 8001FD14 9484BF96 */   lhu       $a0, %lo(D_8008BF96)($a0)
/* 20918 8001FD18 3C0D8009 */  lui        $t5, %hi(D_8008BE52)
/* 2091C 8001FD1C 25ADBE52 */  addiu      $t5, $t5, %lo(D_8008BE52)
/* 20920 8001FD20 95B80000 */  lhu        $t8, 0x0($t5)
/* 20924 8001FD24 3B0E0002 */  xori       $t6, $t8, 0x2
/* 20928 8001FD28 A5AE0000 */  sh         $t6, 0x0($t5)
/* 2092C 8001FD2C 35CF0004 */  ori        $t7, $t6, 0x4
/* 20930 8001FD30 A5AF0000 */  sh         $t7, 0x0($t5)
.L8001FD34:
/* 20934 8001FD34 8FBF0014 */  lw         $ra, 0x14($sp)
/* 20938 8001FD38 27BD0018 */  addiu      $sp, $sp, 0x18
/* 2093C 8001FD3C 03E00008 */  jr         $ra
/* 20940 8001FD40 00000000 */   nop

glabel func_8001FD44
/* 20944 8001FD44 10C0002D */  beqz       $a2, .L8001FDFC
/* 20948 8001FD48 00001825 */   or        $v1, $zero, $zero
/* 2094C 8001FD4C 8CC20004 */  lw         $v0, 0x4($a2)
/* 20950 8001FD50 8CC30000 */  lw         $v1, 0x0($a2)
/* 20954 8001FD54 10400026 */  beqz       $v0, .L8001FDF0
/* 20958 8001FD58 00000000 */   nop
.L8001FD5C:
/* 2095C 8001FD5C 846E0000 */  lh         $t6, 0x0($v1)
/* 20960 8001FD60 448E2000 */  mtc1       $t6, $f4
/* 20964 8001FD64 00000000 */  nop
/* 20968 8001FD68 46802020 */  cvt.s.w    $f0, $f4
/* 2096C 8001FD6C 460C003E */  c.le.s     $f0, $f12
/* 20970 8001FD70 00000000 */  nop
/* 20974 8001FD74 4502001C */  bc1fl      .L8001FDE8
/* 20978 8001FD78 2442FFFF */   addiu     $v0, $v0, -0x1
/* 2097C 8001FD7C 846F0002 */  lh         $t7, 0x2($v1)
/* 20980 8001FD80 448F3000 */  mtc1       $t7, $f6
/* 20984 8001FD84 00000000 */  nop
/* 20988 8001FD88 468030A0 */  cvt.s.w    $f2, $f6
/* 2098C 8001FD8C 460E103E */  c.le.s     $f2, $f14
/* 20990 8001FD90 00000000 */  nop
/* 20994 8001FD94 45020014 */  bc1fl      .L8001FDE8
/* 20998 8001FD98 2442FFFF */   addiu     $v0, $v0, -0x1
/* 2099C 8001FD9C 84780004 */  lh         $t8, 0x4($v1)
/* 209A0 8001FDA0 46006401 */  sub.s      $f16, $f12, $f0
/* 209A4 8001FDA4 44984000 */  mtc1       $t8, $f8
/* 209A8 8001FDA8 00000000 */  nop
/* 209AC 8001FDAC 468042A0 */  cvt.s.w    $f10, $f8
/* 209B0 8001FDB0 460A803E */  c.le.s     $f16, $f10
/* 209B4 8001FDB4 00000000 */  nop
/* 209B8 8001FDB8 4502000B */  bc1fl      .L8001FDE8
/* 209BC 8001FDBC 2442FFFF */   addiu     $v0, $v0, -0x1
/* 209C0 8001FDC0 84790006 */  lh         $t9, 0x6($v1)
/* 209C4 8001FDC4 46027181 */  sub.s      $f6, $f14, $f2
/* 209C8 8001FDC8 44999000 */  mtc1       $t9, $f18
/* 209CC 8001FDCC 00000000 */  nop
/* 209D0 8001FDD0 46809120 */  cvt.s.w    $f4, $f18
/* 209D4 8001FDD4 4604303E */  c.le.s     $f6, $f4
/* 209D8 8001FDD8 00000000 */  nop
/* 209DC 8001FDDC 45010004 */  bc1t       .L8001FDF0
/* 209E0 8001FDE0 00000000 */   nop
/* 209E4 8001FDE4 2442FFFF */  addiu      $v0, $v0, -0x1
.L8001FDE8:
/* 209E8 8001FDE8 1440FFDC */  bnez       $v0, .L8001FD5C
/* 209EC 8001FDEC 24630018 */   addiu     $v1, $v1, 0x18
.L8001FDF0:
/* 209F0 8001FDF0 54400003 */  bnel       $v0, $zero, .L8001FE00
/* 209F4 8001FDF4 00601025 */   or        $v0, $v1, $zero
/* 209F8 8001FDF8 00001825 */  or         $v1, $zero, $zero
.L8001FDFC:
/* 209FC 8001FDFC 00601025 */  or         $v0, $v1, $zero
.L8001FE00:
/* 20A00 8001FE00 03E00008 */  jr         $ra
/* 20A04 8001FE04 00000000 */   nop

glabel func_8001FE08
/* 20A08 8001FE08 27BDFFA0 */  addiu      $sp, $sp, -0x60
/* 20A0C 8001FE0C F7B60018 */  sdc1       $f22, 0x18($sp)
/* 20A10 8001FE10 F7B40010 */  sdc1       $f20, 0x10($sp)
/* 20A14 8001FE14 46006506 */  mov.s      $f20, $f12
/* 20A18 8001FE18 46007586 */  mov.s      $f22, $f14
/* 20A1C 8001FE1C AFBF0024 */  sw         $ra, 0x24($sp)
/* 20A20 8001FE20 3C058009 */  lui        $a1, %hi(D_8008BF9C)
/* 20A24 8001FE24 8CA5BF9C */  lw         $a1, %lo(D_8008BF9C)($a1)
/* 20A28 8001FE28 00002025 */  or         $a0, $zero, $zero
/* 20A2C 8001FE2C 00001825 */  or         $v1, $zero, $zero
/* 20A30 8001FE30 10A00031 */  beqz       $a1, .L8001FEF8
/* 20A34 8001FE34 00000000 */   nop
/* 20A38 8001FE38 8CA2000C */  lw         $v0, 0xC($a1)
/* 20A3C 8001FE3C 8CA30008 */  lw         $v1, 0x8($a1)
/* 20A40 8001FE40 27A50030 */  addiu      $a1, $sp, 0x30
/* 20A44 8001FE44 10400021 */  beqz       $v0, .L8001FECC
/* 20A48 8001FE48 3C018007 */   lui       $at, %hi(D_8006F528)
/* 20A4C 8001FE4C C430F528 */  lwc1       $f16, %lo(D_8006F528)($at)
/* 20A50 8001FE50 3C018007 */  lui        $at, %hi(D_8006F52C)
/* 20A54 8001FE54 C42EF52C */  lwc1       $f14, %lo(D_8006F52C)($at)
/* 20A58 8001FE58 846E0000 */  lh         $t6, 0x0($v1)
.L8001FE5C:
/* 20A5C 8001FE5C 846F0002 */  lh         $t7, 0x2($v1)
/* 20A60 8001FE60 2442FFFF */  addiu      $v0, $v0, -0x1
/* 20A64 8001FE64 448E2000 */  mtc1       $t6, $f4
/* 20A68 8001FE68 448F4000 */  mtc1       $t7, $f8
/* 20A6C 8001FE6C 468021A0 */  cvt.s.w    $f6, $f4
/* 20A70 8001FE70 468042A0 */  cvt.s.w    $f10, $f8
/* 20A74 8001FE74 46143001 */  sub.s      $f0, $f6, $f20
/* 20A78 8001FE78 46165081 */  sub.s      $f2, $f10, $f22
/* 20A7C 8001FE7C 46000482 */  mul.s      $f18, $f0, $f0
/* 20A80 8001FE80 00000000 */  nop
/* 20A84 8001FE84 46021102 */  mul.s      $f4, $f2, $f2
/* 20A88 8001FE88 46049300 */  add.s      $f12, $f18, $f4
/* 20A8C 8001FE8C 460C703E */  c.le.s     $f14, $f12
/* 20A90 8001FE90 00000000 */  nop
/* 20A94 8001FE94 45000008 */  bc1f       .L8001FEB8
/* 20A98 8001FE98 00000000 */   nop
/* 20A9C 8001FE9C 4610603E */  c.le.s     $f12, $f16
/* 20AA0 8001FEA0 0004C080 */  sll        $t8, $a0, 2
/* 20AA4 8001FEA4 00B8C821 */  addu       $t9, $a1, $t8
/* 20AA8 8001FEA8 45020004 */  bc1fl      .L8001FEBC
/* 20AAC 8001FEAC 28810006 */   slti      $at, $a0, 0x6
/* 20AB0 8001FEB0 AF230000 */  sw         $v1, 0x0($t9)
/* 20AB4 8001FEB4 24840001 */  addiu      $a0, $a0, 0x1
.L8001FEB8:
/* 20AB8 8001FEB8 28810006 */  slti       $at, $a0, 0x6
.L8001FEBC:
/* 20ABC 8001FEBC 10200003 */  beqz       $at, .L8001FECC
/* 20AC0 8001FEC0 24630004 */   addiu     $v1, $v1, 0x4
/* 20AC4 8001FEC4 5440FFE5 */  bnel       $v0, $zero, .L8001FE5C
/* 20AC8 8001FEC8 846E0000 */   lh        $t6, 0x0($v1)
.L8001FECC:
/* 20ACC 8001FECC 14800003 */  bnez       $a0, .L8001FEDC
/* 20AD0 8001FED0 00000000 */   nop
/* 20AD4 8001FED4 10000008 */  b          .L8001FEF8
/* 20AD8 8001FED8 00001825 */   or        $v1, $zero, $zero
.L8001FEDC:
/* 20ADC 8001FEDC 0C009BA4 */  jal        func_80026E90
/* 20AE0 8001FEE0 00000000 */   nop
/* 20AE4 8001FEE4 27A50030 */  addiu      $a1, $sp, 0x30
/* 20AE8 8001FEE8 00024080 */  sll        $t0, $v0, 2
/* 20AEC 8001FEEC 00A84821 */  addu       $t1, $a1, $t0
/* 20AF0 8001FEF0 10000001 */  b          .L8001FEF8
/* 20AF4 8001FEF4 8D230000 */   lw        $v1, 0x0($t1)
.L8001FEF8:
/* 20AF8 8001FEF8 00601025 */  or         $v0, $v1, $zero
/* 20AFC 8001FEFC 8FBF0024 */  lw         $ra, 0x24($sp)
/* 20B00 8001FF00 D7B40010 */  ldc1       $f20, 0x10($sp)
/* 20B04 8001FF04 D7B60018 */  ldc1       $f22, 0x18($sp)
/* 20B08 8001FF08 03E00008 */  jr         $ra
/* 20B0C 8001FF0C 27BD0060 */   addiu     $sp, $sp, 0x60

glabel func_8001FF10
/* 20B10 8001FF10 27BDFF38 */  addiu      $sp, $sp, -0xC8
/* 20B14 8001FF14 F7B40020 */  sdc1       $f20, 0x20($sp)
/* 20B18 8001FF18 AFB00038 */  sw         $s0, 0x38($sp)
/* 20B1C 8001FF1C F7B80030 */  sdc1       $f24, 0x30($sp)
/* 20B20 8001FF20 F7B60028 */  sdc1       $f22, 0x28($sp)
/* 20B24 8001FF24 4486A000 */  mtc1       $a2, $f20
/* 20B28 8001FF28 46006586 */  mov.s      $f22, $f12
/* 20B2C 8001FF2C 46007606 */  mov.s      $f24, $f14
/* 20B30 8001FF30 00E08025 */  or         $s0, $a3, $zero
/* 20B34 8001FF34 AFBF005C */  sw         $ra, 0x5C($sp)
/* 20B38 8001FF38 AFBE0058 */  sw         $fp, 0x58($sp)
/* 20B3C 8001FF3C AFB70054 */  sw         $s7, 0x54($sp)
/* 20B40 8001FF40 AFB60050 */  sw         $s6, 0x50($sp)
/* 20B44 8001FF44 AFB5004C */  sw         $s5, 0x4C($sp)
/* 20B48 8001FF48 AFB40048 */  sw         $s4, 0x48($sp)
/* 20B4C 8001FF4C AFB30044 */  sw         $s3, 0x44($sp)
/* 20B50 8001FF50 AFB20040 */  sw         $s2, 0x40($sp)
/* 20B54 8001FF54 AFB1003C */  sw         $s1, 0x3C($sp)
/* 20B58 8001FF58 96040000 */  lhu        $a0, 0x0($s0)
/* 20B5C 8001FF5C 0C009BA4 */  jal        func_80026E90
/* 20B60 8001FF60 26100002 */   addiu     $s0, $s0, 0x2
/* 20B64 8001FF64 3C048009 */  lui        $a0, %hi(D_8008BF9C)
/* 20B68 8001FF68 8C84BF9C */  lw         $a0, %lo(D_8008BF9C)($a0)
/* 20B6C 8001FF6C 00027040 */  sll        $t6, $v0, 1
/* 20B70 8001FF70 020E7821 */  addu       $t7, $s0, $t6
/* 20B74 8001FF74 95F80000 */  lhu        $t8, 0x0($t7)
/* 20B78 8001FF78 8C880004 */  lw         $t0, 0x4($a0)
/* 20B7C 8001FF7C 8C890000 */  lw         $t1, 0x0($a0)
/* 20B80 8001FF80 0018C8C0 */  sll        $t9, $t8, 3
/* 20B84 8001FF84 03281821 */  addu       $v1, $t9, $t0
/* 20B88 8001FF88 946B0006 */  lhu        $t3, 0x6($v1)
/* 20B8C 8001FF8C 94770004 */  lhu        $s7, 0x4($v1)
/* 20B90 8001FF90 8D2A0000 */  lw         $t2, 0x0($t1)
/* 20B94 8001FF94 000B6080 */  sll        $t4, $t3, 2
/* 20B98 8001FF98 3C1E8009 */  lui        $fp, %hi(D_8008BF90)
/* 20B9C 8001FF9C 018B6023 */  subu       $t4, $t4, $t3
/* 20BA0 8001FFA0 27DEBF90 */  addiu      $fp, $fp, %lo(D_8008BF90)
/* 20BA4 8001FFA4 000C6080 */  sll        $t4, $t4, 2
/* 20BA8 8001FFA8 8C750000 */  lw         $s5, 0x0($v1)
/* 20BAC 8001FFAC 3C128008 */  lui        $s2, %hi(D_8007B908)
/* 20BB0 8001FFB0 2652B908 */  addiu      $s2, $s2, %lo(D_8007B908)
/* 20BB4 8001FFB4 27B6006C */  addiu      $s6, $sp, 0x6C
/* 20BB8 8001FFB8 AFC00000 */  sw         $zero, 0x0($fp)
/* 20BBC 8001FFBC 12E00037 */  beqz       $s7, .L8002009C
/* 20BC0 8001FFC0 014C9821 */   addu      $s3, $t2, $t4
/* 20BC4 8001FFC4 3C108009 */  lui        $s0, %hi(D_8008BE40)
/* 20BC8 8001FFC8 2610BE40 */  addiu      $s0, $s0, %lo(D_8008BE40)
.L8001FFCC:
/* 20BCC 8001FFCC 8EA20008 */  lw         $v0, 0x8($s5)
/* 20BD0 8001FFD0 8EB10004 */  lw         $s1, 0x4($s5)
/* 20BD4 8001FFD4 2654002C */  addiu      $s4, $s2, 0x2C
/* 20BD8 8001FFD8 50400005 */  beql       $v0, $zero, .L8001FFF0
/* 20BDC 8001FFDC 8EAD0000 */   lw        $t5, 0x0($s5)
/* 20BE0 8001FFE0 0C009BA4 */  jal        func_80026E90
/* 20BE4 8001FFE4 24440001 */   addiu     $a0, $v0, 0x1
/* 20BE8 8001FFE8 02228821 */  addu       $s1, $s1, $v0
/* 20BEC 8001FFEC 8EAD0000 */  lw         $t5, 0x0($s5)
.L8001FFF0:
/* 20BF0 8001FFF0 AED10004 */  sw         $s1, 0x4($s6)
/* 20BF4 8001FFF4 3C0E8008 */  lui        $t6, %hi(D_8007B900)
/* 20BF8 8001FFF8 AECD0000 */  sw         $t5, 0x0($s6)
/* 20BFC 8001FFFC 8DCEB900 */  lw         $t6, %lo(D_8007B900)($t6)
/* 20C00 80020000 3C018008 */  lui        $at, %hi(D_8007B900)
/* 20C04 80020004 26D60008 */  addiu      $s6, $s6, 0x8
/* 20C08 80020008 01D17821 */  addu       $t7, $t6, $s1
/* 20C0C 8002000C AC2FB900 */  sw         $t7, %lo(D_8007B900)($at)
/* 20C10 80020010 8FC20000 */  lw         $v0, 0x0($fp)
/* 20C14 80020014 3C018009 */  lui        $at, %hi(D_8008BF70)
/* 20C18 80020018 0002C080 */  sll        $t8, $v0, 2
/* 20C1C 8002001C 00380821 */  addu       $at, $at, $t8
/* 20C20 80020020 AC34BF70 */  sw         $s4, %lo(D_8008BF70)($at)
/* 20C24 80020024 24590001 */  addiu      $t9, $v0, 0x1
/* 20C28 80020028 12200019 */  beqz       $s1, .L80020090
/* 20C2C 8002002C AFD90000 */   sw        $t9, 0x0($fp)
.L80020030:
/* 20C30 80020030 C6640000 */  lwc1       $f4, 0x0($s3)
/* 20C34 80020034 4600A306 */  mov.s      $f12, $f20
/* 20C38 80020038 02002825 */  or         $a1, $s0, $zero
/* 20C3C 8002003C E6040000 */  swc1       $f4, 0x0($s0)
/* 20C40 80020040 C6660004 */  lwc1       $f6, 0x4($s3)
/* 20C44 80020044 2654002C */  addiu      $s4, $s2, 0x2C
/* 20C48 80020048 0C009C6D */  jal        func_800271B4
/* 20C4C 8002004C E6060004 */   swc1      $f6, 0x4($s0)
/* 20C50 80020050 C6080000 */  lwc1       $f8, 0x0($s0)
/* 20C54 80020054 C6100004 */  lwc1       $f16, 0x4($s0)
/* 20C58 80020058 8EA40000 */  lw         $a0, 0x0($s5)
/* 20C5C 8002005C 4608B280 */  add.s      $f10, $f22, $f8
/* 20C60 80020060 4407A000 */  mfc1       $a3, $f20
/* 20C64 80020064 AFB20014 */  sw         $s2, 0x14($sp)
/* 20C68 80020068 4610C480 */  add.s      $f18, $f24, $f16
/* 20C6C 8002006C 44055000 */  mfc1       $a1, $f10
/* 20C70 80020070 AFB40010 */  sw         $s4, 0x10($sp)
/* 20C74 80020074 44069000 */  mfc1       $a2, $f18
/* 20C78 80020078 0C0029B4 */  jal        func_8000A6D0
/* 20C7C 8002007C 00000000 */   nop
/* 20C80 80020080 2631FFFF */  addiu      $s1, $s1, -0x1
/* 20C84 80020084 26520130 */  addiu      $s2, $s2, 0x130
/* 20C88 80020088 1620FFE9 */  bnez       $s1, .L80020030
/* 20C8C 8002008C 2673000C */   addiu     $s3, $s3, 0xC
.L80020090:
/* 20C90 80020090 26F7FFFF */  addiu      $s7, $s7, -0x1
/* 20C94 80020094 16E0FFCD */  bnez       $s7, .L8001FFCC
/* 20C98 80020098 26B5000C */   addiu     $s5, $s5, 0xC
.L8002009C:
/* 20C9C 8002009C 0C002A57 */  jal        func_8000A95C
/* 20CA0 800200A0 00000000 */   nop
/* 20CA4 800200A4 3C088008 */  lui        $t0, %hi(D_8007B900)
/* 20CA8 800200A8 8D08B900 */  lw         $t0, %lo(D_8007B900)($t0)
/* 20CAC 800200AC 3C018009 */  lui        $at, %hi(D_8008BE5A)
/* 20CB0 800200B0 D7B40020 */  ldc1       $f20, 0x20($sp)
/* 20CB4 800200B4 A428BE5A */  sh         $t0, %lo(D_8008BE5A)($at)
/* 20CB8 800200B8 8FBF005C */  lw         $ra, 0x5C($sp)
/* 20CBC 800200BC D7B60028 */  ldc1       $f22, 0x28($sp)
/* 20CC0 800200C0 D7B80030 */  ldc1       $f24, 0x30($sp)
/* 20CC4 800200C4 8FB00038 */  lw         $s0, 0x38($sp)
/* 20CC8 800200C8 8FB1003C */  lw         $s1, 0x3C($sp)
/* 20CCC 800200CC 8FB20040 */  lw         $s2, 0x40($sp)
/* 20CD0 800200D0 8FB30044 */  lw         $s3, 0x44($sp)
/* 20CD4 800200D4 8FB40048 */  lw         $s4, 0x48($sp)
/* 20CD8 800200D8 8FB5004C */  lw         $s5, 0x4C($sp)
/* 20CDC 800200DC 8FB60050 */  lw         $s6, 0x50($sp)
/* 20CE0 800200E0 8FB70054 */  lw         $s7, 0x54($sp)
/* 20CE4 800200E4 8FBE0058 */  lw         $fp, 0x58($sp)
/* 20CE8 800200E8 03E00008 */  jr         $ra
/* 20CEC 800200EC 27BD00C8 */   addiu     $sp, $sp, 0xC8

glabel func_800200F0
/* 20CF0 800200F0 03E00008 */  jr         $ra
/* 20CF4 800200F4 00000000 */   nop

glabel func_800200F8
/* 20CF8 800200F8 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 20CFC 800200FC AFBF0014 */  sw         $ra, 0x14($sp)
/* 20D00 80020100 3C0E8008 */  lui        $t6, %hi(D_8007AA10)
/* 20D04 80020104 8DCEAA10 */  lw         $t6, %lo(D_8007AA10)($t6)
/* 20D08 80020108 24040004 */  addiu      $a0, $zero, 0x4
/* 20D0C 8002010C 3C188009 */  lui        $t8, %hi(D_8008BE52)
/* 20D10 80020110 31CF2000 */  andi       $t7, $t6, 0x2000
/* 20D14 80020114 11E00003 */  beqz       $t7, .L80020124
/* 20D18 80020118 00000000 */   nop
/* 20D1C 8002011C 10000001 */  b          .L80020124
/* 20D20 80020120 24040003 */   addiu     $a0, $zero, 0x3
.L80020124:
/* 20D24 80020124 9718BE52 */  lhu        $t8, %lo(D_8008BE52)($t8)
/* 20D28 80020128 33190100 */  andi       $t9, $t8, 0x100
/* 20D2C 8002012C 17200005 */  bnez       $t9, .L80020144
/* 20D30 80020130 00000000 */   nop
/* 20D34 80020134 0C009BA4 */  jal        func_80026E90
/* 20D38 80020138 00000000 */   nop
/* 20D3C 8002013C 1440000E */  bnez       $v0, .L80020178
/* 20D40 80020140 240400FF */   addiu     $a0, $zero, 0xFF
.L80020144:
/* 20D44 80020144 3C048009 */  lui        $a0, %hi(D_8008BE5A)
/* 20D48 80020148 0C009BA4 */  jal        func_80026E90
/* 20D4C 8002014C 9484BE5A */   lhu       $a0, %lo(D_8008BE5A)($a0)
/* 20D50 80020150 00024080 */  sll        $t0, $v0, 2
/* 20D54 80020154 01024021 */  addu       $t0, $t0, $v0
/* 20D58 80020158 00084080 */  sll        $t0, $t0, 2
/* 20D5C 8002015C 01024023 */  subu       $t0, $t0, $v0
/* 20D60 80020160 00084100 */  sll        $t0, $t0, 4
/* 20D64 80020164 3C098008 */  lui        $t1, %hi(D_8007B930)
/* 20D68 80020168 01284821 */  addu       $t1, $t1, $t0
/* 20D6C 8002016C 8D29B930 */  lw         $t1, %lo(D_8007B930)($t1)
/* 20D70 80020170 10000001 */  b          .L80020178
/* 20D74 80020174 91240034 */   lbu       $a0, 0x34($t1)
.L80020178:
/* 20D78 80020178 00801025 */  or         $v0, $a0, $zero
/* 20D7C 8002017C 8FBF0014 */  lw         $ra, 0x14($sp)
/* 20D80 80020180 27BD0018 */  addiu      $sp, $sp, 0x18
/* 20D84 80020184 03E00008 */  jr         $ra
/* 20D88 80020188 00000000 */   nop

glabel func_8002018C
/* 20D8C 8002018C 03E00008 */  jr         $ra
/* 20D90 80020190 00000000 */   nop
/* 20D94 80020194 00000000 */  nop
/* 20D98 80020198 00000000 */  nop
/* 20D9C 8002019C 00000000 */  nop
