.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.10.1 */

glabel func_800361B0
/* 36DB0 800361B0 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 36DB4 800361B4 3C0400DB */  lui        $a0, %hi(D_DAB5F0)
/* 36DB8 800361B8 2484B5F0 */  addiu      $a0, $a0, %lo(D_DAB5F0)
/* 36DBC 800361BC AFBF0014 */  sw         $ra, 0x14($sp)
/* 36DC0 800361C0 3C0E00DC */  lui        $t6, %hi(D_DC62B0)
/* 36DC4 800361C4 25CE62B0 */  addiu      $t6, $t6, %lo(D_DC62B0)
/* 36DC8 800361C8 3C058021 */  lui        $a1, %hi(func_8020C0D0)
/* 36DCC 800361CC 24A5C0D0 */  addiu      $a1, $a1, %lo(func_8020C0D0)
/* 36DD0 800361D0 0C00A048 */  jal        func_80028120
/* 36DD4 800361D4 01C43023 */   subu      $a2, $t6, $a0
/* 36DD8 800361D8 8FBF0014 */  lw         $ra, 0x14($sp)
/* 36DDC 800361DC 27BD0018 */  addiu      $sp, $sp, 0x18
/* 36DE0 800361E0 03E00008 */  jr         $ra
/* 36DE4 800361E4 00000000 */   nop

glabel func_800361E8
/* 36DE8 800361E8 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 36DEC 800361EC 3C0400DC */  lui        $a0, %hi(D_DC62B0)
/* 36DF0 800361F0 248462B0 */  addiu      $a0, $a0, %lo(D_DC62B0)
/* 36DF4 800361F4 AFBF0014 */  sw         $ra, 0x14($sp)
/* 36DF8 800361F8 3C0E00E2 */  lui        $t6, %hi(D_E22690)
/* 36DFC 800361FC 25CE2690 */  addiu      $t6, $t6, %lo(D_E22690)
/* 36E00 80036200 3C058021 */  lui        $a1, %hi(func_8020C0D0)
/* 36E04 80036204 24A5C0D0 */  addiu      $a1, $a1, %lo(func_8020C0D0)
/* 36E08 80036208 0C00A048 */  jal        func_80028120
/* 36E0C 8003620C 01C43023 */   subu      $a2, $t6, $a0
/* 36E10 80036210 8FBF0014 */  lw         $ra, 0x14($sp)
/* 36E14 80036214 27BD0018 */  addiu      $sp, $sp, 0x18
/* 36E18 80036218 03E00008 */  jr         $ra
/* 36E1C 8003621C 00000000 */   nop

glabel func_80036220
/* 36E20 80036220 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 36E24 80036224 3C0400E2 */  lui        $a0, %hi(D_E22690)
/* 36E28 80036228 24842690 */  addiu      $a0, $a0, %lo(D_E22690)
/* 36E2C 8003622C AFBF0014 */  sw         $ra, 0x14($sp)
/* 36E30 80036230 3C0E00E4 */  lui        $t6, %hi(D_E420D0)
/* 36E34 80036234 25CE20D0 */  addiu      $t6, $t6, %lo(D_E420D0)
/* 36E38 80036238 3C058021 */  lui        $a1, %hi(func_8020C0D0)
/* 36E3C 8003623C 24A5C0D0 */  addiu      $a1, $a1, %lo(func_8020C0D0)
/* 36E40 80036240 0C00A048 */  jal        func_80028120
/* 36E44 80036244 01C43023 */   subu      $a2, $t6, $a0
/* 36E48 80036248 8FBF0014 */  lw         $ra, 0x14($sp)
/* 36E4C 8003624C 27BD0018 */  addiu      $sp, $sp, 0x18
/* 36E50 80036250 03E00008 */  jr         $ra
/* 36E54 80036254 00000000 */   nop
/* 36E58 80036258 00000000 */  nop
/* 36E5C 8003625C 00000000 */  nop
