.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.10.1 */

glabel func_800380B0
/* 38CB0 800380B0 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 38CB4 800380B4 AFA40018 */  sw         $a0, 0x18($sp)
/* 38CB8 800380B8 8FAE0018 */  lw         $t6, 0x18($sp)
/* 38CBC 800380BC 3C018000 */  lui        $at, (0x80000000 >> 16)
/* 38CC0 800380C0 AFBF0014 */  sw         $ra, 0x14($sp)
/* 38CC4 800380C4 01C1082B */  sltu       $at, $t6, $at
/* 38CC8 800380C8 14200007 */  bnez       $at, .L800380E8
/* 38CCC 800380CC 3C01A000 */   lui       $at, (0xA0000000 >> 16)
/* 38CD0 800380D0 01C1082B */  sltu       $at, $t6, $at
/* 38CD4 800380D4 10200004 */  beqz       $at, .L800380E8
/* 38CD8 800380D8 3C011FFF */   lui       $at, (0x1FFFFFFF >> 16)
/* 38CDC 800380DC 3421FFFF */  ori        $at, $at, (0x1FFFFFFF & 0xFFFF)
/* 38CE0 800380E0 1000000E */  b          .L8003811C
/* 38CE4 800380E4 01C11024 */   and       $v0, $t6, $at
.L800380E8:
/* 38CE8 800380E8 8FAF0018 */  lw         $t7, 0x18($sp)
/* 38CEC 800380EC 3C01A000 */  lui        $at, (0xA0000000 >> 16)
/* 38CF0 800380F0 01E1082B */  sltu       $at, $t7, $at
/* 38CF4 800380F4 14200007 */  bnez       $at, .L80038114
/* 38CF8 800380F8 3C01C000 */   lui       $at, (0xC0000000 >> 16)
/* 38CFC 800380FC 01E1082B */  sltu       $at, $t7, $at
/* 38D00 80038100 10200004 */  beqz       $at, .L80038114
/* 38D04 80038104 3C011FFF */   lui       $at, (0x1FFFFFFF >> 16)
/* 38D08 80038108 3421FFFF */  ori        $at, $at, (0x1FFFFFFF & 0xFFFF)
/* 38D0C 8003810C 10000003 */  b          .L8003811C
/* 38D10 80038110 01E11024 */   and       $v0, $t7, $at
.L80038114:
/* 38D14 80038114 0C010460 */  jal        func_80041180
/* 38D18 80038118 8FA40018 */   lw        $a0, 0x18($sp)
.L8003811C:
/* 38D1C 8003811C 8FBF0014 */  lw         $ra, 0x14($sp)
/* 38D20 80038120 27BD0018 */  addiu      $sp, $sp, 0x18
/* 38D24 80038124 03E00008 */  jr         $ra
/* 38D28 80038128 00000000 */   nop
/* 38D2C 8003812C 00000000 */  nop
