.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.10.1 */

# Handwritten function
glabel func_80039950
/* 3A550 80039950 18A00011 */  blez       $a1, .L80039998
/* 3A554 80039954 00000000 */   nop
/* 3A558 80039958 240B4000 */  addiu      $t3, $zero, 0x4000
/* 3A55C 8003995C 00AB082B */  sltu       $at, $a1, $t3
/* 3A560 80039960 1020000F */  beqz       $at, .L800399A0
/* 3A564 80039964 00000000 */   nop
/* 3A568 80039968 00804025 */  or         $t0, $a0, $zero
/* 3A56C 8003996C 00854821 */  addu       $t1, $a0, $a1
/* 3A570 80039970 0109082B */  sltu       $at, $t0, $t1
/* 3A574 80039974 10200008 */  beqz       $at, .L80039998
/* 3A578 80039978 00000000 */   nop
/* 3A57C 8003997C 310A001F */  andi       $t2, $t0, 0x1F
/* 3A580 80039980 2529FFE0 */  addiu      $t1, $t1, -0x20
/* 3A584 80039984 010A4023 */  subu       $t0, $t0, $t2
.L80039988:
/* 3A588 80039988 BD100000 */  cache      0x10, 0x0($t0)
/* 3A58C 8003998C 0109082B */  sltu       $at, $t0, $t1
/* 3A590 80039990 1420FFFD */  bnez       $at, .L80039988
/* 3A594 80039994 25080020 */   addiu     $t0, $t0, 0x20
.L80039998:
/* 3A598 80039998 03E00008 */  jr         $ra
/* 3A59C 8003999C 00000000 */   nop
.L800399A0:
/* 3A5A0 800399A0 3C088000 */  lui        $t0, 0x8000
/* 3A5A4 800399A4 010B4821 */  addu       $t1, $t0, $t3
/* 3A5A8 800399A8 2529FFE0 */  addiu      $t1, $t1, -0x20
.L800399AC:
/* 3A5AC 800399AC BD000000 */  cache      0x00, 0x0($t0)
/* 3A5B0 800399B0 0109082B */  sltu       $at, $t0, $t1
/* 3A5B4 800399B4 1420FFFD */  bnez       $at, .L800399AC
/* 3A5B8 800399B8 25080020 */   addiu     $t0, $t0, (0x80000020 & 0xFFFF)
/* 3A5BC 800399BC 03E00008 */  jr         $ra
/* 3A5C0 800399C0 00000000 */   nop
/* 3A5C4 800399C4 00000000 */  nop
/* 3A5C8 800399C8 00000000 */  nop
/* 3A5CC 800399CC 00000000 */  nop
