.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.16.0 */

glabel func_80039A80
/* 3A680 80039A80 27BDFFD8 */  addiu      $sp, $sp, -0x28
/* 3A684 80039A84 3C0E8007 */  lui        $t6, %hi(D_8006CD20)
/* 3A688 80039A88 8DCECD20 */  lw         $t6, %lo(D_8006CD20)($t6)
/* 3A68C 80039A8C AFBF001C */  sw         $ra, 0x1C($sp)
/* 3A690 80039A90 AFA40028 */  sw         $a0, 0x28($sp)
/* 3A694 80039A94 AFA5002C */  sw         $a1, 0x2C($sp)
/* 3A698 80039A98 AFA60030 */  sw         $a2, 0x30($sp)
/* 3A69C 80039A9C AFA70034 */  sw         $a3, 0x34($sp)
/* 3A6A0 80039AA0 AFB10018 */  sw         $s1, 0x18($sp)
/* 3A6A4 80039AA4 15C00003 */  bnez       $t6, .L80039AB4
/* 3A6A8 80039AA8 AFB00014 */   sw        $s0, 0x14($sp)
/* 3A6AC 80039AAC 10000032 */  b          .L80039B78
/* 3A6B0 80039AB0 2402FFFF */   addiu     $v0, $zero, -0x1
.L80039AB4:
/* 3A6B4 80039AB4 8FAF0030 */  lw         $t7, 0x30($sp)
/* 3A6B8 80039AB8 15E00005 */  bnez       $t7, .L80039AD0
/* 3A6BC 80039ABC 00000000 */   nop
/* 3A6C0 80039AC0 8FB90028 */  lw         $t9, 0x28($sp)
/* 3A6C4 80039AC4 2418000B */  addiu      $t8, $zero, 0xB
/* 3A6C8 80039AC8 10000004 */  b          .L80039ADC
/* 3A6CC 80039ACC A7380000 */   sh        $t8, 0x0($t9)
.L80039AD0:
/* 3A6D0 80039AD0 8FA90028 */  lw         $t1, 0x28($sp)
/* 3A6D4 80039AD4 2408000C */  addiu      $t0, $zero, 0xC
/* 3A6D8 80039AD8 A5280000 */  sh         $t0, 0x0($t1)
.L80039ADC:
/* 3A6DC 80039ADC 8FAA002C */  lw         $t2, 0x2C($sp)
/* 3A6E0 80039AE0 8FAB0028 */  lw         $t3, 0x28($sp)
/* 3A6E4 80039AE4 24010001 */  addiu      $at, $zero, 0x1
/* 3A6E8 80039AE8 A16A0002 */  sb         $t2, 0x2($t3)
/* 3A6EC 80039AEC 8FAD0028 */  lw         $t5, 0x28($sp)
/* 3A6F0 80039AF0 8FAC0040 */  lw         $t4, 0x40($sp)
/* 3A6F4 80039AF4 ADAC0004 */  sw         $t4, 0x4($t5)
/* 3A6F8 80039AF8 8FAF0028 */  lw         $t7, 0x28($sp)
/* 3A6FC 80039AFC 8FAE0038 */  lw         $t6, 0x38($sp)
/* 3A700 80039B00 ADEE0008 */  sw         $t6, 0x8($t7)
/* 3A704 80039B04 8FB90028 */  lw         $t9, 0x28($sp)
/* 3A708 80039B08 8FB80034 */  lw         $t8, 0x34($sp)
/* 3A70C 80039B0C AF38000C */  sw         $t8, 0xC($t9)
/* 3A710 80039B10 8FA90028 */  lw         $t1, 0x28($sp)
/* 3A714 80039B14 8FA8003C */  lw         $t0, 0x3C($sp)
/* 3A718 80039B18 AD280010 */  sw         $t0, 0x10($t1)
/* 3A71C 80039B1C 8FAA0028 */  lw         $t2, 0x28($sp)
/* 3A720 80039B20 AD400014 */  sw         $zero, 0x14($t2)
/* 3A724 80039B24 8FAB002C */  lw         $t3, 0x2C($sp)
/* 3A728 80039B28 1561000A */  bne        $t3, $at, .L80039B54
/* 3A72C 80039B2C 00000000 */   nop
/* 3A730 80039B30 0C01083C */  jal        func_800420F0
/* 3A734 80039B34 00000000 */   nop
/* 3A738 80039B38 00408825 */  or         $s1, $v0, $zero
/* 3A73C 80039B3C 02202025 */  or         $a0, $s1, $zero
/* 3A740 80039B40 8FA50028 */  lw         $a1, 0x28($sp)
/* 3A744 80039B44 0C0107E8 */  jal        func_80041FA0
/* 3A748 80039B48 00003025 */   or        $a2, $zero, $zero
/* 3A74C 80039B4C 10000009 */  b          .L80039B74
/* 3A750 80039B50 00408025 */   or        $s0, $v0, $zero
.L80039B54:
/* 3A754 80039B54 0C01083C */  jal        func_800420F0
/* 3A758 80039B58 00000000 */   nop
/* 3A75C 80039B5C 00408825 */  or         $s1, $v0, $zero
/* 3A760 80039B60 02202025 */  or         $a0, $s1, $zero
/* 3A764 80039B64 8FA50028 */  lw         $a1, 0x28($sp)
/* 3A768 80039B68 0C00DD5C */  jal        func_80037570
/* 3A76C 80039B6C 00003025 */   or        $a2, $zero, $zero
/* 3A770 80039B70 00408025 */  or         $s0, $v0, $zero
.L80039B74:
/* 3A774 80039B74 02001025 */  or         $v0, $s0, $zero
.L80039B78:
/* 3A778 80039B78 8FBF001C */  lw         $ra, 0x1C($sp)
/* 3A77C 80039B7C 8FB00014 */  lw         $s0, 0x14($sp)
/* 3A780 80039B80 8FB10018 */  lw         $s1, 0x18($sp)
/* 3A784 80039B84 03E00008 */  jr         $ra
/* 3A788 80039B88 27BD0028 */   addiu     $sp, $sp, 0x28
/* 3A78C 80039B8C 00000000 */  nop
