.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.17.3 */

glabel func_80039E80
/* 3AA80 80039E80 03E00008 */  jr         $ra
/* 3AA84 80039E84 00000000 */   nop

glabel func_80039E88
/* 3AA88 80039E88 8C8E0044 */  lw         $t6, 0x44($a0)
/* 3AA8C 80039E8C 44852000 */  mtc1       $a1, $f4
/* 3AA90 80039E90 3C018007 */  lui        $at, %hi(D_8006FA90)
/* 3AA94 80039E94 448E4000 */  mtc1       $t6, $f8
/* 3AA98 80039E98 468021A0 */  cvt.s.w    $f6, $f4
/* 3AA9C 80039E9C D424FA90 */  ldc1       $f4, %lo(D_8006FA90)($at)
/* 3AAA0 80039EA0 3C013FE0 */  lui        $at, (0x3FE00000 >> 16)
/* 3AAA4 80039EA4 44813800 */  mtc1       $at, $f7
/* 3AAA8 80039EA8 2401FFF0 */  addiu      $at, $zero, -0x10
/* 3AAAC 80039EAC 468042A0 */  cvt.s.w    $f10, $f8
/* 3AAB0 80039EB0 460A3402 */  mul.s      $f16, $f6, $f10
/* 3AAB4 80039EB4 44803000 */  mtc1       $zero, $f6
/* 3AAB8 80039EB8 460084A1 */  cvt.d.s    $f18, $f16
/* 3AABC 80039EBC 46249203 */  div.d      $f8, $f18, $f4
/* 3AAC0 80039EC0 46264280 */  add.d      $f10, $f8, $f6
/* 3AAC4 80039EC4 46205020 */  cvt.s.d    $f0, $f10
/* 3AAC8 80039EC8 4600040D */  trunc.w.s  $f16, $f0
/* 3AACC 80039ECC 44028000 */  mfc1       $v0, $f16
/* 3AAD0 80039ED0 00000000 */  nop
/* 3AAD4 80039ED4 0041C024 */  and        $t8, $v0, $at
/* 3AAD8 80039ED8 03E00008 */  jr         $ra
/* 3AADC 80039EDC 03001025 */   or        $v0, $t8, $zero

glabel func_80039EE0
/* 3AAE0 80039EE0 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 3AAE4 80039EE4 AFBF0014 */  sw         $ra, 0x14($sp)
/* 3AAE8 80039EE8 AFA40018 */  sw         $a0, 0x18($sp)
/* 3AAEC 80039EEC AFA5001C */  sw         $a1, 0x1C($sp)
/* 3AAF0 80039EF0 0C00E760 */  jal        func_80039D80
/* 3AAF4 80039EF4 00A02025 */   or        $a0, $a1, $zero
/* 3AAF8 80039EF8 8FA50018 */  lw         $a1, 0x18($sp)
/* 3AAFC 80039EFC 8FA4001C */  lw         $a0, 0x1C($sp)
/* 3AB00 80039F00 0C00E76C */  jal        func_80039DB0
/* 3AB04 80039F04 24A50014 */   addiu     $a1, $a1, 0x14
/* 3AB08 80039F08 8FBF0014 */  lw         $ra, 0x14($sp)
/* 3AB0C 80039F0C 27BD0018 */  addiu      $sp, $sp, 0x18
/* 3AB10 80039F10 03E00008 */  jr         $ra
/* 3AB14 80039F14 00000000 */   nop

glabel func_80039F18
/* 3AB18 80039F18 27BDFFD8 */  addiu      $sp, $sp, -0x28
/* 3AB1C 80039F1C AFBF0024 */  sw         $ra, 0x24($sp)
/* 3AB20 80039F20 AFB20020 */  sw         $s2, 0x20($sp)
/* 3AB24 80039F24 AFB1001C */  sw         $s1, 0x1C($sp)
/* 3AB28 80039F28 AFB00018 */  sw         $s0, 0x18($sp)
/* 3AB2C 80039F2C 8C900014 */  lw         $s0, 0x14($a0)
/* 3AB30 80039F30 00808825 */  or         $s1, $a0, $zero
/* 3AB34 80039F34 24920004 */  addiu      $s2, $a0, 0x4
/* 3AB38 80039F38 5200000A */  beql       $s0, $zero, .L80039F64
/* 3AB3C 80039F3C 8FBF0024 */   lw        $ra, 0x24($sp)
.L80039F40:
/* 3AB40 80039F40 0C00E760 */  jal        func_80039D80
/* 3AB44 80039F44 02002025 */   or        $a0, $s0, $zero
/* 3AB48 80039F48 02002025 */  or         $a0, $s0, $zero
/* 3AB4C 80039F4C 0C00E76C */  jal        func_80039DB0
/* 3AB50 80039F50 02402825 */   or        $a1, $s2, $zero
/* 3AB54 80039F54 8E300014 */  lw         $s0, 0x14($s1)
/* 3AB58 80039F58 1600FFF9 */  bnez       $s0, .L80039F40
/* 3AB5C 80039F5C 00000000 */   nop
/* 3AB60 80039F60 8FBF0024 */  lw         $ra, 0x24($sp)
.L80039F64:
/* 3AB64 80039F64 8FB00018 */  lw         $s0, 0x18($sp)
/* 3AB68 80039F68 8FB1001C */  lw         $s1, 0x1C($sp)
/* 3AB6C 80039F6C 8FB20020 */  lw         $s2, 0x20($sp)
/* 3AB70 80039F70 03E00008 */  jr         $ra
/* 3AB74 80039F74 27BD0028 */   addiu     $sp, $sp, 0x28

glabel func_80039F78
/* 3AB78 80039F78 3C028007 */  lui        $v0, %hi(D_8006E6F0)
/* 3AB7C 80039F7C 8C42E6F0 */  lw         $v0, %lo(D_8006E6F0)($v0)
/* 3AB80 80039F80 8C4E002C */  lw         $t6, 0x2C($v0)
/* 3AB84 80039F84 AC8E0000 */  sw         $t6, 0x0($a0)
/* 3AB88 80039F88 03E00008 */  jr         $ra
/* 3AB8C 80039F8C AC44002C */   sw        $a0, 0x2C($v0)

glabel func_80039F90
/* 3AB90 80039F90 3C028007 */  lui        $v0, %hi(D_8006E6F0)
/* 3AB94 80039F94 8C42E6F0 */  lw         $v0, %lo(D_8006E6F0)($v0)
/* 3AB98 80039F98 00001825 */  or         $v1, $zero, $zero
/* 3AB9C 80039F9C 8C44002C */  lw         $a0, 0x2C($v0)
/* 3ABA0 80039FA0 10800005 */  beqz       $a0, .L80039FB8
/* 3ABA4 80039FA4 00000000 */   nop
/* 3ABA8 80039FA8 8C8E0000 */  lw         $t6, 0x0($a0)
/* 3ABAC 80039FAC 00801825 */  or         $v1, $a0, $zero
/* 3ABB0 80039FB0 AC4E002C */  sw         $t6, 0x2C($v0)
/* 3ABB4 80039FB4 AC800000 */  sw         $zero, 0x0($a0)
.L80039FB8:
/* 3ABB8 80039FB8 03E00008 */  jr         $ra
/* 3ABBC 80039FBC 00601025 */   or        $v0, $v1, $zero

glabel func_80039FC0
/* 3ABC0 80039FC0 03E00008 */  jr         $ra
/* 3ABC4 80039FC4 00000000 */   nop

glabel func_80039FC8
/* 3ABC8 80039FC8 27BDFF48 */  addiu      $sp, $sp, -0xB8
/* 3ABCC 80039FCC AFB10030 */  sw         $s1, 0x30($sp)
/* 3ABD0 80039FD0 3C118007 */  lui        $s1, %hi(D_8006E6F0)
/* 3ABD4 80039FD4 8E31E6F0 */  lw         $s1, %lo(D_8006E6F0)($s1)
/* 3ABD8 80039FD8 AFBF004C */  sw         $ra, 0x4C($sp)
/* 3ABDC 80039FDC AFB70048 */  sw         $s7, 0x48($sp)
/* 3ABE0 80039FE0 AFB60044 */  sw         $s6, 0x44($sp)
/* 3ABE4 80039FE4 AFB50040 */  sw         $s5, 0x40($sp)
/* 3ABE8 80039FE8 AFB4003C */  sw         $s4, 0x3C($sp)
/* 3ABEC 80039FEC AFB30038 */  sw         $s3, 0x38($sp)
/* 3ABF0 80039FF0 AFB20034 */  sw         $s2, 0x34($sp)
/* 3ABF4 80039FF4 AFB0002C */  sw         $s0, 0x2C($sp)
/* 3ABF8 80039FF8 F7B60020 */  sdc1       $f22, 0x20($sp)
/* 3ABFC 80039FFC F7B40018 */  sdc1       $f20, 0x18($sp)
/* 3AC00 8003A000 AFA400B8 */  sw         $a0, 0xB8($sp)
/* 3AC04 8003A004 AFA500BC */  sw         $a1, 0xBC($sp)
/* 3AC08 8003A008 A7A000AA */  sh         $zero, 0xAA($sp)
/* 3AC0C 8003A00C 8E2F0000 */  lw         $t7, 0x0($s1)
/* 3AC10 8003A010 00E09825 */  or         $s3, $a3, $zero
/* 3AC14 8003A014 0080A025 */  or         $s4, $a0, $zero
/* 3AC18 8003A018 15E00004 */  bnez       $t7, .L8003A02C
/* 3AC1C 8003A01C 00C0A825 */   or        $s5, $a2, $zero
/* 3AC20 8003A020 ACA00000 */  sw         $zero, 0x0($a1)
/* 3AC24 8003A024 10000081 */  b          .L8003A22C
/* 3AC28 8003A028 00801025 */   or        $v0, $a0, $zero
.L8003A02C:
/* 3AC2C 8003A02C AFA000B4 */  sw         $zero, 0xB4($sp)
/* 3AC30 8003A030 8E220000 */  lw         $v0, 0x0($s1)
/* 3AC34 8003A034 3C037FFF */  lui        $v1, (0x7FFFFFFF >> 16)
/* 3AC38 8003A038 3463FFFF */  ori        $v1, $v1, (0x7FFFFFFF & 0xFFFF)
/* 3AC3C 8003A03C 1040000E */  beqz       $v0, .L8003A078
/* 3AC40 8003A040 2412FFF0 */   addiu     $s2, $zero, -0x10
/* 3AC44 8003A044 8E240020 */  lw         $a0, 0x20($s1)
/* 3AC48 8003A048 8C590010 */  lw         $t9, 0x10($v0)
.L8003A04C:
/* 3AC4C 8003A04C 03244023 */  subu       $t0, $t9, $a0
/* 3AC50 8003A050 0103082A */  slt        $at, $t0, $v1
/* 3AC54 8003A054 50200006 */  beql       $at, $zero, .L8003A070
/* 3AC58 8003A058 8C420000 */   lw        $v0, 0x0($v0)
/* 3AC5C 8003A05C AFA200B4 */  sw         $v0, 0xB4($sp)
/* 3AC60 8003A060 8C490010 */  lw         $t1, 0x10($v0)
/* 3AC64 8003A064 8E240020 */  lw         $a0, 0x20($s1)
/* 3AC68 8003A068 01241823 */  subu       $v1, $t1, $a0
/* 3AC6C 8003A06C 8C420000 */  lw         $v0, 0x0($v0)
.L8003A070:
/* 3AC70 8003A070 5440FFF6 */  bnel       $v0, $zero, .L8003A04C
/* 3AC74 8003A074 8C590010 */   lw        $t9, 0x10($v0)
.L8003A078:
/* 3AC78 8003A078 8FAA00B4 */  lw         $t2, 0xB4($sp)
/* 3AC7C 8003A07C 8E240020 */  lw         $a0, 0x20($s1)
/* 3AC80 8003A080 8D420010 */  lw         $v0, 0x10($t2)
/* 3AC84 8003A084 00445823 */  subu       $t3, $v0, $a0
/* 3AC88 8003A088 0173082A */  slt        $at, $t3, $s3
/* 3AC8C 8003A08C 10200038 */  beqz       $at, .L8003A170
/* 3AC90 8003A090 AE22001C */   sw        $v0, 0x1C($s1)
/* 3AC94 8003A094 3C013FE0 */  lui        $at, (0x3FE00000 >> 16)
/* 3AC98 8003A098 4481B800 */  mtc1       $at, $f23
/* 3AC9C 8003A09C 3C018007 */  lui        $at, %hi(D_8006FA98)
/* 3ACA0 8003A0A0 4480B000 */  mtc1       $zero, $f22
/* 3ACA4 8003A0A4 D434FA98 */  ldc1       $f20, %lo(D_8006FA98)($at)
.L8003A0A8:
/* 3ACA8 8003A0A8 8E2C001C */  lw         $t4, 0x1C($s1)
/* 3ACAC 8003A0AC 3C107FFF */  lui        $s0, (0x7FFFFFFF >> 16)
/* 3ACB0 8003A0B0 3610FFFF */  ori        $s0, $s0, (0x7FFFFFFF & 0xFFFF)
/* 3ACB4 8003A0B4 01926824 */  and        $t5, $t4, $s2
/* 3ACB8 8003A0B8 AE2D001C */  sw         $t5, 0x1C($s1)
/* 3ACBC 8003A0BC 8FA400B4 */  lw         $a0, 0xB4($sp)
/* 3ACC0 8003A0C0 8C990008 */  lw         $t9, 0x8($a0)
/* 3ACC4 8003A0C4 0320F809 */  jalr       $t9
/* 3ACC8 8003A0C8 00000000 */   nop
/* 3ACCC 8003A0CC 8E380044 */  lw         $t8, 0x44($s1)
/* 3ACD0 8003A0D0 44822000 */  mtc1       $v0, $f4
/* 3ACD4 8003A0D4 8FA800B4 */  lw         $t0, 0xB4($sp)
/* 3ACD8 8003A0D8 44984000 */  mtc1       $t8, $f8
/* 3ACDC 8003A0DC 468021A0 */  cvt.s.w    $f6, $f4
/* 3ACE0 8003A0E0 8D090010 */  lw         $t1, 0x10($t0)
/* 3ACE4 8003A0E4 468042A0 */  cvt.s.w    $f10, $f8
/* 3ACE8 8003A0E8 460A3402 */  mul.s      $f16, $f6, $f10
/* 3ACEC 8003A0EC 460084A1 */  cvt.d.s    $f18, $f16
/* 3ACF0 8003A0F0 46349103 */  div.d      $f4, $f18, $f20
/* 3ACF4 8003A0F4 46362200 */  add.d      $f8, $f4, $f22
/* 3ACF8 8003A0F8 46204020 */  cvt.s.d    $f0, $f8
/* 3ACFC 8003A0FC 4600018D */  trunc.w.s  $f6, $f0
/* 3AD00 8003A100 44023000 */  mfc1       $v0, $f6
/* 3AD04 8003A104 00000000 */  nop
/* 3AD08 8003A108 01225021 */  addu       $t2, $t1, $v0
/* 3AD0C 8003A10C AD0A0010 */  sw         $t2, 0x10($t0)
/* 3AD10 8003A110 AFA000B4 */  sw         $zero, 0xB4($sp)
/* 3AD14 8003A114 8E230000 */  lw         $v1, 0x0($s1)
/* 3AD18 8003A118 5060000F */  beql       $v1, $zero, .L8003A158
/* 3AD1C 8003A11C 8FAF00B4 */   lw        $t7, 0xB4($sp)
/* 3AD20 8003A120 8E240020 */  lw         $a0, 0x20($s1)
/* 3AD24 8003A124 8C6B0010 */  lw         $t3, 0x10($v1)
.L8003A128:
/* 3AD28 8003A128 01646023 */  subu       $t4, $t3, $a0
/* 3AD2C 8003A12C 0190082A */  slt        $at, $t4, $s0
/* 3AD30 8003A130 50200006 */  beql       $at, $zero, .L8003A14C
/* 3AD34 8003A134 8C630000 */   lw        $v1, 0x0($v1)
/* 3AD38 8003A138 AFA300B4 */  sw         $v1, 0xB4($sp)
/* 3AD3C 8003A13C 8C6D0010 */  lw         $t5, 0x10($v1)
/* 3AD40 8003A140 8E240020 */  lw         $a0, 0x20($s1)
/* 3AD44 8003A144 01A48023 */  subu       $s0, $t5, $a0
/* 3AD48 8003A148 8C630000 */  lw         $v1, 0x0($v1)
.L8003A14C:
/* 3AD4C 8003A14C 5460FFF6 */  bnel       $v1, $zero, .L8003A128
/* 3AD50 8003A150 8C6B0010 */   lw        $t3, 0x10($v1)
/* 3AD54 8003A154 8FAF00B4 */  lw         $t7, 0xB4($sp)
.L8003A158:
/* 3AD58 8003A158 8E240020 */  lw         $a0, 0x20($s1)
/* 3AD5C 8003A15C 8DE20010 */  lw         $v0, 0x10($t7)
/* 3AD60 8003A160 0044C823 */  subu       $t9, $v0, $a0
/* 3AD64 8003A164 0333082A */  slt        $at, $t9, $s3
/* 3AD68 8003A168 1420FFCF */  bnez       $at, .L8003A0A8
/* 3AD6C 8003A16C AE22001C */   sw        $v0, 0x1C($s1)
.L8003A170:
/* 3AD70 8003A170 8E38001C */  lw         $t8, 0x1C($s1)
/* 3AD74 8003A174 2412FFF0 */  addiu      $s2, $zero, -0x10
/* 3AD78 8003A178 27B700AA */  addiu      $s7, $sp, 0xAA
/* 3AD7C 8003A17C 03127024 */  and        $t6, $t8, $s2
/* 3AD80 8003A180 1A600022 */  blez       $s3, .L8003A20C
/* 3AD84 8003A184 AE2E001C */   sw        $t6, 0x1C($s1)
/* 3AD88 8003A188 3C160700 */  lui        $s6, (0x7000000 >> 16)
.L8003A18C:
/* 3AD8C 8003A18C 8E220048 */  lw         $v0, 0x48($s1)
/* 3AD90 8003A190 02608025 */  or         $s0, $s3, $zero
/* 3AD94 8003A194 0053082A */  slt        $at, $v0, $s3
/* 3AD98 8003A198 10200003 */  beqz       $at, .L8003A1A8
/* 3AD9C 8003A19C 00000000 */   nop
/* 3ADA0 8003A1A0 10000001 */  b          .L8003A1A8
/* 3ADA4 8003A1A4 00408025 */   or        $s0, $v0, $zero
.L8003A1A8:
/* 3ADA8 8003A1A8 AE960000 */  sw         $s6, 0x0($s4)
/* 3ADAC 8003A1AC AE800004 */  sw         $zero, 0x4($s4)
/* 3ADB0 8003A1B0 8E320038 */  lw         $s2, 0x38($s1)
/* 3ADB4 8003A1B4 24050006 */  addiu      $a1, $zero, 0x6
/* 3ADB8 8003A1B8 02A03025 */  or         $a2, $s5, $zero
/* 3ADBC 8003A1BC 8E590008 */  lw         $t9, 0x8($s2)
/* 3ADC0 8003A1C0 02402025 */  or         $a0, $s2, $zero
/* 3ADC4 8003A1C4 0320F809 */  jalr       $t9
/* 3ADC8 8003A1C8 00000000 */   nop
/* 3ADCC 8003A1CC 8E270020 */  lw         $a3, 0x20($s1)
/* 3ADD0 8003A1D0 26890008 */  addiu      $t1, $s4, 0x8
/* 3ADD4 8003A1D4 AFA90010 */  sw         $t1, 0x10($sp)
/* 3ADD8 8003A1D8 8E590004 */  lw         $t9, 0x4($s2)
/* 3ADDC 8003A1DC 02402025 */  or         $a0, $s2, $zero
/* 3ADE0 8003A1E0 02E02825 */  or         $a1, $s7, $zero
/* 3ADE4 8003A1E4 0320F809 */  jalr       $t9
/* 3ADE8 8003A1E8 02003025 */   or        $a2, $s0, $zero
/* 3ADEC 8003A1EC 8E2B0020 */  lw         $t3, 0x20($s1)
/* 3ADF0 8003A1F0 02709823 */  subu       $s3, $s3, $s0
/* 3ADF4 8003A1F4 00104080 */  sll        $t0, $s0, 2
/* 3ADF8 8003A1F8 01706021 */  addu       $t4, $t3, $s0
/* 3ADFC 8003A1FC 0040A025 */  or         $s4, $v0, $zero
/* 3AE00 8003A200 02A8A821 */  addu       $s5, $s5, $t0
/* 3AE04 8003A204 1E60FFE1 */  bgtz       $s3, .L8003A18C
/* 3AE08 8003A208 AE2C0020 */   sw        $t4, 0x20($s1)
.L8003A20C:
/* 3AE0C 8003A20C 8FAD00B8 */  lw         $t5, 0xB8($sp)
/* 3AE10 8003A210 8FAE00BC */  lw         $t6, 0xBC($sp)
/* 3AE14 8003A214 02202025 */  or         $a0, $s1, $zero
/* 3AE18 8003A218 028D7823 */  subu       $t7, $s4, $t5
/* 3AE1C 8003A21C 000FC0C3 */  sra        $t8, $t7, 3
/* 3AE20 8003A220 0C00E7C6 */  jal        func_80039F18
/* 3AE24 8003A224 ADD80000 */   sw        $t8, 0x0($t6)
/* 3AE28 8003A228 02801025 */  or         $v0, $s4, $zero
.L8003A22C:
/* 3AE2C 8003A22C 8FBF004C */  lw         $ra, 0x4C($sp)
/* 3AE30 8003A230 D7B40018 */  ldc1       $f20, 0x18($sp)
/* 3AE34 8003A234 D7B60020 */  ldc1       $f22, 0x20($sp)
/* 3AE38 8003A238 8FB0002C */  lw         $s0, 0x2C($sp)
/* 3AE3C 8003A23C 8FB10030 */  lw         $s1, 0x30($sp)
/* 3AE40 8003A240 8FB20034 */  lw         $s2, 0x34($sp)
/* 3AE44 8003A244 8FB30038 */  lw         $s3, 0x38($sp)
/* 3AE48 8003A248 8FB4003C */  lw         $s4, 0x3C($sp)
/* 3AE4C 8003A24C 8FB50040 */  lw         $s5, 0x40($sp)
/* 3AE50 8003A250 8FB60044 */  lw         $s6, 0x44($sp)
/* 3AE54 8003A254 8FB70048 */  lw         $s7, 0x48($sp)
/* 3AE58 8003A258 03E00008 */  jr         $ra
/* 3AE5C 8003A25C 27BD00B8 */   addiu     $sp, $sp, 0xB8

glabel func_8003A260
/* 3AE60 8003A260 27BDFF88 */  addiu      $sp, $sp, -0x78
/* 3AE64 8003A264 AFBF0044 */  sw         $ra, 0x44($sp)
/* 3AE68 8003A268 AFBE0040 */  sw         $fp, 0x40($sp)
/* 3AE6C 8003A26C AFB7003C */  sw         $s7, 0x3C($sp)
/* 3AE70 8003A270 AFB60038 */  sw         $s6, 0x38($sp)
/* 3AE74 8003A274 AFB50034 */  sw         $s5, 0x34($sp)
/* 3AE78 8003A278 AFB40030 */  sw         $s4, 0x30($sp)
/* 3AE7C 8003A27C AFB3002C */  sw         $s3, 0x2C($sp)
/* 3AE80 8003A280 AFB20028 */  sw         $s2, 0x28($sp)
/* 3AE84 8003A284 AFB10024 */  sw         $s1, 0x24($sp)
/* 3AE88 8003A288 AFB00020 */  sw         $s0, 0x20($sp)
/* 3AE8C 8003A28C 8CB70014 */  lw         $s7, 0x14($a1)
/* 3AE90 8003A290 AC800000 */  sw         $zero, 0x0($a0)
/* 3AE94 8003A294 8CAE0004 */  lw         $t6, 0x4($a1)
/* 3AE98 8003A298 AC800020 */  sw         $zero, 0x20($a0)
/* 3AE9C 8003A29C AC80001C */  sw         $zero, 0x1C($a0)
/* 3AEA0 8003A2A0 AC8E003C */  sw         $t6, 0x3C($a0)
/* 3AEA4 8003A2A4 8CAF0018 */  lw         $t7, 0x18($a1)
/* 3AEA8 8003A2A8 241800A0 */  addiu      $t8, $zero, 0xA0
/* 3AEAC 8003A2AC AC980048 */  sw         $t8, 0x48($a0)
/* 3AEB0 8003A2B0 AC8F0044 */  sw         $t7, 0x44($a0)
/* 3AEB4 8003A2B4 8CB90010 */  lw         $t9, 0x10($a1)
/* 3AEB8 8003A2B8 0080B025 */  or         $s6, $a0, $zero
/* 3AEBC 8003A2BC 00A0F025 */  or         $fp, $a1, $zero
/* 3AEC0 8003A2C0 2408001C */  addiu      $t0, $zero, 0x1C
/* 3AEC4 8003A2C4 AC990024 */  sw         $t9, 0x24($a0)
/* 3AEC8 8003A2C8 AFA80010 */  sw         $t0, 0x10($sp)
/* 3AECC 8003A2CC 00002025 */  or         $a0, $zero, $zero
/* 3AED0 8003A2D0 00002825 */  or         $a1, $zero, $zero
/* 3AED4 8003A2D4 24070001 */  addiu      $a3, $zero, 0x1
/* 3AED8 8003A2D8 0C00E6F4 */  jal        func_80039BD0
/* 3AEDC 8003A2DC 02E03025 */   or        $a2, $s7, $zero
/* 3AEE0 8003A2E0 AFA2005C */  sw         $v0, 0x5C($sp)
/* 3AEE4 8003A2E4 0C01091C */  jal        func_80042470
/* 3AEE8 8003A2E8 00402025 */   or        $a0, $v0, $zero
/* 3AEEC 8003A2EC 8FA9005C */  lw         $t1, 0x5C($sp)
/* 3AEF0 8003A2F0 240A004C */  addiu      $t2, $zero, 0x4C
/* 3AEF4 8003A2F4 00002025 */  or         $a0, $zero, $zero
/* 3AEF8 8003A2F8 AEC90038 */  sw         $t1, 0x38($s6)
/* 3AEFC 8003A2FC AFAA0010 */  sw         $t2, 0x10($sp)
/* 3AF00 8003A300 00002825 */  or         $a1, $zero, $zero
/* 3AF04 8003A304 02E03025 */  or         $a2, $s7, $zero
/* 3AF08 8003A308 0C00E6F4 */  jal        func_80039BD0
/* 3AF0C 8003A30C 24070001 */   addiu     $a3, $zero, 0x1
/* 3AF10 8003A310 240B0001 */  addiu      $t3, $zero, 0x1
/* 3AF14 8003A314 AEC20034 */  sw         $v0, 0x34($s6)
/* 3AF18 8003A318 AECB0040 */  sw         $t3, 0x40($s6)
/* 3AF1C 8003A31C 8FC70004 */  lw         $a3, 0x4($fp)
/* 3AF20 8003A320 240C0004 */  addiu      $t4, $zero, 0x4
/* 3AF24 8003A324 AFAC0010 */  sw         $t4, 0x10($sp)
/* 3AF28 8003A328 00002025 */  or         $a0, $zero, $zero
/* 3AF2C 8003A32C 00002825 */  or         $a1, $zero, $zero
/* 3AF30 8003A330 0C00E6F4 */  jal        func_80039BD0
/* 3AF34 8003A334 02E03025 */   or        $a2, $s7, $zero
/* 3AF38 8003A338 8EC40034 */  lw         $a0, 0x34($s6)
/* 3AF3C 8003A33C 00402825 */  or         $a1, $v0, $zero
/* 3AF40 8003A340 0C010942 */  jal        func_80042508
/* 3AF44 8003A344 8FC60004 */   lw        $a2, 0x4($fp)
/* 3AF48 8003A348 240D0020 */  addiu      $t5, $zero, 0x20
/* 3AF4C 8003A34C AFAD0010 */  sw         $t5, 0x10($sp)
/* 3AF50 8003A350 00002025 */  or         $a0, $zero, $zero
/* 3AF54 8003A354 00002825 */  or         $a1, $zero, $zero
/* 3AF58 8003A358 02E03025 */  or         $a2, $s7, $zero
/* 3AF5C 8003A35C 0C00E6F4 */  jal        func_80039BD0
/* 3AF60 8003A360 24070001 */   addiu     $a3, $zero, 0x1
/* 3AF64 8003A364 AEC20030 */  sw         $v0, 0x30($s6)
/* 3AF68 8003A368 8FC70004 */  lw         $a3, 0x4($fp)
/* 3AF6C 8003A36C 240E0004 */  addiu      $t6, $zero, 0x4
/* 3AF70 8003A370 AFAE0010 */  sw         $t6, 0x10($sp)
/* 3AF74 8003A374 00002025 */  or         $a0, $zero, $zero
/* 3AF78 8003A378 00002825 */  or         $a1, $zero, $zero
/* 3AF7C 8003A37C 0C00E6F4 */  jal        func_80039BD0
/* 3AF80 8003A380 02E03025 */   or        $a2, $s7, $zero
/* 3AF84 8003A384 8EC40030 */  lw         $a0, 0x30($s6)
/* 3AF88 8003A388 00402825 */  or         $a1, $v0, $zero
/* 3AF8C 8003A38C 0C01092D */  jal        func_800424B4
/* 3AF90 8003A390 8FC60004 */   lw        $a2, 0x4($fp)
/* 3AF94 8003A394 93CF001C */  lbu        $t7, 0x1C($fp)
/* 3AF98 8003A398 02C02025 */  or         $a0, $s6, $zero
/* 3AF9C 8003A39C 03C03025 */  or         $a2, $fp, $zero
/* 3AFA0 8003A3A0 11E00006 */  beqz       $t7, .L8003A3BC
/* 3AFA4 8003A3A4 24050002 */   addiu     $a1, $zero, 0x2
/* 3AFA8 8003A3A8 00002825 */  or         $a1, $zero, $zero
/* 3AFAC 8003A3AC 0C010B04 */  jal        func_80042C10
/* 3AFB0 8003A3B0 02E03825 */   or        $a3, $s7, $zero
/* 3AFB4 8003A3B4 10000005 */  b          .L8003A3CC
/* 3AFB8 8003A3B8 AEC00004 */   sw        $zero, 0x4($s6)
.L8003A3BC:
/* 3AFBC 8003A3BC 8EC40030 */  lw         $a0, 0x30($s6)
/* 3AFC0 8003A3C0 0C010B2C */  jal        func_80042CB0
/* 3AFC4 8003A3C4 8EC60034 */   lw        $a2, 0x34($s6)
/* 3AFC8 8003A3C8 AEC00004 */  sw         $zero, 0x4($s6)
.L8003A3CC:
/* 3AFCC 8003A3CC AEC00008 */  sw         $zero, 0x8($s6)
/* 3AFD0 8003A3D0 AEC00014 */  sw         $zero, 0x14($s6)
/* 3AFD4 8003A3D4 AEC00018 */  sw         $zero, 0x18($s6)
/* 3AFD8 8003A3D8 AEC0000C */  sw         $zero, 0xC($s6)
/* 3AFDC 8003A3DC AEC00010 */  sw         $zero, 0x10($s6)
/* 3AFE0 8003A3E0 8FC70004 */  lw         $a3, 0x4($fp)
/* 3AFE4 8003A3E4 241800DC */  addiu      $t8, $zero, 0xDC
/* 3AFE8 8003A3E8 AFB80010 */  sw         $t8, 0x10($sp)
/* 3AFEC 8003A3EC 00002025 */  or         $a0, $zero, $zero
/* 3AFF0 8003A3F0 00002825 */  or         $a1, $zero, $zero
/* 3AFF4 8003A3F4 0C00E6F4 */  jal        func_80039BD0
/* 3AFF8 8003A3F8 02E03025 */   or        $a2, $s7, $zero
/* 3AFFC 8003A3FC 8FD90004 */  lw         $t9, 0x4($fp)
/* 3B000 8003A400 0000A025 */  or         $s4, $zero, $zero
/* 3B004 8003A404 00408025 */  or         $s0, $v0, $zero
/* 3B008 8003A408 1B20002F */  blez       $t9, .L8003A4C8
/* 3B00C 8003A40C 26C50004 */   addiu     $a1, $s6, 0x4
/* 3B010 8003A410 2451008C */  addiu      $s1, $v0, 0x8C
/* 3B014 8003A414 24520058 */  addiu      $s2, $v0, 0x58
/* 3B018 8003A418 24530010 */  addiu      $s3, $v0, 0x10
/* 3B01C 8003A41C AFA50048 */  sw         $a1, 0x48($sp)
.L8003A420:
/* 3B020 8003A420 8FA50048 */  lw         $a1, 0x48($sp)
/* 3B024 8003A424 0200A825 */  or         $s5, $s0, $zero
/* 3B028 8003A428 0C00E76C */  jal        func_80039DB0
/* 3B02C 8003A42C 02002025 */   or        $a0, $s0, $zero
/* 3B030 8003A430 AE000008 */  sw         $zero, 0x8($s0)
/* 3B034 8003A434 8EC50024 */  lw         $a1, 0x24($s6)
/* 3B038 8003A438 02602025 */  or         $a0, $s3, $zero
/* 3B03C 8003A43C 0C010979 */  jal        func_800425E4
/* 3B040 8003A440 02E03025 */   or        $a2, $s7, $zero
/* 3B044 8003A444 02602025 */  or         $a0, $s3, $zero
/* 3B048 8003A448 24050001 */  addiu      $a1, $zero, 0x1
/* 3B04C 8003A44C 0C010B80 */  jal        func_80042E00
/* 3B050 8003A450 00003025 */   or        $a2, $zero, $zero
/* 3B054 8003A454 02402025 */  or         $a0, $s2, $zero
/* 3B058 8003A458 0C010957 */  jal        func_8004255C
/* 3B05C 8003A45C 02E02825 */   or        $a1, $s7, $zero
/* 3B060 8003A460 02402025 */  or         $a0, $s2, $zero
/* 3B064 8003A464 24050001 */  addiu      $a1, $zero, 0x1
/* 3B068 8003A468 0C010E54 */  jal        func_80043950
/* 3B06C 8003A46C 02603025 */   or        $a2, $s3, $zero
/* 3B070 8003A470 02202025 */  or         $a0, $s1, $zero
/* 3B074 8003A474 0C0109A3 */  jal        func_8004268C
/* 3B078 8003A478 02E02825 */   or        $a1, $s7, $zero
/* 3B07C 8003A47C 02202025 */  or         $a0, $s1, $zero
/* 3B080 8003A480 24050001 */  addiu      $a1, $zero, 0x1
/* 3B084 8003A484 0C010F59 */  jal        func_80043D64
/* 3B088 8003A488 02403025 */   or        $a2, $s2, $zero
/* 3B08C 8003A48C 8EC40034 */  lw         $a0, 0x34($s6)
/* 3B090 8003A490 24050002 */  addiu      $a1, $zero, 0x2
/* 3B094 8003A494 0C01122C */  jal        func_800448B0
/* 3B098 8003A498 02203025 */   or        $a2, $s1, $zero
/* 3B09C 8003A49C 26A8008C */  addiu      $t0, $s5, 0x8C
/* 3B0A0 8003A4A0 AEA8000C */  sw         $t0, 0xC($s5)
/* 3B0A4 8003A4A4 8FC90004 */  lw         $t1, 0x4($fp)
/* 3B0A8 8003A4A8 26940001 */  addiu      $s4, $s4, 0x1
/* 3B0AC 8003A4AC 261000DC */  addiu      $s0, $s0, 0xDC
/* 3B0B0 8003A4B0 0289082A */  slt        $at, $s4, $t1
/* 3B0B4 8003A4B4 263100DC */  addiu      $s1, $s1, 0xDC
/* 3B0B8 8003A4B8 265200DC */  addiu      $s2, $s2, 0xDC
/* 3B0BC 8003A4BC 1420FFD8 */  bnez       $at, .L8003A420
/* 3B0C0 8003A4C0 267300DC */   addiu     $s3, $s3, 0xDC
/* 3B0C4 8003A4C4 0000A025 */  or         $s4, $zero, $zero
.L8003A4C8:
/* 3B0C8 8003A4C8 8FA4005C */  lw         $a0, 0x5C($sp)
/* 3B0CC 8003A4CC 24050001 */  addiu      $a1, $zero, 0x1
/* 3B0D0 8003A4D0 0C011270 */  jal        func_800449C0
/* 3B0D4 8003A4D4 8EC60030 */   lw        $a2, 0x30($s6)
/* 3B0D8 8003A4D8 8FC70008 */  lw         $a3, 0x8($fp)
/* 3B0DC 8003A4DC 240A001C */  addiu      $t2, $zero, 0x1C
/* 3B0E0 8003A4E0 AFAA0010 */  sw         $t2, 0x10($sp)
/* 3B0E4 8003A4E4 00002025 */  or         $a0, $zero, $zero
/* 3B0E8 8003A4E8 00002825 */  or         $a1, $zero, $zero
/* 3B0EC 8003A4EC 0C00E6F4 */  jal        func_80039BD0
/* 3B0F0 8003A4F0 02E03025 */   or        $a2, $s7, $zero
/* 3B0F4 8003A4F4 AEC0002C */  sw         $zero, 0x2C($s6)
/* 3B0F8 8003A4F8 8FCB0008 */  lw         $t3, 0x8($fp)
/* 3B0FC 8003A4FC 00401825 */  or         $v1, $v0, $zero
/* 3B100 8003A500 5960000B */  blezl      $t3, .L8003A530
/* 3B104 8003A504 AED70028 */   sw        $s7, 0x28($s6)
/* 3B108 8003A508 8ECC002C */  lw         $t4, 0x2C($s6)
.L8003A50C:
/* 3B10C 8003A50C 26940001 */  addiu      $s4, $s4, 0x1
/* 3B110 8003A510 AC6C0000 */  sw         $t4, 0x0($v1)
/* 3B114 8003A514 AEC3002C */  sw         $v1, 0x2C($s6)
/* 3B118 8003A518 8FCD0008 */  lw         $t5, 0x8($fp)
/* 3B11C 8003A51C 2463001C */  addiu      $v1, $v1, 0x1C
/* 3B120 8003A520 028D082A */  slt        $at, $s4, $t5
/* 3B124 8003A524 5420FFF9 */  bnel       $at, $zero, .L8003A50C
/* 3B128 8003A528 8ECC002C */   lw        $t4, 0x2C($s6)
/* 3B12C 8003A52C AED70028 */  sw         $s7, 0x28($s6)
.L8003A530:
/* 3B130 8003A530 8FBF0044 */  lw         $ra, 0x44($sp)
/* 3B134 8003A534 8FBE0040 */  lw         $fp, 0x40($sp)
/* 3B138 8003A538 8FB7003C */  lw         $s7, 0x3C($sp)
/* 3B13C 8003A53C 8FB60038 */  lw         $s6, 0x38($sp)
/* 3B140 8003A540 8FB50034 */  lw         $s5, 0x34($sp)
/* 3B144 8003A544 8FB40030 */  lw         $s4, 0x30($sp)
/* 3B148 8003A548 8FB3002C */  lw         $s3, 0x2C($sp)
/* 3B14C 8003A54C 8FB20028 */  lw         $s2, 0x28($sp)
/* 3B150 8003A550 8FB10024 */  lw         $s1, 0x24($sp)
/* 3B154 8003A554 8FB00020 */  lw         $s0, 0x20($sp)
/* 3B158 8003A558 03E00008 */  jr         $ra
/* 3B15C 8003A55C 27BD0078 */   addiu     $sp, $sp, 0x78

glabel func_8003A560
/* 3B160 8003A560 3C0EA450 */  lui        $t6, %hi(D_A4500004)
/* 3B164 8003A564 03E00008 */  jr         $ra
/* 3B168 8003A568 8DC20004 */   lw        $v0, %lo(D_A4500004)($t6)
/* 3B16C 8003A56C 00000000 */  nop
