.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.16.0 */

glabel func_8003A630
/* 3B230 8003A630 27BDFFD0 */  addiu      $sp, $sp, -0x30
/* 3B234 8003A634 AFBF0014 */  sw         $ra, 0x14($sp)
/* 3B238 8003A638 8C8E002C */  lw         $t6, 0x2C($a0)
/* 3B23C 8003A63C 24010001 */  addiu      $at, $zero, 0x1
/* 3B240 8003A640 00803825 */  or         $a3, $a0, $zero
/* 3B244 8003A644 55C10013 */  bnel       $t6, $at, .L8003A694
/* 3B248 8003A648 8FBF0014 */   lw        $ra, 0x14($sp)
/* 3B24C 8003A64C 8C840018 */  lw         $a0, 0x18($a0)
/* 3B250 8003A650 27A5001C */  addiu      $a1, $sp, 0x1C
/* 3B254 8003A654 5080000F */  beql       $a0, $zero, .L8003A694
/* 3B258 8003A658 8FBF0014 */   lw        $ra, 0x14($sp)
/* 3B25C 8003A65C 0C00F10F */  jal        func_8003C43C
/* 3B260 8003A660 AFA70030 */   sw        $a3, 0x30($sp)
/* 3B264 8003A664 1040000A */  beqz       $v0, .L8003A690
/* 3B268 8003A668 8FA70030 */   lw        $a3, 0x30($sp)
/* 3B26C 8003A66C A7A00020 */  sh         $zero, 0x20($sp)
/* 3B270 8003A670 8CEF0024 */  lw         $t7, 0x24($a3)
/* 3B274 8003A674 8FB8001C */  lw         $t8, 0x1C($sp)
/* 3B278 8003A678 24E40048 */  addiu      $a0, $a3, 0x48
/* 3B27C 8003A67C 27A50020 */  addiu      $a1, $sp, 0x20
/* 3B280 8003A680 01F80019 */  multu      $t7, $t8
/* 3B284 8003A684 00003012 */  mflo       $a2
/* 3B288 8003A688 0C010893 */  jal        func_8004224C
/* 3B28C 8003A68C 00000000 */   nop
.L8003A690:
/* 3B290 8003A690 8FBF0014 */  lw         $ra, 0x14($sp)
.L8003A694:
/* 3B294 8003A694 27BD0030 */  addiu      $sp, $sp, 0x30
/* 3B298 8003A698 03E00008 */  jr         $ra
/* 3B29C 8003A69C 00000000 */   nop

glabel func_8003A6A0
/* 3B2A0 8003A6A0 8C820018 */  lw         $v0, 0x18($a0)
/* 3B2A4 8003A6A4 241801E8 */  addiu      $t8, $zero, 0x1E8
/* 3B2A8 8003A6A8 50400008 */  beql       $v0, $zero, .L8003A6CC
/* 3B2AC 8003A6AC AC980024 */   sw        $t8, 0x24($a0)
/* 3B2B0 8003A6B0 C4440008 */  lwc1       $f4, 0x8($v0)
/* 3B2B4 8003A6B4 46046182 */  mul.s      $f6, $f12, $f4
/* 3B2B8 8003A6B8 4600320D */  trunc.w.s  $f8, $f6
/* 3B2BC 8003A6BC 440F4000 */  mfc1       $t7, $f8
/* 3B2C0 8003A6C0 03E00008 */  jr         $ra
/* 3B2C4 8003A6C4 AC8F0024 */   sw        $t7, 0x24($a0)
/* 3B2C8 8003A6C8 AC980024 */  sw         $t8, 0x24($a0)
.L8003A6CC:
/* 3B2CC 8003A6CC 03E00008 */  jr         $ra
/* 3B2D0 8003A6D0 00000000 */   nop
/* 3B2D4 8003A6D4 03E00008 */  jr         $ra
/* 3B2D8 8003A6D8 00000000 */   nop

glabel func_8003A6DC
/* 3B2DC 8003A6DC 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 3B2E0 8003A6E0 AFBF0014 */  sw         $ra, 0x14($sp)
/* 3B2E4 8003A6E4 90AE0008 */  lbu        $t6, 0x8($a1)
/* 3B2E8 8003A6E8 240100FF */  addiu      $at, $zero, 0xFF
/* 3B2EC 8003A6EC 00008025 */  or         $s0, $zero, $zero
/* 3B2F0 8003A6F0 15C1006A */  bne        $t6, $at, .L8003A89C
/* 3B2F4 8003A6F4 00009825 */   or        $s3, $zero, $zero
/* 3B2F8 8003A6F8 90AF0009 */  lbu        $t7, 0x9($a1)
/* 3B2FC 8003A6FC 24010051 */  addiu      $at, $zero, 0x51
/* 3B300 8003A700 24A20004 */  addiu      $v0, $a1, 0x4
/* 3B304 8003A704 55E10066 */  bnel       $t7, $at, .L8003A8A0
/* 3B308 8003A708 8FBF0014 */   lw        $ra, 0x14($sp)
/* 3B30C 8003A70C 904E0008 */  lbu        $t6, 0x8($v0)
/* 3B310 8003A710 90580007 */  lbu        $t8, 0x7($v0)
/* 3B314 8003A714 8EFE0024 */  lw         $fp, 0x24($s7)
/* 3B318 8003A718 000E7A00 */  sll        $t7, $t6, 8
/* 3B31C 8003A71C 904E0009 */  lbu        $t6, 0x9($v0)
/* 3B320 8003A720 0018CC00 */  sll        $t9, $t8, 16
/* 3B324 8003A724 032FC025 */  or         $t8, $t9, $t7
/* 3B328 8003A728 030E1825 */  or         $v1, $t8, $t6
/* 3B32C 8003A72C 44832000 */  mtc1       $v1, $f4
/* 3B330 8003A730 02E02025 */  or         $a0, $s7, $zero
/* 3B334 8003A734 0C00E9A8 */  jal        func_8003A6A0
/* 3B338 8003A738 46802320 */   cvt.s.w   $f12, $f4
/* 3B33C 8003A73C 8EF10050 */  lw         $s1, 0x50($s7)
/* 3B340 8003A740 1220001D */  beqz       $s1, .L8003A7B8
/* 3B344 8003A744 00000000 */   nop
/* 3B348 8003A748 24140015 */  addiu      $s4, $zero, 0x15
.L8003A74C:
/* 3B34C 8003A74C 862F000C */  lh         $t7, 0xC($s1)
/* 3B350 8003A750 8E390008 */  lw         $t9, 0x8($s1)
/* 3B354 8003A754 8E320000 */  lw         $s2, 0x0($s1)
/* 3B358 8003A758 168F0015 */  bne        $s4, $t7, .L8003A7B0
/* 3B35C 8003A75C 02198021 */   addu      $s0, $s0, $t9
/* 3B360 8003A760 0C00E760 */  jal        func_80039D80
/* 3B364 8003A764 02202025 */   or        $a0, $s1, $zero
/* 3B368 8003A768 52600007 */  beql       $s3, $zero, .L8003A788
/* 3B36C 8003A76C AE200000 */   sw        $zero, 0x0($s1)
/* 3B370 8003A770 02202025 */  or         $a0, $s1, $zero
/* 3B374 8003A774 0C00E76C */  jal        func_80039DB0
/* 3B378 8003A778 02602825 */   or        $a1, $s3, $zero
/* 3B37C 8003A77C 10000004 */  b          .L8003A790
/* 3B380 8003A780 00000000 */   nop
/* 3B384 8003A784 AE200000 */  sw         $zero, 0x0($s1)
.L8003A788:
/* 3B388 8003A788 AE200004 */  sw         $zero, 0x4($s1)
/* 3B38C 8003A78C 02209825 */  or         $s3, $s1, $zero
.L8003A790:
/* 3B390 8003A790 12400006 */  beqz       $s2, .L8003A7AC
/* 3B394 8003A794 02001825 */   or        $v1, $s0, $zero
/* 3B398 8003A798 8E220008 */  lw         $v0, 0x8($s1)
/* 3B39C 8003A79C 8E580008 */  lw         $t8, 0x8($s2)
/* 3B3A0 8003A7A0 02028023 */  subu       $s0, $s0, $v0
/* 3B3A4 8003A7A4 03027021 */  addu       $t6, $t8, $v0
/* 3B3A8 8003A7A8 AE4E0008 */  sw         $t6, 0x8($s2)
.L8003A7AC:
/* 3B3AC 8003A7AC AE230008 */  sw         $v1, 0x8($s1)
.L8003A7B0:
/* 3B3B0 8003A7B0 1640FFE6 */  bnez       $s2, .L8003A74C
/* 3B3B4 8003A7B4 02408825 */   or        $s1, $s2, $zero
.L8003A7B8:
/* 3B3B8 8003A7B8 12600038 */  beqz       $s3, .L8003A89C
/* 3B3BC 8003A7BC 02608825 */   or        $s1, $s3, $zero
/* 3B3C0 8003A7C0 26F40048 */  addiu      $s4, $s7, 0x48
/* 3B3C4 8003A7C4 26950008 */  addiu      $s5, $s4, 0x8
/* 3B3C8 8003A7C8 2416FFF8 */  addiu      $s6, $zero, -0x8
.L8003A7CC:
/* 3B3CC 8003A7CC 8E390008 */  lw         $t9, 0x8($s1)
/* 3B3D0 8003A7D0 8EEF0024 */  lw         $t7, 0x24($s7)
/* 3B3D4 8003A7D4 8E320000 */  lw         $s2, 0x0($s1)
/* 3B3D8 8003A7D8 033E001A */  div        $zero, $t9, $fp
/* 3B3DC 8003A7DC 00001012 */  mflo       $v0
/* 3B3E0 8003A7E0 24040001 */  addiu      $a0, $zero, 0x1
/* 3B3E4 8003A7E4 17C00002 */  bnez       $fp, .L8003A7F0
/* 3B3E8 8003A7E8 00000000 */   nop
/* 3B3EC 8003A7EC 0007000D */  break      7
.L8003A7F0:
/* 3B3F0 8003A7F0 2401FFFF */  addiu      $at, $zero, -0x1
/* 3B3F4 8003A7F4 17C10004 */  bne        $fp, $at, .L8003A808
/* 3B3F8 8003A7F8 3C018000 */   lui       $at, (0x80000000 >> 16)
/* 3B3FC 8003A7FC 17210002 */  bne        $t9, $at, .L8003A808
/* 3B400 8003A800 00000000 */   nop
/* 3B404 8003A804 0006000D */  break      6
.L8003A808:
/* 3B408 8003A808 01E20019 */  multu      $t7, $v0
/* 3B40C 8003A80C 02A08025 */  or         $s0, $s5, $zero
/* 3B410 8003A810 0000C012 */  mflo       $t8
/* 3B414 8003A814 AE380008 */  sw         $t8, 0x8($s1)
/* 3B418 8003A818 0C00DD34 */  jal        func_800374D0
/* 3B41C 8003A81C 00000000 */   nop
/* 3B420 8003A820 1296001A */  beq        $s4, $s6, .L8003A88C
/* 3B424 8003A824 00409825 */   or        $s3, $v0, $zero
/* 3B428 8003A828 8E040000 */  lw         $a0, 0x0($s0)
.L8003A82C:
/* 3B42C 8003A82C 54800007 */  bnel       $a0, $zero, .L8003A84C
/* 3B430 8003A830 8E220008 */   lw        $v0, 0x8($s1)
/* 3B434 8003A834 02202025 */  or         $a0, $s1, $zero
/* 3B438 8003A838 0C00E76C */  jal        func_80039DB0
/* 3B43C 8003A83C 02002825 */   or        $a1, $s0, $zero
/* 3B440 8003A840 10000012 */  b          .L8003A88C
/* 3B444 8003A844 00000000 */   nop
/* 3B448 8003A848 8E220008 */  lw         $v0, 0x8($s1)
.L8003A84C:
/* 3B44C 8003A84C 8C830008 */  lw         $v1, 0x8($a0)
/* 3B450 8003A850 00803025 */  or         $a2, $a0, $zero
/* 3B454 8003A854 0043082A */  slt        $at, $v0, $v1
/* 3B458 8003A858 10200008 */  beqz       $at, .L8003A87C
/* 3B45C 8003A85C 0043C823 */   subu      $t9, $v0, $v1
/* 3B460 8003A860 00627023 */  subu       $t6, $v1, $v0
/* 3B464 8003A864 AC8E0008 */  sw         $t6, 0x8($a0)
/* 3B468 8003A868 02202025 */  or         $a0, $s1, $zero
/* 3B46C 8003A86C 0C00E76C */  jal        func_80039DB0
/* 3B470 8003A870 02002825 */   or        $a1, $s0, $zero
/* 3B474 8003A874 10000005 */  b          .L8003A88C
/* 3B478 8003A878 00000000 */   nop
.L8003A87C:
/* 3B47C 8003A87C AE390008 */  sw         $t9, 0x8($s1)
/* 3B480 8003A880 8E100000 */  lw         $s0, 0x0($s0)
/* 3B484 8003A884 5600FFE9 */  bnel       $s0, $zero, .L8003A82C
/* 3B488 8003A888 8E040000 */   lw        $a0, 0x0($s0)
.L8003A88C:
/* 3B48C 8003A88C 0C00DD34 */  jal        func_800374D0
/* 3B490 8003A890 02602025 */   or        $a0, $s3, $zero
/* 3B494 8003A894 1640FFCD */  bnez       $s2, .L8003A7CC
/* 3B498 8003A898 02408825 */   or        $s1, $s2, $zero
.L8003A89C:
/* 3B49C 8003A89C 8FBF0014 */  lw         $ra, 0x14($sp)
.L8003A8A0:
/* 3B4A0 8003A8A0 27BD0018 */  addiu      $sp, $sp, 0x18
/* 3B4A4 8003A8A4 03E00008 */  jr         $ra
/* 3B4A8 8003A8A8 00000000 */   nop

glabel func_8003A8AC
/* 3B4AC 8003A8AC 27BDFF48 */  addiu      $sp, $sp, -0xB8
/* 3B4B0 8003A8B0 AFBF0024 */  sw         $ra, 0x24($sp)
/* 3B4B4 8003A8B4 91160008 */  lbu        $s6, 0x8($t0)
/* 3B4B8 8003A8B8 91140009 */  lbu        $s4, 0x9($t0)
/* 3B4BC 8003A8BC 9111000A */  lbu        $s1, 0xA($t0)
/* 3B4C0 8003A8C0 32C300F0 */  andi       $v1, $s6, 0xF0
/* 3B4C4 8003A8C4 246FFF80 */  addiu      $t7, $v1, -0x80
/* 3B4C8 8003A8C8 2DE10061 */  sltiu      $at, $t7, 0x61
/* 3B4CC 8003A8CC 32CE000F */  andi       $t6, $s6, 0xF
/* 3B4D0 8003A8D0 102001FC */  beqz       $at, .L8003B0C4
/* 3B4D4 8003A8D4 01C0B025 */   or        $s6, $t6, $zero
/* 3B4D8 8003A8D8 000F7880 */  sll        $t7, $t7, 2
/* 3B4DC 8003A8DC 3C018007 */  lui        $at, %hi(jtbl_8006FAA0_main)
/* 3B4E0 8003A8E0 002F0821 */  addu       $at, $at, $t7
/* 3B4E4 8003A8E4 8C2FFAA0 */  lw         $t7, %lo(jtbl_8006FAA0_main)($at)
/* 3B4E8 8003A8E8 01E00008 */  jr         $t7
/* 3B4EC 8003A8EC 00000000 */   nop
glabel .L8003A8F0
/* 3B4F0 8003A8F0 522000E8 */  beql       $s1, $zero, .L8003AC94
/* 3B4F4 8003A8F4 02402025 */   or        $a0, $s2, $zero
/* 3B4F8 8003A8F8 8E58002C */  lw         $t8, 0x2C($s2)
/* 3B4FC 8003A8FC 24010001 */  addiu      $at, $zero, 0x1
/* 3B500 8003A900 02402025 */  or         $a0, $s2, $zero
/* 3B504 8003A904 170101EF */  bne        $t8, $at, .L8003B0C4
/* 3B508 8003A908 328500FF */   andi      $a1, $s4, 0xFF
/* 3B50C 8003A90C 322600FF */  andi       $a2, $s1, 0xFF
/* 3B510 8003A910 32C700FF */  andi       $a3, $s6, 0xFF
/* 3B514 8003A914 0C01146C */  jal        func_800451B0
/* 3B518 8003A918 AFA800BC */   sw        $t0, 0xBC($sp)
/* 3B51C 8003A91C 104001E9 */  beqz       $v0, .L8003B0C4
/* 3B520 8003A920 0040B825 */   or        $s7, $v0, $zero
/* 3B524 8003A924 8E590060 */  lw         $t9, 0x60($s2)
/* 3B528 8003A928 0016F100 */  sll        $fp, $s6, 4
/* 3B52C 8003A92C 02402025 */  or         $a0, $s2, $zero
/* 3B530 8003A930 033E7021 */  addu       $t6, $t9, $fp
/* 3B534 8003A934 91CF0008 */  lbu        $t7, 0x8($t6)
/* 3B538 8003A938 A7A00076 */  sh         $zero, 0x76($sp)
/* 3B53C 8003A93C A3A00078 */  sb         $zero, 0x78($sp)
/* 3B540 8003A940 328500FF */  andi       $a1, $s4, 0xFF
/* 3B544 8003A944 322600FF */  andi       $a2, $s1, 0xFF
/* 3B548 8003A948 32C700FF */  andi       $a3, $s6, 0xFF
/* 3B54C 8003A94C 0C011450 */  jal        func_80045140
/* 3B550 8003A950 A7AF0074 */   sh        $t7, 0x74($sp)
/* 3B554 8003A954 104001DB */  beqz       $v0, .L8003B0C4
/* 3B558 8003A958 00408025 */   or        $s0, $v0, $zero
/* 3B55C 8003A95C 8E440014 */  lw         $a0, 0x14($s2)
/* 3B560 8003A960 24450004 */  addiu      $a1, $v0, 0x4
/* 3B564 8003A964 AFA50038 */  sw         $a1, 0x38($sp)
/* 3B568 8003A968 0C0119E2 */  jal        func_80046788
/* 3B56C 8003A96C 27A60074 */   addiu     $a2, $sp, 0x74
/* 3B570 8003A970 AE170020 */  sw         $s7, 0x20($s0)
/* 3B574 8003A974 A2000034 */  sb         $zero, 0x34($s0)
/* 3B578 8003A978 8E580060 */  lw         $t8, 0x60($s2)
/* 3B57C 8003A97C 24150002 */  addiu      $s5, $zero, 0x2
/* 3B580 8003A980 031EC821 */  addu       $t9, $t8, $fp
/* 3B584 8003A984 932E000B */  lbu        $t6, 0xB($t9)
/* 3B588 8003A988 29C10040 */  slti       $at, $t6, 0x40
/* 3B58C 8003A98C 54200004 */  bnel       $at, $zero, .L8003A9A0
/* 3B590 8003A990 A2000035 */   sb        $zero, 0x35($s0)
/* 3B594 8003A994 10000002 */  b          .L8003A9A0
/* 3B598 8003A998 A2150035 */   sb        $s5, 0x35($s0)
/* 3B59C 8003A99C A2000035 */  sb         $zero, 0x35($s0)
.L8003A9A0:
/* 3B5A0 8003A9A0 8EE20004 */  lw         $v0, 0x4($s7)
/* 3B5A4 8003A9A4 904F0004 */  lbu        $t7, 0x4($v0)
/* 3B5A8 8003A9A8 804E0005 */  lb         $t6, 0x5($v0)
/* 3B5AC 8003A9AC 028FC023 */  subu       $t8, $s4, $t7
/* 3B5B0 8003A9B0 0018C880 */  sll        $t9, $t8, 2
/* 3B5B4 8003A9B4 0338C823 */  subu       $t9, $t9, $t8
/* 3B5B8 8003A9B8 0019C8C0 */  sll        $t9, $t9, 3
/* 3B5BC 8003A9BC 0338C821 */  addu       $t9, $t9, $t8
/* 3B5C0 8003A9C0 0019C880 */  sll        $t9, $t9, 2
/* 3B5C4 8003A9C4 032E2021 */  addu       $a0, $t9, $t6
/* 3B5C8 8003A9C8 00047C00 */  sll        $t7, $a0, 16
/* 3B5CC 8003A9CC 0C011A34 */  jal        func_800468D0
/* 3B5D0 8003A9D0 000F2403 */   sra       $a0, $t7, 16
/* 3B5D4 8003A9D4 E6000028 */  swc1       $f0, 0x28($s0)
/* 3B5D8 8003A9D8 8EF90000 */  lw         $t9, 0x0($s7)
/* 3B5DC 8003A9DC 3C0142FE */  lui        $at, (0x42FE0000 >> 16)
/* 3B5E0 8003A9E0 44812000 */  mtc1       $at, $f4
/* 3B5E4 8003A9E4 932E000C */  lbu        $t6, 0xC($t9)
/* 3B5E8 8003A9E8 A20E0030 */  sb         $t6, 0x30($s0)
/* 3B5EC 8003A9EC 8EF80000 */  lw         $t8, 0x0($s7)
/* 3B5F0 8003A9F0 8E4F001C */  lw         $t7, 0x1C($s2)
/* 3B5F4 8003A9F4 8F190000 */  lw         $t9, 0x0($t8)
/* 3B5F8 8003A9F8 A2000037 */  sb         $zero, 0x37($s0)
/* 3B5FC 8003A9FC 01F97021 */  addu       $t6, $t7, $t9
/* 3B600 8003AA00 AE0E0024 */  sw         $t6, 0x24($s0)
/* 3B604 8003AA04 8E580060 */  lw         $t8, 0x60($s2)
/* 3B608 8003AA08 031E7821 */  addu       $t7, $t8, $fp
/* 3B60C 8003AA0C 8DF10000 */  lw         $s1, 0x0($t7)
/* 3B610 8003AA10 E7A40064 */  swc1       $f4, 0x64($sp)
/* 3B614 8003AA14 92260004 */  lbu        $a2, 0x4($s1)
/* 3B618 8003AA18 50C0001A */  beql       $a2, $zero, .L8003AA84
/* 3B61C 8003AA1C 4458F800 */   cfc1      $t8, $31
/* 3B620 8003AA20 8E420070 */  lw         $v0, 0x70($s2)
/* 3B624 8003AA24 50400017 */  beql       $v0, $zero, .L8003AA84
/* 3B628 8003AA28 4458F800 */   cfc1      $t8, $31
/* 3B62C 8003AA2C 92390006 */  lbu        $t9, 0x6($s1)
/* 3B630 8003AA30 92270005 */  lbu        $a3, 0x5($s1)
/* 3B634 8003AA34 27A4005C */  addiu      $a0, $sp, 0x5C
/* 3B638 8003AA38 AFB90010 */  sw         $t9, 0x10($sp)
/* 3B63C 8003AA3C 922E0007 */  lbu        $t6, 0x7($s1)
/* 3B640 8003AA40 27A50064 */  addiu      $a1, $sp, 0x64
/* 3B644 8003AA44 0040F809 */  jalr       $v0
/* 3B648 8003AA48 AFAE0014 */   sw        $t6, 0x14($sp)
/* 3B64C 8003AA4C 1040000C */  beqz       $v0, .L8003AA80
/* 3B650 8003AA50 24180016 */   addiu     $t8, $zero, 0x16
/* 3B654 8003AA54 8FAF005C */  lw         $t7, 0x5C($sp)
/* 3B658 8003AA58 A7B8008C */  sh         $t8, 0x8C($sp)
/* 3B65C 8003AA5C AFB00090 */  sw         $s0, 0x90($sp)
/* 3B660 8003AA60 26440048 */  addiu      $a0, $s2, 0x48
/* 3B664 8003AA64 27A5008C */  addiu      $a1, $sp, 0x8C
/* 3B668 8003AA68 00403025 */  or         $a2, $v0, $zero
/* 3B66C 8003AA6C 0C010893 */  jal        func_8004224C
/* 3B670 8003AA70 AFAF0094 */   sw        $t7, 0x94($sp)
/* 3B674 8003AA74 92190037 */  lbu        $t9, 0x37($s0)
/* 3B678 8003AA78 372E0001 */  ori        $t6, $t9, 0x1
/* 3B67C 8003AA7C A20E0037 */  sb         $t6, 0x37($s0)
.L8003AA80:
/* 3B680 8003AA80 4458F800 */  cfc1       $t8, $31
.L8003AA84:
/* 3B684 8003AA84 240F0001 */  addiu      $t7, $zero, 0x1
/* 3B688 8003AA88 44CFF800 */  ctc1       $t7, $31
/* 3B68C 8003AA8C C7A60064 */  lwc1       $f6, 0x64($sp)
/* 3B690 8003AA90 3C014F00 */  lui        $at, (0x4F000000 >> 16)
/* 3B694 8003AA94 46003224 */  cvt.w.s    $f8, $f6
/* 3B698 8003AA98 444FF800 */  cfc1       $t7, $31
/* 3B69C 8003AA9C 00000000 */  nop
/* 3B6A0 8003AAA0 31EF0078 */  andi       $t7, $t7, 0x78
/* 3B6A4 8003AAA4 51E00013 */  beql       $t7, $zero, .L8003AAF4
/* 3B6A8 8003AAA8 440F4000 */   mfc1      $t7, $f8
/* 3B6AC 8003AAAC 44814000 */  mtc1       $at, $f8
/* 3B6B0 8003AAB0 240F0001 */  addiu      $t7, $zero, 0x1
/* 3B6B4 8003AAB4 46083201 */  sub.s      $f8, $f6, $f8
/* 3B6B8 8003AAB8 44CFF800 */  ctc1       $t7, $31
/* 3B6BC 8003AABC 00000000 */  nop
/* 3B6C0 8003AAC0 46004224 */  cvt.w.s    $f8, $f8
/* 3B6C4 8003AAC4 444FF800 */  cfc1       $t7, $31
/* 3B6C8 8003AAC8 00000000 */  nop
/* 3B6CC 8003AACC 31EF0078 */  andi       $t7, $t7, 0x78
/* 3B6D0 8003AAD0 15E00005 */  bnez       $t7, .L8003AAE8
/* 3B6D4 8003AAD4 00000000 */   nop
/* 3B6D8 8003AAD8 440F4000 */  mfc1       $t7, $f8
/* 3B6DC 8003AADC 3C018000 */  lui        $at, (0x80000000 >> 16)
/* 3B6E0 8003AAE0 10000007 */  b          .L8003AB00
/* 3B6E4 8003AAE4 01E17825 */   or        $t7, $t7, $at
.L8003AAE8:
/* 3B6E8 8003AAE8 10000005 */  b          .L8003AB00
/* 3B6EC 8003AAEC 240FFFFF */   addiu     $t7, $zero, -0x1
/* 3B6F0 8003AAF0 440F4000 */  mfc1       $t7, $f8
.L8003AAF4:
/* 3B6F4 8003AAF4 00000000 */  nop
/* 3B6F8 8003AAF8 05E0FFFB */  bltz       $t7, .L8003AAE8
/* 3B6FC 8003AAFC 00000000 */   nop
.L8003AB00:
/* 3B700 8003AB00 3C013F80 */  lui        $at, (0x3F800000 >> 16)
/* 3B704 8003AB04 44815000 */  mtc1       $at, $f10
/* 3B708 8003AB08 A20F0036 */  sb         $t7, 0x36($s0)
/* 3B70C 8003AB0C 44D8F800 */  ctc1       $t8, $31
/* 3B710 8003AB10 E7AA0064 */  swc1       $f10, 0x64($sp)
/* 3B714 8003AB14 92260008 */  lbu        $a2, 0x8($s1)
/* 3B718 8003AB18 26550048 */  addiu      $s5, $s2, 0x48
/* 3B71C 8003AB1C 50C0001B */  beql       $a2, $zero, .L8003AB8C
/* 3B720 8003AB20 C7A40064 */   lwc1      $f4, 0x64($sp)
/* 3B724 8003AB24 8E420070 */  lw         $v0, 0x70($s2)
/* 3B728 8003AB28 50400018 */  beql       $v0, $zero, .L8003AB8C
/* 3B72C 8003AB2C C7A40064 */   lwc1      $f4, 0x64($sp)
/* 3B730 8003AB30 9239000A */  lbu        $t9, 0xA($s1)
/* 3B734 8003AB34 92270009 */  lbu        $a3, 0x9($s1)
/* 3B738 8003AB38 27A4005C */  addiu      $a0, $sp, 0x5C
/* 3B73C 8003AB3C AFB90010 */  sw         $t9, 0x10($sp)
/* 3B740 8003AB40 922E000B */  lbu        $t6, 0xB($s1)
/* 3B744 8003AB44 27A50064 */  addiu      $a1, $sp, 0x64
/* 3B748 8003AB48 0040F809 */  jalr       $v0
/* 3B74C 8003AB4C AFAE0014 */   sw        $t6, 0x14($sp)
/* 3B750 8003AB50 1040000D */  beqz       $v0, .L8003AB88
/* 3B754 8003AB54 24180017 */   addiu     $t8, $zero, 0x17
/* 3B758 8003AB58 8FAF005C */  lw         $t7, 0x5C($sp)
/* 3B75C 8003AB5C A7B8008C */  sh         $t8, 0x8C($sp)
/* 3B760 8003AB60 AFB00090 */  sw         $s0, 0x90($sp)
/* 3B764 8003AB64 A3B60098 */  sb         $s6, 0x98($sp)
/* 3B768 8003AB68 02A02025 */  or         $a0, $s5, $zero
/* 3B76C 8003AB6C 27A5008C */  addiu      $a1, $sp, 0x8C
/* 3B770 8003AB70 00403025 */  or         $a2, $v0, $zero
/* 3B774 8003AB74 0C010893 */  jal        func_8004224C
/* 3B778 8003AB78 AFAF0094 */   sw        $t7, 0x94($sp)
/* 3B77C 8003AB7C 92190037 */  lbu        $t9, 0x37($s0)
/* 3B780 8003AB80 372E0002 */  ori        $t6, $t9, 0x2
/* 3B784 8003AB84 A20E0037 */  sb         $t6, 0x37($s0)
.L8003AB88:
/* 3B788 8003AB88 C7A40064 */  lwc1       $f4, 0x64($sp)
.L8003AB8C:
/* 3B78C 8003AB8C C6080028 */  lwc1       $f8, 0x28($s0)
/* 3B790 8003AB90 02002025 */  or         $a0, $s0, $zero
/* 3B794 8003AB94 E604002C */  swc1       $f4, 0x2C($s0)
/* 3B798 8003AB98 8E580060 */  lw         $t8, 0x60($s2)
/* 3B79C 8003AB9C C604002C */  lwc1       $f4, 0x2C($s0)
/* 3B7A0 8003ABA0 02402825 */  or         $a1, $s2, $zero
/* 3B7A4 8003ABA4 031E1021 */  addu       $v0, $t8, $fp
/* 3B7A8 8003ABA8 C446000C */  lwc1       $f6, 0xC($v0)
/* 3B7AC 8003ABAC 9051000A */  lbu        $s1, 0xA($v0)
/* 3B7B0 8003ABB0 46083282 */  mul.s      $f10, $f6, $f8
/* 3B7B4 8003ABB4 00000000 */  nop
/* 3B7B8 8003ABB8 46045502 */  mul.s      $f20, $f10, $f4
/* 3B7BC 8003ABBC 0C011421 */  jal        func_80045084
/* 3B7C0 8003ABC0 00000000 */   nop
/* 3B7C4 8003ABC4 305E00FF */  andi       $fp, $v0, 0xFF
/* 3B7C8 8003ABC8 02002025 */  or         $a0, $s0, $zero
/* 3B7CC 8003ABCC 0C011319 */  jal        func_80044C64
/* 3B7D0 8003ABD0 02402825 */   or        $a1, $s2, $zero
/* 3B7D4 8003ABD4 8EEF0000 */  lw         $t7, 0x0($s7)
/* 3B7D8 8003ABD8 8E440014 */  lw         $a0, 0x14($s2)
/* 3B7DC 8003ABDC 8EE60008 */  lw         $a2, 0x8($s7)
/* 3B7E0 8003ABE0 8DF30000 */  lw         $s3, 0x0($t7)
/* 3B7E4 8003ABE4 4407A000 */  mfc1       $a3, $f20
/* 3B7E8 8003ABE8 AFB10018 */  sw         $s1, 0x18($sp)
/* 3B7EC 8003ABEC AFBE0014 */  sw         $fp, 0x14($sp)
/* 3B7F0 8003ABF0 AFA20010 */  sw         $v0, 0x10($sp)
/* 3B7F4 8003ABF4 8FA50038 */  lw         $a1, 0x38($sp)
/* 3B7F8 8003ABF8 0C011A48 */  jal        func_80046920
/* 3B7FC 8003ABFC AFB3001C */   sw        $s3, 0x1C($sp)
/* 3B800 8003AC00 8FAE0038 */  lw         $t6, 0x38($sp)
/* 3B804 8003AC04 24190006 */  addiu      $t9, $zero, 0x6
/* 3B808 8003AC08 A7B9008C */  sh         $t9, 0x8C($sp)
/* 3B80C 8003AC0C AFAE0090 */  sw         $t6, 0x90($sp)
/* 3B810 8003AC10 8EF80000 */  lw         $t8, 0x0($s7)
/* 3B814 8003AC14 02A02025 */  or         $a0, $s5, $zero
/* 3B818 8003AC18 27A5008C */  addiu      $a1, $sp, 0x8C
/* 3B81C 8003AC1C 930F000D */  lbu        $t7, 0xD($t8)
/* 3B820 8003AC20 02603025 */  or         $a2, $s3, $zero
/* 3B824 8003AC24 A3AF0098 */  sb         $t7, 0x98($sp)
/* 3B828 8003AC28 8EF90000 */  lw         $t9, 0x0($s7)
/* 3B82C 8003AC2C 8F2E0004 */  lw         $t6, 0x4($t9)
/* 3B830 8003AC30 0C010893 */  jal        func_8004224C
/* 3B834 8003AC34 AFAE0094 */   sw        $t6, 0x94($sp)
/* 3B838 8003AC38 8FA200BC */  lw         $v0, 0xBC($sp)
/* 3B83C 8003AC3C 240F0015 */  addiu      $t7, $zero, 0x15
/* 3B840 8003AC40 36D90080 */  ori        $t9, $s6, 0x80
/* 3B844 8003AC44 8C58000C */  lw         $t8, 0xC($v0)
/* 3B848 8003AC48 24420004 */  addiu      $v0, $v0, 0x4
/* 3B84C 8003AC4C 5300011E */  beql       $t8, $zero, .L8003B0C8
/* 3B850 8003AC50 8FBF0024 */   lw        $ra, 0x24($sp)
/* 3B854 8003AC54 A7AF008C */  sh         $t7, 0x8C($sp)
/* 3B858 8003AC58 A3B90094 */  sb         $t9, 0x94($sp)
/* 3B85C 8003AC5C A3B40095 */  sb         $s4, 0x95($sp)
/* 3B860 8003AC60 A3A00096 */  sb         $zero, 0x96($sp)
/* 3B864 8003AC64 8C580008 */  lw         $t8, 0x8($v0)
/* 3B868 8003AC68 8E4E0024 */  lw         $t6, 0x24($s2)
/* 3B86C 8003AC6C 02A02025 */  or         $a0, $s5, $zero
/* 3B870 8003AC70 27A5008C */  addiu      $a1, $sp, 0x8C
/* 3B874 8003AC74 01D80019 */  multu      $t6, $t8
/* 3B878 8003AC78 00009812 */  mflo       $s3
/* 3B87C 8003AC7C 02603025 */  or         $a2, $s3, $zero
/* 3B880 8003AC80 0C010893 */  jal        func_8004224C
/* 3B884 8003AC84 00000000 */   nop
/* 3B888 8003AC88 1000010F */  b          .L8003B0C8
/* 3B88C 8003AC8C 8FBF0024 */   lw        $ra, 0x24($sp)
glabel .L8003AC90
/* 3B890 8003AC90 02402025 */  or         $a0, $s2, $zero
.L8003AC94:
/* 3B894 8003AC94 328500FF */  andi       $a1, $s4, 0xFF
/* 3B898 8003AC98 0C011433 */  jal        func_800450CC
/* 3B89C 8003AC9C 32C600FF */   andi      $a2, $s6, 0xFF
/* 3B8A0 8003ACA0 10400108 */  beqz       $v0, .L8003B0C4
/* 3B8A4 8003ACA4 00408025 */   or        $s0, $v0, $zero
/* 3B8A8 8003ACA8 904F0035 */  lbu        $t7, 0x35($v0)
/* 3B8AC 8003ACAC 24160002 */  addiu      $s6, $zero, 0x2
/* 3B8B0 8003ACB0 24190004 */  addiu      $t9, $zero, 0x4
/* 3B8B4 8003ACB4 16CF0003 */  bne        $s6, $t7, .L8003ACC4
/* 3B8B8 8003ACB8 02402025 */   or        $a0, $s2, $zero
/* 3B8BC 8003ACBC 10000101 */  b          .L8003B0C4
/* 3B8C0 8003ACC0 A0590035 */   sb        $t9, 0x35($v0)
.L8003ACC4:
/* 3B8C4 8003ACC4 8E0E0020 */  lw         $t6, 0x20($s0)
/* 3B8C8 8003ACC8 241E0003 */  addiu      $fp, $zero, 0x3
/* 3B8CC 8003ACCC A21E0035 */  sb         $fp, 0x35($s0)
/* 3B8D0 8003ACD0 8DD80000 */  lw         $t8, 0x0($t6)
/* 3B8D4 8003ACD4 26050004 */  addiu      $a1, $s0, 0x4
/* 3B8D8 8003ACD8 0C01133B */  jal        func_80044CEC
/* 3B8DC 8003ACDC 8F060008 */   lw        $a2, 0x8($t8)
/* 3B8E0 8003ACE0 100000F9 */  b          .L8003B0C8
/* 3B8E4 8003ACE4 8FBF0024 */   lw        $ra, 0x24($sp)
glabel .L8003ACE8
/* 3B8E8 8003ACE8 02402025 */  or         $a0, $s2, $zero
/* 3B8EC 8003ACEC 328500FF */  andi       $a1, $s4, 0xFF
/* 3B8F0 8003ACF0 0C011433 */  jal        func_800450CC
/* 3B8F4 8003ACF4 32C600FF */   andi      $a2, $s6, 0xFF
/* 3B8F8 8003ACF8 104000F2 */  beqz       $v0, .L8003B0C4
/* 3B8FC 8003ACFC 00408025 */   or        $s0, $v0, $zero
/* 3B900 8003AD00 A0510033 */  sb         $s1, 0x33($v0)
/* 3B904 8003AD04 00402025 */  or         $a0, $v0, $zero
/* 3B908 8003AD08 0C011319 */  jal        func_80044C64
/* 3B90C 8003AD0C 02402825 */   or        $a1, $s2, $zero
/* 3B910 8003AD10 00028C00 */  sll        $s1, $v0, 16
/* 3B914 8003AD14 00117C03 */  sra        $t7, $s1, 16
/* 3B918 8003AD18 01E08825 */  or         $s1, $t7, $zero
/* 3B91C 8003AD1C 02002025 */  or         $a0, $s0, $zero
/* 3B920 8003AD20 0C011310 */  jal        func_80044C40
/* 3B924 8003AD24 8E45001C */   lw        $a1, 0x1C($s2)
/* 3B928 8003AD28 00113400 */  sll        $a2, $s1, 16
/* 3B92C 8003AD2C 0006CC03 */  sra        $t9, $a2, 16
/* 3B930 8003AD30 03203025 */  or         $a2, $t9, $zero
/* 3B934 8003AD34 8E440014 */  lw         $a0, 0x14($s2)
/* 3B938 8003AD38 26050004 */  addiu      $a1, $s0, 0x4
/* 3B93C 8003AD3C 0C01195C */  jal        func_80046570
/* 3B940 8003AD40 00403825 */   or        $a3, $v0, $zero
/* 3B944 8003AD44 100000E0 */  b          .L8003B0C8
/* 3B948 8003AD48 8FBF0024 */   lw        $ra, 0x24($sp)
glabel .L8003AD4C
/* 3B94C 8003AD4C 8E500064 */  lw         $s0, 0x64($s2)
/* 3B950 8003AD50 520000DD */  beql       $s0, $zero, .L8003B0C8
/* 3B954 8003AD54 8FBF0024 */   lw        $ra, 0x24($sp)
/* 3B958 8003AD58 02C09825 */  or         $s3, $s6, $zero
/* 3B95C 8003AD5C 920E0031 */  lbu        $t6, 0x31($s0)
.L8003AD60:
/* 3B960 8003AD60 02002025 */  or         $a0, $s0, $zero
/* 3B964 8003AD64 02402825 */  or         $a1, $s2, $zero
/* 3B968 8003AD68 566E0011 */  bnel       $s3, $t6, .L8003ADB0
/* 3B96C 8003AD6C 8E100000 */   lw        $s0, 0x0($s0)
/* 3B970 8003AD70 0C011319 */  jal        func_80044C64
/* 3B974 8003AD74 A2140033 */   sb        $s4, 0x33($s0)
/* 3B978 8003AD78 00028C00 */  sll        $s1, $v0, 16
/* 3B97C 8003AD7C 0011C403 */  sra        $t8, $s1, 16
/* 3B980 8003AD80 03008825 */  or         $s1, $t8, $zero
/* 3B984 8003AD84 02002025 */  or         $a0, $s0, $zero
/* 3B988 8003AD88 0C011310 */  jal        func_80044C40
/* 3B98C 8003AD8C 8E45001C */   lw        $a1, 0x1C($s2)
/* 3B990 8003AD90 00113400 */  sll        $a2, $s1, 16
/* 3B994 8003AD94 00067C03 */  sra        $t7, $a2, 16
/* 3B998 8003AD98 01E03025 */  or         $a2, $t7, $zero
/* 3B99C 8003AD9C 8E440014 */  lw         $a0, 0x14($s2)
/* 3B9A0 8003ADA0 26050004 */  addiu      $a1, $s0, 0x4
/* 3B9A4 8003ADA4 0C01195C */  jal        func_80046570
/* 3B9A8 8003ADA8 00403825 */   or        $a3, $v0, $zero
/* 3B9AC 8003ADAC 8E100000 */  lw         $s0, 0x0($s0)
.L8003ADB0:
/* 3B9B0 8003ADB0 5600FFEB */  bnel       $s0, $zero, .L8003AD60
/* 3B9B4 8003ADB4 920E0031 */   lbu       $t6, 0x31($s0)
/* 3B9B8 8003ADB8 100000C3 */  b          .L8003B0C8
/* 3B9BC 8003ADBC 8FBF0024 */   lw        $ra, 0x24($sp)
glabel .L8003ADC0
/* 3B9C0 8003ADC0 24010007 */  addiu      $at, $zero, 0x7
/* 3B9C4 8003ADC4 12810023 */  beq        $s4, $at, .L8003AE54
/* 3B9C8 8003ADC8 02801025 */   or        $v0, $s4, $zero
/* 3B9CC 8003ADCC 2401000A */  addiu      $at, $zero, 0xA
/* 3B9D0 8003ADD0 10410009 */  beq        $v0, $at, .L8003ADF8
/* 3B9D4 8003ADD4 24010010 */   addiu     $at, $zero, 0x10
/* 3B9D8 8003ADD8 10410042 */  beq        $v0, $at, .L8003AEE4
/* 3B9DC 8003ADDC 24010040 */   addiu     $at, $zero, 0x40
/* 3B9E0 8003ADE0 10410045 */  beq        $v0, $at, .L8003AEF8
/* 3B9E4 8003ADE4 2401005B */   addiu     $at, $zero, 0x5B
/* 3B9E8 8003ADE8 50410070 */  beql       $v0, $at, .L8003AFAC
/* 3B9EC 8003ADEC 8E590060 */   lw        $t9, 0x60($s2)
/* 3B9F0 8003ADF0 100000B5 */  b          .L8003B0C8
/* 3B9F4 8003ADF4 8FBF0024 */   lw        $ra, 0x24($sp)
.L8003ADF8:
/* 3B9F8 8003ADF8 8E590060 */  lw         $t9, 0x60($s2)
/* 3B9FC 8003ADFC 00167100 */  sll        $t6, $s6, 4
/* 3BA00 8003AE00 032EC021 */  addu       $t8, $t9, $t6
/* 3BA04 8003AE04 A3110007 */  sb         $s1, 0x7($t8)
/* 3BA08 8003AE08 8E500064 */  lw         $s0, 0x64($s2)
/* 3BA0C 8003AE0C 520000AE */  beql       $s0, $zero, .L8003B0C8
/* 3BA10 8003AE10 8FBF0024 */   lw        $ra, 0x24($sp)
/* 3BA14 8003AE14 02C09825 */  or         $s3, $s6, $zero
/* 3BA18 8003AE18 920F0031 */  lbu        $t7, 0x31($s0)
.L8003AE1C:
/* 3BA1C 8003AE1C 02002025 */  or         $a0, $s0, $zero
/* 3BA20 8003AE20 566F0008 */  bnel       $s3, $t7, .L8003AE44
/* 3BA24 8003AE24 8E100000 */   lw        $s0, 0x0($s0)
/* 3BA28 8003AE28 0C011421 */  jal        func_80045084
/* 3BA2C 8003AE2C 02402825 */   or        $a1, $s2, $zero
/* 3BA30 8003AE30 8E440014 */  lw         $a0, 0x14($s2)
/* 3BA34 8003AE34 26050004 */  addiu      $a1, $s0, 0x4
/* 3BA38 8003AE38 0C011A84 */  jal        func_80046A10
/* 3BA3C 8003AE3C 304600FF */   andi      $a2, $v0, 0xFF
/* 3BA40 8003AE40 8E100000 */  lw         $s0, 0x0($s0)
.L8003AE44:
/* 3BA44 8003AE44 5600FFF5 */  bnel       $s0, $zero, .L8003AE1C
/* 3BA48 8003AE48 920F0031 */   lbu       $t7, 0x31($s0)
/* 3BA4C 8003AE4C 1000009E */  b          .L8003B0C8
/* 3BA50 8003AE50 8FBF0024 */   lw        $ra, 0x24($sp)
.L8003AE54:
/* 3BA54 8003AE54 8E590060 */  lw         $t9, 0x60($s2)
/* 3BA58 8003AE58 00167100 */  sll        $t6, $s6, 4
/* 3BA5C 8003AE5C 032EC021 */  addu       $t8, $t9, $t6
/* 3BA60 8003AE60 A3110009 */  sb         $s1, 0x9($t8)
/* 3BA64 8003AE64 8E500064 */  lw         $s0, 0x64($s2)
/* 3BA68 8003AE68 52000097 */  beql       $s0, $zero, .L8003B0C8
/* 3BA6C 8003AE6C 8FBF0024 */   lw        $ra, 0x24($sp)
/* 3BA70 8003AE70 02C09825 */  or         $s3, $s6, $zero
/* 3BA74 8003AE74 24140003 */  addiu      $s4, $zero, 0x3
/* 3BA78 8003AE78 920F0031 */  lbu        $t7, 0x31($s0)
.L8003AE7C:
/* 3BA7C 8003AE7C 566F0015 */  bnel       $s3, $t7, .L8003AED4
/* 3BA80 8003AE80 8E100000 */   lw        $s0, 0x0($s0)
/* 3BA84 8003AE84 92190034 */  lbu        $t9, 0x34($s0)
/* 3BA88 8003AE88 02002025 */  or         $a0, $s0, $zero
/* 3BA8C 8003AE8C 52990011 */  beql       $s4, $t9, .L8003AED4
/* 3BA90 8003AE90 8E100000 */   lw        $s0, 0x0($s0)
/* 3BA94 8003AE94 0C011319 */  jal        func_80044C64
/* 3BA98 8003AE98 02402825 */   or        $a1, $s2, $zero
/* 3BA9C 8003AE9C 00028C00 */  sll        $s1, $v0, 16
/* 3BAA0 8003AEA0 00117403 */  sra        $t6, $s1, 16
/* 3BAA4 8003AEA4 01C08825 */  or         $s1, $t6, $zero
/* 3BAA8 8003AEA8 02002025 */  or         $a0, $s0, $zero
/* 3BAAC 8003AEAC 0C011310 */  jal        func_80044C40
/* 3BAB0 8003AEB0 8E45001C */   lw        $a1, 0x1C($s2)
/* 3BAB4 8003AEB4 00113400 */  sll        $a2, $s1, 16
/* 3BAB8 8003AEB8 0006C403 */  sra        $t8, $a2, 16
/* 3BABC 8003AEBC 03003025 */  or         $a2, $t8, $zero
/* 3BAC0 8003AEC0 8E440014 */  lw         $a0, 0x14($s2)
/* 3BAC4 8003AEC4 26050004 */  addiu      $a1, $s0, 0x4
/* 3BAC8 8003AEC8 0C01195C */  jal        func_80046570
/* 3BACC 8003AECC 00403825 */   or        $a3, $v0, $zero
/* 3BAD0 8003AED0 8E100000 */  lw         $s0, 0x0($s0)
.L8003AED4:
/* 3BAD4 8003AED4 5600FFE9 */  bnel       $s0, $zero, .L8003AE7C
/* 3BAD8 8003AED8 920F0031 */   lbu       $t7, 0x31($s0)
/* 3BADC 8003AEDC 1000007A */  b          .L8003B0C8
/* 3BAE0 8003AEE0 8FBF0024 */   lw        $ra, 0x24($sp)
.L8003AEE4:
/* 3BAE4 8003AEE4 8E4F0060 */  lw         $t7, 0x60($s2)
/* 3BAE8 8003AEE8 0016C900 */  sll        $t9, $s6, 4
/* 3BAEC 8003AEEC 01F97021 */  addu       $t6, $t7, $t9
/* 3BAF0 8003AEF0 10000074 */  b          .L8003B0C4
/* 3BAF4 8003AEF4 A1D10008 */   sb        $s1, 0x8($t6)
.L8003AEF8:
/* 3BAF8 8003AEF8 8E580060 */  lw         $t8, 0x60($s2)
/* 3BAFC 8003AEFC 00167900 */  sll        $t7, $s6, 4
/* 3BB00 8003AF00 030FC821 */  addu       $t9, $t8, $t7
/* 3BB04 8003AF04 A331000B */  sb         $s1, 0xB($t9)
/* 3BB08 8003AF08 8E500064 */  lw         $s0, 0x64($s2)
/* 3BB0C 8003AF0C 5200006E */  beql       $s0, $zero, .L8003B0C8
/* 3BB10 8003AF10 8FBF0024 */   lw        $ra, 0x24($sp)
/* 3BB14 8003AF14 02C09825 */  or         $s3, $s6, $zero
/* 3BB18 8003AF18 24160002 */  addiu      $s6, $zero, 0x2
/* 3BB1C 8003AF1C 241E0003 */  addiu      $fp, $zero, 0x3
/* 3BB20 8003AF20 24170004 */  addiu      $s7, $zero, 0x4
/* 3BB24 8003AF24 24150002 */  addiu      $s5, $zero, 0x2
/* 3BB28 8003AF28 24140003 */  addiu      $s4, $zero, 0x3
/* 3BB2C 8003AF2C 920E0031 */  lbu        $t6, 0x31($s0)
.L8003AF30:
/* 3BB30 8003AF30 566E0019 */  bnel       $s3, $t6, .L8003AF98
/* 3BB34 8003AF34 8E100000 */   lw        $s0, 0x0($s0)
/* 3BB38 8003AF38 92020035 */  lbu        $v0, 0x35($s0)
/* 3BB3C 8003AF3C 2A210040 */  slti       $at, $s1, 0x40
/* 3BB40 8003AF40 52820015 */  beql       $s4, $v0, .L8003AF98
/* 3BB44 8003AF44 8E100000 */   lw        $s0, 0x0($s0)
/* 3BB48 8003AF48 14200005 */  bnez       $at, .L8003AF60
/* 3BB4C 8003AF4C 00000000 */   nop
/* 3BB50 8003AF50 54400011 */  bnel       $v0, $zero, .L8003AF98
/* 3BB54 8003AF54 8E100000 */   lw        $s0, 0x0($s0)
/* 3BB58 8003AF58 1000000E */  b          .L8003AF94
/* 3BB5C 8003AF5C A2150035 */   sb        $s5, 0x35($s0)
.L8003AF60:
/* 3BB60 8003AF60 16C20003 */  bne        $s6, $v0, .L8003AF70
/* 3BB64 8003AF64 00000000 */   nop
/* 3BB68 8003AF68 1000000A */  b          .L8003AF94
/* 3BB6C 8003AF6C A2000035 */   sb        $zero, 0x35($s0)
.L8003AF70:
/* 3BB70 8003AF70 56E20009 */  bnel       $s7, $v0, .L8003AF98
/* 3BB74 8003AF74 8E100000 */   lw        $s0, 0x0($s0)
/* 3BB78 8003AF78 8E180020 */  lw         $t8, 0x20($s0)
/* 3BB7C 8003AF7C A21E0035 */  sb         $fp, 0x35($s0)
/* 3BB80 8003AF80 02402025 */  or         $a0, $s2, $zero
/* 3BB84 8003AF84 8F0F0000 */  lw         $t7, 0x0($t8)
/* 3BB88 8003AF88 26050004 */  addiu      $a1, $s0, 0x4
/* 3BB8C 8003AF8C 0C01133B */  jal        func_80044CEC
/* 3BB90 8003AF90 8DE60008 */   lw        $a2, 0x8($t7)
.L8003AF94:
/* 3BB94 8003AF94 8E100000 */  lw         $s0, 0x0($s0)
.L8003AF98:
/* 3BB98 8003AF98 5600FFE5 */  bnel       $s0, $zero, .L8003AF30
/* 3BB9C 8003AF9C 920E0031 */   lbu       $t6, 0x31($s0)
/* 3BBA0 8003AFA0 10000049 */  b          .L8003B0C8
/* 3BBA4 8003AFA4 8FBF0024 */   lw        $ra, 0x24($sp)
/* 3BBA8 8003AFA8 8E590060 */  lw         $t9, 0x60($s2)
.L8003AFAC:
/* 3BBAC 8003AFAC 00167100 */  sll        $t6, $s6, 4
/* 3BBB0 8003AFB0 032EC021 */  addu       $t8, $t9, $t6
/* 3BBB4 8003AFB4 A311000A */  sb         $s1, 0xA($t8)
/* 3BBB8 8003AFB8 8E500064 */  lw         $s0, 0x64($s2)
/* 3BBBC 8003AFBC 52000042 */  beql       $s0, $zero, .L8003B0C8
/* 3BBC0 8003AFC0 8FBF0024 */   lw        $ra, 0x24($sp)
/* 3BBC4 8003AFC4 02C09825 */  or         $s3, $s6, $zero
/* 3BBC8 8003AFC8 920F0031 */  lbu        $t7, 0x31($s0)
.L8003AFCC:
/* 3BBCC 8003AFCC 26050004 */  addiu      $a1, $s0, 0x4
/* 3BBD0 8003AFD0 322600FF */  andi       $a2, $s1, 0xFF
/* 3BBD4 8003AFD4 566F0004 */  bnel       $s3, $t7, .L8003AFE8
/* 3BBD8 8003AFD8 8E100000 */   lw        $s0, 0x0($s0)
/* 3BBDC 8003AFDC 0C011AA8 */  jal        func_80046AA0
/* 3BBE0 8003AFE0 8E440014 */   lw        $a0, 0x14($s2)
/* 3BBE4 8003AFE4 8E100000 */  lw         $s0, 0x0($s0)
.L8003AFE8:
/* 3BBE8 8003AFE8 5600FFF8 */  bnel       $s0, $zero, .L8003AFCC
/* 3BBEC 8003AFEC 920F0031 */   lbu       $t7, 0x31($s0)
/* 3BBF0 8003AFF0 10000035 */  b          .L8003B0C8
/* 3BBF4 8003AFF4 8FBF0024 */   lw        $ra, 0x24($sp)
glabel .L8003AFF8
/* 3BBF8 8003AFF8 8E420020 */  lw         $v0, 0x20($s2)
/* 3BBFC 8003AFFC 00147080 */  sll        $t6, $s4, 2
/* 3BC00 8003B000 02402025 */  or         $a0, $s2, $zero
/* 3BC04 8003B004 84590000 */  lh         $t9, 0x0($v0)
/* 3BC08 8003B008 02C03025 */  or         $a2, $s6, $zero
/* 3BC0C 8003B00C 004EC021 */  addu       $t8, $v0, $t6
/* 3BC10 8003B010 0299082A */  slt        $at, $s4, $t9
/* 3BC14 8003B014 5020002C */  beql       $at, $zero, .L8003B0C8
/* 3BC18 8003B018 8FBF0024 */   lw        $ra, 0x24($sp)
/* 3BC1C 8003B01C 0C0112AC */  jal        func_80044AB0
/* 3BC20 8003B020 8F05000C */   lw        $a1, 0xC($t8)
/* 3BC24 8003B024 10000028 */  b          .L8003B0C8
/* 3BC28 8003B028 8FBF0024 */   lw        $ra, 0x24($sp)
glabel .L8003B02C
/* 3BC2C 8003B02C 8E4F0060 */  lw         $t7, 0x60($s2)
/* 3BC30 8003B030 0016F100 */  sll        $fp, $s6, 4
/* 3BC34 8003B034 0011C1C0 */  sll        $t8, $s1, 7
/* 3BC38 8003B038 01FEC821 */  addu       $t9, $t7, $fp
/* 3BC3C 8003B03C 872E0004 */  lh         $t6, 0x4($t9)
/* 3BC40 8003B040 03147821 */  addu       $t7, $t8, $s4
/* 3BC44 8003B044 25F9E000 */  addiu      $t9, $t7, -0x2000
/* 3BC48 8003B048 01D90019 */  multu      $t6, $t9
/* 3BC4C 8003B04C 00002012 */  mflo       $a0
/* 3BC50 8003B050 04810003 */  bgez       $a0, .L8003B060
/* 3BC54 8003B054 0004C343 */   sra       $t8, $a0, 13
/* 3BC58 8003B058 24811FFF */  addiu      $at, $a0, 0x1FFF
/* 3BC5C 8003B05C 0001C343 */  sra        $t8, $at, 13
.L8003B060:
/* 3BC60 8003B060 0C011A34 */  jal        func_800468D0
/* 3BC64 8003B064 03002025 */   or        $a0, $t8, $zero
/* 3BC68 8003B068 8E4F0060 */  lw         $t7, 0x60($s2)
/* 3BC6C 8003B06C 46000506 */  mov.s      $f20, $f0
/* 3BC70 8003B070 01FE7021 */  addu       $t6, $t7, $fp
/* 3BC74 8003B074 E5C0000C */  swc1       $f0, 0xC($t6)
/* 3BC78 8003B078 8E500064 */  lw         $s0, 0x64($s2)
/* 3BC7C 8003B07C 52000012 */  beql       $s0, $zero, .L8003B0C8
/* 3BC80 8003B080 8FBF0024 */   lw        $ra, 0x24($sp)
/* 3BC84 8003B084 02C09825 */  or         $s3, $s6, $zero
/* 3BC88 8003B088 92190031 */  lbu        $t9, 0x31($s0)
.L8003B08C:
/* 3BC8C 8003B08C 5679000B */  bnel       $s3, $t9, .L8003B0BC
/* 3BC90 8003B090 8E100000 */   lw        $s0, 0x0($s0)
/* 3BC94 8003B094 C6060028 */  lwc1       $f6, 0x28($s0)
/* 3BC98 8003B098 C60A002C */  lwc1       $f10, 0x2C($s0)
/* 3BC9C 8003B09C 8E440014 */  lw         $a0, 0x14($s2)
/* 3BCA0 8003B0A0 46143202 */  mul.s      $f8, $f6, $f20
/* 3BCA4 8003B0A4 26050004 */  addiu      $a1, $s0, 0x4
/* 3BCA8 8003B0A8 460A4102 */  mul.s      $f4, $f8, $f10
/* 3BCAC 8003B0AC 44062000 */  mfc1       $a2, $f4
/* 3BCB0 8003B0B0 0C011984 */  jal        func_80046610
/* 3BCB4 8003B0B4 00000000 */   nop
/* 3BCB8 8003B0B8 8E100000 */  lw         $s0, 0x0($s0)
.L8003B0BC:
/* 3BCBC 8003B0BC 5600FFF3 */  bnel       $s0, $zero, .L8003B08C
/* 3BCC0 8003B0C0 92190031 */   lbu       $t9, 0x31($s0)
glabel .L8003B0C4
/* 3BCC4 8003B0C4 8FBF0024 */  lw         $ra, 0x24($sp)
.L8003B0C8:
/* 3BCC8 8003B0C8 27BD00B8 */  addiu      $sp, $sp, 0xB8
/* 3BCCC 8003B0CC 03E00008 */  jr         $ra
/* 3BCD0 8003B0D0 00000000 */   nop
/* 3BCD4 8003B0D4 03E00008 */  jr         $ra
/* 3BCD8 8003B0D8 00000000 */   nop

glabel func_8003B0DC
/* 3BCDC 8003B0DC 27BDFF60 */  addiu      $sp, $sp, -0xA0
/* 3BCE0 8003B0E0 AFB50034 */  sw         $s5, 0x34($sp)
/* 3BCE4 8003B0E4 AFB20028 */  sw         $s2, 0x28($sp)
/* 3BCE8 8003B0E8 248E0038 */  addiu      $t6, $a0, 0x38
/* 3BCEC 8003B0EC 00809025 */  or         $s2, $a0, $zero
/* 3BCF0 8003B0F0 AFBF0044 */  sw         $ra, 0x44($sp)
/* 3BCF4 8003B0F4 AFBE0040 */  sw         $fp, 0x40($sp)
/* 3BCF8 8003B0F8 AFB7003C */  sw         $s7, 0x3C($sp)
/* 3BCFC 8003B0FC AFB60038 */  sw         $s6, 0x38($sp)
/* 3BD00 8003B100 AFB40030 */  sw         $s4, 0x30($sp)
/* 3BD04 8003B104 AFB3002C */  sw         $s3, 0x2C($sp)
/* 3BD08 8003B108 AFB10024 */  sw         $s1, 0x24($sp)
/* 3BD0C 8003B10C AFB00020 */  sw         $s0, 0x20($sp)
/* 3BD10 8003B110 F7B40018 */  sdc1       $f20, 0x18($sp)
/* 3BD14 8003B114 AFAE0050 */  sw         $t6, 0x50($sp)
/* 3BD18 8003B118 24950048 */  addiu      $s5, $a0, 0x48
.L8003B11C:
/* 3BD1C 8003B11C 964F0038 */  lhu        $t7, 0x38($s2)
/* 3BD20 8003B120 2DE10018 */  sltiu      $at, $t7, 0x18
/* 3BD24 8003B124 1020015D */  beqz       $at, .L8003B69C
/* 3BD28 8003B128 000F7880 */   sll       $t7, $t7, 2
/* 3BD2C 8003B12C 3C018007 */  lui        $at, %hi(jtbl_8006FC24_main)
/* 3BD30 8003B130 002F0821 */  addu       $at, $at, $t7
/* 3BD34 8003B134 8C2FFC24 */  lw         $t7, %lo(jtbl_8006FC24_main)($at)
/* 3BD38 8003B138 01E00008 */  jr         $t7
/* 3BD3C 8003B13C 00000000 */   nop
glabel .L8003B140
/* 3BD40 8003B140 8E440018 */  lw         $a0, 0x18($s2)
/* 3BD44 8003B144 50800156 */  beql       $a0, $zero, .L8003B6A0
/* 3BD48 8003B148 02A02025 */   or        $a0, $s5, $zero
/* 3BD4C 8003B14C 0C00EF55 */  jal        func_8003BD54
/* 3BD50 8003B150 27A50058 */   addiu     $a1, $sp, 0x58
/* 3BD54 8003B154 87B80058 */  lh         $t8, 0x58($sp)
/* 3BD58 8003B158 2719FFFF */  addiu      $t9, $t8, -0x1
/* 3BD5C 8003B15C 2F210014 */  sltiu      $at, $t9, 0x14
/* 3BD60 8003B160 1020014E */  beqz       $at, .L8003B69C
/* 3BD64 8003B164 0019C880 */   sll       $t9, $t9, 2
/* 3BD68 8003B168 3C018007 */  lui        $at, %hi(jtbl_8006FC84_main)
/* 3BD6C 8003B16C 00390821 */  addu       $at, $at, $t9
/* 3BD70 8003B170 8C39FC84 */  lw         $t9, %lo(jtbl_8006FC84_main)($at)
/* 3BD74 8003B174 03200008 */  jr         $t9
/* 3BD78 8003B178 00000000 */   nop
glabel .L8003B17C
/* 3BD7C 8003B17C 27A80058 */  addiu      $t0, $sp, 0x58
/* 3BD80 8003B180 AFB200A0 */  sw         $s2, 0xA0($sp)
/* 3BD84 8003B184 0C00EA2B */  jal        func_8003A8AC
/* 3BD88 8003B188 AFB5004C */   sw        $s5, 0x4C($sp)
/* 3BD8C 8003B18C 8FB200A0 */  lw         $s2, 0xA0($sp)
/* 3BD90 8003B190 8FB5004C */  lw         $s5, 0x4C($sp)
/* 3BD94 8003B194 0C00E98C */  jal        func_8003A630
/* 3BD98 8003B198 02402025 */   or        $a0, $s2, $zero
/* 3BD9C 8003B19C 10000140 */  b          .L8003B6A0
/* 3BDA0 8003B1A0 02A02025 */   or        $a0, $s5, $zero
glabel .L8003B1A4
/* 3BDA4 8003B1A4 0240B825 */  or         $s7, $s2, $zero
/* 3BDA8 8003B1A8 27A50058 */  addiu      $a1, $sp, 0x58
/* 3BDAC 8003B1AC AFB200A0 */  sw         $s2, 0xA0($sp)
/* 3BDB0 8003B1B0 0C00E9B7 */  jal        func_8003A6DC
/* 3BDB4 8003B1B4 AFB5004C */   sw        $s5, 0x4C($sp)
/* 3BDB8 8003B1B8 8FB200A0 */  lw         $s2, 0xA0($sp)
/* 3BDBC 8003B1BC 8FB5004C */  lw         $s5, 0x4C($sp)
/* 3BDC0 8003B1C0 0C00E98C */  jal        func_8003A630
/* 3BDC4 8003B1C4 02402025 */   or        $a0, $s2, $zero
/* 3BDC8 8003B1C8 10000135 */  b          .L8003B6A0
/* 3BDCC 8003B1CC 02A02025 */   or        $a0, $s5, $zero
glabel .L8003B1D0
/* 3BDD0 8003B1D0 240E0002 */  addiu      $t6, $zero, 0x2
/* 3BDD4 8003B1D4 AE4E002C */  sw         $t6, 0x2C($s2)
/* 3BDD8 8003B1D8 240F0010 */  addiu      $t7, $zero, 0x10
/* 3BDDC 8003B1DC 3C067FFF */  lui        $a2, (0x7FFFFFFF >> 16)
/* 3BDE0 8003B1E0 A7AF0058 */  sh         $t7, 0x58($sp)
/* 3BDE4 8003B1E4 34C6FFFF */  ori        $a2, $a2, (0x7FFFFFFF & 0xFFFF)
/* 3BDE8 8003B1E8 02A02025 */  or         $a0, $s5, $zero
/* 3BDEC 8003B1EC 0C010893 */  jal        func_8004224C
/* 3BDF0 8003B1F0 27A50058 */   addiu     $a1, $sp, 0x58
/* 3BDF4 8003B1F4 1000012A */  b          .L8003B6A0
/* 3BDF8 8003B1F8 02A02025 */   or        $a0, $s5, $zero
glabel .L8003B1FC
/* 3BDFC 8003B1FC 0C00E98C */  jal        func_8003A630
/* 3BE00 8003B200 02402025 */   or        $a0, $s2, $zero
/* 3BE04 8003B204 10000126 */  b          .L8003B6A0
/* 3BE08 8003B208 02A02025 */   or        $a0, $s5, $zero
glabel .L8003B20C
/* 3BE0C 8003B20C 24180009 */  addiu      $t8, $zero, 0x9
/* 3BE10 8003B210 A7B8008C */  sh         $t8, 0x8C($sp)
/* 3BE14 8003B214 8E46005C */  lw         $a2, 0x5C($s2)
/* 3BE18 8003B218 02A02025 */  or         $a0, $s5, $zero
/* 3BE1C 8003B21C 0C010893 */  jal        func_8004224C
/* 3BE20 8003B220 27A5008C */   addiu     $a1, $sp, 0x8C
/* 3BE24 8003B224 1000011E */  b          .L8003B6A0
/* 3BE28 8003B228 02A02025 */   or        $a0, $s5, $zero
glabel .L8003B22C
/* 3BE2C 8003B22C 8E50003C */  lw         $s0, 0x3C($s2)
/* 3BE30 8003B230 8E440014 */  lw         $a0, 0x14($s2)
/* 3BE34 8003B234 0C011910 */  jal        func_80046440
/* 3BE38 8003B238 02002825 */   or        $a1, $s0, $zero
/* 3BE3C 8003B23C 8E440014 */  lw         $a0, 0x14($s2)
/* 3BE40 8003B240 0C011930 */  jal        func_800464C0
/* 3BE44 8003B244 02002825 */   or        $a1, $s0, $zero
/* 3BE48 8003B248 8E110010 */  lw         $s1, 0x10($s0)
/* 3BE4C 8003B24C 02402025 */  or         $a0, $s2, $zero
/* 3BE50 8003B250 92390037 */  lbu        $t9, 0x37($s1)
/* 3BE54 8003B254 53200004 */  beql       $t9, $zero, .L8003B268
/* 3BE58 8003B258 02402025 */   or        $a0, $s2, $zero
/* 3BE5C 8003B25C 0C01183C */  jal        func_800460F0
/* 3BE60 8003B260 02202825 */   or        $a1, $s1, $zero
/* 3BE64 8003B264 02402025 */  or         $a0, $s2, $zero
.L8003B268:
/* 3BE68 8003B268 0C0113B0 */  jal        func_80044EC0
/* 3BE6C 8003B26C 02002825 */   or        $a1, $s0, $zero
/* 3BE70 8003B270 1000010B */  b          .L8003B6A0
/* 3BE74 8003B274 02A02025 */   or        $a0, $s5, $zero
glabel .L8003B278
/* 3BE78 8003B278 8E50003C */  lw         $s0, 0x3C($s2)
/* 3BE7C 8003B27C 240F0001 */  addiu      $t7, $zero, 0x1
/* 3BE80 8003B280 8E110010 */  lw         $s1, 0x10($s0)
/* 3BE84 8003B284 922E0034 */  lbu        $t6, 0x34($s1)
/* 3BE88 8003B288 55C00003 */  bnel       $t6, $zero, .L8003B298
/* 3BE8C 8003B28C 8E530040 */   lw        $s3, 0x40($s2)
/* 3BE90 8003B290 A22F0034 */  sb         $t7, 0x34($s1)
/* 3BE94 8003B294 8E530040 */  lw         $s3, 0x40($s2)
.L8003B298:
/* 3BE98 8003B298 8E58001C */  lw         $t8, 0x1C($s2)
/* 3BE9C 8003B29C 02202025 */  or         $a0, $s1, $zero
/* 3BEA0 8003B2A0 02402825 */  or         $a1, $s2, $zero
/* 3BEA4 8003B2A4 0313C821 */  addu       $t9, $t8, $s3
/* 3BEA8 8003B2A8 AE390024 */  sw         $t9, 0x24($s1)
/* 3BEAC 8003B2AC 924E0044 */  lbu        $t6, 0x44($s2)
/* 3BEB0 8003B2B0 0C011319 */  jal        func_80044C64
/* 3BEB4 8003B2B4 A22E0030 */   sb        $t6, 0x30($s1)
/* 3BEB8 8003B2B8 00023400 */  sll        $a2, $v0, 16
/* 3BEBC 8003B2BC 00067C03 */  sra        $t7, $a2, 16
/* 3BEC0 8003B2C0 01E03025 */  or         $a2, $t7, $zero
/* 3BEC4 8003B2C4 8E440014 */  lw         $a0, 0x14($s2)
/* 3BEC8 8003B2C8 02002825 */  or         $a1, $s0, $zero
/* 3BECC 8003B2CC 0C01195C */  jal        func_80046570
/* 3BED0 8003B2D0 02603825 */   or        $a3, $s3, $zero
/* 3BED4 8003B2D4 100000F2 */  b          .L8003B6A0
/* 3BED8 8003B2D8 02A02025 */   or        $a0, $s5, $zero
glabel .L8003B2DC
/* 3BEDC 8003B2DC 8E590074 */  lw         $t9, 0x74($s2)
/* 3BEE0 8003B2E0 8E540040 */  lw         $s4, 0x40($s2)
/* 3BEE4 8003B2E4 8E51003C */  lw         $s1, 0x3C($s2)
/* 3BEE8 8003B2E8 27A50078 */  addiu      $a1, $sp, 0x78
/* 3BEEC 8003B2EC 0320F809 */  jalr       $t9
/* 3BEF0 8003B2F0 02802025 */   or        $a0, $s4, $zero
/* 3BEF4 8003B2F4 4458F800 */  cfc1       $t8, $31
/* 3BEF8 8003B2F8 240E0001 */  addiu      $t6, $zero, 0x1
/* 3BEFC 8003B2FC 44CEF800 */  ctc1       $t6, $31
/* 3BF00 8003B300 C7A40078 */  lwc1       $f4, 0x78($sp)
/* 3BF04 8003B304 00409825 */  or         $s3, $v0, $zero
/* 3BF08 8003B308 3C014F00 */  lui        $at, (0x4F000000 >> 16)
/* 3BF0C 8003B30C 460021A4 */  cvt.w.s    $f6, $f4
/* 3BF10 8003B310 02202025 */  or         $a0, $s1, $zero
/* 3BF14 8003B314 02402825 */  or         $a1, $s2, $zero
/* 3BF18 8003B318 444EF800 */  cfc1       $t6, $31
/* 3BF1C 8003B31C 00000000 */  nop
/* 3BF20 8003B320 31CE0078 */  andi       $t6, $t6, 0x78
/* 3BF24 8003B324 51C00013 */  beql       $t6, $zero, .L8003B374
/* 3BF28 8003B328 440E3000 */   mfc1      $t6, $f6
/* 3BF2C 8003B32C 44813000 */  mtc1       $at, $f6
/* 3BF30 8003B330 240E0001 */  addiu      $t6, $zero, 0x1
/* 3BF34 8003B334 46062181 */  sub.s      $f6, $f4, $f6
/* 3BF38 8003B338 44CEF800 */  ctc1       $t6, $31
/* 3BF3C 8003B33C 00000000 */  nop
/* 3BF40 8003B340 460031A4 */  cvt.w.s    $f6, $f6
/* 3BF44 8003B344 444EF800 */  cfc1       $t6, $31
/* 3BF48 8003B348 00000000 */  nop
/* 3BF4C 8003B34C 31CE0078 */  andi       $t6, $t6, 0x78
/* 3BF50 8003B350 15C00005 */  bnez       $t6, .L8003B368
/* 3BF54 8003B354 00000000 */   nop
/* 3BF58 8003B358 440E3000 */  mfc1       $t6, $f6
/* 3BF5C 8003B35C 3C018000 */  lui        $at, (0x80000000 >> 16)
/* 3BF60 8003B360 10000007 */  b          .L8003B380
/* 3BF64 8003B364 01C17025 */   or        $t6, $t6, $at
.L8003B368:
/* 3BF68 8003B368 10000005 */  b          .L8003B380
/* 3BF6C 8003B36C 240EFFFF */   addiu     $t6, $zero, -0x1
/* 3BF70 8003B370 440E3000 */  mfc1       $t6, $f6
.L8003B374:
/* 3BF74 8003B374 00000000 */  nop
/* 3BF78 8003B378 05C0FFFB */  bltz       $t6, .L8003B368
/* 3BF7C 8003B37C 00000000 */   nop
.L8003B380:
/* 3BF80 8003B380 44D8F800 */  ctc1       $t8, $31
/* 3BF84 8003B384 0C011319 */  jal        func_80044C64
/* 3BF88 8003B388 A22E0036 */   sb        $t6, 0x36($s1)
/* 3BF8C 8003B38C 00028400 */  sll        $s0, $v0, 16
/* 3BF90 8003B390 00107C03 */  sra        $t7, $s0, 16
/* 3BF94 8003B394 01E08025 */  or         $s0, $t7, $zero
/* 3BF98 8003B398 02202025 */  or         $a0, $s1, $zero
/* 3BF9C 8003B39C 0C011310 */  jal        func_80044C40
/* 3BFA0 8003B3A0 8E45001C */   lw        $a1, 0x1C($s2)
/* 3BFA4 8003B3A4 00103400 */  sll        $a2, $s0, 16
/* 3BFA8 8003B3A8 0006CC03 */  sra        $t9, $a2, 16
/* 3BFAC 8003B3AC 03203025 */  or         $a2, $t9, $zero
/* 3BFB0 8003B3B0 8E440014 */  lw         $a0, 0x14($s2)
/* 3BFB4 8003B3B4 26250004 */  addiu      $a1, $s1, 0x4
/* 3BFB8 8003B3B8 0C01195C */  jal        func_80046570
/* 3BFBC 8003B3BC 00403825 */   or        $a3, $v0, $zero
/* 3BFC0 8003B3C0 24180016 */  addiu      $t8, $zero, 0x16
/* 3BFC4 8003B3C4 A7B8008C */  sh         $t8, 0x8C($sp)
/* 3BFC8 8003B3C8 AFB10090 */  sw         $s1, 0x90($sp)
/* 3BFCC 8003B3CC AFB40094 */  sw         $s4, 0x94($sp)
/* 3BFD0 8003B3D0 02A02025 */  or         $a0, $s5, $zero
/* 3BFD4 8003B3D4 27A5008C */  addiu      $a1, $sp, 0x8C
/* 3BFD8 8003B3D8 0C010893 */  jal        func_8004224C
/* 3BFDC 8003B3DC 02603025 */   or        $a2, $s3, $zero
/* 3BFE0 8003B3E0 100000AF */  b          .L8003B6A0
/* 3BFE4 8003B3E4 02A02025 */   or        $a0, $s5, $zero
glabel .L8003B3E8
/* 3BFE8 8003B3E8 8E590074 */  lw         $t9, 0x74($s2)
/* 3BFEC 8003B3EC 8E540040 */  lw         $s4, 0x40($s2)
/* 3BFF0 8003B3F0 8E51003C */  lw         $s1, 0x3C($s2)
/* 3BFF4 8003B3F4 92500044 */  lbu        $s0, 0x44($s2)
/* 3BFF8 8003B3F8 27A50078 */  addiu      $a1, $sp, 0x78
/* 3BFFC 8003B3FC 0320F809 */  jalr       $t9
/* 3C000 8003B400 02802025 */   or        $a0, $s4, $zero
/* 3C004 8003B404 C7A80078 */  lwc1       $f8, 0x78($sp)
/* 3C008 8003B408 C6240028 */  lwc1       $f4, 0x28($s1)
/* 3C00C 8003B40C 00107900 */  sll        $t7, $s0, 4
/* 3C010 8003B410 E628002C */  swc1       $f8, 0x2C($s1)
/* 3C014 8003B414 C626002C */  lwc1       $f6, 0x2C($s1)
/* 3C018 8003B418 8E4E0060 */  lw         $t6, 0x60($s2)
/* 3C01C 8003B41C 00409825 */  or         $s3, $v0, $zero
/* 3C020 8003B420 46062202 */  mul.s      $f8, $f4, $f6
/* 3C024 8003B424 01CFC021 */  addu       $t8, $t6, $t7
/* 3C028 8003B428 C70A000C */  lwc1       $f10, 0xC($t8)
/* 3C02C 8003B42C 8E440014 */  lw         $a0, 0x14($s2)
/* 3C030 8003B430 26250004 */  addiu      $a1, $s1, 0x4
/* 3C034 8003B434 46085102 */  mul.s      $f4, $f10, $f8
/* 3C038 8003B438 44062000 */  mfc1       $a2, $f4
/* 3C03C 8003B43C 0C011984 */  jal        func_80046610
/* 3C040 8003B440 00000000 */   nop
/* 3C044 8003B444 24190017 */  addiu      $t9, $zero, 0x17
/* 3C048 8003B448 A7B9008C */  sh         $t9, 0x8C($sp)
/* 3C04C 8003B44C AFB10090 */  sw         $s1, 0x90($sp)
/* 3C050 8003B450 AFB40094 */  sw         $s4, 0x94($sp)
/* 3C054 8003B454 A3B00098 */  sb         $s0, 0x98($sp)
/* 3C058 8003B458 02A02025 */  or         $a0, $s5, $zero
/* 3C05C 8003B45C 27A5008C */  addiu      $a1, $sp, 0x8C
/* 3C060 8003B460 0C010893 */  jal        func_8004224C
/* 3C064 8003B464 02603025 */   or        $a2, $s3, $zero
/* 3C068 8003B468 1000008D */  b          .L8003B6A0
/* 3C06C 8003B46C 02A02025 */   or        $a0, $s5, $zero
glabel .L8003B470
/* 3C070 8003B470 8FA80050 */  lw         $t0, 0x50($sp)
/* 3C074 8003B474 AFB200A0 */  sw         $s2, 0xA0($sp)
/* 3C078 8003B478 0C00EA2B */  jal        func_8003A8AC
/* 3C07C 8003B47C AFB5004C */   sw        $s5, 0x4C($sp)
/* 3C080 8003B480 8FB200A0 */  lw         $s2, 0xA0($sp)
/* 3C084 8003B484 10000085 */  b          .L8003B69C
/* 3C088 8003B488 8FB5004C */   lw        $s5, 0x4C($sp)
glabel .L8003B48C
/* 3C08C 8003B48C 0240B825 */  or         $s7, $s2, $zero
/* 3C090 8003B490 8FA50050 */  lw         $a1, 0x50($sp)
/* 3C094 8003B494 AFB200A0 */  sw         $s2, 0xA0($sp)
/* 3C098 8003B498 0C00E9B7 */  jal        func_8003A6DC
/* 3C09C 8003B49C AFB5004C */   sw        $s5, 0x4C($sp)
/* 3C0A0 8003B4A0 8FB200A0 */  lw         $s2, 0xA0($sp)
/* 3C0A4 8003B4A4 1000007D */  b          .L8003B69C
/* 3C0A8 8003B4A8 8FB5004C */   lw        $s5, 0x4C($sp)
glabel .L8003B4AC
/* 3C0AC 8003B4AC 8E510064 */  lw         $s1, 0x64($s2)
/* 3C0B0 8003B4B0 864E003C */  lh         $t6, 0x3C($s2)
/* 3C0B4 8003B4B4 12200079 */  beqz       $s1, .L8003B69C
/* 3C0B8 8003B4B8 A64E0032 */   sh        $t6, 0x32($s2)
/* 3C0BC 8003B4BC 02202025 */  or         $a0, $s1, $zero
.L8003B4C0:
/* 3C0C0 8003B4C0 0C011319 */  jal        func_80044C64
/* 3C0C4 8003B4C4 02402825 */   or        $a1, $s2, $zero
/* 3C0C8 8003B4C8 00028400 */  sll        $s0, $v0, 16
/* 3C0CC 8003B4CC 00107C03 */  sra        $t7, $s0, 16
/* 3C0D0 8003B4D0 01E08025 */  or         $s0, $t7, $zero
/* 3C0D4 8003B4D4 02202025 */  or         $a0, $s1, $zero
/* 3C0D8 8003B4D8 0C011310 */  jal        func_80044C40
/* 3C0DC 8003B4DC 8E45001C */   lw        $a1, 0x1C($s2)
/* 3C0E0 8003B4E0 00103400 */  sll        $a2, $s0, 16
/* 3C0E4 8003B4E4 0006C403 */  sra        $t8, $a2, 16
/* 3C0E8 8003B4E8 03003025 */  or         $a2, $t8, $zero
/* 3C0EC 8003B4EC 8E440014 */  lw         $a0, 0x14($s2)
/* 3C0F0 8003B4F0 26250004 */  addiu      $a1, $s1, 0x4
/* 3C0F4 8003B4F4 0C01195C */  jal        func_80046570
/* 3C0F8 8003B4F8 00403825 */   or        $a3, $v0, $zero
/* 3C0FC 8003B4FC 8E310000 */  lw         $s1, 0x0($s1)
/* 3C100 8003B500 5620FFEF */  bnel       $s1, $zero, .L8003B4C0
/* 3C104 8003B504 02202025 */   or        $a0, $s1, $zero
/* 3C108 8003B508 10000065 */  b          .L8003B6A0
/* 3C10C 8003B50C 02A02025 */   or        $a0, $s5, $zero
glabel .L8003B510
/* 3C110 8003B510 8E59002C */  lw         $t9, 0x2C($s2)
/* 3C114 8003B514 24010001 */  addiu      $at, $zero, 0x1
/* 3C118 8003B518 240E0001 */  addiu      $t6, $zero, 0x1
/* 3C11C 8003B51C 1321005F */  beq        $t9, $at, .L8003B69C
/* 3C120 8003B520 02402025 */   or        $a0, $s2, $zero
/* 3C124 8003B524 0C00E98C */  jal        func_8003A630
/* 3C128 8003B528 AE4E002C */   sw        $t6, 0x2C($s2)
/* 3C12C 8003B52C 1000005C */  b          .L8003B6A0
/* 3C130 8003B530 02A02025 */   or        $a0, $s5, $zero
glabel .L8003B534
/* 3C134 8003B534 8E4F002C */  lw         $t7, 0x2C($s2)
/* 3C138 8003B538 24010002 */  addiu      $at, $zero, 0x2
/* 3C13C 8003B53C 55E10058 */  bnel       $t7, $at, .L8003B6A0
/* 3C140 8003B540 02A02025 */   or        $a0, $s5, $zero
/* 3C144 8003B544 8E510064 */  lw         $s1, 0x64($s2)
/* 3C148 8003B548 12200013 */  beqz       $s1, .L8003B598
/* 3C14C 8003B54C 26300004 */   addiu     $s0, $s1, 0x4
.L8003B550:
/* 3C150 8003B550 02002825 */  or         $a1, $s0, $zero
/* 3C154 8003B554 0C011910 */  jal        func_80046440
/* 3C158 8003B558 8E440014 */   lw        $a0, 0x14($s2)
/* 3C15C 8003B55C 8E440014 */  lw         $a0, 0x14($s2)
/* 3C160 8003B560 0C011930 */  jal        func_800464C0
/* 3C164 8003B564 02002825 */   or        $a1, $s0, $zero
/* 3C168 8003B568 92380037 */  lbu        $t8, 0x37($s1)
/* 3C16C 8003B56C 02402025 */  or         $a0, $s2, $zero
/* 3C170 8003B570 53000004 */  beql       $t8, $zero, .L8003B584
/* 3C174 8003B574 02402025 */   or        $a0, $s2, $zero
/* 3C178 8003B578 0C01183C */  jal        func_800460F0
/* 3C17C 8003B57C 02202825 */   or        $a1, $s1, $zero
/* 3C180 8003B580 02402025 */  or         $a0, $s2, $zero
.L8003B584:
/* 3C184 8003B584 0C0113B0 */  jal        func_80044EC0
/* 3C188 8003B588 02002825 */   or        $a1, $s0, $zero
/* 3C18C 8003B58C 8E510064 */  lw         $s1, 0x64($s2)
/* 3C190 8003B590 5620FFEF */  bnel       $s1, $zero, .L8003B550
/* 3C194 8003B594 26300004 */   addiu     $s0, $s1, 0x4
.L8003B598:
/* 3C198 8003B598 10000040 */  b          .L8003B69C
/* 3C19C 8003B59C AE40002C */   sw        $zero, 0x2C($s2)
glabel .L8003B5A0
/* 3C1A0 8003B5A0 8E59002C */  lw         $t9, 0x2C($s2)
/* 3C1A4 8003B5A4 24010001 */  addiu      $at, $zero, 0x1
/* 3C1A8 8003B5A8 02A02025 */  or         $a0, $s5, $zero
/* 3C1AC 8003B5AC 5721003C */  bnel       $t9, $at, .L8003B6A0
/* 3C1B0 8003B5B0 02A02025 */   or        $a0, $s5, $zero
/* 3C1B4 8003B5B4 0C01084C */  jal        func_80042130
/* 3C1B8 8003B5B8 00002825 */   or        $a1, $zero, $zero
/* 3C1BC 8003B5BC 02A02025 */  or         $a0, $s5, $zero
/* 3C1C0 8003B5C0 0C01084C */  jal        func_80042130
/* 3C1C4 8003B5C4 24050015 */   addiu     $a1, $zero, 0x15
/* 3C1C8 8003B5C8 02A02025 */  or         $a0, $s5, $zero
/* 3C1CC 8003B5CC 0C01084C */  jal        func_80042130
/* 3C1D0 8003B5D0 24050002 */   addiu     $a1, $zero, 0x2
/* 3C1D4 8003B5D4 8E510064 */  lw         $s1, 0x64($s2)
/* 3C1D8 8003B5D8 1220000D */  beqz       $s1, .L8003B610
/* 3C1DC 8003B5DC 26300004 */   addiu     $s0, $s1, 0x4
.L8003B5E0:
/* 3C1E0 8003B5E0 02002825 */  or         $a1, $s0, $zero
/* 3C1E4 8003B5E4 02402025 */  or         $a0, $s2, $zero
/* 3C1E8 8003B5E8 0C011386 */  jal        func_80044E18
/* 3C1EC 8003B5EC 3406C350 */   ori       $a2, $zero, 0xC350
/* 3C1F0 8003B5F0 10400004 */  beqz       $v0, .L8003B604
/* 3C1F4 8003B5F4 02402025 */   or        $a0, $s2, $zero
/* 3C1F8 8003B5F8 02002825 */  or         $a1, $s0, $zero
/* 3C1FC 8003B5FC 0C01133B */  jal        func_80044CEC
/* 3C200 8003B600 3406C350 */   ori       $a2, $zero, 0xC350
.L8003B604:
/* 3C204 8003B604 8E310000 */  lw         $s1, 0x0($s1)
/* 3C208 8003B608 5620FFF5 */  bnel       $s1, $zero, .L8003B5E0
/* 3C20C 8003B60C 26300004 */   addiu     $s0, $s1, 0x4
.L8003B610:
/* 3C210 8003B610 240E0002 */  addiu      $t6, $zero, 0x2
/* 3C214 8003B614 AE4E002C */  sw         $t6, 0x2C($s2)
/* 3C218 8003B618 240F0010 */  addiu      $t7, $zero, 0x10
/* 3C21C 8003B61C 3C067FFF */  lui        $a2, (0x7FFFFFFF >> 16)
/* 3C220 8003B620 A7AF008C */  sh         $t7, 0x8C($sp)
/* 3C224 8003B624 34C6FFFF */  ori        $a2, $a2, (0x7FFFFFFF & 0xFFFF)
/* 3C228 8003B628 02A02025 */  or         $a0, $s5, $zero
/* 3C22C 8003B62C 0C010893 */  jal        func_8004224C
/* 3C230 8003B630 27A5008C */   addiu     $a1, $sp, 0x8C
/* 3C234 8003B634 1000001A */  b          .L8003B6A0
/* 3C238 8003B638 02A02025 */   or        $a0, $s5, $zero
glabel .L8003B63C
/* 3C23C 8003B63C 9250003C */  lbu        $s0, 0x3C($s2)
/* 3C240 8003B640 8E590060 */  lw         $t9, 0x60($s2)
/* 3C244 8003B644 9258003D */  lbu        $t8, 0x3D($s2)
/* 3C248 8003B648 00107100 */  sll        $t6, $s0, 4
/* 3C24C 8003B64C 032E7821 */  addu       $t7, $t9, $t6
/* 3C250 8003B650 10000012 */  b          .L8003B69C
/* 3C254 8003B654 A1F80008 */   sb        $t8, 0x8($t7)
glabel .L8003B658
/* 3C258 8003B658 8E59003C */  lw         $t9, 0x3C($s2)
/* 3C25C 8003B65C 3C018007 */  lui        $at, %hi(D_8006FCD4)
/* 3C260 8003B660 02402025 */  or         $a0, $s2, $zero
/* 3C264 8003B664 AE590018 */  sw         $t9, 0x18($s2)
/* 3C268 8003B668 0C00E9A8 */  jal        func_8003A6A0
/* 3C26C 8003B66C C42CFCD4 */   lwc1      $f12, %lo(D_8006FCD4)($at)
/* 3C270 8003B670 8E450020 */  lw         $a1, 0x20($s2)
/* 3C274 8003B674 50A0000A */  beql       $a1, $zero, .L8003B6A0
/* 3C278 8003B678 02A02025 */   or        $a0, $s5, $zero
/* 3C27C 8003B67C 0C0112E1 */  jal        func_80044B84
/* 3C280 8003B680 02402025 */   or        $a0, $s2, $zero
/* 3C284 8003B684 10000006 */  b          .L8003B6A0
/* 3C288 8003B688 02A02025 */   or        $a0, $s5, $zero
glabel .L8003B68C
/* 3C28C 8003B68C 8E45003C */  lw         $a1, 0x3C($s2)
/* 3C290 8003B690 02402025 */  or         $a0, $s2, $zero
/* 3C294 8003B694 0C0112E1 */  jal        func_80044B84
/* 3C298 8003B698 AE450020 */   sw        $a1, 0x20($s2)
glabel .L8003B69C
/* 3C29C 8003B69C 02A02025 */  or         $a0, $s5, $zero
.L8003B6A0:
/* 3C2A0 8003B6A0 0C0108DC */  jal        func_80042370
/* 3C2A4 8003B6A4 8FA50050 */   lw        $a1, 0x50($sp)
/* 3C2A8 8003B6A8 1040FE9C */  beqz       $v0, .L8003B11C
/* 3C2AC 8003B6AC AE420028 */   sw        $v0, 0x28($s2)
/* 3C2B0 8003B6B0 8E4E001C */  lw         $t6, 0x1C($s2)
/* 3C2B4 8003B6B4 01C2C021 */  addu       $t8, $t6, $v0
/* 3C2B8 8003B6B8 AE58001C */  sw         $t8, 0x1C($s2)
/* 3C2BC 8003B6BC 8FBF0044 */  lw         $ra, 0x44($sp)
/* 3C2C0 8003B6C0 8FBE0040 */  lw         $fp, 0x40($sp)
/* 3C2C4 8003B6C4 8FB7003C */  lw         $s7, 0x3C($sp)
/* 3C2C8 8003B6C8 8FB60038 */  lw         $s6, 0x38($sp)
/* 3C2CC 8003B6CC 8FB50034 */  lw         $s5, 0x34($sp)
/* 3C2D0 8003B6D0 8FB40030 */  lw         $s4, 0x30($sp)
/* 3C2D4 8003B6D4 8FB3002C */  lw         $s3, 0x2C($sp)
/* 3C2D8 8003B6D8 8FB20028 */  lw         $s2, 0x28($sp)
/* 3C2DC 8003B6DC 8FB10024 */  lw         $s1, 0x24($sp)
/* 3C2E0 8003B6E0 8FB00020 */  lw         $s0, 0x20($sp)
/* 3C2E4 8003B6E4 D7B40018 */  ldc1       $f20, 0x18($sp)
/* 3C2E8 8003B6E8 03E00008 */  jr         $ra
/* 3C2EC 8003B6EC 27BD00A0 */   addiu     $sp, $sp, 0xA0

glabel func_8003B6F0
/* 3C2F0 8003B6F0 27BDFFC0 */  addiu      $sp, $sp, -0x40
/* 3C2F4 8003B6F4 AFBF0024 */  sw         $ra, 0x24($sp)
/* 3C2F8 8003B6F8 AFB10020 */  sw         $s1, 0x20($sp)
/* 3C2FC 8003B6FC AFB0001C */  sw         $s0, 0x1C($sp)
/* 3C300 8003B700 8CA6000C */  lw         $a2, 0xC($a1)
/* 3C304 8003B704 AC800020 */  sw         $zero, 0x20($a0)
/* 3C308 8003B708 AC800018 */  sw         $zero, 0x18($a0)
/* 3C30C 8003B70C 3C0E8007 */  lui        $t6, %hi(D_8006E6F0)
/* 3C310 8003B710 8DCEE6F0 */  lw         $t6, %lo(D_8006E6F0)($t6)
/* 3C314 8003B714 240F00FF */  addiu      $t7, $zero, 0xFF
/* 3C318 8003B718 241801E8 */  addiu      $t8, $zero, 0x1E8
/* 3C31C 8003B71C 24197FFF */  addiu      $t9, $zero, 0x7FFF
/* 3C320 8003B720 24083E80 */  addiu      $t0, $zero, 0x3E80
/* 3C324 8003B724 A48F0030 */  sh         $t7, 0x30($a0)
/* 3C328 8003B728 AC980024 */  sw         $t8, 0x24($a0)
/* 3C32C 8003B72C AC800028 */  sw         $zero, 0x28($a0)
/* 3C330 8003B730 AC80002C */  sw         $zero, 0x2C($a0)
/* 3C334 8003B734 A4990032 */  sh         $t9, 0x32($a0)
/* 3C338 8003B738 AC88005C */  sw         $t0, 0x5C($a0)
/* 3C33C 8003B73C AC80001C */  sw         $zero, 0x1C($a0)
/* 3C340 8003B740 AC8E0014 */  sw         $t6, 0x14($a0)
/* 3C344 8003B744 8CA90010 */  lw         $t1, 0x10($a1)
/* 3C348 8003B748 240C0009 */  addiu      $t4, $zero, 0x9
/* 3C34C 8003B74C 00A08825 */  or         $s1, $a1, $zero
/* 3C350 8003B750 AC890070 */  sw         $t1, 0x70($a0)
/* 3C354 8003B754 8CAA0014 */  lw         $t2, 0x14($a1)
/* 3C358 8003B758 00808025 */  or         $s0, $a0, $zero
/* 3C35C 8003B75C 240E0010 */  addiu      $t6, $zero, 0x10
/* 3C360 8003B760 AC8A0074 */  sw         $t2, 0x74($a0)
/* 3C364 8003B764 8CAB0018 */  lw         $t3, 0x18($a1)
/* 3C368 8003B768 A48C0038 */  sh         $t4, 0x38($a0)
/* 3C36C 8003B76C AC8B0078 */  sw         $t3, 0x78($a0)
/* 3C370 8003B770 90AD0008 */  lbu        $t5, 0x8($a1)
/* 3C374 8003B774 00002825 */  or         $a1, $zero, $zero
/* 3C378 8003B778 A08D0034 */  sb         $t5, 0x34($a0)
/* 3C37C 8003B77C 92270008 */  lbu        $a3, 0x8($s1)
/* 3C380 8003B780 AFAE0010 */  sw         $t6, 0x10($sp)
/* 3C384 8003B784 00002025 */  or         $a0, $zero, $zero
/* 3C388 8003B788 0C00E6F4 */  jal        func_80039BD0
/* 3C38C 8003B78C AFA6002C */   sw        $a2, 0x2C($sp)
/* 3C390 8003B790 AE020060 */  sw         $v0, 0x60($s0)
/* 3C394 8003B794 0C01187D */  jal        func_800461F4
/* 3C398 8003B798 02002025 */   or        $a0, $s0, $zero
/* 3C39C 8003B79C 8E270000 */  lw         $a3, 0x0($s1)
/* 3C3A0 8003B7A0 240F0038 */  addiu      $t7, $zero, 0x38
/* 3C3A4 8003B7A4 AFAF0010 */  sw         $t7, 0x10($sp)
/* 3C3A8 8003B7A8 00002025 */  or         $a0, $zero, $zero
/* 3C3AC 8003B7AC 00002825 */  or         $a1, $zero, $zero
/* 3C3B0 8003B7B0 0C00E6F4 */  jal        func_80039BD0
/* 3C3B4 8003B7B4 8FA6002C */   lw        $a2, 0x2C($sp)
/* 3C3B8 8003B7B8 AE00006C */  sw         $zero, 0x6C($s0)
/* 3C3BC 8003B7BC 8E380000 */  lw         $t8, 0x0($s1)
/* 3C3C0 8003B7C0 00002025 */  or         $a0, $zero, $zero
/* 3C3C4 8003B7C4 00002825 */  or         $a1, $zero, $zero
/* 3C3C8 8003B7C8 1B00000B */  blez       $t8, .L8003B7F8
/* 3C3CC 8003B7CC 2409001C */   addiu     $t1, $zero, 0x1C
/* 3C3D0 8003B7D0 00401825 */  or         $v1, $v0, $zero
/* 3C3D4 8003B7D4 8E19006C */  lw         $t9, 0x6C($s0)
.L8003B7D8:
/* 3C3D8 8003B7D8 24840001 */  addiu      $a0, $a0, 0x1
/* 3C3DC 8003B7DC AC790000 */  sw         $t9, 0x0($v1)
/* 3C3E0 8003B7E0 AE03006C */  sw         $v1, 0x6C($s0)
/* 3C3E4 8003B7E4 8E280000 */  lw         $t0, 0x0($s1)
/* 3C3E8 8003B7E8 24630038 */  addiu      $v1, $v1, 0x38
/* 3C3EC 8003B7EC 0088082A */  slt        $at, $a0, $t0
/* 3C3F0 8003B7F0 5420FFF9 */  bnel       $at, $zero, .L8003B7D8
/* 3C3F4 8003B7F4 8E19006C */   lw        $t9, 0x6C($s0)
.L8003B7F8:
/* 3C3F8 8003B7F8 AE000064 */  sw         $zero, 0x64($s0)
/* 3C3FC 8003B7FC AE000068 */  sw         $zero, 0x68($s0)
/* 3C400 8003B800 8E270004 */  lw         $a3, 0x4($s1)
/* 3C404 8003B804 AFA90010 */  sw         $t1, 0x10($sp)
/* 3C408 8003B808 8FA6002C */  lw         $a2, 0x2C($sp)
/* 3C40C 8003B80C 0C00E6F4 */  jal        func_80039BD0
/* 3C410 8003B810 00002025 */   or        $a0, $zero, $zero
/* 3C414 8003B814 26040048 */  addiu      $a0, $s0, 0x48
/* 3C418 8003B818 00402825 */  or         $a1, $v0, $zero
/* 3C41C 8003B81C 0C0108FF */  jal        func_800423FC
/* 3C420 8003B820 8E260004 */   lw        $a2, 0x4($s1)
/* 3C424 8003B824 3C0A8004 */  lui        $t2, %hi(func_8003B0DC)
/* 3C428 8003B828 254AB0DC */  addiu      $t2, $t2, %lo(func_8003B0DC)
/* 3C42C 8003B82C AE000000 */  sw         $zero, 0x0($s0)
/* 3C430 8003B830 AE0A0008 */  sw         $t2, 0x8($s0)
/* 3C434 8003B834 AE100004 */  sw         $s0, 0x4($s0)
/* 3C438 8003B838 3C048007 */  lui        $a0, %hi(D_8006E6F0)
/* 3C43C 8003B83C 8C84E6F0 */  lw         $a0, %lo(D_8006E6F0)($a0)
/* 3C440 8003B840 0C0118FC */  jal        func_800463F0
/* 3C444 8003B844 02002825 */   or        $a1, $s0, $zero
/* 3C448 8003B848 8FBF0024 */  lw         $ra, 0x24($sp)
/* 3C44C 8003B84C 8FB0001C */  lw         $s0, 0x1C($sp)
/* 3C450 8003B850 8FB10020 */  lw         $s1, 0x20($sp)
/* 3C454 8003B854 03E00008 */  jr         $ra
/* 3C458 8003B858 27BD0040 */   addiu     $sp, $sp, 0x40
/* 3C45C 8003B85C 00000000 */  nop
