.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.10.1 */

glabel func_8003C5B0
/* 3D1B0 8003C5B0 27BDFFD8 */  addiu      $sp, $sp, -0x28
/* 3D1B4 8003C5B4 AFBF0014 */  sw         $ra, 0x14($sp)
/* 3D1B8 8003C5B8 240E000D */  addiu      $t6, $zero, 0xD
/* 3D1BC 8003C5BC AFA5001C */  sw         $a1, 0x1C($sp)
/* 3D1C0 8003C5C0 A7AE0018 */  sh         $t6, 0x18($sp)
/* 3D1C4 8003C5C4 27A50018 */  addiu      $a1, $sp, 0x18
/* 3D1C8 8003C5C8 24840048 */  addiu      $a0, $a0, 0x48
/* 3D1CC 8003C5CC 0C010893 */  jal        func_8004224C
/* 3D1D0 8003C5D0 00003025 */   or        $a2, $zero, $zero
/* 3D1D4 8003C5D4 8FBF0014 */  lw         $ra, 0x14($sp)
/* 3D1D8 8003C5D8 27BD0028 */  addiu      $sp, $sp, 0x28
/* 3D1DC 8003C5DC 03E00008 */  jr         $ra
/* 3D1E0 8003C5E0 00000000 */   nop
/* 3D1E4 8003C5E4 00000000 */  nop
/* 3D1E8 8003C5E8 00000000 */  nop
/* 3D1EC 8003C5EC 00000000 */  nop
