.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.10.1 */

glabel func_8003C680
/* 3D280 8003C680 27BDFFD8 */  addiu      $sp, $sp, -0x28
/* 3D284 8003C684 AFBF0014 */  sw         $ra, 0x14($sp)
/* 3D288 8003C688 240E0011 */  addiu      $t6, $zero, 0x11
/* 3D28C 8003C68C A7AE0018 */  sh         $t6, 0x18($sp)
/* 3D290 8003C690 27A50018 */  addiu      $a1, $sp, 0x18
/* 3D294 8003C694 24840048 */  addiu      $a0, $a0, 0x48
/* 3D298 8003C698 0C010893 */  jal        func_8004224C
/* 3D29C 8003C69C 00003025 */   or        $a2, $zero, $zero
/* 3D2A0 8003C6A0 8FBF0014 */  lw         $ra, 0x14($sp)
/* 3D2A4 8003C6A4 27BD0028 */  addiu      $sp, $sp, 0x28
/* 3D2A8 8003C6A8 03E00008 */  jr         $ra
/* 3D2AC 8003C6AC 00000000 */   nop

glabel func_8003C6B0
/* 3D2B0 8003C6B0 03E00008 */  jr         $ra
/* 3D2B4 8003C6B4 8C82002C */   lw        $v0, 0x2C($a0)
/* 3D2B8 8003C6B8 00000000 */  nop
/* 3D2BC 8003C6BC 00000000 */  nop
