.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.17.3 */

glabel func_8003CDD0
/* 3D9D0 8003CDD0 8C860044 */  lw         $a2, 0x44($a0)
/* 3D9D4 8003CDD4 8C820040 */  lw         $v0, 0x40($a0)
/* 3D9D8 8003CDD8 00001825 */  or         $v1, $zero, $zero
/* 3D9DC 8003CDDC 18C00020 */  blez       $a2, .L8003CE60
/* 3D9E0 8003CDE0 24070030 */   addiu     $a3, $zero, 0x30
.L8003CDE4:
/* 3D9E4 8003CDE4 00670019 */  multu      $v1, $a3
/* 3D9E8 8003CDE8 00007012 */  mflo       $t6
/* 3D9EC 8003CDEC 004E2021 */  addu       $a0, $v0, $t6
/* 3D9F0 8003CDF0 8C8F001C */  lw         $t7, 0x1C($a0)
/* 3D9F4 8003CDF4 15E00014 */  bnez       $t7, .L8003CE48
/* 3D9F8 8003CDF8 3C013F80 */   lui       $at, (0x3F800000 >> 16)
/* 3D9FC 8003CDFC 44812000 */  mtc1       $at, $f4
/* 3DA00 8003CE00 24180005 */  addiu      $t8, $zero, 0x5
/* 3DA04 8003CE04 24190040 */  addiu      $t9, $zero, 0x40
/* 3DA08 8003CE08 AC85001C */  sw         $a1, 0x1C($a0)
/* 3DA0C 8003CE0C A4980020 */  sh         $t8, 0x20($a0)
/* 3DA10 8003CE10 AC800028 */  sw         $zero, 0x28($a0)
/* 3DA14 8003CE14 A099002E */  sb         $t9, 0x2E($a0)
/* 3DA18 8003CE18 A080002F */  sb         $zero, 0x2F($a0)
/* 3DA1C 8003CE1C E4840024 */  swc1       $f4, 0x24($a0)
/* 3DA20 8003CE20 90A8000D */  lbu        $t0, 0xD($a1)
/* 3DA24 8003CE24 2401007F */  addiu      $at, $zero, 0x7F
/* 3DA28 8003CE28 00601025 */  or         $v0, $v1, $zero
/* 3DA2C 8003CE2C 00084BC0 */  sll        $t1, $t0, 15
/* 3DA30 8003CE30 01284823 */  subu       $t1, $t1, $t0
/* 3DA34 8003CE34 0121001A */  div        $zero, $t1, $at
/* 3DA38 8003CE38 00005012 */  mflo       $t2
/* 3DA3C 8003CE3C A48A002C */  sh         $t2, 0x2C($a0)
/* 3DA40 8003CE40 03E00008 */  jr         $ra
/* 3DA44 8003CE44 00000000 */   nop
.L8003CE48:
/* 3DA48 8003CE48 24630001 */  addiu      $v1, $v1, 0x1
/* 3DA4C 8003CE4C 00035C00 */  sll        $t3, $v1, 16
/* 3DA50 8003CE50 000B1C03 */  sra        $v1, $t3, 16
/* 3DA54 8003CE54 0066082A */  slt        $at, $v1, $a2
/* 3DA58 8003CE58 1420FFE2 */  bnez       $at, .L8003CDE4
/* 3DA5C 8003CE5C 00000000 */   nop
.L8003CE60:
/* 3DA60 8003CE60 2402FFFF */  addiu      $v0, $zero, -0x1
/* 3DA64 8003CE64 03E00008 */  jr         $ra
/* 3DA68 8003CE68 00000000 */   nop
/* 3DA6C 8003CE6C 00000000 */  nop
