.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.17.3 */

glabel func_8003CF20
/* 3DB20 8003CF20 27BDFFD0 */  addiu      $sp, $sp, -0x30
/* 3DB24 8003CF24 AFBF0014 */  sw         $ra, 0x14($sp)
/* 3DB28 8003CF28 AFA50034 */  sw         $a1, 0x34($sp)
/* 3DB2C 8003CF2C 8C820040 */  lw         $v0, 0x40($a0)
/* 3DB30 8003CF30 240E0008 */  addiu      $t6, $zero, 0x8
/* 3DB34 8003CF34 A7AE0020 */  sh         $t6, 0x20($sp)
/* 3DB38 8003CF38 8C8F003C */  lw         $t7, 0x3C($a0)
/* 3DB3C 8003CF3C 00A04025 */  or         $t0, $a1, $zero
/* 3DB40 8003CF40 A3A80028 */  sb         $t0, 0x28($sp)
/* 3DB44 8003CF44 000FC080 */  sll        $t8, $t7, 2
/* 3DB48 8003CF48 030FC023 */  subu       $t8, $t8, $t7
/* 3DB4C 8003CF4C 0018C100 */  sll        $t8, $t8, 4
/* 3DB50 8003CF50 0302C821 */  addu       $t9, $t8, $v0
/* 3DB54 8003CF54 AFB90024 */  sw         $t9, 0x24($sp)
/* 3DB58 8003CF58 27A50020 */  addiu      $a1, $sp, 0x20
/* 3DB5C 8003CF5C 24840014 */  addiu      $a0, $a0, 0x14
/* 3DB60 8003CF60 0C010893 */  jal        func_8004224C
/* 3DB64 8003CF64 00003025 */   or        $a2, $zero, $zero
/* 3DB68 8003CF68 8FBF0014 */  lw         $ra, 0x14($sp)
/* 3DB6C 8003CF6C 27BD0030 */  addiu      $sp, $sp, 0x30
/* 3DB70 8003CF70 03E00008 */  jr         $ra
/* 3DB74 8003CF74 00000000 */   nop
/* 3DB78 8003CF78 00000000 */  nop
/* 3DB7C 8003CF7C 00000000 */  nop
