.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.17.3 */

glabel func_8003CFD0
/* 3DBD0 8003CFD0 27BDFFD0 */  addiu      $sp, $sp, -0x30
/* 3DBD4 8003CFD4 AFBF0014 */  sw         $ra, 0x14($sp)
/* 3DBD8 8003CFD8 8C820040 */  lw         $v0, 0x40($a0)
/* 3DBDC 8003CFDC 240E0004 */  addiu      $t6, $zero, 0x4
/* 3DBE0 8003CFE0 A7AE0020 */  sh         $t6, 0x20($sp)
/* 3DBE4 8003CFE4 8C8F003C */  lw         $t7, 0x3C($a0)
/* 3DBE8 8003CFE8 44856000 */  mtc1       $a1, $f12
/* 3DBEC 8003CFEC 27A50020 */  addiu      $a1, $sp, 0x20
/* 3DBF0 8003CFF0 000FC080 */  sll        $t8, $t7, 2
/* 3DBF4 8003CFF4 030FC023 */  subu       $t8, $t8, $t7
/* 3DBF8 8003CFF8 0018C100 */  sll        $t8, $t8, 4
/* 3DBFC 8003CFFC 0302C821 */  addu       $t9, $t8, $v0
/* 3DC00 8003D000 AFB90024 */  sw         $t9, 0x24($sp)
/* 3DC04 8003D004 24840014 */  addiu      $a0, $a0, 0x14
/* 3DC08 8003D008 00003025 */  or         $a2, $zero, $zero
/* 3DC0C 8003D00C 0C010893 */  jal        func_8004224C
/* 3DC10 8003D010 E7AC0028 */   swc1      $f12, 0x28($sp)
/* 3DC14 8003D014 8FBF0014 */  lw         $ra, 0x14($sp)
/* 3DC18 8003D018 27BD0030 */  addiu      $sp, $sp, 0x30
/* 3DC1C 8003D01C 03E00008 */  jr         $ra
/* 3DC20 8003D020 00000000 */   nop
/* 3DC24 8003D024 00000000 */  nop
/* 3DC28 8003D028 00000000 */  nop
/* 3DC2C 8003D02C 00000000 */  nop
