.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.17.3 */

glabel func_8003D8D0
/* 3E4D0 8003D8D0 27BDFFF8 */  addiu      $sp, $sp, -0x8
/* 3E4D4 8003D8D4 AFA40008 */  sw         $a0, 0x8($sp)
/* 3E4D8 8003D8D8 AFA5000C */  sw         $a1, 0xC($sp)
/* 3E4DC 8003D8DC AFA60010 */  sw         $a2, 0x10($sp)
/* 3E4E0 8003D8E0 AFA70014 */  sw         $a3, 0x14($sp)
/* 3E4E4 8003D8E4 03E00008 */  jr         $ra
/* 3E4E8 8003D8E8 27BD0008 */   addiu     $sp, $sp, 0x8

glabel func_8003D8EC
/* 3E4EC 8003D8EC 27BDFFF8 */  addiu      $sp, $sp, -0x8
/* 3E4F0 8003D8F0 AFA40008 */  sw         $a0, 0x8($sp)
/* 3E4F4 8003D8F4 AFA5000C */  sw         $a1, 0xC($sp)
/* 3E4F8 8003D8F8 AFA60010 */  sw         $a2, 0x10($sp)
/* 3E4FC 8003D8FC AFA70014 */  sw         $a3, 0x14($sp)
/* 3E500 8003D900 03E00008 */  jr         $ra
/* 3E504 8003D904 27BD0008 */   addiu     $sp, $sp, 0x8
/* 3E508 8003D908 00000000 */  nop
/* 3E50C 8003D90C 00000000 */  nop
