.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.10.1 */

glabel func_8003E220
/* 3EE20 8003E220 27BDFD68 */  addiu      $sp, $sp, -0x298
/* 3EE24 8003E224 AFB70040 */  sw         $s7, 0x40($sp)
/* 3EE28 8003E228 AFB6003C */  sw         $s6, 0x3C($sp)
/* 3EE2C 8003E22C AFB50038 */  sw         $s5, 0x38($sp)
/* 3EE30 8003E230 AFB30030 */  sw         $s3, 0x30($sp)
/* 3EE34 8003E234 AFA5029C */  sw         $a1, 0x29C($sp)
/* 3EE38 8003E238 30AEFFFF */  andi       $t6, $a1, 0xFFFF
/* 3EE3C 8003E23C 01C02825 */  or         $a1, $t6, $zero
/* 3EE40 8003E240 00809825 */  or         $s3, $a0, $zero
/* 3EE44 8003E244 AFBF0044 */  sw         $ra, 0x44($sp)
/* 3EE48 8003E248 AFB40034 */  sw         $s4, 0x34($sp)
/* 3EE4C 8003E24C AFB2002C */  sw         $s2, 0x2C($sp)
/* 3EE50 8003E250 AFB10028 */  sw         $s1, 0x28($sp)
/* 3EE54 8003E254 AFB00024 */  sw         $s0, 0x24($sp)
/* 3EE58 8003E258 AFA702A4 */  sw         $a3, 0x2A4($sp)
/* 3EE5C 8003E25C 0000B025 */  or         $s6, $zero, $zero
/* 3EE60 8003E260 0000B825 */  or         $s7, $zero, $zero
/* 3EE64 8003E264 11C00003 */  beqz       $t6, .L8003E274
/* 3EE68 8003E268 0000A825 */   or        $s5, $zero, $zero
/* 3EE6C 8003E26C 14C00003 */  bnez       $a2, .L8003E27C
/* 3EE70 8003E270 8FB102AC */   lw        $s1, 0x2AC($sp)
.L8003E274:
/* 3EE74 8003E274 100000AC */  b          .L8003E528
/* 3EE78 8003E278 24020005 */   addiu     $v0, $zero, 0x5
.L8003E27C:
/* 3EE7C 8003E27C 263000FF */  addiu      $s0, $s1, 0xFF
/* 3EE80 8003E280 8FB802A8 */  lw         $t8, 0x2A8($sp)
/* 3EE84 8003E284 8FB902B0 */  lw         $t9, 0x2B0($sp)
/* 3EE88 8003E288 06010003 */  bgez       $s0, .L8003E298
/* 3EE8C 8003E28C 00107A03 */   sra       $t7, $s0, 8
/* 3EE90 8003E290 260100FF */  addiu      $at, $s0, 0xFF
/* 3EE94 8003E294 00017A03 */  sra        $t7, $at, 8
.L8003E298:
/* 3EE98 8003E298 01E08025 */  or         $s0, $t7, $zero
/* 3EE9C 8003E29C 01E0A025 */  or         $s4, $t7, $zero
/* 3EEA0 8003E2A0 02602025 */  or         $a0, $s3, $zero
/* 3EEA4 8003E2A4 8FA702A4 */  lw         $a3, 0x2A4($sp)
/* 3EEA8 8003E2A8 A7A5029E */  sh         $a1, 0x29E($sp)
/* 3EEAC 8003E2AC AFA602A0 */  sw         $a2, 0x2A0($sp)
/* 3EEB0 8003E2B0 AFB80010 */  sw         $t8, 0x10($sp)
/* 3EEB4 8003E2B4 0C0122F8 */  jal        func_80048BE0
/* 3EEB8 8003E2B8 AFB90014 */   sw        $t9, 0x14($sp)
/* 3EEBC 8003E2BC 10400005 */  beqz       $v0, .L8003E2D4
/* 3EEC0 8003E2C0 24010005 */   addiu     $at, $zero, 0x5
/* 3EEC4 8003E2C4 50410004 */  beql       $v0, $at, .L8003E2D8
/* 3EEC8 8003E2C8 8FA802B0 */   lw        $t0, 0x2B0($sp)
/* 3EECC 8003E2CC 10000097 */  b          .L8003E52C
/* 3EED0 8003E2D0 8FBF0044 */   lw        $ra, 0x44($sp)
.L8003E2D4:
/* 3EED4 8003E2D4 8FA802B0 */  lw         $t0, 0x2B0($sp)
.L8003E2D8:
/* 3EED8 8003E2D8 2401FFFF */  addiu      $at, $zero, -0x1
/* 3EEDC 8003E2DC 02602025 */  or         $a0, $s3, $zero
/* 3EEE0 8003E2E0 8D090000 */  lw         $t1, 0x0($t0)
/* 3EEE4 8003E2E4 11210003 */  beq        $t1, $at, .L8003E2F4
/* 3EEE8 8003E2E8 00000000 */   nop
/* 3EEEC 8003E2EC 1000008E */  b          .L8003E528
/* 3EEF0 8003E2F0 24020009 */   addiu     $v0, $zero, 0x9
.L8003E2F4:
/* 3EEF4 8003E2F4 0C00F820 */  jal        func_8003E080
/* 3EEF8 8003E2F8 27A50054 */   addiu     $a1, $sp, 0x54
/* 3EEFC 8003E2FC 8FAA0054 */  lw         $t2, 0x54($sp)
/* 3EF00 8003E300 0151082A */  slt        $at, $t2, $s1
/* 3EF04 8003E304 10200003 */  beqz       $at, .L8003E314
/* 3EF08 8003E308 00000000 */   nop
/* 3EF0C 8003E30C 10000086 */  b          .L8003E528
/* 3EF10 8003E310 24020007 */   addiu     $v0, $zero, 0x7
.L8003E314:
/* 3EF14 8003E314 16000003 */  bnez       $s0, .L8003E324
/* 3EF18 8003E318 02602025 */   or        $a0, $s3, $zero
/* 3EF1C 8003E31C 10000082 */  b          .L8003E528
/* 3EF20 8003E320 24020005 */   addiu     $v0, $zero, 0x5
.L8003E324:
/* 3EF24 8003E324 8FAB02B0 */  lw         $t3, 0x2B0($sp)
/* 3EF28 8003E328 00002825 */  or         $a1, $zero, $zero
/* 3EF2C 8003E32C 00003025 */  or         $a2, $zero, $zero
/* 3EF30 8003E330 00003825 */  or         $a3, $zero, $zero
/* 3EF34 8003E334 AFA00010 */  sw         $zero, 0x10($sp)
/* 3EF38 8003E338 0C0122F8 */  jal        func_80048BE0
/* 3EF3C 8003E33C AFAB0014 */   sw        $t3, 0x14($sp)
/* 3EF40 8003E340 10400005 */  beqz       $v0, .L8003E358
/* 3EF44 8003E344 24010005 */   addiu     $at, $zero, 0x5
/* 3EF48 8003E348 50410004 */  beql       $v0, $at, .L8003E35C
/* 3EF4C 8003E34C 8FAC02B0 */   lw        $t4, 0x2B0($sp)
/* 3EF50 8003E350 10000076 */  b          .L8003E52C
/* 3EF54 8003E354 8FBF0044 */   lw        $ra, 0x44($sp)
.L8003E358:
/* 3EF58 8003E358 8FAC02B0 */  lw         $t4, 0x2B0($sp)
.L8003E35C:
/* 3EF5C 8003E35C 2401FFFF */  addiu      $at, $zero, -0x1
/* 3EF60 8003E360 8D8D0000 */  lw         $t5, 0x0($t4)
/* 3EF64 8003E364 55A10004 */  bnel       $t5, $at, .L8003E378
/* 3EF68 8003E368 926E0064 */   lbu       $t6, 0x64($s3)
/* 3EF6C 8003E36C 1000006E */  b          .L8003E528
/* 3EF70 8003E370 24020008 */   addiu     $v0, $zero, 0x8
/* 3EF74 8003E374 926E0064 */  lbu        $t6, 0x64($s3)
.L8003E378:
/* 3EF78 8003E378 00008025 */  or         $s0, $zero, $zero
/* 3EF7C 8003E37C 27B20180 */  addiu      $s2, $sp, 0x180
/* 3EF80 8003E380 19C00049 */  blez       $t6, .L8003E4A8
/* 3EF84 8003E384 27B10080 */   addiu     $s1, $sp, 0x80
.L8003E388:
/* 3EF88 8003E388 02602025 */  or         $a0, $s3, $zero
/* 3EF8C 8003E38C 02402825 */  or         $a1, $s2, $zero
/* 3EF90 8003E390 00003025 */  or         $a2, $zero, $zero
/* 3EF94 8003E394 0C011E85 */  jal        func_80047A14
/* 3EF98 8003E398 320700FF */   andi      $a3, $s0, 0xFF
/* 3EF9C 8003E39C 10400003 */  beqz       $v0, .L8003E3AC
/* 3EFA0 8003E3A0 02602025 */   or        $a0, $s3, $zero
/* 3EFA4 8003E3A4 10000061 */  b          .L8003E52C
/* 3EFA8 8003E3A8 8FBF0044 */   lw        $ra, 0x44($sp)
.L8003E3AC:
/* 3EFAC 8003E3AC 27AF0290 */  addiu      $t7, $sp, 0x290
/* 3EFB0 8003E3B0 27B8028C */  addiu      $t8, $sp, 0x28C
/* 3EFB4 8003E3B4 AFB80018 */  sw         $t8, 0x18($sp)
/* 3EFB8 8003E3B8 AFAF0014 */  sw         $t7, 0x14($sp)
/* 3EFBC 8003E3BC 02402825 */  or         $a1, $s2, $zero
/* 3EFC0 8003E3C0 02803025 */  or         $a2, $s4, $zero
/* 3EFC4 8003E3C4 27A70294 */  addiu      $a3, $sp, 0x294
/* 3EFC8 8003E3C8 0C00F955 */  jal        func_8003E554
/* 3EFCC 8003E3CC AFB00010 */   sw        $s0, 0x10($sp)
/* 3EFD0 8003E3D0 10400003 */  beqz       $v0, .L8003E3E0
/* 3EFD4 8003E3D4 8FA30294 */   lw        $v1, 0x294($sp)
/* 3EFD8 8003E3D8 10000054 */  b          .L8003E52C
/* 3EFDC 8003E3DC 8FBF0044 */   lw        $ra, 0x44($sp)
.L8003E3E0:
/* 3EFE0 8003E3E0 2401FFFF */  addiu      $at, $zero, -0x1
/* 3EFE4 8003E3E4 5061002B */  beql       $v1, $at, .L8003E494
/* 3EFE8 8003E3E8 926B0064 */   lbu       $t3, 0x64($s3)
/* 3EFEC 8003E3EC 16A00004 */  bnez       $s5, .L8003E400
/* 3EFF0 8003E3F0 0016C840 */   sll       $t9, $s6, 1
/* 3EFF4 8003E3F4 A3A30051 */  sb         $v1, 0x51($sp)
/* 3EFF8 8003E3F8 1000000D */  b          .L8003E430
/* 3EFFC 8003E3FC A3B00050 */   sb        $s0, 0x50($sp)
.L8003E400:
/* 3F000 8003E400 02391021 */  addu       $v0, $s1, $t9
/* 3F004 8003E404 A0500000 */  sb         $s0, 0x0($v0)
/* 3F008 8003E408 A0430001 */  sb         $v1, 0x1($v0)
/* 3F00C 8003E40C 02602025 */  or         $a0, $s3, $zero
/* 3F010 8003E410 02202825 */  or         $a1, $s1, $zero
/* 3F014 8003E414 24060001 */  addiu      $a2, $zero, 0x1
/* 3F018 8003E418 0C011E85 */  jal        func_80047A14
/* 3F01C 8003E41C 32E700FF */   andi      $a3, $s7, 0xFF
/* 3F020 8003E420 50400004 */  beql       $v0, $zero, .L8003E434
/* 3F024 8003E424 8FA80290 */   lw        $t0, 0x290($sp)
/* 3F028 8003E428 10000040 */  b          .L8003E52C
/* 3F02C 8003E42C 8FBF0044 */   lw        $ra, 0x44($sp)
.L8003E430:
/* 3F030 8003E430 8FA80290 */  lw         $t0, 0x290($sp)
.L8003E434:
/* 3F034 8003E434 02402025 */  or         $a0, $s2, $zero
/* 3F038 8003E438 02202825 */  or         $a1, $s1, $zero
/* 3F03C 8003E43C 0114082A */  slt        $at, $t0, $s4
/* 3F040 8003E440 5020000A */  beql       $at, $zero, .L8003E46C
/* 3F044 8003E444 0000A025 */   or        $s4, $zero, $zero
/* 3F048 8003E448 0C010194 */  jal        func_80040650
/* 3F04C 8003E44C 24060100 */   addiu     $a2, $zero, 0x100
/* 3F050 8003E450 8FA90290 */  lw         $t1, 0x290($sp)
/* 3F054 8003E454 8FB6028C */  lw         $s6, 0x28C($sp)
/* 3F058 8003E458 321700FF */  andi       $s7, $s0, 0xFF
/* 3F05C 8003E45C 26B50001 */  addiu      $s5, $s5, 0x1
/* 3F060 8003E460 1000000B */  b          .L8003E490
/* 3F064 8003E464 0289A023 */   subu      $s4, $s4, $t1
/* 3F068 8003E468 0000A025 */  or         $s4, $zero, $zero
.L8003E46C:
/* 3F06C 8003E46C 02602025 */  or         $a0, $s3, $zero
/* 3F070 8003E470 02402825 */  or         $a1, $s2, $zero
/* 3F074 8003E474 24060001 */  addiu      $a2, $zero, 0x1
/* 3F078 8003E478 0C011E85 */  jal        func_80047A14
/* 3F07C 8003E47C 320700FF */   andi      $a3, $s0, 0xFF
/* 3F080 8003E480 10400009 */  beqz       $v0, .L8003E4A8
/* 3F084 8003E484 00000000 */   nop
/* 3F088 8003E488 10000028 */  b          .L8003E52C
/* 3F08C 8003E48C 8FBF0044 */   lw        $ra, 0x44($sp)
.L8003E490:
/* 3F090 8003E490 926B0064 */  lbu        $t3, 0x64($s3)
.L8003E494:
/* 3F094 8003E494 26100001 */  addiu      $s0, $s0, 0x1
/* 3F098 8003E498 320A00FF */  andi       $t2, $s0, 0xFF
/* 3F09C 8003E49C 014B082A */  slt        $at, $t2, $t3
/* 3F0A0 8003E4A0 1420FFB9 */  bnez       $at, .L8003E388
/* 3F0A4 8003E4A4 01408025 */   or        $s0, $t2, $zero
.L8003E4A8:
/* 3F0A8 8003E4A8 1E800004 */  bgtz       $s4, .L8003E4BC
/* 3F0AC 8003E4AC 8FA30294 */   lw        $v1, 0x294($sp)
/* 3F0B0 8003E4B0 2401FFFF */  addiu      $at, $zero, -0x1
/* 3F0B4 8003E4B4 14610003 */  bne        $v1, $at, .L8003E4C4
/* 3F0B8 8003E4B8 97AC0050 */   lhu       $t4, 0x50($sp)
.L8003E4BC:
/* 3F0BC 8003E4BC 1000001A */  b          .L8003E528
/* 3F0C0 8003E4C0 24020003 */   addiu     $v0, $zero, 0x3
.L8003E4C4:
/* 3F0C4 8003E4C4 97AD029E */  lhu        $t5, 0x29E($sp)
/* 3F0C8 8003E4C8 8FAE02A0 */  lw         $t6, 0x2A0($sp)
/* 3F0CC 8003E4CC A7AC0066 */  sh         $t4, 0x66($sp)
/* 3F0D0 8003E4D0 A7A0006A */  sh         $zero, 0x6A($sp)
/* 3F0D4 8003E4D4 8FA402A4 */  lw         $a0, 0x2A4($sp)
/* 3F0D8 8003E4D8 27A50070 */  addiu      $a1, $sp, 0x70
/* 3F0DC 8003E4DC 24060010 */  addiu      $a2, $zero, 0x10
/* 3F0E0 8003E4E0 A7AD0064 */  sh         $t5, 0x64($sp)
/* 3F0E4 8003E4E4 0C010194 */  jal        func_80040650
/* 3F0E8 8003E4E8 AFAE0060 */   sw        $t6, 0x60($sp)
/* 3F0EC 8003E4EC 8FA402A8 */  lw         $a0, 0x2A8($sp)
/* 3F0F0 8003E4F0 27A5006C */  addiu      $a1, $sp, 0x6C
/* 3F0F4 8003E4F4 0C010194 */  jal        func_80040650
/* 3F0F8 8003E4F8 24060004 */   addiu     $a2, $zero, 0x4
/* 3F0FC 8003E4FC 8FAF02B0 */  lw         $t7, 0x2B0($sp)
/* 3F100 8003E500 8E79005C */  lw         $t9, 0x5C($s3)
/* 3F104 8003E504 8E640004 */  lw         $a0, 0x4($s3)
/* 3F108 8003E508 8DF80000 */  lw         $t8, 0x0($t7)
/* 3F10C 8003E50C 8E650008 */  lw         $a1, 0x8($s3)
/* 3F110 8003E510 AFA00010 */  sw         $zero, 0x10($sp)
/* 3F114 8003E514 03193021 */  addu       $a2, $t8, $t9
/* 3F118 8003E518 30C8FFFF */  andi       $t0, $a2, 0xFFFF
/* 3F11C 8003E51C 01003025 */  or         $a2, $t0, $zero
/* 3F120 8003E520 0C01222C */  jal        func_800488B0
/* 3F124 8003E524 27A70060 */   addiu     $a3, $sp, 0x60
.L8003E528:
/* 3F128 8003E528 8FBF0044 */  lw         $ra, 0x44($sp)
.L8003E52C:
/* 3F12C 8003E52C 8FB00024 */  lw         $s0, 0x24($sp)
/* 3F130 8003E530 8FB10028 */  lw         $s1, 0x28($sp)
/* 3F134 8003E534 8FB2002C */  lw         $s2, 0x2C($sp)
/* 3F138 8003E538 8FB30030 */  lw         $s3, 0x30($sp)
/* 3F13C 8003E53C 8FB40034 */  lw         $s4, 0x34($sp)
/* 3F140 8003E540 8FB50038 */  lw         $s5, 0x38($sp)
/* 3F144 8003E544 8FB6003C */  lw         $s6, 0x3C($sp)
/* 3F148 8003E548 8FB70040 */  lw         $s7, 0x40($sp)
/* 3F14C 8003E54C 03E00008 */  jr         $ra
/* 3F150 8003E550 27BD0298 */   addiu     $sp, $sp, 0x298

glabel func_8003E554
/* 3F154 8003E554 27BDFFF0 */  addiu      $sp, $sp, -0x10
/* 3F158 8003E558 AFB00008 */  sw         $s0, 0x8($sp)
/* 3F15C 8003E55C 93B00023 */  lbu        $s0, 0x23($sp)
/* 3F160 8003E560 AFB1000C */  sw         $s1, 0xC($sp)
/* 3F164 8003E564 00C08825 */  or         $s1, $a2, $zero
/* 3F168 8003E568 1A000003 */  blez       $s0, .L8003E578
/* 3F16C 8003E56C 240B0080 */   addiu     $t3, $zero, 0x80
/* 3F170 8003E570 10000002 */  b          .L8003E57C
/* 3F174 8003E574 24020001 */   addiu     $v0, $zero, 0x1
.L8003E578:
/* 3F178 8003E578 8C820060 */  lw         $v0, 0x60($a0)
.L8003E57C:
/* 3F17C 8003E57C 28410080 */  slti       $at, $v0, 0x80
/* 3F180 8003E580 1020000A */  beqz       $at, .L8003E5AC
/* 3F184 8003E584 00401825 */   or        $v1, $v0, $zero
/* 3F188 8003E588 00027040 */  sll        $t6, $v0, 1
/* 3F18C 8003E58C 00AE1021 */  addu       $v0, $a1, $t6
/* 3F190 8003E590 240A0003 */  addiu      $t2, $zero, 0x3
.L8003E594:
/* 3F194 8003E594 944F0000 */  lhu        $t7, 0x0($v0)
/* 3F198 8003E598 514F0005 */  beql       $t2, $t7, .L8003E5B0
/* 3F19C 8003E59C 240B0080 */   addiu     $t3, $zero, 0x80
/* 3F1A0 8003E5A0 24630001 */  addiu      $v1, $v1, 0x1
/* 3F1A4 8003E5A4 146BFFFB */  bne        $v1, $t3, .L8003E594
/* 3F1A8 8003E5A8 24420002 */   addiu     $v0, $v0, 0x2
.L8003E5AC:
/* 3F1AC 8003E5AC 240B0080 */  addiu      $t3, $zero, 0x80
.L8003E5B0:
/* 3F1B0 8003E5B0 146B0005 */  bne        $v1, $t3, .L8003E5C8
/* 3F1B4 8003E5B4 240A0003 */   addiu     $t2, $zero, 0x3
/* 3F1B8 8003E5B8 2418FFFF */  addiu      $t8, $zero, -0x1
/* 3F1BC 8003E5BC ACF80000 */  sw         $t8, 0x0($a3)
/* 3F1C0 8003E5C0 10000030 */  b          .L8003E684
/* 3F1C4 8003E5C4 00001025 */   or        $v0, $zero, $zero
.L8003E5C8:
/* 3F1C8 8003E5C8 8FA60024 */  lw         $a2, 0x24($sp)
/* 3F1CC 8003E5CC 00602025 */  or         $a0, $v1, $zero
/* 3F1D0 8003E5D0 24190001 */  addiu      $t9, $zero, 0x1
/* 3F1D4 8003E5D4 00604025 */  or         $t0, $v1, $zero
/* 3F1D8 8003E5D8 2A210002 */  slti       $at, $s1, 0x2
/* 3F1DC 8003E5DC 24630001 */  addiu      $v1, $v1, 0x1
/* 3F1E0 8003E5E0 14200018 */  bnez       $at, .L8003E644
/* 3F1E4 8003E5E4 ACD90000 */   sw        $t9, 0x0($a2)
/* 3F1E8 8003E5E8 28610080 */  slti       $at, $v1, 0x80
/* 3F1EC 8003E5EC 10200015 */  beqz       $at, .L8003E644
/* 3F1F0 8003E5F0 00036040 */   sll       $t4, $v1, 1
/* 3F1F4 8003E5F4 00AC1021 */  addu       $v0, $a1, $t4
/* 3F1F8 8003E5F8 944D0000 */  lhu        $t5, 0x0($v0)
.L8003E5FC:
/* 3F1FC 8003E5FC 00087040 */  sll        $t6, $t0, 1
/* 3F200 8003E600 00AE4821 */  addu       $t1, $a1, $t6
/* 3F204 8003E604 554D0008 */  bnel       $t2, $t5, .L8003E628
/* 3F208 8003E608 8CD90000 */   lw        $t9, 0x0($a2)
/* 3F20C 8003E60C A1300000 */  sb         $s0, 0x0($t1)
/* 3F210 8003E610 A1230001 */  sb         $v1, 0x1($t1)
/* 3F214 8003E614 8CCF0000 */  lw         $t7, 0x0($a2)
/* 3F218 8003E618 00604025 */  or         $t0, $v1, $zero
/* 3F21C 8003E61C 25F80001 */  addiu      $t8, $t7, 0x1
/* 3F220 8003E620 ACD80000 */  sw         $t8, 0x0($a2)
/* 3F224 8003E624 8CD90000 */  lw         $t9, 0x0($a2)
.L8003E628:
/* 3F228 8003E628 24630001 */  addiu      $v1, $v1, 0x1
/* 3F22C 8003E62C 24420002 */  addiu      $v0, $v0, 0x2
/* 3F230 8003E630 0331082A */  slt        $at, $t9, $s1
/* 3F234 8003E634 10200003 */  beqz       $at, .L8003E644
/* 3F238 8003E638 28610080 */   slti      $at, $v1, 0x80
/* 3F23C 8003E63C 5420FFEF */  bnel       $at, $zero, .L8003E5FC
/* 3F240 8003E640 944D0000 */   lhu       $t5, 0x0($v0)
.L8003E644:
/* 3F244 8003E644 146B0008 */  bne        $v1, $t3, .L8003E668
/* 3F248 8003E648 ACE40000 */   sw        $a0, 0x0($a3)
/* 3F24C 8003E64C 8CCC0000 */  lw         $t4, 0x0($a2)
/* 3F250 8003E650 8FAD0028 */  lw         $t5, 0x28($sp)
/* 3F254 8003E654 0191082A */  slt        $at, $t4, $s1
/* 3F258 8003E658 50200004 */  beql       $at, $zero, .L8003E66C
/* 3F25C 8003E65C 00087840 */   sll       $t7, $t0, 1
/* 3F260 8003E660 10000007 */  b          .L8003E680
/* 3F264 8003E664 ADA80000 */   sw        $t0, 0x0($t5)
.L8003E668:
/* 3F268 8003E668 00087840 */  sll        $t7, $t0, 1
.L8003E66C:
/* 3F26C 8003E66C 00AFC021 */  addu       $t8, $a1, $t7
/* 3F270 8003E670 240E0001 */  addiu      $t6, $zero, 0x1
/* 3F274 8003E674 A70E0000 */  sh         $t6, 0x0($t8)
/* 3F278 8003E678 8FB90028 */  lw         $t9, 0x28($sp)
/* 3F27C 8003E67C AF200000 */  sw         $zero, 0x0($t9)
.L8003E680:
/* 3F280 8003E680 00001025 */  or         $v0, $zero, $zero
.L8003E684:
/* 3F284 8003E684 8FB00008 */  lw         $s0, 0x8($sp)
/* 3F288 8003E688 8FB1000C */  lw         $s1, 0xC($sp)
/* 3F28C 8003E68C 03E00008 */  jr         $ra
/* 3F290 8003E690 27BD0010 */   addiu     $sp, $sp, 0x10
/* 3F294 8003E694 00000000 */  nop
/* 3F298 8003E698 00000000 */  nop
/* 3F29C 8003E69C 00000000 */  nop
