.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.17.3 */

glabel func_8003E910
/* 3F510 8003E910 27BDFFE0 */  addiu      $sp, $sp, -0x20
/* 3F514 8003E914 AFBF001C */  sw         $ra, 0x1C($sp)
/* 3F518 8003E918 AFB00018 */  sw         $s0, 0x18($sp)
/* 3F51C 8003E91C AFA50024 */  sw         $a1, 0x24($sp)
/* 3F520 8003E920 AFA60028 */  sw         $a2, 0x28($sp)
/* 3F524 8003E924 90AF0000 */  lbu        $t7, 0x0($a1)
/* 3F528 8003E928 90E20000 */  lbu        $v0, 0x0($a3)
/* 3F52C 8003E92C 00E08025 */  or         $s0, $a3, $zero
/* 3F530 8003E930 00A07025 */  or         $t6, $a1, $zero
/* 3F534 8003E934 104F000A */  beq        $v0, $t7, .L8003E960
/* 3F538 8003E938 00003025 */   or        $a2, $zero, $zero
/* 3F53C 8003E93C A0A20000 */  sb         $v0, 0x0($a1)
/* 3F540 8003E940 91C70000 */  lbu        $a3, 0x0($t6)
/* 3F544 8003E944 AFA40020 */  sw         $a0, 0x20($sp)
/* 3F548 8003E948 0C011E85 */  jal        func_80047A14
/* 3F54C 8003E94C 8FA50028 */   lw        $a1, 0x28($sp)
/* 3F550 8003E950 10400003 */  beqz       $v0, .L8003E960
/* 3F554 8003E954 8FA40020 */   lw        $a0, 0x20($sp)
/* 3F558 8003E958 1000001E */  b          .L8003E9D4
/* 3F55C 8003E95C 8FBF001C */   lw        $ra, 0x1C($sp)
.L8003E960:
/* 3F560 8003E960 92190001 */  lbu        $t9, 0x1($s0)
/* 3F564 8003E964 8FB80028 */  lw         $t8, 0x28($sp)
/* 3F568 8003E968 00194040 */  sll        $t0, $t9, 1
/* 3F56C 8003E96C 03084821 */  addu       $t1, $t8, $t0
/* 3F570 8003E970 95210000 */  lhu        $at, 0x0($t1)
/* 3F574 8003E974 A6010000 */  sh         $at, 0x0($s0)
/* 3F578 8003E978 8C8C0060 */  lw         $t4, 0x60($a0)
/* 3F57C 8003E97C 3023FFFF */  andi       $v1, $at, 0xFFFF
/* 3F580 8003E980 006C082A */  slt        $at, $v1, $t4
/* 3F584 8003E984 5420000C */  bnel       $at, $zero, .L8003E9B8
/* 3F588 8003E988 24010001 */   addiu     $at, $zero, 0x1
/* 3F58C 8003E98C 920D0000 */  lbu        $t5, 0x0($s0)
/* 3F590 8003E990 908F0064 */  lbu        $t7, 0x64($a0)
/* 3F594 8003E994 01AF082A */  slt        $at, $t5, $t7
/* 3F598 8003E998 50200007 */  beql       $at, $zero, .L8003E9B8
/* 3F59C 8003E99C 24010001 */   addiu     $at, $zero, 0x1
/* 3F5A0 8003E9A0 92020001 */  lbu        $v0, 0x1($s0)
/* 3F5A4 8003E9A4 18400003 */  blez       $v0, .L8003E9B4
/* 3F5A8 8003E9A8 28410080 */   slti      $at, $v0, 0x80
/* 3F5AC 8003E9AC 14200008 */  bnez       $at, .L8003E9D0
/* 3F5B0 8003E9B0 00001025 */   or        $v0, $zero, $zero
.L8003E9B4:
/* 3F5B4 8003E9B4 24010001 */  addiu      $at, $zero, 0x1
.L8003E9B8:
/* 3F5B8 8003E9B8 14610003 */  bne        $v1, $at, .L8003E9C8
/* 3F5BC 8003E9BC 00000000 */   nop
/* 3F5C0 8003E9C0 10000003 */  b          .L8003E9D0
/* 3F5C4 8003E9C4 24020005 */   addiu     $v0, $zero, 0x5
.L8003E9C8:
/* 3F5C8 8003E9C8 10000001 */  b          .L8003E9D0
/* 3F5CC 8003E9CC 24020003 */   addiu     $v0, $zero, 0x3
.L8003E9D0:
/* 3F5D0 8003E9D0 8FBF001C */  lw         $ra, 0x1C($sp)
.L8003E9D4:
/* 3F5D4 8003E9D4 8FB00018 */  lw         $s0, 0x18($sp)
/* 3F5D8 8003E9D8 27BD0020 */  addiu      $sp, $sp, 0x20
/* 3F5DC 8003E9DC 03E00008 */  jr         $ra
/* 3F5E0 8003E9E0 00000000 */   nop

glabel func_8003E9E4
/* 3F5E4 8003E9E4 27BDFE90 */  addiu      $sp, $sp, -0x170
/* 3F5E8 8003E9E8 AFBF002C */  sw         $ra, 0x2C($sp)
/* 3F5EC 8003E9EC AFB30028 */  sw         $s3, 0x28($sp)
/* 3F5F0 8003E9F0 AFB20024 */  sw         $s2, 0x24($sp)
/* 3F5F4 8003E9F4 AFB10020 */  sw         $s1, 0x20($sp)
/* 3F5F8 8003E9F8 AFB0001C */  sw         $s0, 0x1C($sp)
/* 3F5FC 8003E9FC AFA60178 */  sw         $a2, 0x178($sp)
/* 3F600 8003EA00 8C8E0050 */  lw         $t6, 0x50($a0)
/* 3F604 8003EA04 30D000FF */  andi       $s0, $a2, 0xFF
/* 3F608 8003EA08 00E08825 */  or         $s1, $a3, $zero
/* 3F60C 8003EA0C 00AE082A */  slt        $at, $a1, $t6
/* 3F610 8003EA10 10200003 */  beqz       $at, .L8003EA20
/* 3F614 8003EA14 00809025 */   or        $s2, $a0, $zero
/* 3F618 8003EA18 04A10003 */  bgez       $a1, .L8003EA28
/* 3F61C 8003EA1C 8FA20180 */   lw        $v0, 0x180($sp)
.L8003EA20:
/* 3F620 8003EA20 100000C5 */  b          .L8003ED38
/* 3F624 8003EA24 24020005 */   addiu     $v0, $zero, 0x5
.L8003EA28:
/* 3F628 8003EA28 18400003 */  blez       $v0, .L8003EA38
/* 3F62C 8003EA2C 304F001F */   andi      $t7, $v0, 0x1F
/* 3F630 8003EA30 11E00003 */  beqz       $t7, .L8003EA40
/* 3F634 8003EA34 00000000 */   nop
.L8003EA38:
/* 3F638 8003EA38 100000BF */  b          .L8003ED38
/* 3F63C 8003EA3C 24020005 */   addiu     $v0, $zero, 0x5
.L8003EA40:
/* 3F640 8003EA40 06200003 */  bltz       $s1, .L8003EA50
/* 3F644 8003EA44 3238001F */   andi      $t8, $s1, 0x1F
/* 3F648 8003EA48 53000004 */  beql       $t8, $zero, .L8003EA5C
/* 3F64C 8003EA4C 8E590000 */   lw        $t9, 0x0($s2)
.L8003EA50:
/* 3F650 8003EA50 100000B9 */  b          .L8003ED38
/* 3F654 8003EA54 24020005 */   addiu     $v0, $zero, 0x5
/* 3F658 8003EA58 8E590000 */  lw         $t9, 0x0($s2)
.L8003EA5C:
/* 3F65C 8003EA5C 02402025 */  or         $a0, $s2, $zero
/* 3F660 8003EA60 33280001 */  andi       $t0, $t9, 0x1
/* 3F664 8003EA64 15000003 */  bnez       $t0, .L8003EA74
/* 3F668 8003EA68 00000000 */   nop
/* 3F66C 8003EA6C 100000B2 */  b          .L8003ED38
/* 3F670 8003EA70 24020005 */   addiu     $v0, $zero, 0x5
.L8003EA74:
/* 3F674 8003EA74 0C011E50 */  jal        func_80047940
/* 3F678 8003EA78 AFA50174 */   sw        $a1, 0x174($sp)
/* 3F67C 8003EA7C 24010002 */  addiu      $at, $zero, 0x2
/* 3F680 8003EA80 54410004 */  bnel       $v0, $at, .L8003EA94
/* 3F684 8003EA84 92490065 */   lbu       $t1, 0x65($s2)
/* 3F688 8003EA88 100000AB */  b          .L8003ED38
/* 3F68C 8003EA8C 24020002 */   addiu     $v0, $zero, 0x2
/* 3F690 8003EA90 92490065 */  lbu        $t1, 0x65($s2)
.L8003EA94:
/* 3F694 8003EA94 02402025 */  or         $a0, $s2, $zero
/* 3F698 8003EA98 51200008 */  beql       $t1, $zero, .L8003EABC
/* 3F69C 8003EA9C 8E4A005C */   lw        $t2, 0x5C($s2)
/* 3F6A0 8003EAA0 0C011BB0 */  jal        func_80046EC0
/* 3F6A4 8003EAA4 00002825 */   or        $a1, $zero, $zero
/* 3F6A8 8003EAA8 50400004 */  beql       $v0, $zero, .L8003EABC
/* 3F6AC 8003EAAC 8E4A005C */   lw        $t2, 0x5C($s2)
/* 3F6B0 8003EAB0 100000A2 */  b          .L8003ED3C
/* 3F6B4 8003EAB4 8FBF002C */   lw        $ra, 0x2C($sp)
/* 3F6B8 8003EAB8 8E4A005C */  lw         $t2, 0x5C($s2)
.L8003EABC:
/* 3F6BC 8003EABC 8FAB0174 */  lw         $t3, 0x174($sp)
/* 3F6C0 8003EAC0 8E440004 */  lw         $a0, 0x4($s2)
/* 3F6C4 8003EAC4 8E450008 */  lw         $a1, 0x8($s2)
/* 3F6C8 8003EAC8 014B3021 */  addu       $a2, $t2, $t3
/* 3F6CC 8003EACC 30CCFFFF */  andi       $t4, $a2, 0xFFFF
/* 3F6D0 8003EAD0 01803025 */  or         $a2, $t4, $zero
/* 3F6D4 8003EAD4 0C011BD0 */  jal        func_80046F40
/* 3F6D8 8003EAD8 27A7014C */   addiu     $a3, $sp, 0x14C
/* 3F6DC 8003EADC 10400003 */  beqz       $v0, .L8003EAEC
/* 3F6E0 8003EAE0 97AD0150 */   lhu       $t5, 0x150($sp)
/* 3F6E4 8003EAE4 10000095 */  b          .L8003ED3C
/* 3F6E8 8003EAE8 8FBF002C */   lw        $ra, 0x2C($sp)
.L8003EAEC:
/* 3F6EC 8003EAEC 11A00003 */  beqz       $t5, .L8003EAFC
/* 3F6F0 8003EAF0 8FAE014C */   lw        $t6, 0x14C($sp)
/* 3F6F4 8003EAF4 15C00003 */  bnez       $t6, .L8003EB04
/* 3F6F8 8003EAF8 97AF0152 */   lhu       $t7, 0x152($sp)
.L8003EAFC:
/* 3F6FC 8003EAFC 1000008E */  b          .L8003ED38
/* 3F700 8003EB00 24020005 */   addiu     $v0, $zero, 0x5
.L8003EB04:
/* 3F704 8003EB04 8E580060 */  lw         $t8, 0x60($s2)
/* 3F708 8003EB08 93B90152 */  lbu        $t9, 0x152($sp)
/* 3F70C 8003EB0C 97AA0152 */  lhu        $t2, 0x152($sp)
/* 3F710 8003EB10 01F8082A */  slt        $at, $t7, $t8
/* 3F714 8003EB14 5420000A */  bnel       $at, $zero, .L8003EB40
/* 3F718 8003EB18 24010001 */   addiu     $at, $zero, 0x1
/* 3F71C 8003EB1C 92480064 */  lbu        $t0, 0x64($s2)
/* 3F720 8003EB20 93A90153 */  lbu        $t1, 0x153($sp)
/* 3F724 8003EB24 0328082A */  slt        $at, $t9, $t0
/* 3F728 8003EB28 50200005 */  beql       $at, $zero, .L8003EB40
/* 3F72C 8003EB2C 24010001 */   addiu     $at, $zero, 0x1
/* 3F730 8003EB30 19200002 */  blez       $t1, .L8003EB3C
/* 3F734 8003EB34 29210080 */   slti      $at, $t1, 0x80
/* 3F738 8003EB38 14200007 */  bnez       $at, .L8003EB58
.L8003EB3C:
/* 3F73C 8003EB3C 24010001 */   addiu     $at, $zero, 0x1
.L8003EB40:
/* 3F740 8003EB40 15410003 */  bne        $t2, $at, .L8003EB50
/* 3F744 8003EB44 00000000 */   nop
/* 3F748 8003EB48 1000007B */  b          .L8003ED38
/* 3F74C 8003EB4C 24020005 */   addiu     $v0, $zero, 0x5
.L8003EB50:
/* 3F750 8003EB50 10000079 */  b          .L8003ED38
/* 3F754 8003EB54 24020003 */   addiu     $v0, $zero, 0x3
.L8003EB58:
/* 3F758 8003EB58 16000007 */  bnez       $s0, .L8003EB78
/* 3F75C 8003EB5C AFB00034 */   sw        $s0, 0x34($sp)
/* 3F760 8003EB60 93AC0154 */  lbu        $t4, 0x154($sp)
/* 3F764 8003EB64 318D0002 */  andi       $t5, $t4, 0x2
/* 3F768 8003EB68 55A00004 */  bnel       $t5, $zero, .L8003EB7C
/* 3F76C 8003EB6C 97AF0152 */   lhu       $t7, 0x152($sp)
/* 3F770 8003EB70 10000071 */  b          .L8003ED38
/* 3F774 8003EB74 24020006 */   addiu     $v0, $zero, 0x6
.L8003EB78:
/* 3F778 8003EB78 97AF0152 */  lhu        $t7, 0x152($sp)
.L8003EB7C:
/* 3F77C 8003EB7C 240E00FF */  addiu      $t6, $zero, 0xFF
/* 3F780 8003EB80 A3AE003B */  sb         $t6, 0x3B($sp)
/* 3F784 8003EB84 06210003 */  bgez       $s1, .L8003EB94
/* 3F788 8003EB88 00111143 */   sra       $v0, $s1, 5
/* 3F78C 8003EB8C 2621001F */  addiu      $at, $s1, 0x1F
/* 3F790 8003EB90 00011143 */  sra        $v0, $at, 5
.L8003EB94:
/* 3F794 8003EB94 28410008 */  slti       $at, $v0, 0x8
/* 3F798 8003EB98 00408025 */  or         $s0, $v0, $zero
/* 3F79C 8003EB9C 1420000D */  bnez       $at, .L8003EBD4
/* 3F7A0 8003EBA0 A7AF0048 */   sh        $t7, 0x48($sp)
/* 3F7A4 8003EBA4 02402025 */  or         $a0, $s2, $zero
.L8003EBA8:
/* 3F7A8 8003EBA8 27A5003B */  addiu      $a1, $sp, 0x3B
/* 3F7AC 8003EBAC 27A6004C */  addiu      $a2, $sp, 0x4C
/* 3F7B0 8003EBB0 0C00FA44 */  jal        func_8003E910
/* 3F7B4 8003EBB4 27A70048 */   addiu     $a3, $sp, 0x48
/* 3F7B8 8003EBB8 10400003 */  beqz       $v0, .L8003EBC8
/* 3F7BC 8003EBBC 2610FFF8 */   addiu     $s0, $s0, -0x8
/* 3F7C0 8003EBC0 1000005E */  b          .L8003ED3C
/* 3F7C4 8003EBC4 8FBF002C */   lw        $ra, 0x2C($sp)
.L8003EBC8:
/* 3F7C8 8003EBC8 2A010008 */  slti       $at, $s0, 0x8
/* 3F7CC 8003EBCC 5020FFF6 */  beql       $at, $zero, .L8003EBA8
/* 3F7D0 8003EBD0 02402025 */   or        $a0, $s2, $zero
.L8003EBD4:
/* 3F7D4 8003EBD4 8FA20180 */  lw         $v0, 0x180($sp)
/* 3F7D8 8003EBD8 8FB10184 */  lw         $s1, 0x184($sp)
/* 3F7DC 8003EBDC 04410003 */  bgez       $v0, .L8003EBEC
/* 3F7E0 8003EBE0 0002C143 */   sra       $t8, $v0, 5
/* 3F7E4 8003EBE4 2441001F */  addiu      $at, $v0, 0x1F
/* 3F7E8 8003EBE8 0001C143 */  sra        $t8, $at, 5
.L8003EBEC:
/* 3F7EC 8003EBEC 1B000031 */  blez       $t8, .L8003ECB4
/* 3F7F0 8003EBF0 03009825 */   or        $s3, $t8, $zero
.L8003EBF4:
/* 3F7F4 8003EBF4 24010008 */  addiu      $at, $zero, 0x8
/* 3F7F8 8003EBF8 16010009 */  bne        $s0, $at, .L8003EC20
/* 3F7FC 8003EBFC 02402025 */   or        $a0, $s2, $zero
/* 3F800 8003EC00 27A5003B */  addiu      $a1, $sp, 0x3B
/* 3F804 8003EC04 27A6004C */  addiu      $a2, $sp, 0x4C
/* 3F808 8003EC08 0C00FA44 */  jal        func_8003E910
/* 3F80C 8003EC0C 27A70048 */   addiu     $a3, $sp, 0x48
/* 3F810 8003EC10 10400003 */  beqz       $v0, .L8003EC20
/* 3F814 8003EC14 00008025 */   or        $s0, $zero, $zero
/* 3F818 8003EC18 10000048 */  b          .L8003ED3C
/* 3F81C 8003EC1C 8FBF002C */   lw        $ra, 0x2C($sp)
.L8003EC20:
/* 3F820 8003EC20 93B90048 */  lbu        $t9, 0x48($sp)
/* 3F824 8003EC24 92480065 */  lbu        $t0, 0x65($s2)
/* 3F828 8003EC28 02402025 */  or         $a0, $s2, $zero
/* 3F82C 8003EC2C 53280008 */  beql       $t9, $t0, .L8003EC50
/* 3F830 8003EC30 93A90049 */   lbu       $t1, 0x49($sp)
/* 3F834 8003EC34 0C011BB0 */  jal        func_80046EC0
/* 3F838 8003EC38 03202825 */   or        $a1, $t9, $zero
/* 3F83C 8003EC3C 50400004 */  beql       $v0, $zero, .L8003EC50
/* 3F840 8003EC40 93A90049 */   lbu       $t1, 0x49($sp)
/* 3F844 8003EC44 1000003D */  b          .L8003ED3C
/* 3F848 8003EC48 8FBF002C */   lw        $ra, 0x2C($sp)
/* 3F84C 8003EC4C 93A90049 */  lbu        $t1, 0x49($sp)
.L8003EC50:
/* 3F850 8003EC50 8FAC0034 */  lw         $t4, 0x34($sp)
/* 3F854 8003EC54 02203825 */  or         $a3, $s1, $zero
/* 3F858 8003EC58 000950C0 */  sll        $t2, $t1, 3
/* 3F85C 8003EC5C 01503021 */  addu       $a2, $t2, $s0
/* 3F860 8003EC60 30CBFFFF */  andi       $t3, $a2, 0xFFFF
/* 3F864 8003EC64 15800007 */  bnez       $t4, .L8003EC84
/* 3F868 8003EC68 01603025 */   or        $a2, $t3, $zero
/* 3F86C 8003EC6C 8E440004 */  lw         $a0, 0x4($s2)
/* 3F870 8003EC70 8E450008 */  lw         $a1, 0x8($s2)
/* 3F874 8003EC74 0C011BD0 */  jal        func_80046F40
/* 3F878 8003EC78 02203825 */   or        $a3, $s1, $zero
/* 3F87C 8003EC7C 10000006 */  b          .L8003EC98
/* 3F880 8003EC80 00401825 */   or        $v1, $v0, $zero
.L8003EC84:
/* 3F884 8003EC84 8E440004 */  lw         $a0, 0x4($s2)
/* 3F888 8003EC88 8E450008 */  lw         $a1, 0x8($s2)
/* 3F88C 8003EC8C 0C01222C */  jal        func_800488B0
/* 3F890 8003EC90 AFA00010 */   sw        $zero, 0x10($sp)
/* 3F894 8003EC94 00401825 */  or         $v1, $v0, $zero
.L8003EC98:
/* 3F898 8003EC98 10400003 */  beqz       $v0, .L8003ECA8
/* 3F89C 8003EC9C 26310020 */   addiu     $s1, $s1, 0x20
/* 3F8A0 8003ECA0 10000025 */  b          .L8003ED38
/* 3F8A4 8003ECA4 00601025 */   or        $v0, $v1, $zero
.L8003ECA8:
/* 3F8A8 8003ECA8 2673FFFF */  addiu      $s3, $s3, -0x1
/* 3F8AC 8003ECAC 1660FFD1 */  bnez       $s3, .L8003EBF4
/* 3F8B0 8003ECB0 26100001 */   addiu     $s0, $s0, 0x1
.L8003ECB4:
/* 3F8B4 8003ECB4 8FAD0034 */  lw         $t5, 0x34($sp)
/* 3F8B8 8003ECB8 93A20154 */  lbu        $v0, 0x154($sp)
/* 3F8BC 8003ECBC 24010001 */  addiu      $at, $zero, 0x1
/* 3F8C0 8003ECC0 15A1001C */  bne        $t5, $at, .L8003ED34
/* 3F8C4 8003ECC4 304E0002 */   andi      $t6, $v0, 0x2
/* 3F8C8 8003ECC8 15C0001A */  bnez       $t6, .L8003ED34
/* 3F8CC 8003ECCC 344F0002 */   ori       $t7, $v0, 0x2
/* 3F8D0 8003ECD0 A3AF0154 */  sb         $t7, 0x154($sp)
/* 3F8D4 8003ECD4 92580065 */  lbu        $t8, 0x65($s2)
/* 3F8D8 8003ECD8 02402025 */  or         $a0, $s2, $zero
/* 3F8DC 8003ECDC 53000008 */  beql       $t8, $zero, .L8003ED00
/* 3F8E0 8003ECE0 8E48005C */   lw        $t0, 0x5C($s2)
/* 3F8E4 8003ECE4 0C011BB0 */  jal        func_80046EC0
/* 3F8E8 8003ECE8 00002825 */   or        $a1, $zero, $zero
/* 3F8EC 8003ECEC 50400004 */  beql       $v0, $zero, .L8003ED00
/* 3F8F0 8003ECF0 8E48005C */   lw        $t0, 0x5C($s2)
/* 3F8F4 8003ECF4 10000011 */  b          .L8003ED3C
/* 3F8F8 8003ECF8 8FBF002C */   lw        $ra, 0x2C($sp)
/* 3F8FC 8003ECFC 8E48005C */  lw         $t0, 0x5C($s2)
.L8003ED00:
/* 3F900 8003ED00 8FB90174 */  lw         $t9, 0x174($sp)
/* 3F904 8003ED04 8E440004 */  lw         $a0, 0x4($s2)
/* 3F908 8003ED08 8E450008 */  lw         $a1, 0x8($s2)
/* 3F90C 8003ED0C 01193021 */  addu       $a2, $t0, $t9
/* 3F910 8003ED10 30C9FFFF */  andi       $t1, $a2, 0xFFFF
/* 3F914 8003ED14 01203025 */  or         $a2, $t1, $zero
/* 3F918 8003ED18 AFA00010 */  sw         $zero, 0x10($sp)
/* 3F91C 8003ED1C 0C01222C */  jal        func_800488B0
/* 3F920 8003ED20 27A7014C */   addiu     $a3, $sp, 0x14C
/* 3F924 8003ED24 50400004 */  beql       $v0, $zero, .L8003ED38
/* 3F928 8003ED28 00001025 */   or        $v0, $zero, $zero
/* 3F92C 8003ED2C 10000003 */  b          .L8003ED3C
/* 3F930 8003ED30 8FBF002C */   lw        $ra, 0x2C($sp)
.L8003ED34:
/* 3F934 8003ED34 00001025 */  or         $v0, $zero, $zero
.L8003ED38:
/* 3F938 8003ED38 8FBF002C */  lw         $ra, 0x2C($sp)
.L8003ED3C:
/* 3F93C 8003ED3C 8FB0001C */  lw         $s0, 0x1C($sp)
/* 3F940 8003ED40 8FB10020 */  lw         $s1, 0x20($sp)
/* 3F944 8003ED44 8FB20024 */  lw         $s2, 0x24($sp)
/* 3F948 8003ED48 8FB30028 */  lw         $s3, 0x28($sp)
/* 3F94C 8003ED4C 03E00008 */  jr         $ra
/* 3F950 8003ED50 27BD0170 */   addiu     $sp, $sp, 0x170
/* 3F954 8003ED54 00000000 */  nop
/* 3F958 8003ED58 00000000 */  nop
/* 3F95C 8003ED5C 00000000 */  nop
