.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.10.1 */

glabel func_8003ED60
/* 3F960 8003ED60 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 3F964 8003ED64 AFBF0014 */  sw         $ra, 0x14($sp)
/* 3F968 8003ED68 8C8E0000 */  lw         $t6, 0x0($a0)
/* 3F96C 8003ED6C 24030005 */  addiu      $v1, $zero, 0x5
/* 3F970 8003ED70 31CF0005 */  andi       $t7, $t6, 0x5
/* 3F974 8003ED74 11E0000B */  beqz       $t7, .L8003EDA4
/* 3F978 8003ED78 00000000 */   nop
/* 3F97C 8003ED7C 0C011DE5 */  jal        func_80047794
/* 3F980 8003ED80 AFA40018 */   sw        $a0, 0x18($sp)
/* 3F984 8003ED84 8FA40018 */  lw         $a0, 0x18($sp)
/* 3F988 8003ED88 14400006 */  bnez       $v0, .L8003EDA4
/* 3F98C 8003ED8C 00401825 */   or        $v1, $v0, $zero
/* 3F990 8003ED90 8C980000 */  lw         $t8, 0x0($a0)
/* 3F994 8003ED94 2401FFFB */  addiu      $at, $zero, -0x5
/* 3F998 8003ED98 0301C824 */  and        $t9, $t8, $at
/* 3F99C 8003ED9C 10000001 */  b          .L8003EDA4
/* 3F9A0 8003EDA0 AC990000 */   sw        $t9, 0x0($a0)
.L8003EDA4:
/* 3F9A4 8003EDA4 8FBF0014 */  lw         $ra, 0x14($sp)
/* 3F9A8 8003EDA8 27BD0018 */  addiu      $sp, $sp, 0x18
/* 3F9AC 8003EDAC 00601025 */  or         $v0, $v1, $zero
/* 3F9B0 8003EDB0 03E00008 */  jr         $ra
/* 3F9B4 8003EDB4 00000000 */   nop
/* 3F9B8 8003EDB8 00000000 */  nop
/* 3F9BC 8003EDBC 00000000 */  nop
