.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.10.1 */

glabel func_8003EFB0
/* 3FBB0 8003EFB0 4442F800 */  cfc1       $v0, $31
/* 3FBB4 8003EFB4 44C4F800 */  ctc1       $a0, $31
/* 3FBB8 8003EFB8 03E00008 */  jr         $ra
/* 3FBBC 8003EFBC 00000000 */   nop

glabel func_8003EFC0
/* 3FBC0 8003EFC0 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 3FBC4 8003EFC4 AFBF0014 */  sw         $ra, 0x14($sp)
/* 3FBC8 8003EFC8 AFA40018 */  sw         $a0, 0x18($sp)
/* 3FBCC 8003EFCC 0C012364 */  jal        func_80048D90
/* 3FBD0 8003EFD0 AFA5001C */   sw        $a1, 0x1C($sp)
/* 3FBD4 8003EFD4 10400003 */  beqz       $v0, .L8003EFE4
/* 3FBD8 8003EFD8 00000000 */   nop
/* 3FBDC 8003EFDC 10000008 */  b          .L8003F000
/* 3FBE0 8003EFE0 2402FFFF */   addiu     $v0, $zero, -0x1
.L8003EFE4:
/* 3FBE4 8003EFE4 8FAE0018 */  lw         $t6, 0x18($sp)
/* 3FBE8 8003EFE8 3C01A000 */  lui        $at, %hi(D_A0000000)
/* 3FBEC 8003EFEC 8FB9001C */  lw         $t9, 0x1C($sp)
/* 3FBF0 8003EFF0 01C17825 */  or         $t7, $t6, $at
/* 3FBF4 8003EFF4 8DF80000 */  lw         $t8, %lo(D_A0000000)($t7)
/* 3FBF8 8003EFF8 00001025 */  or         $v0, $zero, $zero
/* 3FBFC 8003EFFC AF380000 */  sw         $t8, 0x0($t9)
.L8003F000:
/* 3FC00 8003F000 8FBF0014 */  lw         $ra, 0x14($sp)
/* 3FC04 8003F004 27BD0018 */  addiu      $sp, $sp, 0x18
/* 3FC08 8003F008 03E00008 */  jr         $ra
/* 3FC0C 8003F00C 00000000 */   nop

glabel func_8003F010
/* 3FC10 8003F010 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 3FC14 8003F014 AFBF0014 */  sw         $ra, 0x14($sp)
/* 3FC18 8003F018 AFA40018 */  sw         $a0, 0x18($sp)
/* 3FC1C 8003F01C 0C012364 */  jal        func_80048D90
/* 3FC20 8003F020 AFA5001C */   sw        $a1, 0x1C($sp)
/* 3FC24 8003F024 10400003 */  beqz       $v0, .L8003F034
/* 3FC28 8003F028 00000000 */   nop
/* 3FC2C 8003F02C 10000007 */  b          .L8003F04C
/* 3FC30 8003F030 2402FFFF */   addiu     $v0, $zero, -0x1
.L8003F034:
/* 3FC34 8003F034 8FAF0018 */  lw         $t7, 0x18($sp)
/* 3FC38 8003F038 8FAE001C */  lw         $t6, 0x1C($sp)
/* 3FC3C 8003F03C 3C01A000 */  lui        $at, %hi(D_A0000000)
/* 3FC40 8003F040 01E1C025 */  or         $t8, $t7, $at
/* 3FC44 8003F044 00001025 */  or         $v0, $zero, $zero
/* 3FC48 8003F048 AF0E0000 */  sw         $t6, %lo(D_A0000000)($t8)
.L8003F04C:
/* 3FC4C 8003F04C 8FBF0014 */  lw         $ra, 0x14($sp)
/* 3FC50 8003F050 27BD0018 */  addiu      $sp, $sp, 0x18
/* 3FC54 8003F054 03E00008 */  jr         $ra
/* 3FC58 8003F058 00000000 */   nop
/* 3FC5C 8003F05C 00000000 */  nop
