.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.10.1 */

glabel func_8003FA10
/* 40610 8003FA10 3C0EA460 */  lui        $t6, %hi(D_A4600010)
/* 40614 8003FA14 8DC60010 */  lw         $a2, %lo(D_A4600010)($t6)
/* 40618 8003FA18 27BDFFF8 */  addiu      $sp, $sp, -0x8
/* 4061C 8003FA1C 30CF0003 */  andi       $t7, $a2, 0x3
/* 40620 8003FA20 11E00006 */  beqz       $t7, .L8003FA3C
/* 40624 8003FA24 00000000 */   nop
.L8003FA28:
/* 40628 8003FA28 3C18A460 */  lui        $t8, %hi(D_A4600010)
/* 4062C 8003FA2C 8F060010 */  lw         $a2, %lo(D_A4600010)($t8)
/* 40630 8003FA30 30D90003 */  andi       $t9, $a2, 0x3
/* 40634 8003FA34 1720FFFC */  bnez       $t9, .L8003FA28
/* 40638 8003FA38 00000000 */   nop
.L8003FA3C:
/* 4063C 8003FA3C 3C088000 */  lui        $t0, %hi(D_80000308)
/* 40640 8003FA40 8D080308 */  lw         $t0, %lo(D_80000308)($t0)
/* 40644 8003FA44 3C01A000 */  lui        $at, (0xA0000000 >> 16)
/* 40648 8003FA48 00001025 */  or         $v0, $zero, $zero
/* 4064C 8003FA4C 01044825 */  or         $t1, $t0, $a0
/* 40650 8003FA50 01215025 */  or         $t2, $t1, $at
/* 40654 8003FA54 8D4B0000 */  lw         $t3, 0x0($t2)
/* 40658 8003FA58 27BD0008 */  addiu      $sp, $sp, 0x8
/* 4065C 8003FA5C 03E00008 */  jr         $ra
/* 40660 8003FA60 ACAB0000 */   sw        $t3, 0x0($a1)
/* 40664 8003FA64 00000000 */  nop
/* 40668 8003FA68 00000000 */  nop
/* 4066C 8003FA6C 00000000 */  nop
