.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.17.3 */

# Handwritten function
glabel func_8003FB10
/* 40710 8003FB10 40086000 */  mfc0       $t0, $12 # handwritten instruction
/* 40714 8003FB14 2401FFFE */  addiu      $at, $zero, -0x2
/* 40718 8003FB18 01014824 */  and        $t1, $t0, $at
/* 4071C 8003FB1C 40896000 */  mtc0       $t1, $12 # handwritten instruction
/* 40720 8003FB20 31020001 */  andi       $v0, $t0, 0x1
/* 40724 8003FB24 00000000 */  nop
/* 40728 8003FB28 03E00008 */  jr         $ra
/* 4072C 8003FB2C 00000000 */   nop

# Handwritten function
glabel func_8003FB30
/* 40730 8003FB30 40086000 */  mfc0       $t0, $12 # handwritten instruction
/* 40734 8003FB34 01044025 */  or         $t0, $t0, $a0
/* 40738 8003FB38 40886000 */  mtc0       $t0, $12 # handwritten instruction
/* 4073C 8003FB3C 00000000 */  nop
/* 40740 8003FB40 00000000 */  nop
/* 40744 8003FB44 03E00008 */  jr         $ra
/* 40748 8003FB48 00000000 */   nop
/* 4074C 8003FB4C 00000000 */  nop
