.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.17.3 */

glabel func_80040640
/* 41240 80040640 3C0EA404 */  lui        $t6, %hi(D_A4040010)
/* 41244 80040644 03E00008 */  jr         $ra
/* 41248 80040648 8DC20010 */   lw        $v0, %lo(D_A4040010)($t6)
/* 4124C 8004064C 00000000 */  nop
