.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.10.1 */

glabel func_80046610
/* 47210 80046610 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 47214 80046614 AFBF0014 */  sw         $ra, 0x14($sp)
/* 47218 80046618 AFA40018 */  sw         $a0, 0x18($sp)
/* 4721C 8004661C AFA60020 */  sw         $a2, 0x20($sp)
/* 47220 80046620 8CAE0008 */  lw         $t6, 0x8($a1)
/* 47224 80046624 51C00018 */  beql       $t6, $zero, .L80046688
/* 47228 80046628 8FBF0014 */   lw        $ra, 0x14($sp)
/* 4722C 8004662C 0C00E7E4 */  jal        func_80039F90
/* 47230 80046630 AFA5001C */   sw        $a1, 0x1C($sp)
/* 47234 80046634 8FA7001C */  lw         $a3, 0x1C($sp)
/* 47238 80046638 10400012 */  beqz       $v0, .L80046684
/* 4723C 8004663C 00403025 */   or        $a2, $v0, $zero
/* 47240 80046640 8FAF0018 */  lw         $t7, 0x18($sp)
/* 47244 80046644 8CF90008 */  lw         $t9, 0x8($a3)
/* 47248 80046648 240A0007 */  addiu      $t2, $zero, 0x7
/* 4724C 8004664C 8DF8001C */  lw         $t8, 0x1C($t7)
/* 47250 80046650 8F2800D8 */  lw         $t0, 0xD8($t9)
/* 47254 80046654 A44A0008 */  sh         $t2, 0x8($v0)
/* 47258 80046658 24050003 */  addiu      $a1, $zero, 0x3
/* 4725C 8004665C 03084821 */  addu       $t1, $t8, $t0
/* 47260 80046660 AC490004 */  sw         $t1, 0x4($v0)
/* 47264 80046664 C7A40020 */  lwc1       $f4, 0x20($sp)
/* 47268 80046668 AC400000 */  sw         $zero, 0x0($v0)
/* 4726C 8004666C E444000C */  swc1       $f4, 0xC($v0)
/* 47270 80046670 8CEB0008 */  lw         $t3, 0x8($a3)
/* 47274 80046674 8D64000C */  lw         $a0, 0xC($t3)
/* 47278 80046678 8C990008 */  lw         $t9, 0x8($a0)
/* 4727C 8004667C 0320F809 */  jalr       $t9
/* 47280 80046680 00000000 */   nop
.L80046684:
/* 47284 80046684 8FBF0014 */  lw         $ra, 0x14($sp)
.L80046688:
/* 47288 80046688 27BD0018 */  addiu      $sp, $sp, 0x18
/* 4728C 8004668C 03E00008 */  jr         $ra
/* 47290 80046690 00000000 */   nop
/* 47294 80046694 00000000 */  nop
/* 47298 80046698 00000000 */  nop
/* 4729C 8004669C 00000000 */  nop
