.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.10.1 */

glabel func_80046B40
/* 47740 80046B40 27BDFFE8 */  addiu      $sp, $sp, -0x18
/* 47744 80046B44 AFBF0014 */  sw         $ra, 0x14($sp)
/* 47748 80046B48 AFA40018 */  sw         $a0, 0x18($sp)
/* 4774C 80046B4C AFA60020 */  sw         $a2, 0x20($sp)
/* 47750 80046B50 8CAE0008 */  lw         $t6, 0x8($a1)
/* 47754 80046B54 51C0001A */  beql       $t6, $zero, .L80046BC0
/* 47758 80046B58 8FBF0014 */   lw        $ra, 0x14($sp)
/* 4775C 80046B5C 0C00E7E4 */  jal        func_80039F90
/* 47760 80046B60 AFA5001C */   sw        $a1, 0x1C($sp)
/* 47764 80046B64 8FA7001C */  lw         $a3, 0x1C($sp)
/* 47768 80046B68 10400014 */  beqz       $v0, .L80046BBC
/* 4776C 80046B6C 00403025 */   or        $a2, $v0, $zero
/* 47770 80046B70 8FAF0018 */  lw         $t7, 0x18($sp)
/* 47774 80046B74 8CF90008 */  lw         $t9, 0x8($a3)
/* 47778 80046B78 240A000E */  addiu      $t2, $zero, 0xE
/* 4777C 80046B7C 8DF8001C */  lw         $t8, 0x1C($t7)
/* 47780 80046B80 8F2800D8 */  lw         $t0, 0xD8($t9)
/* 47784 80046B84 A44A0008 */  sh         $t2, 0x8($v0)
/* 47788 80046B88 24050003 */  addiu      $a1, $zero, 0x3
/* 4778C 80046B8C 03084821 */  addu       $t1, $t8, $t0
/* 47790 80046B90 AC490004 */  sw         $t1, 0x4($v0)
/* 47794 80046B94 8FAB0020 */  lw         $t3, 0x20($sp)
/* 47798 80046B98 AC400000 */  sw         $zero, 0x0($v0)
/* 4779C 80046B9C AC4B000C */  sw         $t3, 0xC($v0)
/* 477A0 80046BA0 84EC001A */  lh         $t4, 0x1A($a3)
/* 477A4 80046BA4 A44C000A */  sh         $t4, 0xA($v0)
/* 477A8 80046BA8 8CED0008 */  lw         $t5, 0x8($a3)
/* 477AC 80046BAC 8DA4000C */  lw         $a0, 0xC($t5)
/* 477B0 80046BB0 8C990008 */  lw         $t9, 0x8($a0)
/* 477B4 80046BB4 0320F809 */  jalr       $t9
/* 477B8 80046BB8 00000000 */   nop
.L80046BBC:
/* 477BC 80046BBC 8FBF0014 */  lw         $ra, 0x14($sp)
.L80046BC0:
/* 477C0 80046BC0 27BD0018 */  addiu      $sp, $sp, 0x18
/* 477C4 80046BC4 03E00008 */  jr         $ra
/* 477C8 80046BC8 00000000 */   nop
/* 477CC 80046BCC 00000000 */  nop
