.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.10.1 */

glabel func_80048ED0
/* 49AD0 80048ED0 27BDFFD8 */  addiu      $sp, $sp, -0x28
/* 49AD4 80048ED4 AFBF001C */  sw         $ra, 0x1C($sp)
/* 49AD8 80048ED8 AFA40028 */  sw         $a0, 0x28($sp)
/* 49ADC 80048EDC 0C00FEC4 */  jal        func_8003FB10
/* 49AE0 80048EE0 AFB00018 */   sw        $s0, 0x18($sp)
/* 49AE4 80048EE4 8FAF0028 */  lw         $t7, 0x28($sp)
/* 49AE8 80048EE8 3C0E8007 */  lui        $t6, %hi(D_8006CD10)
/* 49AEC 80048EEC 8DCECD10 */  lw         $t6, %lo(D_8006CD10)($t6)
/* 49AF0 80048EF0 2401FBFE */  addiu      $at, $zero, -0x402
/* 49AF4 80048EF4 01E1C024 */  and        $t8, $t7, $at
/* 49AF8 80048EF8 0300C827 */  not        $t9, $t8
/* 49AFC 80048EFC 00408025 */  or         $s0, $v0, $zero
/* 49B00 80048F00 3C018007 */  lui        $at, %hi(D_8006CD10)
/* 49B04 80048F04 01D94024 */  and        $t0, $t6, $t9
/* 49B08 80048F08 AC28CD10 */  sw         $t0, %lo(D_8006CD10)($at)
/* 49B0C 80048F0C 0C00FECC */  jal        func_8003FB30
/* 49B10 80048F10 02002025 */   or        $a0, $s0, $zero
/* 49B14 80048F14 8FBF001C */  lw         $ra, 0x1C($sp)
/* 49B18 80048F18 8FB00018 */  lw         $s0, 0x18($sp)
/* 49B1C 80048F1C 27BD0028 */  addiu      $sp, $sp, 0x28
/* 49B20 80048F20 03E00008 */  jr         $ra
/* 49B24 80048F24 00000000 */   nop
/* 49B28 80048F28 00000000 */  nop
/* 49B2C 80048F2C 00000000 */  nop
