.include "macro.inc"

/* assembler directives */
.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */
.set gp=64     /* allow use of 64-bit general purpose registers */

.section .text, "ax"

/* Generated by spimdisasm 1.17.3 */

# Handwritten function
glabel func_80049300
/* 49F00 80049300 40845800 */  mtc0       $a0, $11 # handwritten instruction
/* 49F04 80049304 03E00008 */  jr         $ra
/* 49F08 80049308 00000000 */   nop
/* 49F0C 8004930C 00000000 */  nop
